### ISSUE TITLE
[bug] not able to connect arrow inside another svg

### ISSUE THREAD

**Issue by tusharnankani** [tldraw/tldraw#1013]
### Description 

- Not able to connect an arrow to an object, inside of another object. 

#### Steps to reproduce

https://user-images.githubusercontent.com/61280281/194503761-2072eb3a-19cf-4463-b9e5-d3da2c6b2d78.mp4

### Expected behavior

The arrow should directly be able to pass through the outer boundary after potential push/drag.

For a result like this:

![image](https://user-images.githubusercontent.com/61280281/194530309-41ef1676-1666-4542-9d50-08f8a2005f2e.png)

Note: used the temporary fix for now^

#### Temporary fix

https://user-images.githubusercontent.com/61280281/194531258-33b00daa-3b59-42f5-b63d-7b31da004487.mp4

Let me know if you need more details.

**Comment by judicaelandria** [comment]
Hey @tusharnankani , thanks for the feedback but actually it's not a bug, it happens because the shape is in the back so you need to move it forward or in the front

https://user-images.githubusercontent.com/46365844/194566367-76dda971-753e-4f6c-a9ac-646ad5f5c33e.mov

**Comment by tusharnankani** [comment]
Oh, okay. 
Thank for the clarification @judicaelandria!
