### ISSUE TITLE
[feature] Clear history or reset internal state so that the tldraw canvas becomes blank

### ISSUE THREAD

**Issue by juliusgb** [tldraw/tldraw#1019]
Is there a way to clear the history and to do a reset so that the tldraw canvas becomes blank, just like in Excalidraw - https://codesandbox.io/s/excalidraw-ehlz3?

![ExcalidrawReset](https://user-images.githubusercontent.com/85777/195615119-996e03ef-76fb-4a51-9c22-a2b5a2ac2e94.gif)

This looked promising but seems to require to go into the lower-levels to make changes -> https://github.com/tldraw/tldraw/blob/main/examples/core-example-advanced/src/state/api.ts#L36

I thought I'd somehow get `Api`, call `Api.reset`, and all's well. 
But how to get Api seems to require dependencies that I'd like to avoid touching 😅 like `useStateDesigner`, `machine`, etc ->
https://github.com/tldraw/tldraw/blob/main/examples/core-example-advanced/src/App.tsx#L184

Reason I want to clear it is so that when i open another `.tldr` file on top another one, then the new file's content should be displayed.
- open `fileA` - has some drawings (state) & clost it.
- open `fileB` - has no drawings & close it.

Problematic part: open `fileB`, don't close it. Then open `fileA`. Expecting to see `fileB`, but still seing `fileA`. 

If I can clear tldraw's state/history when `fileA` disappears, then I can load `fileA` again when its opened.

![WithoutReset](https://user-images.githubusercontent.com/85777/195615297-b6eca687-4025-44fd-ac51-82e6b3b3adf1.gif)

**Comment by juliusgb** [comment]
Using `app.resetDocument()` brings me closer to the goal.

**Comment by judicaelandria** [comment]
seems like it works for you! so gonna close this for now
