### ISSUE TITLE
[bug] Bug description

### ISSUE THREAD

**Issue by afabricioa** [tldraw/tldraw#1057]
It is not working, when i try to draw a shape it is not working properly but when i insert a shape manually with props it is ok.
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@emotion/css": "^11.10.0",
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@tldraw/core": "^1.20.1",
    "@tldraw/tldraw": "^1.26.2",
    "alert": "^5.1.1",
    "antd": "^4.20.6",
    "apexcharts": "^3.26.0",
    "axios": "^0.27.2",
    "babel-plugin-styled-components": "^2.0.7",
    "bootstrap": "^5.1.3",
    "clsx": "^1.2.1",
    "customize-cra": "^1.0.0",
    "flowchart-react": "^3.6.2",
    "image-extensions": "^1.1.0",
    "is-hotkey": "^0.2.0",
    "is-url": "^1.2.4",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.34",
    "next": "12.1.6",
    "nookies": "^2.5.2",
    "notiflix": "^3.2.5",
    "nprogress": "^0.2.0",
    "pareto-chart": "^1.0.22",
    "phosphor-react": "^1.4.1",
    "react": "^16.4.0",
    "react-apexcharts": "^1.3.9",
    "react-bootstrap": "^2.4.0",
    "react-checkbox-tree": "^1.7.3",
    "react-dom": "^16.4.0",
    "react-dropzone": "^14.2.2",
    "react-hook-form": "^7.31.3",
    "react-intl": "^6.0.3",
    "react-intl-universal": "^2.6.6",
    "react-s-alert-v3": "^1.4.2",
    "react-sidebar": "^3.0.2",
    "recharts": "2.1.9",
    "slate": "^0.82.1",
    "slate-history": "^0.66.0",
    "slate-react": "^0.83.0",
    "styled-components": "^5.3.5",
    "throttle-debounce": "^5.0.0",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.17.12",
    "@types/antd": "^1.0.0",
    "@types/cookie": "^0.5.1",
    "@types/node": "^17.0.35",
    "@types/react": "^18.0.9",
    "@types/react-sidebar": "^3.0.2",
    "@types/styled-components-react-native": "^5.1.3",
    "babel-plugin-import": "^1.13.5",
    "eslint": "8.16.0",
    "eslint-config-next": "12.1.6",
    "file-loader": "^6.2.0",
    "less-loader": "^11.0.0",
    "typescript": "^4.7.2"
  },
}

this is my package.json

**Comment by steveruizok** [comment]
I'd need more information on this one. If you can share the error or reproduce the issue on CodeSandbox then happy to investigate! https://codesandbox.io/s/tldraw-example-n539u
