### ISSUE TITLE
[bug] tldraw beta: Reorder-Menu with wrong label: "Bring to Front" => "Send Forward"

### ISSUE THREAD

**Issue by ayalpani** [tldraw/tldraw#1080]
![image](https://user-images.githubusercontent.com/603179/207452794-fddd5515-beeb-48c6-afa0-df13e5379a1f.png)

**Comment by alex-kim-dev** [comment]
There's a separate [repo](https://github.com/tldraw/tldraw-beta) for the beta bugs. I've been mentioning the same issue in tldraw/tldraw-beta#21

**Comment by TodePond** [comment]
Thanks! A fix for this should be coming this week.
