### ISSUE TITLE
[bug] MultiplayerMenu hardcoded href

### ISSUE THREAD

**Issue by vladimirdulov** [tldraw/tldraw#1081]
Hi Steve,

We are building tldraw as a cloudron app and we have a request to amend a few lines as there are some links hardcoded to tldraw.com.

Namely we'd like to have the URL updated in the Multiplayer menu to the real domain in the following files:

https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/components/TopPanel/MultiplayerMenu/MultiplayerMenu.tsx#L133

https://github.com/tldraw/tldraw/blob/main/apps/www/pages/r/%5Bid%5D.tsx#L20

Thank you.

**Comment by steveruizok** [comment]
Would you mind creating a PR for this?
