### ISSUE TITLE
[feature] Attach a link to any element

### ISSUE THREAD

**Issue by gordielachance** [tldraw/tldraw#1118]
Hi, I see that it is now (beta) possible to attach a link to a picture or note, that is so nice !
I guess that a better logic would be to be able to attach a link to everything (frame, text, drawing...).

Thanks for your beautiful work !

**Comment by steveruizok** [comment]
Cheers, thanks. At the moment only certain shapes support URLs, we may try adding urls as a generic property to anything but not there yet. :)

**Comment by gordielachance** [comment]
Thanks, awesome work you’re doing here!
