### ISSUE TITLE
[bug] Beta : is it possible to open a file from the last version ?

### ISSUE THREAD

**Issue by gordielachance** [tldraw/tldraw#1119]
Hi, I'm currently testing the beta. Good work !!!

Is it possible to open a file from the latest version ? The File > open menu has disappeared.

Thanks!

**Comment by judicaelandria** [comment]
Please use this to ask for feature or to report a bug for the beta website https://github.com/tldraw/tldraw-beta/issues

**Comment by steveruizok** [comment]
Not yet! No filesystem support yet but it'll be there before this leaves beta.
