### ISSUE TITLE
[bug]: TypeError: Cannot read properties of undefined (reading 'pages')

### ISSUE THREAD

**Issue by AdditionAddict** [tldraw/tldraw#1176]
Opening an existing .tldr drawing give me console.error:

The UI just says Loading
```
index.mjs:15 TypeError: Cannot read properties of undefined (reading 'pages')
    at n.loadDocument (index.mjs:15:125198)
    at n.<anonymous> (index.mjs:15:126265)
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at S.forEach.e.<computed> [as next] (runtime.js:97:21)
    at o (index.mjs:1:1028)
```

Changed file to .txt
[planning.txt](https://github.com/tldraw/tldraw/files/11061586/planning.txt)

**Comment by SomeHats** [comment]
Hey, thanks for the report! This file looks like a tldraw v2 one. You should be able to open it on beta.tldraw.com instead. This is a little confusing at the moment I know, but we'll be bringing the new version of tldraw over onto the main site in a couple of weeks 😊
