### ISSUE TITLE
[Feature Request] Spline arrows & lines like excalidraw.

### ISSUE THREAD

**Issue by tankmohit** [tldraw/tldraw#1234]
I hate to compare tldraw and excalidraw. But I am a heavy ex excalidraw user.

It would be great if we can make spline arrows & lines as in excalidraw, with multiple control points to adjust the curve.

Currently tldraw only supports circular arrows, which are okay for most of the use cases, but when making flowchart like diagrams, it falls short.

Please add an ability to add multiple waypoints to adjust the curves in arrows and lines.

Also an ability to do it on the go, by single clicking the starting point and producing the curves wherever next click happens. (Just as in excalidraw)

![image](https://user-images.githubusercontent.com/27958239/232089581-6c5d89a7-ccda-476a-a2fa-e96cbc8426a1.png)

**Comment by temportalflux** [comment]
Closing issues/suggestions as completed due to lack of response seems... Less than ideal...
