### ISSUE TITLE
When there are too many strokes, the response of writing is not sensitive

### ISSUE THREAD

**Issue by Tim-Paik** [tldraw/tldraw#1247]
When there are many strokes on the page, it will not be displayed at the first time when the pen is put down, and the curve will be drawn as a straight line

There is no problem after creating a new page, but the reason I use tldraw is that it has an infinite canvas, so I hope it can be improved XD

**Comment by mimecuvalo** [comment]
We've done a lot of work since last year on performance, this should hopefully be much improved. If it's still an issue, please re-open and we'll be happy to dig in further. Thank you for your feedback!

**Comment by thanhnguyen2187** [comment]
![image](https://github.com/user-attachments/assets/2671fa9b-26a2-43d9-9574-b28a0c207dcb)

Hi! Can you take a look at this again? I'm experiencing the same issue with tldraw plugin on Obsidian. At >1000 nodes the lag starts to be much more noticeable
