### ISSUE TITLE
Can't drag canvas on laptop with touch display

### ISSUE THREAD

**Issue by FinnRG** [tldraw/tldraw#1252]
I'm currently using a laptop with a touchscreen, but dragging on my laptop touchscreen doesn't work the same as dragging on my phone or tablet. I looked into this, and it seems, that Firefox fires PointerDown and PointerMove events with the [pointerType](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType#value) set to “touch” instead of touch events.

This is also an issue in the current version: [https://github.com/tldraw/tldraw-v1/issues/75](https://github.com/tldraw/tldraw-v1/issues/75).

https://user-images.githubusercontent.com/65015656/220145376-19f2000d-54b6-45e7-8ea0-de45a6d3c594.MOV

**Comment by mimecuvalo** [comment]
This has since been addressed ^_^ Thanks for reporting!
