### ISSUE TITLE
Suggestion for improvement: paste should pick a different position

### ISSUE THREAD

**Issue by nielsbom** [tldraw/tldraw#1265]
One small thing that I'm always a bit miffed by with tldraw is that when I copy and then paste anything the pasted object is in exactly the same position as the object I copied. This makes it a bit hard to see whether I've actually pasted or need to still do it.

I think an improvement here is changing the position of the element that is being created a bit in relation to the original (I think there's an "active" or "current" position there or something?).

See attached gif as an example.
![paste_in_same_position](https://user-images.githubusercontent.com/327080/215323126-3b495b28-92f5-4f83-9d0f-020ca9cb66c1.gif)

**Comment by MitjaBezensek** [comment]
Definitely agree with this. That said we also have duplicate, which does offer better experience:

https://github.com/tldraw/tldraw/assets/2523721/23d38407-9f4b-4734-881b-93eca0a2ad45

**Comment by Taha-Hassan-Git** [comment]
We went with an indicator blink instead: https://github.com/tldraw/tldraw/pull/2852
