### ISSUE TITLE
Don't change the draw font type, the old one was absolutely great

### ISSUE THREAD

**Issue by navakelvin** [tldraw/tldraw#1270]
The new font type is not too great, guys. Please, consider leaving the old one, it is beautiful and the condensation allows the text to not be spread all over the screen.

PS. Or consider leaving them both perhaps.

## New
![image](https://user-images.githubusercontent.com/77164639/212409024-5091d996-3597-4b2d-80e7-ca4df7e1c9b5.png)

## Old ✨
![image](https://user-images.githubusercontent.com/77164639/212409395-a8c79960-e8b2-4dfb-bd92-703f5db80881.png)

**Comment by TodePond** [comment]
It's been a while and it looks like we'll stick with this font now :)
