### ISSUE TITLE
You should be able to lock shapes

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1271]
Following some discussions in the discord channel, it would be good to be able to lock shapes, like in v1.

<img width="905" alt="Screenshot 2023-01-12 at 15 22 06" src="https://user-images.githubusercontent.com/15892272/212107063-df850b78-e7bb-411e-ab36-36b46691d966.png">

<img width="844" alt="Screenshot 2023-01-12 at 15 24 30" src="https://user-images.githubusercontent.com/15892272/212107827-95fd83f1-8a28-45bb-b41c-3f80c5460d5d.png">

<img width="437" alt="Screenshot 2023-01-12 at 15 24 46" src="https://user-images.githubusercontent.com/15892272/212107887-356379fa-579a-4f5e-aa0f-0640020b812a.png">

**Comment by MitjaBezensek** [comment]
Done! 🎉
