### ISSUE TITLE
It's unclear how to draw an arrow without binding to shapes

### ISSUE THREAD

**Issue by webjoyable** [tldraw/tldraw#1273]
![image](https://user-images.githubusercontent.com/28753190/212030872-255cdbba-1eea-4e0e-b2e4-bc144dceed6e.png)

If you try to draw an arrow from inside of the shape it goes in the back and we need to move it for it to reappear on top

**Comment by irg1008** [comment]
Is there a way to disable arrow binding completely? I am restricting the user to paint in-frame only and it automatically binds when the arrow moves

**Comment by mimecuvalo** [comment]
We've added some improvements here to also be able to bind to other places within a shape (not just the center). We're in the process of closing stale issues and for this issue, as mentioned, you're able to workaround this behavior by holding down Control which is the design trade-off.
