### ISSUE TITLE
Add peer awareness in multiplayer

### ISSUE THREAD

**Issue by krapie** [tldraw/tldraw#1285]
It's good to see that tldraw beta has awesome multiplayer feature!
I have one feature suggestion, and that is peer awareness

Peer awareness is **crucial feature in real-time collaborative applications**, and tldraw beta does not seem to have that feature :(
It may look like this (original tldarw already implemented named cursor for peer awareness)

- tldraw custom (multi) cursor 

  ![multiplayer-cursor](https://user-images.githubusercontent.com/70474071/207048315-074ff10c-768f-420b-ae55-1428a631ef34.PNG)

- tldraw-yorkie (which I implemented for multiplayer tldraw using CRDT store open source Yorkie, I customized tldarw core for namecd cursor)

  ![multiplayer-cursor-2](https://user-images.githubusercontent.com/70474071/207048312-59766b02-7e5d-4112-bd74-6182bb41fe95.PNG)

**Comment by aMySour** [comment]
is this coming soon? whats the status now

**Comment by ds300** [comment]
this was added a while back! https://twitter.com/tldraw/status/1662147444988166173
