### ISSUE TITLE
[bug] Switching a shape type to penta/hexagon changes its dimensions

### ISSUE THREAD

**Issue by alex-kim-dev** [tldraw/tldraw#1289]
[Screencast from 2022-12-12 11-11-47.webm](https://user-images.githubusercontent.com/45559664/207003493-b7de2672-6545-49ee-a3be-d5b3316382c4.webm)

Switching between other types of shapes doesn't change the dimensions.

**Comment by Taha-Hassan-Git** [comment]
Solved here: https://github.com/tldraw/tldraw/pull/2378
