### ISSUE TITLE
Bad protection for read-only room URLs

### ISSUE THREAD

**Issue by labbo-lab** [tldraw/tldraw#1324]
For example, if you have a room with the editable URL being `tldraw.com/r/hello_world`, the resulting read-only URL would be `tldraw.com/v/llehdlrow_o` which is just the original url, reversed and then shifted a few characters to the left, this is especially bad for rooms with custom ids, and can be brute forced easily for the randomly generated ids

**Comment by steveruizok** [comment]
I'd like to improve this too! Scrambling the URL is a very ad-hoc solution, though it does work better with a generated uuid or where there are numbers in the URL (for example, an id like `v2_mvk0fSCdkaVbmsVMWXsC` scrambles to `f0kvm_7vCsXWMVsmbVakdCS`). A much better solution would be to generate a new uuid for the read-only room and keep the mapping in our database.

**Comment by mimecuvalo** [comment]
This has been improved. Thanks for your feedback!
