### ISSUE TITLE
[Bug]: Copy as PNG isn't working on Firefox

### ISSUE THREAD

**Issue by 0xMukesh** [tldraw/tldraw#1325]
### What happened?

Hey! I'm trying to copy a part of my canvas as PNG using "Copy as" option. When I check my clipboard, it's empty. The image isn't copied.
The interesting part is it works on Chrome and other chromium based browsers but not on Firefox.

### How can we reproduce the bug?

- Open Firefox
- Draw a random shape on any page
- Select that specific shape 
- Right click and select "Copy as" and choose PNG
- Check your clipboard 

### What browsers are you seeing the problem on?

Firefox

### Contact Details

0xmukesh@proton.me

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Unfortunately Firefox doesn't let us (or anyone else) put images onto the clipboard. I think we removed the option from the right click menu on Firefox though so I'm surprised you're still seeing it. Here's what I see when I right click on Firefox:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/23072548/236855517-6c875eb7-0f6c-45a2-9762-417c56501c4c.png">

**Comment by 0xMukesh** [comment]
Ah! I didn't knew about that. I'm using the v112.0.2 version of Firefox and I do see "PNG" as an option under the "Copy as" menu
![image](https://user-images.githubusercontent.com/90365542/236880991-d0f01818-8280-4de0-af59-fa595d886afc.png)

**Comment by steveruizok** [comment]
Are you on PC? I wonder if it's different. Here's the check that we use to determine whether to show the paste button:

```ts
const showUiPaste =
	typeof window !== 'undefined' &&
	'navigator' in window &&
	Boolean(navigator.clipboard) &&
	Boolean(navigator.clipboard.read)
```

**Comment by 0xMukesh** [comment]
Nope, I'm using laptop. I've been an user of Excalidraw for quite a long time. If I remember correctly, Excalidraw asks the user to change few configurations under [about:config](about:config) page. I'm unable to recall properly what configurations are they. I'll let you know, if I find them. 

I've pasted the logic to determine whether to show the paste button or not and it returns `true`. It maybe because of those configurations which I've changed while using Excalidraw.

![image](https://user-images.githubusercontent.com/90365542/236984995-0a3800d2-6ab0-48b5-985b-d178437d5113.png)

**Comment by 0xMukesh** [comment]
It's the `dom.events.asyncClipboard.clipboardItem` flag. If it is set to `true` (under the about:config page) then copying image as PNG would be supported on Firefox

**Comment by orangemug** [comment]
@0xMukesh we've added this in https://github.com/tldraw/tldraw/pull/1342 and it'll be in the next release.

**Comment by 0xMukesh** [comment]
Awesome, thanks a lot!
