### ISSUE TITLE
Add pen smoothing control

### ISSUE THREAD

**Issue by undeadf0x** [tldraw/tldraw#1376]
### What's the feature?

Some control over how the smoothing works for the pen would be nice, especially for writing
![image](https://github.com/tldraw/tldraw/assets/62490883/fc192938-4616-4618-8201-66aeb1ac62b6)
(Supposed to say "Arrrg mateys")

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sortedcord** [comment]
Is there a way to disable pen smoothing altogether? As it stands its very cumbersome to write with a stylus on it unless its something really big...

**Comment by mimecuvalo** [comment]
merging into this larger issue https://github.com/tldraw/tldraw/issues/3470
