### ISSUE TITLE
[Feature]: Support pdf render and annotation

### ISSUE THREAD

**Issue by saikatmitra91** [tldraw/tldraw#1383]
### What's the feature?

Need a way to upload local pdf files to tldraw and annotate it.
The pdf files can contain multiple pages for annotation.

### Contact Details

saikatmitra91@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xabierlameiro** [comment]
For our project, this would be a feature that would add a lot of value.

+1

**Comment by username14415** [comment]
+1

**Comment by GarryTime** [comment]
+1

**Comment by mimecuvalo** [comment]
While we don't support this feature directly, part of the power of the SDK is this definitely possible with our tooling!
Here's an example that can help you build what you need: https://examples.tldraw.com/pdf-editor

**Comment by MaloTV** [comment]
+1
