### ISSUE TITLE
pasted tabs don't get converted to spaces in text inputs

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1387]
This leads to some export bugs

![Image](https://user-images.githubusercontent.com/15892272/238615766-f0519053-9887-4d42-b168-c27aab14d393.png)

![Image](https://user-images.githubusercontent.com/15892272/238616165-a6109daf-fabc-45f0-b550-d034b1fc141f.png)

**Comment by ravindUwU** [comment]
Thoughts on introducing 2 preferences to make this configurable? 🤔
1. Convert tabs to spaces, which defaults to `true`
2. Tab size, which defaults to `2` <sup><sup><sup><small>that rhymes lol</small></sup></sup></sup>

This way,
- Conversion can be switched off to preserve the identation of typed/pasted text.
- If this (still) causes the previously mentioned export bugs to resurface, the export could always convert tabs to spaces using the tab size preference, regardless of the conversion preference.
