### ISSUE TITLE
[Feature]: Image re-sampling / level of detail

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#1404]
### What's the feature?

Improvements to tldraw's handling of images in order to improve performance.

## How do images work in tldraw?

In tldraw, images work like this:
- a user drops an image onto the canvas or selects it via `Upload media`
- tldraw creates a `TLImageAsset` for the image that contains a source for the image
- tldraw creates a `TLImageShape` that references the asset
- the image is rendered via the `TLImageUtil`'s render method, with the asset's source set as the background image for a div

By default, tldraw creates the image's source as a dataURI string where the image is serialized to base64. An override for this behavior is provided (`onCreateAssetFromFile`) that can return a different source string. On tldraw.com, we upload the image to a bucket and returning the image's source URL. For this issue, I'll refer to images created with the default strategy as **local images** and images created with the hosted strategy as **hosted images**.

## Performance issues

There are a few issues with the above system in tldraw:
- a user can add very large images to the canvas, which can lead to high memory usage
- local images (especially large local images) are _very_ slow to read, as the dataURI must be parsed by the CPU
- hosted images are much better but there is no feedback that they are loading; large images look invisible
- scaling very large images can be slow
- local images do not seem to be cached in the same way as remote images, so images are re-parsed when remounted, such as when an image leaves and returns to the viewport

## Image rescaling

We could rescale images so that they never are above a certain size. For example, we might rescale images so that the source itself is never more than 1000 pixels on any edge, though the final image is displayed at the original size. For example, a 1600x900 image would be resampled to 1000x563, then displayed in tldraw as a shape with a page unit width of 1600 and height of 900.

<img width="803" alt="image" src="https://github.com/tldraw/tldraw/assets/23072548/4f97cbdd-f5cf-48a8-af51-8b033188e109">

## Level of Detail 

We could implement a **level of detail** (LOD) system in tldraw that creates a set of alternatives for each image. This is common practice on the web in order to allow sites to load the smallest image necessary, given the eventual rendered size of the image on the user's viewport. In tldraw, our LOD system would choose the smallest image possible given the size of the image in screen units.

<img width="882" alt="image" src="https://github.com/tldraw/tldraw/assets/23072548/dc77771b-7318-4608-84c8-f1487d86141e">

This has its own tradeoffs for local images. First, we would have to resample each image when created in order to store the multiple versions of the images. Second, we would need to store multiple base64 images rather than a single base64 image, increasing the size of the data in the store. Third, the user's device would need to parse this dataURI each time it chooses a different image.

Implementing LOD with hosted images is much easier: the server could create the images on upload and the shape would simply load and cache the other sized images as needed.

## View in browser / Download original

If we did limit the size of images, we could implement a "view in browser" or "view original size" feature that would allow users to load the original image outside of tldraw or in a new tab. Likewise, we could add a "download original" button that allows an asset to be downloaded from the canvas.

---

Any other ideas?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
We could also look at tiling in combination with a LOD system. If I upload a photo from an iphone camera, that's ~4000px wide. At full resolution, that'll almost never fit on a screen all at once. If we wanted to avoid having a "view in browser"/"view original size" feature (personally i don't think that's a great UX compared to just being able to zoom all the way in), then we could look at splitting images into tiles and culling based on those too

**Comment by LeonFedotov** [comment]
iv'e been looking into this, 
theres def a problem with having too many images and storing them urlencoded on the DOM
would be great to use something like is described here 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
in congestion with something like this on a server: https://sharp.pixelplumbing.com/
