### ISSUE TITLE
[Bug]: Error when uploading png

### ISSUE THREAD

**Issue by theoryshaw** [tldraw/tldraw#1433]
### What happened?

Get the following when trying to upload a png...
![image](https://github.com/tldraw/tldraw/assets/507113/dbf49ade-5603-4a32-8f03-93bec056ad41)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TodePond** [comment]
Any chance you can click "Show details" and let us know what it says? :)
