### ISSUE TITLE
[Feature]: To zoom out further

### ISSUE THREAD

**Issue by theoryshaw** [tldraw/tldraw#1434]
### What's the feature?

Ideally, be able to zoom out more. 

We add a lot of sheets to a canvas, and draw a lot of annotation pointing from one sheet to the other. 
example: https://www.tldraw.com/r/20230511_Whitefish_Bay

make it a little harder if you're limited to how far you can zoom out. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aoreidmarr** [comment]
This would great. Wonder if it could just be infinite zoom? Sometimes that makes it easy to get lost on the page, but with the "back to content" feature already in place, seems like infinite zoom could work really well.
