### ISSUE TITLE
[Feature]: Shape locking

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#1445]
### What's the feature?

Implement simple shape locking for the shape `isLocked` property.

## Minimal feature

Shapes with `isLocked` should not be selected by clicks, box brushing, scribble brushing, or "select all", but only by a right click.

## UI

Create an action (e.g. "toggle locked") that toggles `isLocked`. This should be available from the context menu. In a mixed set of locked and unlocked shapes, set `isLocked` for all shapes to true. In a uniform set, invert `isLocked`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Done!
