### ISSUE TITLE
SVG g tag unrecognized in browser

### ISSUE THREAD

**Issue by bianpratama** [tldraw/tldraw#1448]
### What happened?

When `asset.props.src` is undefined, `TLImageUtil` will display `DefaultSpinner`, but it is wrapped in `<g>` tag. I think it should be either:
- Wrap `<g>` in `<svg>`, or
- `<g>` should be `<div>`.

Reference on [TLImageUtil](https://github.com/tldraw/tldraw/blob/787eab75d695cb5f614b3c072a2d798dfa4a3936/packages/editor/src/lib/app/shapeutils/TLImageUtil/TLImageUtil.tsx#LL145C3-L145C3).

### How can we reproduce the bug?

Make sure to have asset with no `props.src`.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

bian@prata.ma

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
This has since been reworked. Thank you for the bug report though nonetheless!
