### ISSUE TITLE
Cannot find module core-js in polyfill

### ISSUE THREAD

**Issue by kartlife** [tldraw/tldraw#1449]
### What happened?

First of all, congrats to all devs that contribute to this project because it's a great library. We are trying to  implement tldraw to an NextJS app with TypeScript. We have followed install instructions given at https://tldraw.dev/docs/ucg/installation . But when we try to run, an exception is thrown, with message:

> Error: Cannot find module '{pc_path}\node_modules\core-js\stable\array\at' imported from D:\G\zlogic\iLawyer\lexik\node_modules\@tldraw\polyfills\dist-esm\lib\polyfills.mjs
> Did you mean to import core-js/stable/array/at.js?

We have tried to solve this issue google it, without a solution. 

Any light about it?

### How can we reproduce the bug?

Following instructions given at https://tldraw.dev/docs/ucg/installation

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kartlife** [comment]
yep, you have to use new nextjs app structure.

**Comment by muresanandrei** [comment]
@kartlife But I don't use next js

**Comment by MitjaBezensek** [comment]
@muresanandrei what are you using? Do you maybe have a repo where this happens? Would help us a lot to narrow this down.

**Comment by muresanandrei** [comment]
@MitjaBezensek  I just started using something better called excalidraw that doesn't need all this extra dependencies. To be honest this so broken I see no reason to waste anymore time on it.

**Comment by MitjaBezensek** [comment]
@muresanandrei sorry to hear that! Good luck with your work.

**Comment by lucas-santosP** [comment]
I'm having the same problem using Next.js 13 using "pages" folder, not "app"...

**Comment by oguzgelal** [comment]
This is likely due to the `TLDraw` component was server-side rendered - it was with Next.js in my case.

Dynamic importing did the job.

```ts
import dynamic from "next/dynamic"

const TLDrawWithoutSSR = dynamic(
  () => import("@tldraw/tldraw").then((p) => p.Tldraw),
  { ssr: false }
)
```

**Comment by Businesspunk** [comment]
What about regular Webpack builder? It can not be compiled for now

**Comment by Businesspunk** [comment]
@steveruizok friendly ping. Is it due to alpha version?

**Comment by Businesspunk** [comment]
resolved, issue was on my side, regarding webpack, it have to resolve mjs files, so these fix 
```
config.module.rules.push({
		test: /tldraw\/editor\/dist-esm\/index.mjs/,
		type: "javascript/auto",
	},
	{
		test: /tldraw\/editor\/dist-esm\/index.mjs/,
		resolve: {
			fullySpecified: false,
		},
	}
)
```
should help, if anyone faces that
