### ISSUE TITLE
[Feature]: clickable urls or markdown links

### ISSUE THREAD

**Issue by theoryshaw** [tldraw/tldraw#1472]
### What's the feature?

Have clickable urls or markdown links. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TodePond** [comment]
If you paste a URL, it should appear as a 'Bookmark shape'. You can also right-click some shapes, and click 'Edit link' to add a link to them.

Do either of those help? Or are you hoping for something else?

Thanks!

**Comment by steveruizok** [comment]
Closing this one. It probably cuts into rich text / markdown editing, which is loosely planned but not soonly.
