### ISSUE TITLE
[Bug]: Paste applied to all tldraw components on a screen, not just the active one.

### ISSUE THREAD

**Issue by yarrichar** [tldraw/tldraw#1479]
### What happened?

My app ([Emblazon](https://emblazon.app)) allows you to have multiple tldraw components on the screen at once.

When pasting an image into one tldraw component it actually gets pasted into all tldraw components.

I would expect it to just paste into the active one

### How can we reproduce the bug?

Go to [Emblazon](https://emblazon.app), create a note, type /whiteboard to insert a tldraw component, do that again so you have multiple. Now try pasting an image into one of the components - it will end up in all of them.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

Discord - yarrichar#4856

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey [yarrichar](https://github.com/yarrichar)!

I think what you are seeing is that these instances are connected. One thing you can try to do is to pass in a unique `persistenceKey` to every `Tldraw` component you create:

```javascript
<Tldraw persistenceKey={uniqueKey} />
```

When I do that in our example the paste then works correctly

https://github.com/tldraw/tldraw/assets/2523721/d39f0e6c-3f83-44c4-b181-eea8dfa63731


Does that work for you?

**Comment by mimecuvalo** [comment]
@MitjaBezensek is right in his recommendation. Please do reach out if you're still having issues though!
