### ISSUE TITLE
[Bug]: Should 'onPointerEnter' be 'onPointerLeave'?

### ISSUE THREAD

**Issue by maundytime** [tldraw/tldraw#1483]
### What happened?

packages/editor/src/lib/app/statechart/TLSelectTool/children/idle.ts

Should `onPointerEnter` be `onPointerLeave`?

```ts
	onPointerLeave: TLEventHandlers['onPointerEnter'] = (info) => {
		switch (info.target) {
			case 'shape': {
				this.app.setHoveredId(null)
				break
			}
		}
	}
```

### How can we reproduce the bug?

Not sure if it trigger bug.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
closed my pr since tldraw does not accept a contributions for now

**Comment by judicaelandria** [comment]
>converted the pr to draft until Tldraw CLA is up

**Comment by MitjaBezensek** [comment]
Fixed here https://github.com/tldraw/tldraw/pull/1486
