### ISSUE TITLE
[Feature]: Manually set pen mode

### ISSUE THREAD

**Issue by Kochanac** [tldraw/tldraw#1510]
### What's the feature?

When I draw with a pen on an ipad, I don't want to exit "pen mode" automatically after some finger taps, because my palm also does them. So, I would like to have a setting that enables "pen mode" until after I turn it off on used device.

### Contact Details

kochanac@ya.ru

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey @Kochanac, I added the "turn off pen mode after three touch events that occur before a pen event" because some people would get stuck there. Not a very good or predictable solution. Any other ideas, short of turning that feature off?

**Comment by steveruizok** [comment]
> It's very easy to make 3 touch events with a palm. I think it would be good to have a setting in the menu that turns pen mode on until manually turning it off

We've removed this now. You can only exit pen mode by refreshing or tapping the **Exit pen mode** button. Should be all fixed!
