### ISSUE TITLE
[Bug]: Can not undo deleting frame

### ISSUE THREAD

**Issue by Shay-repos** [tldraw/tldraw#1511]
### What happened?

After copying a frame and deleting it. I could not redo the operation
Got so frustrated though. Lost several weeks of work. I'm literally crying rn
You can reproduce it using my link below
https://www.tldraw.com/r/v2_c_uOVBXZxKcJp-onfBTFqJC?viewport=-3753%2C-3625%2C20180%2C13210&page=page%3AnCME7D6q3rmk-qZnnoDOu.

If you can recover it. Please let me know

### How can we reproduce the bug?

You can reproduce it using my link below
https://www.tldraw.com/r/v2_c_uOVBXZxKcJp-onfBTFqJC?viewport=-3753%2C-3625%2C20180%2C13210&page=page%3AnCME7D6q3rmk-qZnnoDOu

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
And it only happens in multiplayer?
