### ISSUE TITLE
Docs links do not scroll to correct position

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1516]
### What happened?

When I'm on the docs site...
On the API Reference page...
I sometimes want to link someone to a specific place on the page.

eg: https://tldraw.dev/gen/editor/App-class#App-updateInstanceState-member-1

However, this doesn't move their scroll to the correct place.
If they manually refresh *again*, then it works. But the first landing place is wrong.

Sidenote: We should probably clean up those links, and make it easy for a user to link to them. Maybe a separate issue though!

cc @steveruizok @hermy0211

### How can we reproduce the bug?

1. Follow this link: https://tldraw.dev/gen/editor/App-class#App-updateInstanceState-member-1

Expected: `updateInstanceState` should be at the top of your screen.
Actual: It's not.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TodePond** [comment]
Annoyingly, this bug seems to happen in production, but not dev.

eg: Bug with https://canary.tldraw.dev/gen/editor/Editor-class#Editor-setErasingIds-member-1
eg: No bug with http://localhost:3000/gen/editor/Editor-class#Editor-setErasingIds-member-1

**Comment by TodePond** [comment]
Maybe it's this. It would explain why it doesn't happen in dev

https://stackoverflow.com/questions/46474689/anchor-links-scrolling-to-wrong-position

**Comment by TodePond** [comment]
Currently investigating: https://github.com/vercel/next.js/issues/44295

**Comment by mimecuvalo** [comment]
This has since been reworked. Thanks for reporting!
