### ISSUE TITLE
Docs search has no feedback

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1518]
### What happened?

When you search on the docs site...
There's no feedback that you've pressed the Enter key.

Most of the time, this is fine, because it happens quickly.
But sometimes... if it takes longer (because of a slow connection or slow machine), there's no way of knowing that it's "doing something".

Watch for the small gap when you've pressed the Enter key:

![2023-06-05 at 11 55 05 - Indigo Locust](https://github.com/tldraw/tldraw/assets/15892272/790ce4ee-c212-41cb-b95d-fcd525d73b80)

### How can we reproduce the bug?

1. Type something into the search bar.
2. Press enter.

Expected: There should be some sort of indication that you've pressed enter, before the results actually load.
Actual: No feedback, and then the results show afterwards.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TodePond** [comment]
Seeing as you're currently looking at this sorta thing - cc @hermy0211 here TOO!

**Comment by Taha-Hassan-Git** [comment]
Docs search got an overhaul
