### ISSUE TITLE
[Bug]: How to recover

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [tldraw/tldraw#1541]
### What happened?

I was editing in my web browser and suddenly everything was gone. Is there an way to do that? I don't know what happened. Thanks

### What browsers are you seeing the problem on?

Chrome

### Contact Details

viniciusbrbio@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, could you give it a reload? We just did a release and there was some downtime while the server updated ahead of the client. (Nothing was lost, just had things happen in the wrong order). Either way, everything should be back now!

**Comment by ViniciusBRodrigues** [comment]
Yeap! It worked. Many thanks
