### ISSUE TITLE
Pasting in frame has random positioning

### ISSUE THREAD

**Issue by hermy0211** [tldraw/tldraw#1542]
### What happened?

As you can see below, if you copy and paste a node within a frame, it will paste in random locations across the frame. This is especially true when you paste while the previous copied node is still selected.
We should make the paste behavior consistent with when it is outside of a frame.
(Side note, but I think the `Command + C` and `Command + D` functionality should be reversed 😉)

https://github.com/tldraw/tldraw/assets/11720453/1ffe5a9c-bb93-42bf-8c3c-902f9572a2af

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
can confirm! it seems like sometimes it doesn't get the right point (where the cursor is pointing); it happened when I paste for the first time then it works after
may has something to do with this
https://github.com/tldraw/tldraw/blob/0cc91eec62cc879f1c164d5fc04252a9dfefa91c/packages/ui/src/lib/hooks/clipboard/pasteTldrawContent.ts#L13-L14
*point*

**Comment by steveruizok** [comment]
There are a few factors here: whether you’re pasting into a frame, whether the paste position is in view, and whether you’re holding a modifier. 

Paste position is notoriously tricky to get right, but this one is a definite miss: the logic should at least be the same inside of a frame as outside of one, with the exception that if the frame itself is out of view when you paste, the shape should be placed at the center of the frame.

We could also consider copying AE / Figma’s behavior just for cross app consistency. They have a few more rules about placement at the center but also along a shared axis if one exists. Paste position there isn’t intuitive either, however, so following the convention may not get us much further.

**Comment by MitjaBezensek** [comment]
This can probably be closed as we now paste to the center of the frame
https://github.com/tldraw/tldraw/pull/1859
