### ISSUE TITLE
Loading indicator for pasted images

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#1567]
### What's the feature?

When an image is added to the canvas, we currently show nothing on the canvas while the image loads. This was a prior design decision in the absence of anything better. We don’t know the size of the image or ultimately where it will be placed, so creating a loading state shape for each image was distracting and misleading. 

I think we’re now better placed to give some feedback. We can use scoped records to make the indicator(s) don’t sync between users. We can use the svg overlay layer to place indicators at the paste position, even in the case of multiple images being uploaded or added. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Being worked on in https://github.com/tldraw/tldraw/pull/3988
