### ISSUE TITLE
Markers have rendering issues when zoomed in Chrome

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#1575]
### What happened?

Marker strokes disappear/reappear in a flickery way when I was zooming into a bunch of overlapping strokes. I did draw all strokes criss crossed and overlapping.

See video:

https://github.com/tldraw/tldraw/assets/1845/8f9451c5-567a-441d-b77a-feae167ac35b

### How can we reproduce the bug?

1. Load this attached .tldr file into tldraw.com. ([markers.tldr](https://github.com/tldraw/tldraw/files/11725776/markers.tldr.txt))
    1. Change the extension from .tldr.txt to .tldr after downloading, Github didn't allow me to attach .tldr files.
3. Then pinch and zoom into the many marker lines
4. They should start to flicker as the marker lines intersect the viewport edges

### What browsers are you seeing the problem on?

Chrome

### Contact Details

francoislaberge@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Thanks for the report! This is a pretty rough one 😅

This looks like a browser bug. I've done a little investigation and can reproduce this on chrome on high-DPI screens (e.g. a macbook retina display). It seems to go away if you move the same browser over to a screen with lower DPI.

I'm not sure what we're going to be able to do about this one in the short term unfortunately. I've filed a bug report with Chromium to see if they can point us at something helpful: https://bugs.chromium.org/p/chromium/issues/detail?id=1454425

**Comment by seflless** [comment]
Ah makes sense. I'm on a high def screen for sure. It's a 31.5-inch Gigabyte Monitor (3840 × 2160), with a devicePixelRatio of 2. 

Hopefully it's not an issue much in practice. The filed bug looks great to me.

**Comment by steveruizok** [comment]
Looks like there's a fix in progress on that issue. 🤞

**Comment by mimecuvalo** [comment]
We've done a lot of work on perf/culling. This issue looks to be resolved after testing the tldr file!
