### ISSUE TITLE
hoveredId not set when pointer enters from off-canvas

### ISSUE THREAD

**Issue by BrianHung** [tldraw/tldraw#1584]
### What happened?

`editor.hoveredId` is not set when pointer moves from off-canvas into a shape. See gif.

https://github.com/tldraw/tldraw/assets/15721634/b040caa2-12bb-4e7c-9e3d-5ba0312dbd34

Expected behavior is `editor.hoveredId` is set to the shape id.

### How can we reproduce the bug?

Move from a shape to an element off-canvas like the popover menu, back to a shape. Log `editor.hoveredId` in dev tools; it is null.

I've dug into the issue and discovered that `useCanvasEvents.onPointerEnter` gets called before `useShapeEvents.onPointerEnter` and as a result, the event gets "killed" in the former handler before it reaches the latter. Because it is killed, the editor does not dispatch a `onPointerEnter` with `target: shape` so `setHoveredId` is not called in `EditingShape.onPointerEnter`.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

brianlhung@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Looks like this has since been resolved. Thanks for reporting!
