### ISSUE TITLE
[Bug]: Release tarballs are empty

### ISSUE THREAD

**Issue by gramakri** [tldraw/tldraw#1588]
### What happened?

The release archives under https://github.com/tldraw/tldraw/releases are empty

### How can we reproduce the bug?

Download release and extract it

### Contact Details

girish@cloudron.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Thanks for the report @gramakri! 

We're in a bit of a weird spot with our releases at the moment - the `alpha.12` release was made from a different repo before we open-sourced the 2.0 version of tldraw, so currently the release tag for that on this repo points to the commit where we deleted all the 1.0 stuff, but before we added in the new 2.0 stuff. We don't have a good way to get at the source code for `alpha.12` at the moment unfortunately, but we should be doing a new release soon.

What were you looking for in the release source code tarball? We might be able to help you out some other way :)

**Comment by gramakri** [comment]
@SomeHats ah fair enough. I was actually updating the Cloudron tldraw package. I noticed that you had put out 2.0 and tried with the release tarball :-) Building for master works. I wasn't sure if you were aware of the problem since I didn't find a similar issue.

I guess this issue can be closed!

**Comment by gramakri** [comment]
FWIW, this was the commit - https://git.cloudron.io/cloudron/tldraw-app/-/commit/b728c1a03c095d8a3b230fcbcb637548451ab74e
