### ISSUE TITLE
[Bug]: When image is resized, getting two lines in boundaries.

### ISSUE THREAD

**Issue by Shubhdeep12** [tldraw/tldraw#1597]
### What happened?

I uploaded the image and then resized it on a windows laptop in Chrome.

the smaller resized image has two lines on the boundaries.
![image](https://github.com/tldraw/tldraw/assets/43654389/554a006a-12ce-499a-bec6-cb42883e8e45)
Windows

### How can we reproduce the bug?

Upload the image then resize the image.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

chhabrashubhdeep@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Thanks, will investigate!

**Comment by mimecuvalo** [comment]
Looks like this has since been resolved. Thanks for reporting!
