### ISSUE TITLE
Add placeholder text styles like scribble and blocks

### ISSUE THREAD

**Issue by burrijw** [tldraw/tldraw#1604]
### What's the feature?

It'd be nice if there was a built in text style for placeholder text like the fonts in [this googleblog post](https://fonts.googleblog.com/2022/01/flow-and-redacted-check-out-these-new.html).

This would really help with quick lo-fi wireframes. I am particularly interested in the [Redacted Script](https://fonts.google.com/specimen/Redacted+Script?query=Redacted) font, tho I really like [Flow Rounded](https://fonts.google.com/specimen/Flow+Rounded?query=Dan+Ross) as well.

<img width="461" alt="image" src="https://github.com/tldraw/tldraw/assets/50222543/2f340b9e-7f63-4171-8d4c-9a77e1df21c5">
<img width="463" alt="image" src="https://github.com/tldraw/tldraw/assets/50222543/eaacc050-b285-4b33-abad-4a50e6aeb5fd">

### Contact Details

josh@jburri.dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
This is interesting—would you want this to work in the same way as text, or as a shape? i.e. we could have something that works like the rectangle tool, but has a repeating pattern for text like that, so that you could could draw out blocks of text like that.

**Comment by burrijw** [comment]
My initial thought was to have it as a font option next to the three current ones. I'm okay throwing some placeholder text in from a lorem ipsum generator or something like that on my own. 

But I'm open to having it be a shape that's just filled with lines. As long as that supports different weights/sizes to differentiate between headings, paragraphs, etc.
