### ISSUE TITLE
[Feature]: Right Click HAND mode 

### ISSUE THREAD

**Issue by stevespaw** [tldraw/tldraw#1628]
### What's the feature?

This may be combined with : https://github.com/tldraw/tldraw/issues/1254
But if we could have Right Click (Drag-Move) as a temporary Hand mode. This is a very useful feature that other tools use.

Thanks!
BTW Draw.io does this.

### Contact Details

stevespaw@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
I mean we already have space for Hand mode. but I think right click drag move is reserved (for selecting shapes)

**Comment by steveruizok** [comment]
Oh that's interesting, I hadn't seen that interaction before. In the meantime, we do have middle click + drag for hand mode or spacebar as @judicaelandria suggested.

**Comment by judicaelandria** [comment]
I think he meant the middle button

**Comment by stevespaw** [comment]
I had to try another mouse that had Middle wheel button, and that works. Maybe be able to set in settings to right button for those without scroll wheel button or a touch pad.? But that is the correct function. Thanks. 

Also maybe a tooltip for this, because I would not have tried it.

**Comment by mimecuvalo** [comment]
This is aligned with of https://github.com/tldraw/tldraw/issues/1254 (@stevespaw I see you commented there, too).
Rolling this issue into that issue.
