### ISSUE TITLE
Remember text alignment or default to start

### ISSUE THREAD

**Issue by szamanr** [tldraw/tldraw#1634]
### What's the feature?

in the add text tool, it's aligned to centre by default. if you change the alignment, it remembers that value but only until the end of the session. i always align to start, so i find myself having to change this once per session.

i would like the app to either remember the setting and persist it across sessions, or make it align to start by default, which seems like a more common use case.

![tldraw text default](https://github.com/tldraw/tldraw/assets/2622838/9a4ac472-6021-4701-b3d4-dfbc2e7c85ae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
We used to persist these properties but this was dropped after some changes to user presence / styles. @ds300 could you provide context on this one?

**Comment by ds300** [comment]
Yeah we no longer persist the `propsForNextShape` when stashing instance state. It could be done pretty easily. Shall I do it?

**Comment by szamanr** [comment]
@steveruizok bump on the above :)

**Comment by szamanr** [comment]
@steveruizok @ds300  bump

**Comment by szamanr** [comment]
@ds300 @steveruizok bump

**Comment by hxgqh** [comment]
It will be very useful

**Comment by szamanr** [comment]
@steveruizok @ds300 any plans to add this functionality?

**Comment by steveruizok** [comment]
Sorry, it's a bit more complicated. I'd like to find a solution but our current "shared styles across tools" pattern doesn't really support it, so we're considering changing that pattern!

**Comment by xuan-nguyen-swe** [comment]
Not only the alignment, but also remembering other settings is very useful.
I think usually settings should be considered globally remembering across tools.
Example, when we want to use red for Draw tool, we want to keep this color when switching to Line tool.
