### ISSUE TITLE
[Bug]: can't unlock a group of objets

### ISSUE THREAD

**Issue by Xeikos76** [tldraw/tldraw#1656]
### What happened?

The group of objects could not be unlocked

I wanted to create a grid and lock it so that I didn't accidentally move a row or column,
so I made it an object group and locked it.

![firefox_FaZqXiALys](https://github.com/tldraw/tldraw/assets/1506361/963cbf9f-472f-4bf7-99da-539fd334f525)

### How can we reproduce the bug?

select a group of object and group it
when the group of objects is selected, click in the free space in the object group selection box and click on "toggle locked".
then no object can be unlocked, and if the object group is selected (after right-clicking on one of the shapes in it) when the shape is created, the shape will become part of the group as soon as it has been created

![ezgif com-crop](https://github.com/tldraw/tldraw/assets/1506361/b2e24074-cfb3-4f79-adaa-aaa625469466)

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Contact Details

benjiof76@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, thanks for the bug report.

I've tried to reproduce this but it seems like it's working for me.

1. Group two or more shapes.
2. Right click the empty space in the group
3. Select Toggle Locked to lock the group
4. Right click on on one the shapes
5. Select Toggle Locked to unlock the group

![Kapture 2023-06-28 at 12 08 07](https://github.com/tldraw/tldraw/assets/23072548/33cb6ea3-cab7-47bd-a5e1-13afd7c50dec)

It's hard to tell from your GIF, but there is a bug where if you double-right-click then you'll "select into" the group, in the same way as you would when double clicking into a not-locked group. That's a legit bug and you'll need to click out of the group.

<img width="660" alt="image" src="https://github.com/tldraw/tldraw/assets/23072548/246c832f-eb9c-4ec0-83ce-d77de253f71a">

**Comment by antoinekh** [comment]
Hello,

I also have the same bug on Firefox 117 and Chrome 116.0.5845.188.

The Toggle Locked to unlock the group is not working.
![problem_lock](https://github.com/tldraw/tldraw/assets/52744345/de402429-c871-484b-8c80-524dcd83be84)

Also could it be possible to change the text from Toggle Locked to Toggle Unlocked when the ressource is already locked?

**Comment by mimecuvalo** [comment]
Looks like this has since been fixed. Thanks for reporting! If you're still experiencing the issue, please do reopen this though.
