### ISSUE TITLE
[feature] Images

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#166]
A user should be able to drag and drop or paste an image into their project.

As an MVP, consider taking URLs that were pasted into the app; if the URL is an image, add the image as a shape.

As a next step, consider converting images to dataURIs and storing them in the document that way. (This is kind of and would require a migration to fix).

Later, create a storage bucket where the image can be uploaded. Consider using the local data until that asset is ready from the remote host.

**Comment by FarazzShaikh** [comment]
@steveruizok @proful Is this feature still in the works? I have been toying around with this lib and developed a Photo and Video shape on [my fork](https://github.com/FarazzShaikh/tldraw/tree/feature/image-video-shapes).

This shape uses base64 encoding as default but provides callbacks that can be used to very easily incorporate a storage bucket as I have done for the tldraw example.

Maybe we can dynamically switch between the two different approaches based on if multiplayer is active. I have found base64 to be unusably slow on multiplayer.

**Comment by proful** [comment]
@FarazzShaikh  Please raise a PR.
Sorry I kept it assigned in my name.

**Comment by FarazzShaikh** [comment]
@proful No problem mate, will do. Can you assign this issue to me?

**Comment by steveruizok** [comment]
Excited to see what you've come up with!
