### ISSUE TITLE
[Bug]: v2.0.0-alpha.13 - @tldraw/utils is missing lib folder

### ISSUE THREAD

**Issue by chief-nerd** [tldraw/tldraw#1664]
### What happened?

checked out v2.0.0-alpha.13 -- seems broken because of a couple of spaces:

- @tldraw/utils is missing ./lib folder
- @tldraw/assets is still looking for `import { formatAssetUrl } from "./utils.mjs";` instead of  `from "@tldraw/utils"

### How can we reproduce the bug?

checkout v2.0.0-alpha.13 and create a test app

### Contact Details

jakob.work@reiter.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Thanks for the report @chief-nerd! I'm having a hard time reproducing this one - could you share some more information about how/where you saw this? Is there a specific bundler etc. where you saw this issue? How did you create your test app?

**Comment by chief-nerd** [comment]
Resolved. Seems to have been an npm caching error. Deep clean solved it.
