### ISSUE TITLE
Add WebP and WebM support

### ISSUE THREAD

**Issue by patrickporto** [tldraw/tldraw#1668]
### What's the feature?

You may change `ACCEPTED_IMG_TYPE` and `ACCEPTED_VID_TYPE` to accept webp and webm like the following example:

```javascript
const ACCEPTED_IMG_TYPE = ["image/jpeg", "image/png", "image/gif", "image/svg+xml", 'image/webp'];
const ACCEPTED_VID_TYPE = ["video/mp4", "video/quicktime", 'video/webm'];
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
We've since added this. Thanks for reporting!
