### ISSUE TITLE
[Feature]: Drive mobile / desktop from JavaScript, allow overrides.

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#1684]
### What's the feature?

Instead of using media queries, we should use a top-level data property to drive our mobile vs. desktop breakpoints; and have this property set using JavaScript, so that we can again support a `forceLayout="desktop"` or `forceLayout="mobile"` prop.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
I think this is now done!
