### ISSUE TITLE
Copied element in frame centers instead of staying in place

### ISSUE THREAD

**Issue by csholmq** [tldraw/tldraw#1689]
### What happened?

When copying an element inside of a frame the duplicate always ends up in the center of that frame as opposed to on top of itself, as the expected behavior is.

### How can we reproduce the bug?

Create a frame. Place an element, e.g text, off center inside of that frame. Copy and paste the element and the duplicate should end up in the center of the frame, i.e not where the original element is.

Note 1: Should you deselect the copied element before pasting it ends up on top of itself, as expected. 
Note 2: This behavior is true if any element is selected inside of the frame.

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Looks like this is intentional cc @ds300 as he worked on this here https://github.com/tldraw/tldraw/pull/1859
