### ISSUE TITLE
[Feature]: Different backgrounds like lined or squared so the app mimicks a real paper

### ISSUE THREAD

**Issue by dmuiX** [tldraw/tldraw#1720]
### What's the feature?

Would be Amazing to have different Backgrounds like lined or squared like on real writing papers. So this app could be used as a journal with a pen.

### Contact Details

daniel.ullrich_c@posteo.de

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Thanks for the idea. Because tldraw is a tooling library that can be remixed in a million different ways, this type of theming can definitely be added by a developer using the library for their own custom purpose!
