### ISSUE TITLE
PWA orientation locked to portrait

### ISSUE THREAD

**Issue by AnTheMaker** [tldraw/tldraw#1724]
### What happened?

Hi there!
Love tldraw - especially on my tablet! I tried installing the site as a PWA to my homescreen, but it seems to only work in portrait-mode - which is quite bad on a large tablet where landscape mode would be perfect. It works fine in landscape in the browser, just not as a PWA.
It's probably because of the last line in your PWA Manifest located at https://www.tldraw.com/manifest.json:
`... "orientation": "portrait" }`

This should be `"any"` to allow viewing the PWA in both portrait and landscape mode.¹

 I couldn't find this manifest anywhere in this Repo, otherwise I would've created a PR!
Hope this can be changed soon!
Keep up the great work!
_An_

¹ https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Yep, that's on a private repo for the dot com site. I'll take a shot!

**Comment by steveruizok** [comment]
Unfortunately I can't figure out a way to do this on mobile that doesn't also prevent landscape on tablet etc. You might need to stick with device settings (ie orientation lock) until the orientation property is more nuanced.

**Comment by Sahadev18** [comment]
I am interested in solving this issue. Could you assign me this issue or allow a PR

**Comment by CHVrolledout** [comment]
It is working as expected I have tested it on ipad (10th generation) ios 16.4
![Simulator Screenshot - iPad (10th generation) - 2023-09-14 at 16 16 27](https://github.com/tldraw/tldraw/assets/57061278/c067c8df-cd3a-4622-94ae-8d7f722cf963)
![Simulator Screenshot - iPad (10th generation) - 2023-09-14 at 16 16 19](https://github.com/tldraw/tldraw/assets/57061278/710891ea-9422-4e33-a697-3269ffd2d4e2)

**Comment by Sahadev18** [comment]
Looks great, hope it is working well on every device.
Thank you for letting me know.
