### ISSUE TITLE
Compile error with react-vite asset configuration

### ISSUE THREAD

**Issue by richburdon** [tldraw/tldraw#1725]
### What happened?

The following error is generated via `react-vite`:

If I render `<Tldraw />` without attributes I get the warning: "Could not load assets. Please refresh the page." (reading the Discord bugs channel I was expecting assets to load from the CDN by default).

If I add `<Tldraw assetBaseUrl='https://unpkg.com/@tldraw/assets@2.0.0-alpha.12/' />` then I get the following runtime error:

```
✘ [ERROR] Could not resolve "./lib/index.mjs"

    node_modules/.pnpm/@tldraw+utils@2.0.0-canary.225e3969/node_modules/@tldraw/utils/dist-esm/index.mjs:1:14:
      1 │ export * from "./lib/index.mjs";
        ╵               ~~~~~~~~~~~~~~~~~
```

I get a similar error if I try to import `getAssetUrls` from `@tldraw/assets`.

### Contact Details

rich.burdon@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Let us know if this is still an issue. You might want to look at our https://github.com/tldraw/vite-template for any patterns there that might help!
