### ISSUE TITLE
Undo/redo issues

### ISSUE THREAD

**Issue by benjinus** [tldraw/tldraw#1726]
### What happened?

local dev version, undo/redo not working.

### How can we reproduce the bug?

create some drawings, click undo until all shapes gone, and then click redo, shapes not going back. 

https://github.com/tldraw/tldraw/assets/40568853/841aa3c1-876f-49d1-b3aa-9e1d00f05e06

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
This will only happen on the `api` endpoint (because there's an interval there that's effecting the history). Try the regular route and you should be ok!
