### ISSUE TITLE
Docker image for tldraw

### ISSUE THREAD

**Issue by Altagen** [tldraw/tldraw#1741]
### What's the feature?

# Introduction
tldraw is a very good whiteboard, thank for the work and I hope it continues to go in that direction.

In my opinion, tldraw is really well-designed, and the deployment should be as well-designed and easy to use as the application. In order to do so, we could add a dockerfile to the repository

## What is Docker ? 

Docker is an open-source platform that automates the deployment, scaling, and management of applications, by encapsulating them into containers, which are isolated environments with their own software, libraries, and configuration files. These containers ensure the application works uniformly across different computing environments.

## What is the interest for tldraw to use docker ?

Docker ensures application consistency across multiple development and deployment environments by eliminating the "it works on my machine" problem, as it packages the application with all the dependencies into a standardized unit. It also improves security by isolating applications in separate containers, allows for more efficient use of system resources compared to virtual machines, and simplifies software updates and scalability.

## How it works ? 

You can either build the docker image on your own machine, or you can download images from docker registry (ghcr.io or docker.io) but it needs to be uploaded, usually by the maintainer of the application.

I already written a dockerfile a little bit of time ago on the first repository : 

https://github.com/tldraw/tldraw-v1/issues/96#issuecomment-1536405070

I'm happy to contribute and to discuss about those matters.

Best,
Ange

### Contact Details

contact@ange-cesari.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey @Ange-Cesari, thanks for the issue.

This was talked about a lot last year when the first version of tldraw came out: in the end in the context of a "self-hosted tldraw". We decided to skip that because it would not have worked with the multiplayer, which at the time required a specific vendor in order to work. In this newer version, our tldraw.com website is both no longer open source, and either way would require external configuration. 

Self-hosted tldraw aside, we could consider making a docker image for the tldraw examples site, or for the open source repo, if those would be useful?

**Comment by Ange-Cesari** [comment]
Hey @steveruizok ,
I guess it depends on the usage ?

I was not even aware that tldraw is not open source anymore. I'm pretty sad about it, but hey, everyone must go on I guess.

If it's not maintained, I don't think it's worth the shot, maybe only à docker file might be interesting and users build it themselves for the old repo ?

Creating the image also implies hosting it which can take some time to manage. 

I any case, the fact that you are no longer open source means a docker image for the current version of tldraw won't exist 

So I guess you should let that to the Community, building with only a docker file

**Comment by accforgithubtest** [comment]
I came looking for a docker version to host it myself. 

Checking the repo, its still showing up as Apache 2 licensed.  

Can you pls clarify what is under the apache license and what is not opensource ? 

Is there anything stopping from creating a dockerised version ?

**Comment by Ange-Cesari** [comment]
Hey @accforgithubtest,

Thanks for the answer. I think a docker image would be interesting as it no longer receives new update. It would be seen as a "final" docker image that completes the repository.

Thanks for still answering this issue and taking the time,

Best,
Ange

**Comment by matbgn** [comment]
Really sad about that kind-of "silent" license upgrade also

**Comment by accforgithubtest** [comment]
I think you mean the license downgrade and also not being open / clear about it. :)
