### ISSUE TITLE
[Feature]: how to extend an existing shape?

### ISSUE THREAD

**Issue by lakesare** [tldraw/tldraw#1743]
### What's the feature?

Hi folks! Our question is - is there a nice way to subclass the existing shape, so that its functionality is intact?

___

### Our attempts

1. We needed to make the arrows disappear when two nodes touch each other.
In order to do this, we subclassed the `TLArrowUtil`: [github.com/Paper-Proof/paper-proof/~/CustomArrowShape.tsx](https://github.com/Paper-Proof/paper-proof/blob/21821a405d5ce6c8151ee93c2da087ecd5fc7c98/app/src/shapes/CustomArrowShape.tsx).
Now, every time I remove the node attached to the `CustomArrow`, I get an error. I think that happens because tldraw depends on `type = "arrow"` somewhere (and this certainly happens for frames, see 2.).

2. The same happens with our custom frames [https://github.com/Paper-Proof/paper-proof/~/WindowShape.tsx](https://github.com/Paper-Proof/paper-proof/blob/21821a405d5ce6c8151ee93c2da087ecd5fc7c98/app/src/shapes/WindowShape.tsx).
Insted of inheriting from `TLFrameUtil`, we just created a custom shape by copypasting everything this time. This also raises errors because tldraw depends on `if (shape.type === 'frame')` in the `2.0.0-alpha.12` and on `this.editor.isShapeOfType(shape, FrameShapeUtil)` in `2.0.0-alpha.14`.

[Here is a slightly more detailed description of this issue: [paper-proof/issues/11](https://github.com/Paper-Proof/paper-proof/issues/11)]

### Contact Details

lakesare@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
Hi! Haven't tried to make a custom arrow but I'm sure you can do that (while preserving the feature), but I did make a custom iframe, it's been a while since I touched this project (I'm not sure if there is a better way to do it) but here's how I did before at that time https://github.com/judicaelandria/miro-like/blob/main/src/components/shapes/CFrame.tsx

**Comment by lakesare** [comment]
@judicaelandria, aha, so in your code you're copypasting stuff from `TLFrameShape` in `CFrame`, pretty much exactly like we're doing for our `WindowShape` (https://github.com/Paper-Proof/paper-proof/blob/21821a405d5ce6c8151ee93c2da087ecd5fc7c98/app/src/shapes/WindowShape.tsx, we also inherit from the tldraw's frame).

Both of our solutions struggle from the same issue, the nodes inside of the custom frame get stretched upon the frame resizing.
Here is the issue shown on [miro-like.vercel.app](https://miro-like.vercel.app):

![2023-07-21 12 57 54](https://github.com/tldraw/tldraw/assets/7578559/d82cac75-c2b6-451c-9028-c61dfc128bf6)

**Comment by lakesare** [comment]
So with the latest `main` (`2.0.0-canary.e17074a8b3a6`) extending the existing shapes works sorta fine, e.g. here is what I'm doing for the arrows.

```
export default class CustomArrowUtil extends ArrowShapeUtil {
  static override type = 'customArrow' as const

  override component(arrowShape: TLArrowShape) {
    // Important to store it here and not later
    const superRender = super.component(arrowShape);

    // Don't show the arrow when the nodes are super close
    const ifVerticalDistanceBetweenNodesIs0 = getIfVerticalDistanceBetweenNodesIs0(this.editor.getArrowInfo(arrowShape)!);
    const ifNodesTouch = getIfNodesTouch(arrowShape, this.editor);
    if (ifVerticalDistanceBetweenNodesIs0 && ifNodesTouch) return null;

    return superRender;
  }
}
```

The problem with tldraw depending on `this.isShapeOfType<TLArrowShape>(shape, 'arrow')` everywhere remains though. This creates issues such as the afforementioned "vertical frame scaling" and the arrow's "we get an error when we delete the node without deleting the arrows first".

<img width="644" alt="image" src="https://github.com/tldraw/tldraw/assets/7578559/1bd52b51-ee17-4c0f-9e5e-bff39e124ee7">

**Comment by mrmianbao** [comment]
Can you copy the arrows code, build your own custom implementation with the type 'arrow', then provide that when you create the schema?

```
export declare function createTLSchema({ shapes }: {
    shapes: Record<string, SchemaShapeInfo>;
}): TLSchema;
```
I created a bunch of custom shapes to support importing from figma

<img width="817" alt="Screen Shot 2023-08-25 at 3 23 47 PM" src="https://github.com/tldraw/tldraw/assets/113153548/366dd4e4-0c65-4717-a5af-60f8a1915dca">

**Comment by dungnhcntt** [comment]
I have a problem with the text tool, it cannot have css styles like: fontWeight, fontFamily (robo, arial...)...
The library cannot be extended, so I cloned the source of text tool feature, now it can upgrade to anything I want
I also want to improve arrow, I'm also thinking of clone source arrow, but the logic is too much.
