### ISSUE TITLE
[Bug]: Postcss-calc: Lexical error on line 1: Unrecognized text.

### ISSUE THREAD

**Issue by xabierlameiro** [tldraw/tldraw#1775]
Hi guys, In this line of styles there is one rule r: max(calc(14px * var(--tl-scale)), 20px / max(1, var(--tl-zoom)));
This generates an error, regards

https://github.com/tldraw/tldraw/blob/2e4989255c2741889c21da0085242c82d0df0372/packages/editor/editor.css#L481

**Comment by steveruizok** [comment]
Hi @xabierlameiro, `r` is a valid CSS property. See this discussion for more info: https://github.com/microsoft/vscode/issues/85828 . Is it actually crashing postcss?

**Comment by xabierlameiro** [comment]
Hi @steveruizok oh nice! Thank you but I didn't know it was valid. Yes, it breaks my project
![image](https://github.com/tldraw/tldraw/assets/44481156/6d68b21f-78e0-40df-bf34-94a15493528c)
![image](https://github.com/tldraw/tldraw/assets/44481156/e936364e-7bd3-48aa-8c28-d56519cb9190)

Regards!

**Comment by steveruizok** [comment]
Hm, tough call here. The browsers seem to agree that the `r` value is okay, but it's not much work to replace the CSS calculation with something in JavaScript instead. I'll do that and see if it fixes the problem.
