### ISSUE TITLE
[Bug]: yarn error `node-gyp` not installed

### ISSUE THREAD

**Issue by joshpoll** [tldraw/tldraw#1782]
### What happened?

I ran `yarn` on the latest version of the repo and got the following error:

```bash
➤ YN0000: │ deasync@npm:0.1.28 STDOUT Usage Error: Couldn't find a script name "node-gyp" in the top-level (used by deasync@npm:0.1.28). This typically happens because some package depends on "node-gyp" to build itself, but didn't list it in their dependencies. To fix that, please run "yarn add node-gyp" into your top-level workspace. You also can open an issue on the repository of the specified package to suggest them to use an optional peer dependency.
```

Running `yarn add node-gyp` seemed to fix the problem. I'm not sure what kind of dependency this should be.

### How can we reproduce the bug?

Clone the repo and run `yarn` when `node-gyp` is not installed.

### Contact Details

jopo@mit.edu

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakesare** [comment]
Had the same issue, also fixed it with `yarn add node-gyp`.

**Comment by steveruizok** [comment]
Ah I think this is coming in with our yjs example. I may need to move that into its own repo.

**Comment by steveruizok** [comment]
Ok, I've removed the yjs example (out to https://github.com/tldraw/tldraw-yjs-example). You should be able to install without those extra dependencies. See the diff [here](https://github.com/tldraw/tldraw/pull/1795/files#diff-0ea0031cdbd926a4ef28ca50a144e85f67f8f6e9d06150221f700bac6276b523).
