### ISSUE TITLE
Export gives weird result with image over frame

### ISSUE THREAD

**Issue by mohdzaryab** [tldraw/tldraw#1801]
### What happened?

Exporting an image when it superimposes a frame completely gives weird result. 
Attaching video for reference.

https://github.com/tldraw/tldraw/assets/45558484/6979e806-cdac-4f1b-97f3-e9c806790afb

### How can we reproduce the bug?

Steps to Reproduce:
1. Create a frame.
2. Upload an image. 
3. Resize the frame to be of exact same dimension as the image is.
4. Move the image to frame so that it becomes the child of the frame.
5. Now, if the image superimposes the frame, export it.
6. Now, move the image a bit to any side using keyboard arrows and then export.
7. Compare the results, the first image will be broken.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Contact Details

mohammadzaryab0@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, I can't reproduce this one. I don't think we fixed anything related to images lately, so it may be just a failure to reproduce rather than a fixed bug. Could you try again though and confirm that it's still an issue?

**Comment by mohdzaryab** [comment]
Hey, Yes I can still reproduce the issue. It only occurs if image complete superimposes the frame. x, y, w and h are same for frame and height

https://github.com/tldraw/tldraw/assets/45558484/dfc7b040-e5eb-4340-810f-33922eb343c6
