### ISSUE TITLE
Copying video crashes tldraw.com

### ISSUE THREAD

**Issue by leolorenzoluis** [tldraw/tldraw#1802]
### What happened?

Uploading a sample video media

### How can we reproduce the bug?

Upload a video
Select the shape then press copy
The UI freezes

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Does this depend on the size of the video? I can't reproduce with small videos. If you're offline then we'll be putting the whole serialized video into the clipboard, which may be hitting some sort of clipboard size limit. If nothing else, we should display an error in this case, or perhaps exclude the asset if it's too large; in that case you could still paste between files but not between projects.

**Comment by leolorenzoluis** [comment]
Yes it was a large video around 500 MB just to do performance test. I might have seen some updates on the file assets though on handling if it's a large file.

**Comment by mimecuvalo** [comment]
We've done work on this so that we don't base64 encode these files anymore. This should hopefully be better but please do reopen if it's still an issue and we'll see what we can do.
