### ISSUE TITLE
Cannot delete polygons on multiplayer whiteboard

### ISSUE THREAD

**Issue by chinaowl** [tldraw/tldraw#1807]
### What happened?

I have a multiplayer whiteboard that two users are accessing, A and B. User A can delete freehand drawings and circles and User B gets the updates just fine, but when User A tries to delete a polygon shape, User B gets this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at precise (polygon-helpers.ts:5:1)
    at getRoundedInkyPolygonPath (polygon-helpers.ts:49:1)
    at DrawStylePolygon2 (DrawStylePolygon.tsx:26:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js:19425:1)
    at beginWork (react-dom.development.js:21678:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

I see that it's happening in this function, where `A` is undefined:

```
function precise(A: VecLike) {
    return ${toDomPrecision(A.x)},${toDomPrecision(A.y)} 
}
```

### How can we reproduce the bug?

Unfortunately I am unable to provide sample code showing this error happening. I was also unable to repro it using the YJS example. I am using ShareDB instead of YJS but I don't think that should matter?

The code where I am applying changes from remote to my local Tldraw store looks very similar to the example:

```
const toPut: TLRecord[] = [];
const toRemove: TLRecord["id"][] = [];

ops.forEach((op) => {
  const { oi, od } = op; // oi = object insert, od = object delete
  if (oi) {
    toPut.push(oi);
  } else if (od) {
    toRemove.push(od.id);
  }
});

store.mergeRemoteChanges(() => {
  if (toPut.length) {
    store.put(toPut);
  } else if (toRemove.length) {
    store.remove(toRemove);
  }
});
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
It seems like the shape is still trying to render after being deleted. I would change the `else if` to just an `else` so that mixed ops can be applied at the same time... but beyond that there's not much I can advise from this side. If it were me, I'd patch in some logs (or do some debugger work) to see the value of `shape` inside of the geo shape's render method.

**Comment by steveruizok** [comment]
If you can create a small repro then that would be very helpful, though I understand it's a bit complicated given your stack!

**Comment by steveruizok** [comment]
I did update the yjs example (see here https://github.com/tldraw/tldraw-yjs-example/pull/2), which could address this.

**Comment by chinaowl** [comment]
Updating to [v2.0.0-alpha.15](https://github.com/tldraw/tldraw/releases/tag/v2.0.0-alpha.15) fixed the issue for me!

**Comment by Georgiana-Lingurariu** [comment]
Hi @chinaowl ! Would you be so kind to share the steps you did for the multiplayer mechanism?
For example, what is "ops"? how did you get it?
