### ISSUE TITLE
Add extra fonts

### ISSUE THREAD

**Issue by niloofar-torab** [tldraw/tldraw#1812]
### What's the feature?

I love this app. However it'd be nice if it gave users access to more fonts. It could either be:
1. Either asking for a .ttf file from user. Ttf files are usually tiny. (But there are rarely massive fonts which contain characters from all languages.) This gives users an unlimited choice.
2. Or having A set of maybe 10 famous fonts in app, one font from each font category that are most widely used across the internet. Containing some cursive fonts. And preferably give users a choice about which ones they want to put in the 4 fonts box for quick access.

I'd even suggest the same thing for colors. Add a colour picker and set space for 4 main colours (just like a normal class that has 4 colours of markers) and then give the option of colour picker to let users choose which colours they want to put among the 4.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kannanjayachandran** [comment]
This may cause issues with Handwriting font types as they does not scale well.
