### ISSUE TITLE
[Bug]: Indicators are wrong when browser zoom isn't 100%

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1834]
### What happened?

As discovered by @genmon, indicators appear in the wrong place when your browser zoom isn't at 100%

![image](https://github.com/tldraw/tldraw/assets/15892272/bffcb60f-ad23-4bdc-bb06-03c07a814745)

### How can we reproduce the bug?

1. Draw a rectangle.
2. Change your browser's zoom level (note: not tldraw's zoom level, just your browser's).
3. Select the rectangle.

Expected: A selection indicator appears on the rectangle.
Actual: The selection indicator is misaligned with the rectangle. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leolorenzoluis** [comment]
How come `tldraw.com` works and handles it perfectly fine?

**Comment by steveruizok** [comment]
Do we remember how we fixed this last time?

**Comment by steveruizok** [comment]
https://github.com/tldraw/tldraw/pull/1380

**Comment by steveruizok** [comment]
Also https://github.com/tldraw/tldraw/pull/1380

**Comment by steveruizok** [comment]
This regression was introduced by me in https://github.com/tldraw/tldraw/pull/1380

**Comment by steveruizok** [comment]
Cancel that, it was introduced all the way back in https://github.com/tldraw/tldraw/pull/1751

**Comment by TodePond** [comment]
> How come `https://tldraw.com` works and handles it perfectly fine? It doesn't work with `examples` nor pulling the library and self hosting.

@leolorenzoluis That's because this bug is happening in the latest canary release. tldraw.com is using an older version of the library, so doesn't have the bug. We'll fix it before we roll it out to tldraw.com

**Comment by leolorenzoluis** [comment]
Hi @steveruizok that patch only fixes 150% but if OS defaults to 125% or 175% it's still misaligned. Maybe we need to use `rem` instead of `px` with deviceRatio and media queries (not sure not a CSS expert).

`tldraw.com` can accomodates any zoom level.

**Comment by ds300** [comment]
@leolorenzoluis can you provide more context on this

> if OS defaults to 125% or 175%

which OS and which browser and how are you setting the defaults?

**Comment by leolorenzoluis** [comment]
@ds300 Windows. Depending on the default resolution it uses either of those scale. This is using Chrome. You can modify the settings in control panel and change the default zoom under accessibility.
