### ISSUE TITLE
Get accurate pen coordinates while moving

### ISSUE THREAD

**Issue by xiaohuahegege** [tldraw/tldraw#1835]
### What happened?

Hi, I have a need to add a tail behind the pen. I called ScribbleManager and used the currentPagePoint coordinates to display the effect of the tail, but I found that the coordinates of the currentPagePoint are somewhat different from those drawn by the pen. Can someone tell me how to accurately get the current What are the coordinate values of the pen?

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
You can take a look at our [laser tool](https://github.com/tldraw/tldraw/tree/main/packages/tldraw/src/lib/tools/LaserTool), it does exactly what you want.
