### ISSUE TITLE
[Bug]: Unable to add context menu item in uiOverrides.

### ISSUE THREAD

**Issue by AdventureBeard** [tldraw/tldraw#1844]
### What happened?

This is in 2.0.0-canary.e7ad05fbf538.

When I add an item to the contextMenu callback to uiOverrides, it doesn't seem to get added in the UI. If I set a breakpoint in the contextMenu function, it looks like my breakpoint is being hit when I close the context menu, rather than when I open it. This could just be a idiosyncracy of my debugger, though. 

### How can we reproduce the bug?

1. Create a uiOverrides object with a contextMenu function.
2. Push a TLUiMenuItem onto the contextMenu and return the contextMenu.
3. Observe that the item does not appear in the UI. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakesare** [comment]
```
const uiOverrides: TLUiOverrides = {
  contextMenu: (editor, schema : TLUiMenuSchema, helpers): TLUiMenuSchema => {
    return [
      {
        id: '1',
        type: 'item',
        readonlyOk: true,
        disabled: false,
        checked: false,
        actionItem: {
          id: "2",
          readonlyOk: true,
          label: "Copy" as any,
          onSelect: (xxx) => {
            console.log({helpers});
            const shape = editor.onlySelectedShape;
            if (shape) {
              copyTextToClipboard(shape.props.text)
            }
          },
        },
      }
    ]
  }
}

<Tldraw onMount={handleMount} shapeUtils={customShapeUtils} overrides={uiOverrides}>
  {/* ContextMeny is necessary for the right-click menu to appear */}
  <ContextMenu>
    <Canvas/>
    <ErrorToast/>
  </ContextMenu>
</Tldraw>
```

The following works for me on `"@tldraw/tldraw": "^2.0.0-canary.13ef8be58d15",`. Inserting nearly verbatim as to not miss anything.

**Comment by lakesare** [comment]
While we're at it - pretty confused as to how to disable my "Copy" menu item for certain shapes.
In overrides, `contextMenu()` (see `console.log("outside")`) only gets called occasionally, and disabling menu items within `onSelect()` (see `console.log("inside")`) is too late.

```js
const uiOverrides: TLUiOverrides = {
  contextMenu: (editor, schema : TLUiMenuSchema, helpers): TLUiMenuSchema => {
    console.log("outside");
    // This only gets called once
    return [{
      actionItem: {
        onSelect: () => {
          console.log("inside");
          // This gets called on every click
        }
      }
   }]
  }
}
```

**Comment by MitjaBezensek** [comment]
Hey @AdventureBeard! This seems to work for me on the latest canary:
```typescript
const uiOverrides: TLUiOverrides = {
	contextMenu: (_editor, schema: TLUiMenuSchema, _helpers): TLUiMenuSchema => {
		const newItem: TLUiMenuItem = {
			id: 'newItem',
			type: 'item',
			readonlyOk: false,
			actionItem: {
				label: 'New item',
				id: 'newActionItem',
				readonlyOk: false,
				onSelect: () => {
					console.log('New Item')
				},
			},
			disabled: false,
			checked: false,
		}

		schema.push(newItem)
		return schema
	},
}
```
