### ISSUE TITLE
SVG export uses incorrect fonts

### ISSUE THREAD

**Issue by chr15m** [tldraw/tldraw#1845]
### What happened?

When I export an SVG and pull it in to Inkscape the fonts come in as `tldraw_draw` instead of Shantell Sans and so they default to my sans font which looks pretty wonk.

### How can we reproduce the bug?

Use the text tool in a drawing. Export to SVG. Open SVG in a different tool and observe the fonts are out of whack.

### What browsers are you seeing the problem on?

Firefox

### Contact Details

chris@mccormick.cx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PratikAwaik** [comment]
Hey @chr15m Were you able to find a fix for this issue?

**Comment by chr15m** [comment]
@PratikAwaik no I didn't find a fix.

**Comment by SomeHats** [comment]
We embed our fonts in the exported SVGs (it's not exactly shantell sans, it's a slightly customised version of it). I'm surprised that inkscape doesn't pick up the embedded font and use that...

**Comment by chr15m** [comment]
I've just tested this again. I exported an SVG from Chrome on my phone and shared it with myself over email.

In my email client (Thunderbird) the font looks the same as it does in tldraw. When I view it with my image viewer ("ristretto") it looks like Arial or some default font. When I open it in Inkscape it also looks like Arial.

Maybe the way in which the font is being embedded is not widely suppored?

**Comment by SomeHats** [comment]
It looks like inkscape doesn't support fonts embedded in SVGs at all: https://gitlab.com/inkscape/inbox/-/issues/301

I don't think there's a reasonable fix for us here - as noted on that issue, the same thing applies to excalidraw exports. We can't get our exports reliably looking correct without font embedding as we use custom versions of some fonts, so I think this is more an issue with inkscape not supporting this SVG feature. Sorry!

**Comment by chr15m** [comment]
@SomeHats a good solution (from my end-user perspective) would be:
1. Allow people to download the custom versions of the fonts.
2. Make sure the font name in the SVG matches the custom version.

That would let people install the fonts on their local and get consistency between what is exported from tldraw and what they are seeing in e.g. Inkscape.
