### ISSUE TITLE
Add transitions in presentation mode

### ISSUE THREAD

**Issue by Atreyu-94** [tldraw/tldraw#1853]
### What's the feature?

Sometimes I would like to have a drawing made before and enter a kind of "presentation mode" where it can be drawn without altering the background. 

My idea is that it's as basic as this isn't a presentation tool, but it would help introduce content chronologically without the need to leave the App.

Some ideas: 
* A **presentation mode** where changes are not saved and all features can be used.
* **Timesteps** to the elements in edit mode (normal mode) so that they appear in chronological order in presentation mode by touching some **keymap**.
* Assign a **keymap** in edit mode to add the elements to the **timeline**.

This would help to work chronologically on a content already developed, very useful for example in online classes.

I don't know if I made myself understood and if you think it's a good idea, :)

### Contact Details

vlamaro123@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Atreyu-94** [comment]
I think this can be solved by some kind of sidebar with graphic elements that can be reusable as it exists in Excalidraw. What do you think? 

![imagen](https://github.com/tldraw/tldraw/assets/39834909/183d66e6-50c4-4988-bb09-ce67d50adfba)

**Comment by waldenn** [comment]
I like this idea. I would also like to see some more other "presentation" utilities, like:
- Fullscreen mode toggle
- Ability to hide/show the UI menus (plus locking the underlaying page, but allowing for some simple annotation during the presentation)
- Responding to DOWN / UP and RIGHT / LEFT keys (go to the next / previous page)
- Quick access to the pages via entering a number
- More complex to implement: having a  global background page, which is rendered as a background for all pages in presentation mode.
- Thumbnail view of all pages for quick access / editing
- ...

**Comment by ams1** [comment]
Great project!

I'm guessing that "presentation mode" is on the roadmap, right? 
I mean https://prezi.com/ also has an infinite canvas -, the "frame" (aka slide) object is already here... 

IMO makes a LOT of sense from a Product Management perspective.

**Comment by trivikramak** [comment]
yes, this looks like a very good addition!

**Comment by mimecuvalo** [comment]
Thanks for the suggestions! This is definitely possible with our library. Please take a look at our examples on how you can use the tooling to make this happen:
- https://examples.tldraw.com/slideshow
- and https://examples.tldraw.com/slides
