### ISSUE TITLE
[Feature]: Midpoints in a Box and arrows on click.

### ISSUE THREAD

**Issue by ChakshuGautam** [tldraw/tldraw#1863]
### What's the feature?

I am trying to test this out as an alternative to to draw.io but I am missing a couple of features that I use the most there. 

1. Midpoint in a box - Currently, I can start and end an arrow anywhere on the box/rectangle (something that I love here and hated in draw.io) but when building flow diagrams, sometimes I want to be exactly in the middle.
2. Show an arrow on click - When connecting boxes, I mostly use the [click on box => click arrow => draw => snap to the midpoint of the next box] workflow.

Sharing an image blow on how draw.io is doing it.
<img width="201" alt="Screenshot 2023-09-12 at 8 04 52 AM" src="https://github.com/tldraw/tldraw/assets/7413816/a8d2fbd2-16cd-4380-9b87-658471cc7b48">

I am not sure if this is something in the pipeline but as a user, would love to have it here and possibly contribute to it too.

Thanks a bunch for this tool @steveruizok. I have been following your journey through Twitter and have taken a lot of inspiration from you.

### Contact Details

chaks.gautam@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
> Midpoint in a box - Currently, I can start and end an arrow anywhere on the box/rectangle (something that I love here and hated in draw.io) but when building flow diagrams, sometimes I want to be exactly in the middle.

This part is definitely available - you can get an arrow to pop right into the middle of a box. (we have little "magnetic" areas in the middle to help with this :)

> Show an arrow on click - When connecting boxes, I mostly use the [click on box => click arrow => draw => snap to the midpoint of the next box] workflow.

This is still being considered!
