### ISSUE TITLE
[Bug]: tldraw.com iframe embed steals focus on load

### ISSUE THREAD

**Issue by josephrocca** [tldraw/tldraw#1864]
### What happened?

When I embed a tldraw.com canvas (e.g. in a web page, notion doc, etc.), it steals focus when the iframe loads, which causes the page to scroll down to the iframe embed, and also takes focus from e.g. a text area that the user is typing in.

I'm not sure if this is expected behavior. If it is, I should have posted this as a feature request - i.e. a URL hash parameter to disable this "auto-focus on load" behavior.

### How can we reproduce the bug?

Just load this page: https://jsbin.com/mobozisali/edit?html,output

Notice that it scrolls all the way to the bottom of the page when the iframe loads.

You can also try typing in the code editor, and notice that it steals focus as you type.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
We have an `autofocus` prop which should allow you to customize this.
https://tldraw.dev/reference/editor/TLEditorOptions#autoFocus
