### ISSUE TITLE
[Bug]: Pen pressure not registering in Firefox

### ISSUE THREAD

**Issue by PseudoResonance** [tldraw/tldraw#1868]
### What happened?

I get proper pen pressure support on https://openprocessing.org/sketch/591905/ and in Edge/Chromium, but not in Firefox. The little "Exit pen mode" box shows up when I touch the pen to the tablet, so tldraw knows it's a pen, but the pressure doesn't register.

This is with a Huion Inspiroy Q11K with native Windows drivers only.

![image](https://github.com/tldraw/tldraw/assets/7216500/1b40c213-67af-4bdb-a1e1-ec15138afc46)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PseudoResonance** [comment]
I wasn't able to find much info from the site, and the only thing in the logs was `Ignoring ‘preventDefault()’ call on event of type ‘touchstart’ from a listener registered as ‘passive’.` when I first touched the pen to the tablet. I can provide some more information or logs if needed.

**Comment by mimecuvalo** [comment]
@PseudoResonance we've done some work here to make things better. Potentially this is better, can you take another look if you don't mind? We'd be curious if this is still an issue or not.

**Comment by PseudoResonance** [comment]
This appears to be fixed, at least with my setup. Thanks!
