### ISSUE TITLE
[Feature]: Customizable left/right pen buttons

### ISSUE THREAD

**Issue by haji-ali** [tldraw/tldraw#1870]
### What's the feature?

I am using the Wacom tablet which has a left and right buttons. Currently, the right click opens a menu while the left button turns on pan.

Could there be a customization so that I can assign other functions to the buttons? I would rather have the left button transform the pointer to the laser tool while it is pressed (and back to current tool when it is released) while have the right button transform the pointer to an eraser while it is pressed. Panning is already well served by the space bar.
This is similar to possible customization in Xournal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by notPlancha** [comment]
I still think it could be a good idea
