### ISSUE TITLE
[Bug]: Select all on Safari iPad does not work

### ISSUE THREAD

**Issue by leolorenzoluis** [tldraw/tldraw#1877]
### What happened?

Pressing right click or key board short cut CMD + A does not select all the elements

### How can we reproduce the bug?

1. Open tldraw.com on iPad
2. Press CMD + A
3. Shapes are not selected

1. Open tldraw.com on iPad
2. Right click
3. Observe there's a native select all that shows up from iOS
4. Select the select all context menu from tldraw
5. No shapes are selected

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey!
Tried it out now it it seems to work, so it might have been fixed. Could you please double check it?

**Comment by mimecuvalo** [comment]
If you're still experiencing this issue, please reopen!
