### ISSUE TITLE
[Bug]: Collaborator cursors are blurred when > 100% zoom 

### ISSUE THREAD

**Issue by leolorenzoluis** [tldraw/tldraw#1880]
### What happened?

Collaborator cursors are blurred when > 100% zoom 

### How can we reproduce the bug?

1. Turn on collaboration
2. Follow user
3. Zoom to 200-800% for another user
4. Observe the pixels and cursor icons are super blurry

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shashankshet** [comment]
Hi @leolorenzoluis,


Steps I tried to reproduce this bug:
1. I couldn't find the collaboration option, hence I tried this Share project option and opened it in a new tab.
<img width="421" alt="Screenshot 2023-09-16 at 11 14 56 AM" src="https://github.com/tldraw/tldraw/assets/48438739/b62eb417-1a3e-4763-875a-475becf0413b">

2. I made changes and tried to zoom in icons and cursor looked clear

Maybe you can provide more details on this or correct me if i'm wrong 😄

**Comment by leolorenzoluis** [comment]
It's not the icons of the menu. It's the collaborator icons under `LiveCollaborators.tsx` component in tldraw. It's when folks are moving around and you scale out. in another user's perspective to 200-800% it's not scaled.

**Comment by mimecuvalo** [comment]
We're in the process of closing stale issues in tldraw. We're currently unable to reproduce this particular issue. If you can provide some more steps, maybe a screenshot of the issue (if it's still happening), that would be helpful. Feel free to reopen if it's still causing problems.
