### ISSUE TITLE
Line shapes snap to an imaginary inside box on geo shapes

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1896]
1. Draw a small rectangle (easier if you zoom in, and set size style to Small).
2. Draw a line while holding the cmd/ctrl key.
3. Move the end of the line to just inside the edge of the rectangle.

Expected: It snaps to the edge.

Actual: It snaps to the edge, but also an invisible rectangle immediately inside the edge.

![Image](https://user-images.githubusercontent.com/15892272/265668854-170fe791-562e-4811-a868-34b081b46e1b.gif)

**Comment by TodePond** [comment]
Related to #1897 

This seems to be happening:



![Image](https://github.com/tldraw/tldraw/assets/15892272/20301851-5973-4632-9582-181124313d47)

**Comment by MitjaBezensek** [comment]
Probably related https://github.com/tldraw/tldraw/issues/1931

**Comment by TodePond** [comment]
Hey I think this one was fixed!
