### ISSUE TITLE
Lines vibrate when rotated 90 degrees

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1911]
Lines vibrate when rotated 90 degrees using their first handle. This doesn't happen on tldraw.com

1. Draw a line.
2. Move the first handle of the line so that it's rotated 90 degrees.

Expected: The line doesn't shake.
Actual: The line shakes.

This happens to a lesser extent with arrows too. It doesn't on tldraw.com

![2023-09-18 at 15 21 26 - Peach Horse](https://github.com/tldraw/tldraw/assets/15892272/de6cacae-8d47-4612-8c95-f33d06c1e973)

**Comment by ds300** [comment]
an oldie but a goodie

**Comment by jamesbvaughan** [comment]
I'm seeing this issue on current tldraw.com. It seems to happen whenever the initial point has been moved and is no longer at the shape's origin point, and then the second point is moved.

![Image](https://github.com/user-attachments/assets/279baba5-13a2-4a17-910c-ae64c6cb80cb)

**Comment by jamesbvaughan** [comment]
I can try to submit a fix today
