### ISSUE TITLE
Error when shift-clicking to draw lines

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1913]
I think one of our recent changes broke shift-clicking to draw lines?

1. Choose the line tool.
2. Click somewhere on the canvas.
3. Hold shift.
4. Click somewhere else on the canvas.

Expected: A line on the canvas.
Actual: Errors in the console.

<img width="297" alt="image" src="https://github.com/tldraw/tldraw/assets/15892272/a7a7b72c-1b35-421a-8959-7b5950688c56">

<br>

<img width="438" alt="image" src="https://github.com/tldraw/tldraw/assets/15892272/2341fbd4-d142-4d5b-936e-1bb93a69ccf9">

**Comment by Taha-Hassan-Git** [comment]
This happens even without holding shift

**Comment by Taha-Hassan-Git** [comment]
It only happens when drawing lines with dash set to "draw" and spline set to "line"

**Comment by Taha-Hassan-Git** [comment]
I've not been able to fix it but I figured out that it's a divide by zero error that is evaluating to NaN in line 106 of poygon-helpers.ts. I think it all comes down to the fact that an extra handle is being generated on every line, so even when the line is displaying correctly and there's no error in the console, you can still do this:

![Kapture 2023-09-20 at 16 13 47](https://github.com/tldraw/tldraw/assets/98838967/3dfc2bae-b8b4-457c-a3a1-c5b87ca6daa6)

I've just been completely unable to find where in the codebase this is happening.
