### ISSUE TITLE
Arrows extend inside the x box shape, but only on some sides

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#1931]
https://github.com/tldraw/tldraw/assets/2523721/ea6c0890-80d7-4ca2-bc56-6375cabd5246

**Comment by Sanyam-jain30** [comment]
Can I be assigned to it? I would like to solve this issue.

**Comment by frojo** [comment]
Seems fixed?

[Screencast from 11-05-2023 07:13:18 PM.webm](https://github.com/tldraw/tldraw/assets/15605453/df96d73f-2435-40d1-ba7f-becb3ad6b406)
