### ISSUE TITLE
Share button missing

### ISSUE THREAD

**Issue by itsArfinn** [tldraw/tldraw#1935]
### What's the feature?

I'm running tldraw in my local and checking how it is working. In my local everything is working fine except share option.

kindly help me out from this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mhtpyurt** [comment]
🙏

**Comment by MitjaBezensek** [comment]
Yes, the share options are not part of the open source package. To make them work you need your own custom backend that will be able to server the multiplayer data.

**Comment by jacksongoode** [comment]
I'm not sure if this issue is related to multiplayer. Just the ability to export a static copy of the page at a url?

**Comment by MitjaBezensek** [comment]
> I'm not sure if this issue is related to multiplayer. Just the ability to export a static copy of the page at a url?

Share button creates a multiplayer room (copies the room to the server and generates an url that you an share with others). Exporting static data is done via File -> Save a copy. This part is also not open sourced, but you can see how to serialize and deserialize all the data in our [persistence example](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/PersistenceExample.tsx).
