### ISSUE TITLE
[Bug]: Module '"@tldraw/editor"' has no exported member 'partition'.ts(2305)

### ISSUE THREAD

**Issue by linonetwo** [tldraw/tldraw#1939]
### What happened?

```
Module '"@tldraw/editor"' has no exported member 'partition'.ts(2305)

Property 'value' does not exist on type 'Result<TLStore, TldrawFileParseError>'.
  Property 'value' does not exist on type 'ErrorResult<TldrawFileParseError>'.ts(2339)

Property 'ensureStoreIsUsable' does not exist on type 'TLStore'.ts(2339)

Property 'updateRenderingBounds' does not exist on type 'Editor'. Did you mean 'renderingBounds'?ts(2551)
```

when using this logic in my app

https://github.com/tldraw/tldraw/blob/5cd74f4bd602fd2c56bdd57219aa92bde681b104/packages/tldraw/src/lib/utils/file.ts#L216-L301

### How can we reproduce the bug?

Use latest cannary

    "@tldraw/tldraw": "2.0.0-canary.b6ebe1e2749e",
    "@tldraw/editor": "2.0.0-canary.b6ebe1e2749e",

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! `parseAndLoadDocument` is really something internal right now. We use it to parse and load files in our deployment of the tldraw app at www.tldraw.com and for our VS Code extension. It has some quite specific things to these two use cases (like showing toasts,...) which you probably don't want in your application.

We do want to offer proper saving and loading functionality in the future.
