### ISSUE TITLE
Allow overwriting default utils

### ISSUE THREAD

**Issue by linonetwo** [tldraw/tldraw#1942]
### What's the feature?

Error: Shape type "note" is defined more than once

I want to remove the default note, and add a more powerful one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey!
You can do that already. The only [core shape](https://tldraw.dev/docs/shapes) right now is the Group shape. If you use the `Tldraw` component then we do use our default shapes. But if you would go with `TldrawEditor` component then you can avoid using those. You can take a look at our [Exploded example](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/ExplodedExample.tsx). There we do pass in our default shapes, but you can also just filter out the note shape.

**Comment by MitjaBezensek** [comment]
Makes sense. Will see if there's something we can do here. Either expose things that would be necessary to reproduce `TldrawEditor` or better extensibility of `TldrawEditor`. Thanks for the report!

**Comment by irg1008** [comment]
And what about importing the default fonts and assets as well? With the exploded example the fonts are not imported.

Thanks

**Comment by irg1008** [comment]
Also with the exploded example uploading assets does not work and options like `acceptedImageMimeTypes` or `maxImageDimension` cannot be set
