### ISSUE TITLE
serializeTldrawJson file cannot open in VS Code

### ISSUE THREAD

**Issue by linonetwo** [tldraw/tldraw#1944]
### What happened?

I'm createing a plugin for tiddlywiki, an opensource alternative to Obsidian.

I found the tldr file saved with `await serializeTldrawJson(editor.store)`, can't open in vscode's tldr extension, will lost all content, become white.

### How can we reproduce the bug?

    "@tldraw/editor": "2.0.0-canary.b6ebe1e2749e",
    "@tldraw/tldraw": "2.0.0-canary.b6ebe1e2749e",

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey!
As we add new features to canary we might use some data migrations that cause the two not to be compatible. We don't build a VS Code extension for every canary release, but we do do that for each alpha release. So I'd suggest you either build the VS Code extension from Canary yourself, or you can also wait for alpha releases and use that.

**Comment by linonetwo** [comment]
That's reasonable.
