### ISSUE TITLE
Collapsible canvas

### ISSUE THREAD

**Issue by bhaktibhatt** [tldraw/tldraw#1945]
### What's the feature?

the tlui-style-panel component with style class tlui-style-panel can be collapsed when user is done choosing what color etc they need, and minimize that component, so that full screen can be utilized. 
If this issue is valid please contact me

### Contact Details

bhaktinirbhaybhatt@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
We do have a focus mode that hides all the UI. Would this work for you?

![CleanShot 2023-11-10 at 12 00 52](https://github.com/tldraw/tldraw/assets/2523721/a330affb-e28e-4348-bbc7-5b14c0c0b39b)

**Comment by bhaktibhatt** [comment]
Thanks! But i think having that little part collapsable would look much neater
