### ISSUE TITLE
Non-infinite canvas

### ISSUE THREAD

**Issue by elianparedes** [tldraw/tldraw#1946]
### What's the feature?

I was wondering if there's a way to turn off the infinite canvas and set a fixed size for it instead. It would be really useful in various situations to have a canvas with fixed dimensions and not let users pan or scroll to infinity.

I tried to disable the infinite canvas using the code that Steve implemented for issue [#221](https://github.com/tldraw/tldraw-v1/issues/221) in the old repo, but I couldn't get it to work. I think it might be because of the new API attributes so I've been trying to find equivalent attributes, but no luck so far.

By the way, thanks for creating this awesome app and library!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by momenthana** [comment]
```ts
  const editor = useEditor();

  useEffect(() => {
    editor.addListener("frame", () => {
      const { x, y } = editor.camera;

      if (x !== 0 || y !== 0) {
        editor.setCamera({ x: 0, y: 0 });
      }
    });
  }, [editor]);
```
this can offset the camera movement.

![IMG_0004](https://github.com/tldraw/tldraw/assets/59823089/d2a29995-a08d-4fbb-965b-4d7907b0a75c)

One additional suggestion is that leveraging the implementation of the existing frame tool would help you implement a limited canvas.

**Comment by momenthana** [comment]
example code for limit camera range to specific range

```ts
  const editor = useEditor();

  useEffect(() => {
    const limit = 4096;

    editor.addListener("frame", () => {
      const { x, y } = editor.camera;

      if (Math.abs(x) > limit) editor.setCamera({ x: limit * Math.sign(x), y });
      if (Math.abs(y) > limit) editor.setCamera({ x, y: limit * Math.sign(y) });
    });
  }, [editor]);
```

**Comment by jpike88** [comment]
@MitjaBezensek this is a very important feature for our needs, and other situations where a canvas size needs containing with snap to grid in order for the output to suit pdfs and printouts... it seems none of the libraries I can find out there have really had this as a priority, closest I can find is this PR https://github.com/excalidraw/excalidraw/pull/6731...

Any thoughts on this?

**Comment by MitjaBezensek** [comment]
@jpike88 Hey! It's definitely something we want to support and also high on our list of things to work on as it does seem quite highly requested.

**Comment by jpike88** [comment]
Just one more thought on our particular use case:

We provide mudmaps/sketch components for our forms for house inspections, which allow users to outline a house, stamp stuff around it, provide notes etc.

Aside from custom width and height (in pixels is fine), a max zoom would be appropriate (the max being in our case where canvas fits the screen, to suit all screen aspect ratios), I know some non-infinite canvas solutions allow you to zoom way out.

**Comment by faizkhan12** [comment]
> example code for limit camera range to specific range
> 
> ```ts
>   const editor = useEditor();
> 
>   useEffect(() => {
>     const limit = 4096;
> 
>     editor.addListener("frame", () => {
>       const { x, y } = editor.camera;
> 
>       if (Math.abs(x) > limit) editor.setCamera({ x: limit * Math.sign(x), y });
>       if (Math.abs(y) > limit) editor.setCamera({ x, y: limit * Math.sign(y) });
>     });
>   }, [editor]);
> ```
> 
> more detailed implementation
> 
> ```ts
>   const editor = useEditor();
> 
>   useEffect(() => {
>     const limit = 16384;
>     const negLimit = limit * -1;
> 
>     const viewportPageLimit = () => {
>       const { x, y } = editor.camera;
>       const { x: cx, y: cy } = editor.viewportPageCenter;
>       const w = (x + cx) * 2;
>       const h = (y + cy) * 2;
> 
>       if (x > limit && y + h < negLimit)
>         editor.setCamera({ x: limit, y: negLimit - h });
>       else if (x + w < negLimit && y > limit)
>         editor.setCamera({ x: negLimit - w, y: limit });
>       else if (x + w < negLimit && y + h < negLimit)
>         editor.setCamera({ x: negLimit - w, y: negLimit - h });
>       else if (x > limit && y > limit) editor.setCamera({ x: limit, y: limit });
>       else if (x > limit) editor.setCamera({ x: limit, y });
>       else if (y > limit) editor.setCamera({ x, y: limit });
>       else if (x + w < negLimit) editor.setCamera({ x: negLimit - w, y });
>       else if (y + h < negLimit) editor.setCamera({ x, y: negLimit - h });
>     };
> 
>     editor.addListener("frame", viewportPageLimit);
> 
>     return () => {
>       editor.removeListener("frame", viewportPageLimit);
>     };
>   }, [editor]);
> ```

It says editor.addListener is not a function. Do you know why is that?

**Comment by MitjaBezensek** [comment]
Can you check if you have an instance of the editor at all? It should have an `addListener` method on it.

If editor is undefined then you are probably not using the `useEditor()` hook inside the editor context. In that case you might want to look into [getting the editor from](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/api/APIExample.tsx#L17) `onMount`

**Comment by jpike88** [comment]
I can get the above example to work @faizkhan12, just `npm ci` in this directory and then run `npm dev`

[sketch.zip](https://github.com/tldraw/tldraw/files/13944972/sketch.zip)

Thought it's very prototypical, not much use. You lose the grid, there's no zoom enforcement, can't enforce size of the frame etc etc... what's really needed is the canvas itself behaving like this, with clear borders and no grid outside them.

**Comment by faizkhan12** [comment]
> Can you check if you have an instance of the editor at all? It should have an `addListener` method on it.
> 
> If editor is undefined then you are probably not using the `useEditor()` hook inside the editor context. In that case you might want to look into [getting the editor from](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/api/APIExample.tsx#L17) `onMount`

yes, I needed to use the instance of the editor inside the editor context. Thank you.

**Comment by tienskowl** [comment]
Is there any update on this issue? I am also troubled by this problem

**Comment by SomeHats** [comment]
We're working on a proper API for constraining the camera at the moment. In the mean time, we added two new examples showing how you can achieve a fixed-size canvas effect with tldraw today:

- Image annotator: [demo](https://examples.tldraw.com/image-annotator/full) • [code](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx)
- PDF editor: [demo](https://examples.tldraw.com/pdf-editor/full) • [code](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/pdf-editor/PdfEditor.tsx)

They both contain `ConstrainCamera` components that could be adapted for other types of camera constraints. They also both include overlay components that grey-out stuff outside a main focus area - not exactly limiting drawing to being within a certain area, but at least indicating to the user that stuff placed outside of a certain region won't be exported.

**Comment by mimecuvalo** [comment]
The work that @SomeHats mentioned in the previous comment has landed and SDK users can constrain the canvas to be non-infinite! Excited to see what you all build with these new features.
