### ISSUE TITLE
[Bug]:  Can't resolve 'core-js/stable/array/at'

### ISSUE THREAD

**Issue by cnichte** [tldraw/tldraw#1947]
### What happened?

Hi, have installed the npm like so: `npm install @tldraw/tldraw@canary`

an imported tldraw in the render process of my Electron-App, as in your example...

```js
import { Tldraw } from '@tldraw/tldraw'
import '@tldraw/tldraw/tldraw.css'
```

But only get this error on start: 

```
ERROR in ./node_modules/@tldraw/editor/dist-esm/index.mjs 255:0-33
Module not found: Error: Can't resolve 'core-js/stable/array/at' in '.../node_modules/@tldraw/editor/dist-esm'

BREAKING CHANGE: The request 'core-js/stable/array/at' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.

Add the extension to the request.
 @ ./node_modules/@tldraw/tldraw/dist-esm/index.mjs 3:0-31 3:0-31
```

I don't know if this is a bug or if it's me...  Any suggestions?

best regards Carsten

### What browsers are you seeing the problem on?

Chrome

### Contact Details

c.nichte@t-online.de

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by merobal** [comment]
`npm i core-js` (`yarn add core-js`) fixed this issue for me

**Comment by steveruizok** [comment]
https://github.com/tldraw/tldraw/pull/2940

**Comment by steveruizok** [comment]
Landed, should be resolved now!
