### ISSUE TITLE
[Bug]: Can not run local development on Windows by run "yarn dev" at rootDir

### ISSUE THREAD

**Issue by ttlpta** [tldraw/tldraw#1959]
### What happened?

I can not start local development server by run `yarn dev` even after install all dependencies successfully. I tried Window PS, git bash, window command, all are not working
![image](https://github.com/tldraw/tldraw/assets/9917124/355287cb-c74e-4b83-a38c-f457285870f0)

the local server only works when I run `yarn dev` inside folder **apps/examples** and **packages/tldraw**. I think it related to this issue of [lazyrepo](https://github.com/ds300/lazyrepo/issues/87)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mishrababhishek** [comment]
i am also getting the same issue

**Comment by ttlpta** [comment]
the root of this issue is the same to this closed issue https://github.com/tldraw/tldraw/issues/1746#issuecomment-1740468144

I will close this issue.

**Comment by MitjaBezensek** [comment]
> the root of this issue is the same to this closed issue [#1746 (comment)](https://github.com/tldraw/tldraw/issues/1746#issuecomment-1740468144)
> 
> I will close this issue.

Thanks for letting us know 🎉 

@mishrababhishek does this also solve your problem?
