### ISSUE TITLE
Touch: When style menu is open, can't brush on canvas

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1970]
When using a touch device on a small screen...
When style menu is open, you can't brush on canvas.
You can only 'tap'.

To repro:
1. On a touch device... with a small screen...
2. Choose the rectangle tool.
3. Open the style menu.
4. Try to draw a rectangle on the canvas by touching and dragging.

Expected: You can drag to draw a rectangle.
Actual: You can only tap to draw a rectangle.

I'm pretty sure this one is caused by me with one of the fixes I did (#1923). If we can't find a new fix, we could revert the old fix.

**Comment by Taha-Hassan-Git** [comment]
I think this was inadvertently fixed here: https://github.com/tldraw/tldraw/pull/1979
