### ISSUE TITLE
[Chrome] Dotted draw shape rendering issue when zoomed out

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#1995]
When using the dotted option with the draw tool you might not see the shapes you draw if you are zoomed out.

Drawing not rendering on the left where I'm creating the shape, but it is shown on the right in a different browser.
https://github.com/tldraw/tldraw/assets/2523721/dd2e42ed-9646-4cd3-897d-ca843299fb87

**Comment by mimecuvalo** [comment]
Looks like this is ok now, but lemme know if you're still seeing it @MitjaBezensek !

**Comment by MitjaBezensek** [comment]
Still happening. Chrome, 10% zoom, draw tool, Dash - dotted option. Probably a Chrome rendering issue 🤷‍♂️ 

https://github.com/user-attachments/assets/b34aa1c7-88ee-4ae8-ae3f-2ec62546c212

**Comment by mimecuvalo** [comment]
Huh, weird... it works on my machine (why I closed it). Let's figure out what's different on your machine!

**Comment by mimecuvalo** [comment]
I had dynamic size on, is why it was different!
