### ISSUE TITLE
Edit CSS variables

### ISSUE THREAD

**Issue by WillTaylor22** [tldraw/tldraw#2014]
### What's the feature?

Hi team,

I'm probably being stupid here, but is there a way to change the css variables? In my case, setting --color-background to transparent? 

Currently, I'm using a quite hacky:

```
   .tl-container, .tl-canvas, .tl-background{
    background-color: red !important;
  }
```

This doesn't work
```
<div style={{'--color-background': 'red'}}>
 <Tldraw />
</div>
```

Ideally it would look like this?
```
<Tldraw style={{'--color-background': 'red'}} />
or
<Tldraw colorBackground={'red'} />
```

I'm using v2.0.0-alpha.14

### Contact Details

wrftaylor@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Sorry to respond very late :)

You could achieve this by doing:
```
<style>
{`
  .tl-container {
   --color-background: red;
  }
`}
</style>
<div style={{ position: 'fixed', inset: 0 }}>
  <Tldraw/>
</div>
```

Hope that helps!
