### ISSUE TITLE
[bug]: Keyboard shortcuts do not work in vs-code

### ISSUE THREAD

**Issue by ShravanSunder** [tldraw/tldraw#2028]
### What's the feature?

When a shape is selected
- keyboard enter should allow you to write in the shape
- double tap in ipad should allow you to enter text in shape

### Contact Details

github mention

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
I'm not sure about ipad (I don't have one so I cannot test it) but if you select a shape and then hit enter, the state pass on editing shape so it's already implemented

**Comment by ShravanSunder** [comment]
I apologize, 1. is an issue with the vs code plugin, not the web app.  it could be related to https://github.com/tldraw/tldraw/issues/2029

**Comment by judicaelandria** [comment]
I'm still not able to reproduce this, it working fine on my end, which vs code extension are you in?

**Comment by ShravanSunder** [comment]
It looks like none of the keyboard shortcuts work in the extension for me in vscode
- i'm using https://marketplace.visualstudio.com/items?itemName=tldraw-org.tldraw-vscode
- i've tried disabling all extensions and using a clean env
- everything else about the app is working.  
- on the tldraw webapp my keyboard shortcuts work

thanks @judicaelandria 

![2023-10-09 1035 Brave Browser Feature  Writing easily in shapes · Issue #2028 · tldrawtldraw](https://github.com/tldraw/tldraw/assets/5294949/48872fe2-6e79-4e2e-affe-58dae29ac3b6)

**Comment by thiagobraddock** [comment]
Hey @ShravanSunder and @judicaelandria I'm experiencing the same issue. I'm using Mac OS Sonoma with VSCODE Version 1.83.1. In the extension on VSCODE, it's not possible to DELETE, DUPLICATE, or use any shortcuts.

**Comment by thiagobraddock** [comment]
So, If I roll back to version **2.0.11**, it works.

**Comment by judicaelandria** [comment]
Hey I looked at it again and something I found is that this only happen when we use the cmd `tldraw: New File` but if you open or create a tldraw file manually the keyboard shortcuts should work.
maybe, I'm not sure but the cmd `tldraw: New File` has an issue with autoFocus
cc @steveruizok

**Comment by ShravanSunder** [comment]
@judicaelandria It also doesn't work for me if i create a new file
- vs code new file
- name it x.tldr

still same issul

**Comment by ShravanSunder** [comment]
changed the title to reflect the issue

**Comment by changemewtf** [comment]
Same as @ShravanSunder I am using that extension and have tried without other extensions enabled. The keys work fine in the browser version.

@thiagobraddock's workaround fixed the issue for me. I right-clicked tldraw in the Extension list and selected "Install another version..."; in 2.0.11 the keyboard shortcuts are now working for me.
