### ISSUE TITLE
[Bug]: Visual Code shortcuts

### ISSUE THREAD

**Issue by ShravanSunder** [tldraw/tldraw#2029]
### What happened?

- undo redo shortcuts don't seem to work in visual code extension

### How can we reproduce the bug?

1. Create a drawing and a shape
2. delete a shape
3. try to hit cmd-z in mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Looks like this has been fixed. Thanks for reporting!
