### ISSUE TITLE
Palm hits still firing before pen

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2048]
1. Using the pen
2. Rest palm against screen
3. Draw with the pen

expected: The initial palm marks will be erased
actual: they remain

**Comment by Taha-Hassan-Git** [comment]
Originally reported here: https://github.com/tldraw/tldraw/issues/1436

**Comment by mimecuvalo** [comment]
dupe of https://github.com/tldraw/tldraw/issues/1436, as mentioned above
