### ISSUE TITLE
Google maps share links don't work for embeds

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2050]
1. go to google maps
2. find something that has a share link (a pin, whatever)
3. paste into embed view

![Image](https://github.com/tldraw/tldraw/assets/1242537/ae478a52-8048-44e2-9c64-dce62d40c4e2)

**Comment by MitjaBezensek** [comment]
Seems like there's no easy way to get the data for the embed from short links. Others seem to follow the redirect url and then use that one to get the location data https://github.com/discourse/onebox/pull/280/files
