### ISSUE TITLE
Snapshot link doesn't capture the camera position?

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#2052]

**Comment by codingdud** [comment]
Can u provide pictures of problem

**Comment by MitjaBezensek** [comment]
Looks like this one only happens when sharing snapshot links of local rooms, since we don't have the viewport params there.

**Comment by MitjaBezensek** [comment]
Thought I could reproduce this but on second thought I don't think I can. @Taha-Hassan-Git are you still seeing this?

**Comment by assada** [comment]
same issue.

editor.store.getSnapshot() does not return camera object =(

**Comment by kobe651jp** [comment]
Is this problem still unresolved?
I have the same problem.

**Comment by mimecuvalo** [comment]
Looks like this is fixed afaict. 👍
