### ISSUE TITLE
[Bug]: VScode extension menus cover screen

### ISSUE THREAD

**Issue by otter502** [tldraw/tldraw#2063]
### What happened?

I might have found a bug where when a dropdown menu is opened using the vscode extension version of tldraw, all of the drawing section and options are covered / hidden with only the menu being visible.

<img width="956" alt="image" src="https://github.com/tldraw/tldraw/assets/115671877/19f2a3c2-229f-4c3d-b7d6-49e401ff341f">
<img width="961" alt="image" src="https://github.com/tldraw/tldraw/assets/115671877/af0a2110-1b7b-4e2f-8695-735ddec1a1f6">
<img width="952" alt="image" src="https://github.com/tldraw/tldraw/assets/115671877/ca47739d-e376-40b2-b02a-d3c3cebbcfa8">

### How can we reproduce the bug?

steps to reproduce:
1. startup vscode with the tldraw extension found in the extensions menu (id: tldraw-org.tldraw-vscode)
2. press ctrl shift p
3. run the command "tldraw: new file"  
4. once the new file loads click on a dropdown menu button (styles, the shape tool, the sandwich menu)
5. see if you can still see the rest of the document (IE: anything you have drawn )

expected result (based on the web based version of tldraw):
the menu will be opened and the document can be edited (also suggested by the fact that the styles menu has a keep open option)

actual result:
the drawing section and all options (including the debug bar) is hidden and the only thing visible is the dropdown menu. The dropdown menu can be closed by clicking off of it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
Hey @otter502 , you're using the old vs code extension (actually it's the v1 vs code extension) you need to update to get the latest

**Comment by steveruizok** [comment]
Closing this one as we've solved this issue in the new version. Upgrade and you should be good to go!
