### ISSUE TITLE
[Bug]: Keyboard Shortcuts Stopped Working Chrome

### ISSUE THREAD

**Issue by chipallen2** [tldraw/tldraw#2077]
### What happened?

Shortcuts stopped working on the latest chrome. Still works in Firefox.

### How can we reproduce the bug?

Chrome Version 118.0.5993.70 at https://www.tldraw.com/. Create a new project > Hitting D for Draw tool or any other shortcuts does nothing.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chipallen2** [comment]
Actually happens in all browsers. Steps seem to be.

- Open a new tab > go to https://www.tldraw.com/ (with an existing project with stuff in it)
- Shortcuts work!
- File > New

Now shortcuts stop working

**Comment by MitjaBezensek** [comment]
Fixed here https://github.com/tldraw/brivate/pull/3179

Should be fixed with the next release, probably by the end to this week.
