### ISSUE TITLE
[Bug]: Touch: Can't tap off the style menu or context menu

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2079]
### What happened?

When the style menu or context menu is open, you can't touch the canvas to close the menu.

### How can we reproduce the bug?

1. Open the style menu, or context menu.
2. Touch the canvas.

Expected: The menu closes.
Actual: It stays open.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Seems to work for me. Maybe it's a special device?

**Comment by TodePond** [comment]
This was fixed :)
