### ISSUE TITLE
[Bug]: Cropped images can overlap their outline

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2080]
### What happened?

On android, I was cropping an image from the bottom, and it was cropping in large 'jumps' and it overlapped the bottom edge of the image.

It happens reliably when I upload an image on android, but the it can also happen on desktop with large images when zoomed in.

https://github.com/tldraw/tldraw/assets/15892272/73beedbc-a9d9-4fb2-a6f0-13a35afb22c5

<img width="744" alt="image" src="https://github.com/tldraw/tldraw/assets/15892272/7d4d1a96-8a1a-4cea-b427-e5a9886298c8">

### How can we reproduce the bug?

1. Use android chrome to make the bug more visible.
2. Upload a large image.
3. Crop it from the bottom.

Expected: It should crop smoothly and it shouldn't overlap the outline.
Actual: It crops in large 'jumps' and overlaps the outline.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
See fix that we made for regular (not cropped) shapes https://github.com/tldraw/tldraw/pull/2002
