### ISSUE TITLE
Edit link dialog prevents mouse events from working correctly

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#2085]
Could not select shapes, changing tools did change the tool on the toolbar, but I could not use the tools. 

Steps to reproduce:
1. Insert a shape
2. Right click the shape and Edit link
3. Dismiss the dialog
4. Range selection stops working. You can still single click select shapes.

Seems like other tools still work if you use them on top of other shapes, so it sees like it's just the canvas is not receiving pointer events?

https://github.com/tldraw/tldraw/assets/2523721/34ee05ab-4ae6-4d95-88df-ccac0f3df62f

**Comment by steveruizok** [comment]
Should be closed by https://github.com/tldraw/tldraw/pull/2086

**Comment by MitjaBezensek** [comment]
> Should be closed by #2086

Still seems to be an issue.
