### ISSUE TITLE
Selection boxes wrong position in VS Code

### ISSUE THREAD

**Issue by dragonman225** [tldraw/tldraw#2111]
### What happened?

I created a drawing with tldraw website (tldraw.com), and I opened the drawing with tldraw VSCode extension, then I found the selection and resize boxes don't show in the right position and size.

<img width="646" alt="Screenshot 2023-10-22 at 2 33 12 PM" src="https://github.com/tldraw/tldraw/assets/25148955/c6cbabf1-aea2-4b79-a353-a6ba3570eb56">

But if I create a drawing with tldraw VSCode extension from the beginning, this does not happen.

### How can we reproduce the bug?

1. Create a new drawing with tldraw.com
2. Save the drawing to a file
3. Open the file with tldraw VSCode extension

I used Chrome 118.0.5993.96, macOS 13.5.1, VSCode 1.83.1, tldraw extension 2.0.14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
I can't reproduce this issue at the moment, it could be that this has since been resolved.
If however, you're still seeing this please reopen and we'll take a look!
