### ISSUE TITLE
Copy as PNG crashes VS Code and corrupts file

### ISSUE THREAD

**Issue by eklem** [tldraw/tldraw#2112]
### What happened?

Drawing a big drawing in VSCode, and using right-click (ctrl + mouse click since its OSX Sonoma) to get the `copy as PNG` with transparent checked.

After some times, VSCode crashes. After that, the .tldr file seems corrupt. I can't select any part of the drawing (highlights when hovering, but not possible to select with mouse clicking). Also, if I draw a line, it's impossible to stop. I have to close the file to stop drawing the line.

I can open the .tldr file in a browser, and then the same behavior continues. But if I close and open the browser, the file seems okay again, and I can `save as`and open that .tldr file in VSCode again and all is good. The `save as PNG` from the hamburger-menu seems okay.

### How can we reproduce the bug?

Draw a lot of drawings. Happy to send some files (corrupt & not corrupt versions of same file) for debugging.

### What browsers are you seeing the problem on?

Firefox

### Contact Details

espen.klem@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Firefox260** [comment]
I think this is a mac specific issue with the html support for PNG files. I can look into it for you.

**Comment by eklem** [comment]
Should I create a file that reproduces the error?

**Comment by MitjaBezensek** [comment]
I'd love to see an example of this. Could not reproduce it with images I tried.

**Comment by eklem** [comment]
I'll try to set up an example tomorrow! And I'll find out if I still got the same problem =)

**Comment by eklem** [comment]
Ok, try this:

* Fork https://github.com/eklem/draw-to-communicate-workshops
* Clone it to your desktop
* Open up VSCode (with tldraw plugin)
* Open the repository folder in VSCode
* Open the reproduce-test.tldr file
* Click on the drawing of the bike
* Wait a little and VSCode crashes.

I've tested to delete the folder and clone it again and it still happens.

**Comment by MitjaBezensek** [comment]
Thanks for setting this up. I wasn't able to reproduce it on my machine, but will as a few colleagues to try it on their machine.

Browser doesn't really matter in this case, VS Code ships with it's own version of the browser. Maybe you could let us know what VS Code version and what tldraw extension version are you using?

For VS Code you can go under Code -> About Visual Studio code. And for the extension you can go to the extension tab, then select tldraw and you should see it right there.

**Comment by eklem** [comment]
VSCode: 
```
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
```

tldraw: v2.0.21

**Comment by eklem** [comment]
And now it doesn't crash anymore here either. Just gets a little sluggish when hovering after `copy as .png`. Irritating, but still good! I'll give it a couple more tries.

**Comment by MitjaBezensek** [comment]
I notice that you are using Universal version of VS Code, maybe the apple silicon version would help (seems like you are using the apple silicon chip)?

We will also ship [some improvements](https://github.com/tldraw/tldraw/pull/2442) for the copy as png code. We noticed that it is quite slow when using it for the first time. Might be related to the issue you are seeing. Will let you know when we have a new version of the extension ready.

**Comment by eklem** [comment]
Yes, Apple silicon chip. Installed that version now, and I'll test when the new extension is out. Thanks!

**Comment by eklem** [comment]
Anyway, super happy with tldraw!

**Comment by MitjaBezensek** [comment]
Happy to hear that! Let us know if you see this again, can take another look.

**Comment by eklem** [comment]
I'll do! Just close this for now then?
