### ISSUE TITLE
[Feature]: Adding Support for Baisc Offline Function.

### ISSUE THREAD

**Issue by gitiy1** [tldraw/tldraw#2115]
### What's the feature?

Sometimes, users may not require features that depend on an internet connection, such as multi-user collaboration, and instead, they may only need the drawing functionality of a whiteboard, especially in PWA applications, while device using  chromeOS may have no access to the network  some times.
[The Excalidraw project](https://github.com/excalidraw/excalidraw) supports using a whiteboard in offline mode, and I hope that Tldraw can also implement this feature soon! 
Thanks to the developers and the community for their hard work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Hiya, tldraw does indeed have an offline mode. You can setup the editor to behave that way and we also show that when are on a multiplayer room that loses connection!
