### ISSUE TITLE
VS Code extension mouse and keyboard broken

### ISSUE THREAD

**Issue by jhoogeboom** [tldraw/tldraw#2116]
### What happened?

Using tldraw extension v2.0.14 on VSCode version:

```
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z (2 wks ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

Mouse input outside of clicking is ignored, so I cannot pan or zoom. Also keyboard input is ignored, when I click on "A", arrow tool is not started, also backspace does not delete anything.

### How can we reproduce the bug?

Start up VSCode with that version installed, start a new drawing, draw anything and try to pan.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ehaspulat** [comment]
Same problem, cannot copy-paste or delete anything with keyboard.

I just installed the extension and tried to give it a shot for the first time but ran into this problem. Then I saw this issue and downgraded the extension to a random version (2.0.10) and these problems seem to go away.

**Comment by jhoogeboom** [comment]
Oh good point, I tried a few and found that 2.0.12 works, but 2.0.13 has the behaviour I described.

**Comment by jhoogeboom** [comment]
To be more detailed, 2.0.12 is able to open tldrawings that were made with earlier versions and there it works ok. But if you create a new drawing with 2.0.12, it also does not work.

**Comment by zxzjim** [comment]
same here, shortcuts and trackpad gestures on v2.0.14 are also not working, please fix it...

**Comment by ShravanSunder** [comment]
related to #2028

**Comment by mikanIchinose** [comment]
same issue at v2.0.15
