### ISSUE TITLE
[bug] App hangs on iPad 

### ISSUE THREAD

**Issue by emiltamas** [tldraw/tldraw#212]
Here are two videos with the issue. 

https://vimeo.com/640237059
https://vimeo.com/640237017

*Some* steps to repro:

– Add a shape (note, rect, text)
– Type a few things
– Select/deselect 
– Perhaps put palm on the screen

Results:
– Apps enters unresponsive state. I can zoom/pan around but nothing else works.

**Comment by steveruizok** [comment]
Fixed!
