### ISSUE TITLE
[Feature]: Adding features regarding BG Changing and Erasing

### ISSUE THREAD

**Issue by TheDarkSoulster** [tldraw/tldraw#2134]
### What's the feature?

Make the user be able to change the background color, and change the background to an image. Consider adding another feature, where the eraser tool can erase those parts which it is taken over, since it is too much of a punishment for people with a cursive handwriting to erase the entire word just for one small mistake. Talking about erasing; how about a feature which can detect palm of a user, for larger screens? If the palm is detected, it spawns a larger eraser under, kind of like a duster on a whiteboard.

I appreciate you reading until here, and hope to see these features implemented.
Thank you.

### Contact Details

saket.dhulipala.vibgyorschools@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Thanks for the feedback, I'm going to close this bug and refer you to these other bugs that split out your requests - you can Subscribe to them for any updates as they get looked at!

- background: https://github.com/tldraw/tldraw/issues/2245
- erasing: https://github.com/tldraw/tldraw/issues/2671
- palm: https://github.com/tldraw/tldraw/issues/1436
