### ISSUE TITLE
[Bug]: Global CSS cannot be imported from within node_modules in Next.js

### ISSUE THREAD

**Issue by TheKnarf** [tldraw/tldraw#2135]
### What happened?

I tried using the `@tldraw/tldraw` package in a Next.js project.
Using the following import in my project:

```javascript
import { Tldraw } from '@tldraw/tldraw';
```

Produces the following error:

```
Failed to compile
../node_modules/@fontsource/caveat-brush/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../node_modules/@tldraw/tldraw/dist/index.mjs
```

### How can we reproduce the bug?

Tried using tldraw in a next.js project with the following versions taken from my `package.json`:

```
    "@tldraw/tldraw": "^1.29.2",
    "next": "^13.0.4",
    "react": "^18.2.0",
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheKnarf** [comment]
I didn't read the docs fully, where it said to use `@tldraw/tldraw@alpha`.
When doing so the above problem goes away and is replaced with:

```
Error: Cannot find module '/Users/knarf/projects/drawpresenter/node_modules/@tldraw/editor/node_modules/core-js/stable/array/at' imported from /Users/knarf/projects/drawpresenter/node_modules/@tldraw/editor/dist-esm/index.mjs
Did you mean to import core-js/stable/array/at.js?
```

**Comment by judicaelandria** [comment]
https://github.com/tldraw/tldraw/issues/2133

**Comment by TheKnarf** [comment]
Ah ok, closing this as a duplicate then.
