### ISSUE TITLE
Actions menu stays open after grouping

### ISSUE THREAD

**Issue by i-faraz-ahmed** [tldraw/tldraw#2139]
### What happened?

I just saw a bug related to "actions menu". Whenever I group/ungroup some shapes, right after this action If I click anywhere on the canvas, the actions menu does not close. 
Normally it does close on clicking the canvas..

https://discord.com/channels/859816885297741824/859816885801713729/1169308232234303589

### How can we reproduce the bug?

https://www.loom.com/share/57b212ecda2743e1acd791ea66a24dae?sid=88a9cdc1-86d7-4fae-8494-db430f74aff8

![image](https://github.com/tldraw/tldraw/assets/43345962/aa7373ae-7d02-4e2f-9a57-2cc14b5821b4)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Contact Details

faraz1340@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Fix in the next version!

**Comment by steveruizok** [comment]
#2187
