### ISSUE TITLE
[Bug]: Cursor disappears while typing text

### ISSUE THREAD

**Issue by jonstvns** [tldraw/tldraw#2146]
### What happened?

While zoomed out on the canvas and typing in a text element, the text cursor sporadically disappears. 

I could only reproduce this issue on Firefox, and it's the same issue I've encountered on Miro under the same scenario. It's likely related to this very old, unresolved bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=226301

Video of the issue:
[tldraw_cursor_disappear.webm](https://github.com/tldraw/tldraw/assets/1030863/257ee2a7-6dd4-48f6-b3f2-9efa19c9f54b)

### How can we reproduce the bug?

1. Zoom out to 80%
2. Place a text element
3. Write a length of text
4. Watch the cursor occasionally disappear
5. Stop typing
6. Navigate the cursor around the text
7. Watch the cursor occasionally disappear

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
I took a short look and we don't seem to be doing anything custom here so I'd say it's very likely the linked bug. Thanks for reporting this and also for the link, super helpful.

**Comment by steveruizok** [comment]
Closing this one, Firefox has some quirks and this looks to be one of them. Thanks @jonstvns
