### ISSUE TITLE
[Bug]: PDF Export Frame Broke

### ISSUE THREAD

**Issue by calebeby** [tldraw/tldraw#2147]
### What happened?

This was working as of a few weeks ago but now it doesn't work correctly.

Here is my document: https://www.tldraw.com/r/hkRFOW-UWjju0xg8r3L4j?viewport=594,2922,3331,1893&page=page:OS7K6JByaiADITjPQu0bO

Previously, I could have nothing selected and do ctrl+p to do a PDF export. It would fit everything into the PDF viewport and it worked great! Now it exports like this:

![image](https://github.com/tldraw/tldraw/assets/13206945/f9386632-9f83-48d5-bf52-82eeda9333eb)

It looks like the TLDraw UI is rendered on top of the part that is intended to be exported (the "this is an example" text.

Additionally, previously I was able to select a single frame to export just the content in that frame. This workflow used to work really well for me to set up documents/worksheets for my teaching. Now, it has a similar ui-rendering-on-top issue (if I select frame 1 and then do ctrl+p):

![image](https://github.com/tldraw/tldraw/assets/13206945/95c833b1-f5c0-4fa9-a0f4-fa86811af6de)

I'd appreciate however you are able to fix this! I assume it was some sort of small CSS change that affected the print output that wasn't tested.

Thanks for this great product I use it all the time!

- Caleb :)

### How can we reproduce the bug?

https://www.tldraw.com/r/hkRFOW-UWjju0xg8r3L4j?viewport=594,2922,3331,1893&page=page:OS7K6JByaiADITjPQu0bO

Select "frame 1"

Ctrl+p or cmd+p

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jatin-Ahirwar** [comment]
i am getting this same issue this is my code 
import React from 'react';
import { FaRegFilePdf } from 'react-icons/fa';

const PrintPdf = () => {
    const handleClick = () => {
        window.print(); 
    };

    return (
        <button
            onClick={handleClick}
            className="absolute top-0 left-[22%] z-[999] bg-[#EDF0F2] text-black font-bold py-3 px-4 rounded-br hover:bg-[#E3E6E8] transition duration-200"
        >
            <FaRegFilePdf />
        </button>
    );
};

export default PrintPdf;

import React from 'react';
import { Tldraw } from 'tldraw';
import PrintPdf from './PrintPdf'; // Import the renamed PrintPdf component

const Whiteboard = () => {
  return (
    <div className="h-[100vh] w-[100vw] relative">
      <Tldraw />
      <PrintPdf /> {/* Use the PrintPdf component */}
    </div>
  );
};

export default Whiteboard;
 
![Screenshot (2)](https://github.com/user-attachments/assets/1615e29f-2743-48d7-ac2b-908a455beb6d)
