### ISSUE TITLE
Text in geo shapes is not centred

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2156]
1. Create a small-ish geo shape.
2. Add a text label.
3. Start typing.

If it doesn't happen, try making the shape smaller, or type more!

Some examples here
https://staging.tldraw.com/r/deploy-2023-11-07?viewport=0,0,853,1302&page=page:bv1533422fvZVpezYNPAC

![Image](https://github.com/tldraw/tldraw/assets/2523721/6d997e8a-2c03-466f-bb45-c4faf0d9399b)

It's even worse with mono font

![Image](https://github.com/tldraw/tldraw/assets/2523721/fd4e5ad6-433e-4396-a31f-e39b3d90391f)

**Comment by TodePond** [comment]
![Image](https://github.com/tldraw/tldraw/assets/15892272/31b88ea9-c5a1-4a43-a70d-6e79bc5d5571)
