### ISSUE TITLE
[Bug]: If you hideUi, text tool it's borked and slow. Cursor jumps to end

### ISSUE THREAD

**Issue by irg1008** [tldraw/tldraw#2190]
### What happened?

When hiding default ui, everything works as expected except for the *text tool*. When using this tool the text element looks like it's being re-rendered multiple times. This makes the text tool unusable. When you start typing, the cursor jumps to the end and sometimes moving with the keyboard through the text does not work either.

In the Custom UI example in the stackblitz happens as well.

### How can we reproduce the bug?

1. Go to the stackblitz examples.
2. Then go to "Custom UI"
3. Create a text shape
4. Type something (be careful of hotkeys or disable to test)
5. Try moving the cursor around with the keyboard

You can see just by using it that there are tons of glitches and blinking happening

https://github.com/tldraw/tldraw/assets/47559427/146d4ba7-9459-4f6c-89ac-38c551532e62

### What browsers are you seeing the problem on?

Chrome

### Contact Details

ivansudevlop@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
It seems like this might be a bit better now? Could you please try it again?

**Comment by irg1008** [comment]
But there is no update for three weeks. This issue was created using the latest available version 🤔

**Comment by MitjaBezensek** [comment]
There's a PR from 5 days ago that updated Custom UI Example
https://github.com/tldraw/tldraw/pull/2253

**Comment by irg1008** [comment]
Oh I see, Thanks
