### ISSUE TITLE
[Bug]: Can not drag an item from the dock

### ISSUE THREAD

**Issue by vladfaust** [tldraw/tldraw#2194]
### What happened?

I can't drag an item from the dock.

https://github.com/tldraw/tldraw/assets/7955682/65aafc43-c10c-4226-acbb-95a6c95b5e91

### How can we reproduce the bug?

Try dragging anything from the dock on the canvas.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Our UI works a bit differently. You select the tool that you want. You can then click or drag on top of the canvas to use that tool.

https://github.com/tldraw/tldraw/assets/2523721/3a197363-0128-4d22-bb26-e6cbdb761b2b




That said if we do decide to add a library of objects you could add to the whiteboard it would probably make sense to allow them to be dragged in.
