### ISSUE TITLE
[Bug]: You can sometimes see two submenus in the main menu

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#2195]
### What happened?

If you move the mouse quickly between different menus you can sometimes see two submenu items at the same time.

### How can we reproduce the bug?

[InsideOfEditorContext](https://github.com/tldraw/tldraw/assets/2523721/84967987-98e5-4d05-b107-4446a97145a3)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by keshari1arya** [comment]
Hello, @MitjaBezensek , I've attempted to replicate the issue using Chrome, Firefox, and Brave browsers, but I haven't encountered it. Could you please provide more details or check if the problem still persists on your end?

**Comment by mimecuvalo** [comment]
I tackled this a while back :) Should be fixed!
