### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by powerdot** [tldraw/tldraw#2196]
### What happened?

Performance issues occur in a document with many shapes:
Drawing and camera movement starts to slow down on the iPad Pro (2018), iPadOS 17.0.3, Safari.

https://www.tldraw.com/r/iimW-GTfGCn9nRofmlJqx?viewport=733,1107,2175,1191&page=page:page

### What browsers are you seeing the problem on?

Safari

### Contact Details

donpsix@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
We are aware of this issue with multiple shapes. As a temporary workaround we now have an option to flatten shapes. This takes the selected shapes and creates one image out of them. The shapes are not editable any longer, but it should help with performance.
