### ISSUE TITLE
Arrow binding to shapes inside frame

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#2204]
### What happened?

Looks like binding the arrow to a shape within a frame leads to some undesired results.

### How can we reproduce the bug?

1. Create a frame
2. Create a shape inside of it
3. Create an arrow inside of the frame and bind it to the shape.

https://github.com/tldraw/tldraw/assets/2523721/99a51d45-0a6e-4bf2-8f39-d72bfa1dd0bd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrielchl** [comment]
(a temporary solution would be to start the arrow with alt-click, so alt-click and hold, then release on the target, this makes the arrow starting point not the middle of the frame but the actual point you clicked in the frame, it seems to give better results, for now)

**Comment by keshari1arya** [comment]
Yeah only press and hold click or ctrl + click gives desired result.
so are we considering this as a bug?

**Comment by MitjaBezensek** [comment]
Yes, there's work in progress on this here https://github.com/tldraw/tldraw/pull/2265
