### ISSUE TITLE
[Feature]: Change the color of the status bar in dark mode

### ISSUE THREAD

**Issue by atychang** [tldraw/tldraw#2209]
### What's the feature?

When "tldraw.com" is added to the iPhone/iPad home screen and dark mode is enabled, the status bar remains white.

![IMG_D850407D2955-1](https://github.com/tldraw/tldraw/assets/13390788/7cabe71d-088f-4716-bbf6-71ee7d6c196d)

It would be nice if we could change the color dynamically. We can do that by changing the content of [theme-color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) when the light/dark mode is changed.

### Contact Details

allen.ty.chang@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tiwaritech18** [comment]
Hi everyone! I'm interested in contributing to this feature. I see that the status bar color in dark mode for "tldraw.com" is currently an issue. I would like to take on the task of changing the color dynamically based on the light/dark mode. Any guidance or suggestions on how to approach this would be appreciated!

**Comment by tiwaritech18** [comment]
Hi everyone! I noticed the feature request to change the status bar color dynamically in dark mode #2209. I'm interested in working on this and would like to contribute to the implementation. If there's any guidance or specific considerations, please let me know. Looking forward to being part of this enhancement!
