### ISSUE TITLE
[Bug]: The pencil not work when move above or left of stat drawing point

### ISSUE THREAD

**Issue by haipdminu** [tldraw/tldraw#2226]
### What happened?

When use select pencil tool and start drawing on the screen. If the mouse moved to the left or above the staring drawing point, the drawing content will bot be filled.
![image](https://github.com/tldraw/tldraw/assets/135192499/234ab322-1eb9-49ff-a456-a4d5250bf1ad)

### How can we reproduce the bug?

It is happening on version 2.0.0-alpha.18 and can be easy checked on the demo 
https://www.tldraw.com/

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Likith123** [comment]
Hi @haipdminu , it seems working fine. Please check again.

**Comment by haipdminu** [comment]
Thank you @Likith123, i just take a deeper look. The error only happen with the Chrome browser on Ubuntu. We can close it. It may come from the browser.
