### ISSUE TITLE
[Feature]: Is it possible to make a static build?

### ISSUE THREAD

**Issue by waldenn** [tldraw/tldraw#2237]
### What's the feature?

Hi, would it be possible to avoid the server-side code (including live-sharing functionality) and only build a working client-side version of tldraw?

I would prefer that, since it the deploy is much easier in my context. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irg1008** [comment]
> You can take a look at our BasicExample. It does just that
> 
> https://github.com/tldraw/tldraw/blob/main/apps/examples/src/BasicExample.tsx

I don't see how the basic example does just that or how does ir relates to static build

**Comment by MitjaBezensek** [comment]
> > You can take a look at our BasicExample. It does just that
> > https://github.com/tldraw/tldraw/blob/main/apps/examples/src/BasicExample.tsx
> 
> I don't see how the basic example does just that or how does ir relates to static build

Use vite app just like we do there and use tldraw as we do in the BasicExample and you will get a client side only app, no server or api needed. Once you build it you will end up with just static files in `dist` folders, which you can easily host as a static website. By default our app does not do any fetching, it stores the data to local storage.

But maybe I'm missing something?

**Comment by waldenn** [comment]
Tried it out and it works great! Thank you @MitjaBezensek and others!
