### ISSUE TITLE
[Bug]: is my button being covered? Using M3 Pro 14"

### ISSUE THREAD

**Issue by AntDX316** [tldraw/tldraw#2241]
### What happened?

My button is covered?
![Screenshot 2023-11-19 at 4 57 01 AM](https://github.com/tldraw/tldraw/assets/34279421/801a77e9-3982-4e60-b433-d667edae9980)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

The Make Real button is missing..
At least have the ability to move the top right menu?

I've tried Safari and tried different screen sizes and fullscreen. It's still broken.

**Comment by AntDX316** [comment]
How do I do the Make Real?

**Comment by gabrielchl** [comment]
the repository is here https://github.com/tldraw/draw-a-ui
and the deployed version is here https://makereal.tldraw.com/

**Comment by AntDX316** [comment]
> the repository is here https://github.com/tldraw/draw-a-ui and the deployed version is here https://makereal.tldraw.com/

The Make Real button is missing. : (

**Comment by prakashkbd** [comment]
``
![Uploading IMG_20231122_193244.jpg…]()

**Comment by prakashkbd** [comment]
Hlo sir

**Comment by prakashkbd** [comment]
Data entry

**Comment by gabrielchl** [comment]
> > the repository is here https://github.com/tldraw/draw-a-ui and the deployed version is here https://makereal.tldraw.com/
> 
> The Make Real button is missing. : (

no it is not https://makereal.tldraw.com/

**Comment by AntDX316** [comment]
How come on the macbook is broken?

**Comment by gabrielchl** [comment]
> How come on the macbook is broken?

no it is not broken, on any devices
the website is here in this link: https://makereal.tldraw.com/
and the code for that website is here in this link: https://github.com/tldraw/draw-a-ui (it's separate from the code repository this issue is currently in)

**Comment by MitjaBezensek** [comment]
We have separate repos for that. 

Make real is the repo that is hosted on `makereal.tldraw.com`
https://github.com/tldraw/make-real

And if you want to play around with it you should look into the starter repo:
https://github.com/tldraw/make-real-starter

**Comment by AntDX316** [comment]
> We have separate repos for that.
> 
> Make real is the repo that is hosted on `makereal.tldraw.com` https://github.com/tldraw/make-real
> 
> And if you want to play around with it you should look into the starter repo: https://github.com/tldraw/make-real-starter

This is what I was looking for.
