### ISSUE TITLE
[Bug]: Recover lost projects

### ISSUE THREAD

**Issue by feresr** [tldraw/tldraw#2243]
### What happened?

I believe that clearing the chrome cache deleted all of my projects. 
They were not "shared" projects. They lost forever, aren't they? 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Yeah, if they weren't shared then they were only stored locally on your computer. Clearing the cache then removed them 😞 

We do want to offer saving your work on our servers in the future.
