### ISSUE TITLE
[Documentation]: ExplodedExample.tsx does not provide default components for resize handles and whatnot

### ISSUE THREAD

**Issue by codenamegary** [tldraw/tldraw#2246]
### What happened?

When rendering a tldraw editor in an exploded manner, resize handles and selection components are not loaded. Shapes cannot be resized.

I will submit a PR to update it.

### How can we reproduce the bug?

https://examples.tldraw.com/exploded

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Contact Details

gary@powrit.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Hm, this seems to be working ok: https://examples.tldraw.com/exploded
Quite possible that it was an issue and since resolved. Let us know though if you're still seeing a problem!
