### ISSUE TITLE
[Bug]: Cropped images are positioned incorrectly when exported

### ISSUE THREAD

**Issue by myandrienko** [tldraw/tldraw#2254]
### What happened?

When page contains a cropped image, it's positioned incorrectly when exported.

Here's an example page containing two images, one of them cropped:

![page](https://github.com/tldraw/tldraw/assets/975978/dddd4bda-41b9-441a-b8d4-9d5b52114ed6)

This is an expected export result:

![expected](https://github.com/tldraw/tldraw/assets/975978/890e561b-3162-4783-bf10-cdee55a3a9e9)

This is an actual export result:

<img width="1064" alt="actual" src="https://github.com/tldraw/tldraw/assets/975978/df1fabb5-d33c-423d-acc7-15af618710af">

### How can we reproduce the bug?

Reproduction project: https://www.tldraw.com/r/khidz2Q97fC4Q0uN8waQY?viewport=-236%2C-162%2C1652%2C1111&page=page%3Apage

1. Add an image
2. Crop it
3. Export it (as PNG in my case)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Contact Details

m.y.andrienko@outlook.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Thanks for reporting this, opened a PR for this, will probably land with the next update.
