### ISSUE TITLE
Double-click to erase

### ISSUE THREAD

**Issue by MananGandhi1810** [tldraw/tldraw#2256]
### What's the feature?

Like the Apple Pencil's double tap to erase feature, I propose to add a double right click to switch to eraser feature.

### Contact Details

ardumanan@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irg1008** [comment]
You can do this pretty easy on your own. You pick the double tap event and swap the tool:

```typescript
  const tools = useTools();

editor.on("event", (e) => {
	if (e.name === "double_click") {
    // Maybe check if double clicking on empty space or no shapes are selected
    if (editor.selectedShapes.length > 0) return;
    editor.setCurrentTool("eraser") // Or any other wanted tool
  }
});
```
