### ISSUE TITLE
[Feature]: Disable context menu

### ISSUE THREAD

**Issue by irg1008** [tldraw/tldraw#2276]
### What's the feature?

How can i disable context menu to prevent users from using the context menu at all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
You can already do that with ui overrides. It includes a `contextMenu` [override](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/ui/overrides.ts#L64).

Looking at our custom config example, you can go to `ui-overrides.ts` and add this for the [context menu override](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/CustomConfigExample/ui-overrides.ts):
```typescript
	contextMenu(_app, _contextMenu, _other) {
		return []
	},
```

**Comment by irg1008** [comment]
That works, but prevents native browser context menu from appearing at all 🤔
