### ISSUE TITLE
[project] Desktop App

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#228]
This issue tracks the progress on a desktop app for TLDraw. 

## Motivation

The repo contains a folder named `electron` when you can find an electron app for TLDraw. Electron is a technology that allows web-apps to be distributed as native applications. If you haven't heard of electron apps, you almost certainly have used them: Slack, Figma, Discord, and may others use electron to distribute applications across platforms.

There are several reasons why we might consider an electron app for TLDraw. Unlike the web-app, an electron app has full access to node at runtime, which allows for a native interaction with the file system (opening and saving files). There are other APIs that the browser doesn't support, even with modern PWAs. At the expense of a larger download, an electron app can provide a guaranteed browser experience as it ships with its own chromium engine. And while nothing is as easily distributed as a website, a downloadable app offers many opportunities for distribution. Downloading an electron app may be easier to understand for some users.

An electron app may also eventually be an opportunity to monetize. I want TLDraw to remain free, of course; but I also want users to have opportunities to support its development. At this point, the unique aspects of TLDraw do not need to be in its functionality (though obviously it should do those things well), rather its sell should be in the care and quality of those experiences. Combined with the community support aspect of TLDraw, downloading a desktop application—and getting its minor improvement on the UX—could be worth the ten bux.

## Requirements

For TLDraw, we would need our app to minimally support:
- The same menu actions as the regular app
- Creating, opening and saving files
- A clear divide between "local mode" windows and "multiplayer mode" windows
- Support for multiple windows, each for a file or multiplayer file

## Next Steps

I'm going to be hacking on the electron app for TLDraw when I can—but hopefully not on my own! I invite anyone interested to join this discussion. I'm not wedded to electron as a technology and am open to alternatives, however electron is where I personally have the most experience.

**Comment by zakaria-chahboun** [comment]
PWA is the best choice

**Comment by steveruizok** [comment]
We do have PWA support! But it is still somewhat limited compared to an Electron app, so worth exploring here.
