### ISSUE TITLE
[Feature]: Disabling context menu should allow for native menu to show up

### ISSUE THREAD

**Issue by irg1008** [tldraw/tldraw#2281]
### What's the feature?

Currently disabling context menu disables the native menu from showing at all. Could we be able to prevent the event from propagating and show native menu instead?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
You can disable the context menu to get the native menu like so:

```
const components: TLComponents = {
	ContextMenu: null
}

export function MultiplayerEditor() {
	return <Tldraw components={components} />
}
```

Hope that helps and sorry for the late reply :)
