### ISSUE TITLE
Selected shape shows wrong border in VS Code

### ISSUE THREAD

**Issue by editfund-founder** [tldraw/tldraw#2283]
### What happened?

Condition:
```
OS=Windows10
VScode Extension=tldraw-v2.0.17
Windows 10 Display Settings ➝ Zoom & Layout=150%
```
Bug:
```
The selected graph displays the wrong border. （VSCode Extension:tldraw-v2.0.17)
```

![bug-img](https://github.com/tldraw/tldraw/assets/61936162/dc65c871-786a-45f7-b11d-920324fec090)

### How can we reproduce the bug?

1. Windows 10 Display Settings ➝ Zoom & Layout=150%.
2. start VSCode(extension tldraw)➝The bug appear.
3. Windows 10 display settings ➝ Zoom & Layout=100%➝The bug disappears.
4. Windows 10 display settings ➝ Zoom & layout=150%.➝The bug did not appear.
5. restart VSCode(extension tldraw)➝ The bug has reappeared.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by editfund-founder** [comment]
#2111

**Comment by mimecuvalo** [comment]
Similar to #2111 I couldn't reproduce this issue at the moment, it could be that this has since been resolved.
If however, you're still seeing this please reopen and we'll take a look!
