### ISSUE TITLE
small spacing in exit pen mode, and back to content buttons?

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2285]
Looks like the spacing in these buttons is a bit small?

![Image](https://github.com/tldraw/tldraw/assets/15892272/cfd119ed-afe2-447f-af36-c69829d85fe8)

**Comment by MitjaBezensek** [comment]
Fixed here https://github.com/orgs/tldraw/projects/27/views/1?pane=issue&itemId=46647098
