### ISSUE TITLE
jumpy arrows (sometimes? over multiplayer?) when rotating grouped shapes

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2291]
Not sure how to reproduce this one

![Image](https://github.com/tldraw/tldraw/assets/1489520/a9f0a942-da2f-46bc-a010-b0de6341ea23)

**Comment by mimecuvalo** [comment]
I think this is the same as https://github.com/tldraw/tldraw/issues/2160
closing as dupe of that one
