### ISSUE TITLE
[Bug]: Arrows without target are not rendered in the PNG export

### ISSUE THREAD

**Issue by angaz** [tldraw/tldraw#2305]
### What happened?

The arrow should be rendered in the PNG export.

### How can we reproduce the bug?

1. Draw a rectangle
2. Draw a frame around it
3. Draw an arrow coming out of the box, but without a target
4. Export the frame as PNG

The arrow is missing

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by angaz** [comment]
It looks like the arrow is not part of the frame, because if I duplicate the frame, the arrow is not part of it.

**Comment by Steffo99** [comment]
I think I stumbled on this bug too with the attached frame.

[Example JSON Export](https://github.com/tldraw/tldraw/files/13626110/Grafo.iniziale.1.json)

Exporting as PNG is fine on Chromium:

<img width="1082" alt="Lines are rendered perfectly" src="https://github.com/tldraw/tldraw/assets/1540885/5a2e50ac-916d-43e8-8878-97280e110d4e">

But on Firefox 120 it exports as follows:

<img width="1082" alt="Lines are rendered only partially" src="https://github.com/tldraw/tldraw/assets/1540885/13c93e2c-a528-49b4-8623-dcda66740e3c">

Seems related to how Firefox renders SVGs; when exporting to SVG from any browser, Chrome renders them as in the former image, while Firefox renders them as in the latter.

**Comment by MitjaBezensek** [comment]
@angaz would you expect the arrow to point to nothing in this case? Or also the to the element it is attached to? 

The logic now is to only show the elements that are inside the frame (without showing the frame itself). One thing you an do is to select both the frame and the arrow and then do the export. But that will show the frame as well, not sure if you'd like that.

@Steffo99 Could you send me the `.tldr` file of this? Just go to `File -> Save a copy` to create it.

**Comment by angaz** [comment]
@MitjaBezensek pointing at nothing. I want to indicate a request leaving the network, just have the arrow point towards the edge of the frame to indicate that.

I tried selecting both the frame and the arrow and it didn't make a difference, at least, on Firefox. Should I try on Chrome?

**Comment by angaz** [comment]
Ok, this is weird, it's working now, even in firefox, so I don't know what I was doing wrong before because I'm 100% sure I tried this, and it didn't work. Makes no sense.

https://www.tldraw.com/s/v2_c_VGQororSS3pQU1YvHR75s?viewport=0%2C0%2C2556%2C1297&page=page%3Apage

Select all
<img width="974" alt="shapes at 23-12-11 16 01 05" src="https://github.com/tldraw/tldraw/assets/10219618/d2e9f6df-e7d5-42b1-b56b-52a718963c7c">

Only frame
<img width="910" alt="png" src="https://github.com/tldraw/tldraw/assets/10219618/062e64d7-23e2-4f9c-84ca-c2fa247e9e36">

I'll have to crop the first one, but it's not the end of the world, at least the arrow is rendered.

**Comment by MitjaBezensek** [comment]
Oh, that's a nice catch. I seems like that arrow is bound (attached) to the frame, but it is not parented to the frame. 

I'll see if there's something we can do in this case. Looks like if you creating arrows inside the frame is different than creating them outside then dragging them in. 

https://github.com/tldraw/tldraw/assets/2523721/aca09266-c5ed-4312-87de-2f01c95a4a3f

**Comment by angaz** [comment]
Yeah that is interesting. I created the arrow in the opposite direction, but I guess the result is the same.

**Comment by Steffo99** [comment]
@MitjaBezensek Here you go!

As you can see in the image below, the only lines not being rendered correctly are the ones which don't have endpoints on either side nor labels.

**[Untitled.tldr.zip](https://github.com/tldraw/tldraw/files/13641544/Untitled.tldr.zip)**

<img width="1082" src="https://github.com/tldraw/tldraw/assets/1540885/a6914e6e-ab76-461b-b602-707491acb4a8">

**Comment by Ch1sKey** [comment]
Have few thoughts about this issue. Please check #2319 https://github.com/tldraw/tldraw/pull/2319
I guess it is a step in right direction
