### ISSUE TITLE
Add font weight to text styles

### ISSUE THREAD

**Issue by navaru** [tldraw/tldraw#2307]
### What's the feature?

I would like to have the ability to change the font-weight: [Light | Regular | Bold].

I've looked at the implementation for text size editing, I could create a PR and implement this feature.

PS: Great product! I would appreciate it if this would be taken into consideration.

### Contact Details

eugen.tudorancea@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
I'll close this one in favor of #1879
