### ISSUE TITLE
Text not vertically centered in hexagon

### ISSUE THREAD

**Issue by peilingjiang** [tldraw/tldraw#2309]
### What happened?

The text inside the hexagons is not vertically aligned.

![tldraw](https://github.com/tldraw/tldraw/assets/25191575/db75bd8d-c16c-48cb-ad0f-d2e8c823ad96)

### How can we reproduce the bug?

Create a hexagon shape, double-click, and type in text.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trinhtuanvy** [comment]
Thanks

**Comment by peilingjiang** [comment]
Related to #1924 and #1927. It seems the previous patch didn't fully resolve the issue.

**Comment by mishrababhishek** [comment]
is this issue resolved if not i would like to work on this issue

**Comment by MitjaBezensek** [comment]
@mishrababhishek this is still an issue, feel free to go ahead! I think the issue is something similar the star shape. Here's how we handle that https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx#L161-L201

**Comment by mishrababhishek** [comment]
I Have fixed the issue in local dev environment but i am not able to push the changes because there is an error in test of build-types::<rootDir> ∙ ERROR ∙ failed

**Comment by anugoyal998** [comment]
Is this issue resolved? I would like to work on it.

**Comment by steveruizok** [comment]
Take a shot!

**Comment by SomeHats** [comment]
Fixed in #2378
