### ISSUE TITLE
Edges of thin shapes should be draggable while cropping

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#2314]
When a cropping shape is really thin, we only show 2 crop corner handles.
When this happens, you can't drag the shape's long edges to crop.
We should allow to drag those edges.

![Image](https://github.com/tldraw/tldraw/assets/15892272/03a4c653-67c9-45de-b3ac-b1807b15950c)

**Comment by MitjaBezensek** [comment]
This kinda seems intentional in code. I guess with very narrow shapes the left and right resize handle can get quite close to each other and it might be hard to select the right one.

@steveruizok what's your take on this?

**Comment by mimecuvalo** [comment]
Yeah I agree with @MitjaBezensek that this is intentional, otherwise things start getting too tight to click on.
