### ISSUE TITLE
[Bug]: useEffect can't get the editor by useEditor

### ISSUE THREAD

**Issue by BadHuang** [tldraw/tldraw#2317]
### What happened?

I can't get the editor by useEditor in useEffect

### How can we reproduce the bug?

```
export default function App() {
	const editor = useEditor()
	useEffect(() => {
		console.log('Tldraw OnReady', editor);
	}, [editor]);

	return (
		<div className="editor">
			<Tldraw
				persistenceKey="make-real"
				// shareZone={<MakeRealButton />}
				shapeUtils={shapeUtils}
			>
				{/* <TldrawLogo /> */}
				{/* <RiskyButCoolAPIKeyInput /> */}
			</Tldraw>
		</div>
	)
}
```

the editor is a empty object

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by merobal** [comment]
Try this way (you need to be inside the context of the Tldraw Editor):

```
function ReachEditor() {
	const editor = useEditor()
	useEffect(() => {
		console.log('Tldraw OnReady', editor);
	}, [editor]);

	return null;
}

export default function App() {
	return (
		<div className="editor">
			<Tldraw
				persistenceKey="make-real"
				// shareZone={<MakeRealButton />}
				shapeUtils={shapeUtils}
			>
				<ReachEditor />
			</Tldraw>
		</div>
	)
}
```

**Comment by BadHuang** [comment]
> Try this way (you need to be inside the context of the Tldraw Editor):
> 
> ```
> function ReachEditor() {
> 	const editor = useEditor()
> 	useEffect(() => {
> 		console.log('Tldraw OnReady', editor);
> 	}, [editor]);
> 
> 	return null;
> }
> 
> export default function App() {
> 	return (
> 		<div className="editor">
> 			<Tldraw
> 				persistenceKey="make-real"
> 				// shareZone={<MakeRealButton />}
> 				shapeUtils={shapeUtils}
> 			>
> 				<ReachEditor />
> 			</Tldraw>
> 		</div>
> 	)
> }
> ```

thanks for your reply, I found the onMount function in Tldraw‘s props, it also can work and get the editor
