### ISSUE TITLE
Enormous snapshot size for little sized assets

### ISSUE THREAD

**Issue by irg1008** [tldraw/tldraw#2320]
### What happened?

When uploading small sized assets (around 50kB images) and then downloading snapshot for later restore, the generated snapshot with encoded assets has a x10-15 increase in size. 

For example a bare bone example with one 45kB image results in a 1.9MB snapshot. 

When trying to persist and store this in a custom backend storage, this shortly becomes a problem when handling hundreds of store snapshots.

Is there a better way to store assets in editor store or maybe provide a way to allow for custom asset storage or asset shape url manipulation

Anyway, thank you for this amazing library!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irg1008** [comment]
For example when adding this image to the editor:
<img src="https://github.com/tldraw/tldraw/assets/47559427/84d6fd7a-6b2f-4251-a2a6-3db2198fae4d" alt="drawing" width="200"/>


The jpg size is: `42.3KB`

When encoding using https://base64.guru/converter/encode/image the size is `56.4KB`

But when exporting the editor snapshots the base64 for said assets takes up to whopping `1.9MB`

This is probably because we are converting a canvas element to base64 instead of the original image:

```typescript
const getStateFrame = async (url: string) => {
	const image = await loadImage(url)

	const canvas = document.createElement('canvas')
	canvas.width = image.width
	canvas.height = image.height

	const ctx = canvas.getContext('2d')
	if (!ctx) return

	ctx.drawImage(image, 0, 0)
	return canvas.toDataURL()
}
```

Is this happening to allow for asset cropping? If it is, is there any optimization option here?

Thank you

**Comment by irg1008** [comment]
In the next snippet of [ImageShapeUtil](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx):
```typescript
async function getDataURIFromURL(url: string): Promise<string> {
	const response = await fetch(url)
	const blob = await response.blob()
	return new Promise((resolve, reject) => {
		const reader = new FileReader()
		reader.onloadend = () => resolve(reader.result as string)
		reader.onerror = reject
		reader.readAsDataURL(blob)
	})
}
```

Could replacing readAsDataURL with createObjectURL fix the asset oversize? Does this break something else?

**Comment by irg1008** [comment]
It is definitely the downscale library: Check the next example:

[codesanbox.io/tldraw-downscale-bug](https://codesandbox.io/p/sandbox/react-typescript-react-ts?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq3rx8a70006356hn3xjcftj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq3rx8a70002356hr76ozlsn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq3rx8a70003356hi5w4xjmq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq3rx8cb000i356h0v71a8lw%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq3rx8a70005356hl43zep0a%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq3rx8a70002356hr76ozlsn%2522%253A%257B%2522id%2522%253A%2522clq3rx8a70002356hr76ozlsn%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq3rx8a70005356hl43zep0a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3rx8a70004356hra7bxzoo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq3rx8a70005356hl43zep0a%2522%252C%2522activeTabId%2522%253A%2522clq3rx8a70004356hra7bxzoo%2522%257D%252C%2522clq3rx8a70003356hi5w4xjmq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq3rx8a70003356hi5w4xjmq%2522%257D%252C%2522clq3rx8cb000i356h0v71a8lw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clq3rx8cb000i356h0v71a8lw%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Check the console to see a x10 increase in size. It's nuts, it's suppose to be "downscale"

**Comment by steveruizok** [comment]
Thanks for the issue! I’ll look into it. We had our own strategy for re-scaling but swapped it for downscale; I wonder if we can just swap back to the older (slower) approach.

**Comment by irg1008** [comment]
FOUND IT!!

The `file.type` passed to the downscale library is wrongly formatted:

We are passing "image/jpeg" when only "jpeg" should be passed. Changing this prevents the defalt "png" value from being used and the new size for the image is `87kB`

Quoting from `downscale` docs:

> An object with properties representing optional function parameters:
imageType
A [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString) indicating image format. Possible values are jpeg, png, webp. The default format type is jpeg.

"Possible values are jpeg, png, webp"

If we convert the `file.type` to one of those values, the image size should be reduce considerably (x10 times for jpeg as stated above). 

Would this boost performance and improve storage size optimization? Probably for larger images

Waiting to see what you think and how to proceed

**Comment by irg1008** [comment]
I wasn't able to build the forked repo to create a pull request but this seems like an easy enough fix
