### ISSUE TITLE
Move page caret to front of page name

### ISSUE THREAD

**Issue by eklem** [tldraw/tldraw#2321]
### What's the feature?

I know using yourself as an example user isn't ideal, but I find myself clicking the hamburger menu instead of the page name or caret-down when I want to swap to another page. Would it be an idea to move the caret down in front of the page name?

It will better follow one of the principles of grouping: Proximity
"The Gestalt law of proximity states that "objects or shapes that are close to one another appear to form groups". 
--> So making the caret-down and the text be one group/clickable object.

https://en.wikipedia.org/wiki/Principles_of_grouping#Proximity

How it is now:
![Screenshot 2023-12-13 at 14 39 35](https://github.com/tldraw/tldraw/assets/236656/abf0dbab-0cc8-4b7b-980d-c70c42bb1d39)

How it could be with the arrow moved infront of the text:
![Screenshot 2023-12-13 at 14 39 43](https://github.com/tldraw/tldraw/assets/236656/f31bfa76-f4e5-465b-9a0b-1926dec87245)

### Contact Details

espen.klem@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Thanks for the suggestion @eklem ! It's a tricky one, I definitely hear you on the _feel_ of things being something that is hard to pin down since it can be subjective. I will say we're currently rethinking our page UI in general and it will probably move to a different place in general. Thanks though for the thought!

**Comment by eklem** [comment]
No problem at all @mimecuvalo
 You're making a fantastic tool that I enjoy using every week.
