### ISSUE TITLE
[Bug]: Opacity is zero when creating image shape through API

### ISSUE THREAD

**Issue by vmishevski** [tldraw/tldraw#2326]
### What happened?

I am manually inserting an image shape (the default core shape). The shape shows up in the editor, but it's white and image is not shown. When I send `opacity: 1` as parameter in the `editor.createShape`, then the image is shown correctly.
Link to open image in new tab is visible and when clicked it works fine.

This feels like the opacity is by default 0 and opacity is an optional parameter. 

The expectation would be that opacity is 1 if the user is not specifying opacity parameter in the function call.

### How can we reproduce the bug?

Example code that doesn't show the image:

```
const asset = await editor.getAssetForExternalContent({ type: 'url', url })

editor.createShape({
  id: createShapeId(),
  type: 'image',
  x: 10,
  y: 10,
  props: {
    w: size.w,
    h: size.h,
    assetId: asset?.id,
  },
  meta: {},
});
```

Code that shows the image:
```
const asset = await editor.getAssetForExternalContent({ type: 'url', url })

editor.createShape({
  id: createShapeId(),
  type: 'image',
  x: 10,
  y: 10,
  opacity: 1,
  props: {
    w: size.w,
    h: size.h,
    assetId: asset?.id,
  },
  meta: {},
});
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
`TLInstanceState` includes a property called `opacityForNextShape` which is used a a default value for opacity if the opacity is not specified when calling `createShape` / `createShapes`. It should be set to [1 as default](https://github.com/tldraw/tldraw/blob/main/packages/tlschema/src/records/TLInstance.ts#L108-L108), but maybe something overrode that for you?

In any case, you can use `editor.setOpacityForNextShapes(1)` to set that back to 1. Any shapes that are created after that should have opacity of 1, even if you don't specify it.

**Comment by steveruizok** [comment]
Answered and closed! I hope this part of our API is a bit better in the future (ie having tools use props for next shape rather than having the createShapes API use it)
