### ISSUE TITLE
[Bug]: Images added via the API is not shown

### ISSUE THREAD

**Issue by merobal** [tldraw/tldraw#2367]
### What happened?

I wanted to add images via the editor API (`createShape`) but the image is not shown (both via URL and base64 string). Only the frame is visible showing that a shape could be there.

### How can we reproduce the bug?

https://stackblitz.com/edit/tldraw-tldraw-gqf92g?file=src%2Fexamples%2FAPIExample.tsx

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kesavaraja** [comment]
Facing same issue but only with iOS devices and with a particular image. Can you help me on how you resolved that issue ?
