### ISSUE TITLE
Color not changing immediately via keyboard while drawing

### ISSUE THREAD

**Issue by wei-yuuuu** [tldraw/tldraw#2381]
### What happened?

I've noticed that while drawing and attempting to select another color by keyboard (`tab` + `enter`) simultaneously, it appears that the color change is deferred in seconds. Not sure whether this behavior is intentional or not.

### How can we reproduce the bug?

1. Keep pressing the mouse to draw without releasing
2. Use `tab` to navigate and `enter` to change colors

https://github.com/tldraw/tldraw/assets/16896941/0839742b-d3bb-48e7-ad8a-ee2e3d53a731

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
We don’t update the shape of you change the color while creating it. What you’re actually seeing is that we create additional shapes for very long lines (for performance / abuse reasons), and that new shape is getting the new color.
