### ISSUE TITLE
Cannot destructure MaxX from null getSelectionPageBounds

### ISSUE THREAD

**Issue by natea** [tldraw/tldraw#2382]
### What happened?

I tried to recreate the single player pong game, and when I click "Make Real", I see this error in the lower right hand corner of the screen:

![CleanShot 2023-12-26 at 08 27 43@2x](https://github.com/tldraw/tldraw/assets/118984/7e254452-8b50-45b8-be04-9389db438537)

### How can we reproduce the bug?

Recreate the single pong game as described in this Tweet, and click the Make Real button.
https://x.com/dr_cintas/status/1725908894197682192?s=20

### What browsers are you seeing the problem on?

Chrome

### Contact Details

natejaune@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Do you have anything selected when you click the make real button? There should be a check for that already, but having an empty selection is the only reason I can think for why the bounds would be null.
