### ISSUE TITLE
How to listen for selection changes

### ISSUE THREAD

**Issue by irg1008** [tldraw/tldraw#2384]
### What happened?

After 2.0.0-beta-1 update there is no way to hook into selection changes.

Before I would do something like useMemo(<derivedValue>, [editor.selectedShapes])

How can I do this now with the new getters for this properties

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
`getSelectedShapes` is a computed signal, so you can just [wrap your component](https://signia.tldraw.dev/docs/API/signia_react/functions/track) with `track` and it should work. Here's an example of how I modified our `Things on the canvas` example and it seems to work:
![CleanShot 2024-01-04 at 10 45 35](https://github.com/tldraw/tldraw/assets/2523721/242bb585-3724-4f9c-a973-dfc7a54ad2af)

**Comment by irg1008** [comment]
A little counterintuitive but if it works... Thank you 😊
