### ISSUE TITLE
Stuck on Connecting in Safari iOS

### ISSUE THREAD

**Issue by LimpingK** [tldraw/tldraw#2385]
### What happened?

I have 3 iOS devices at the same wi-fi network.
And 2 of them work fine. Only the last does not load the page. It keeps _"Connecting..."_ all the time.
How can I find a problem? May be look at some logs at Keenetic router?

### How can we reproduce the bug?

iPhone X
Safari

### What browsers are you seeing the problem on?

Safari

### Contact Details

k.limping@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LimpingK** [comment]
> Hm, they're all trying to load the same shared project? 

Yes, they open a shared link. It was created at MacBook.
iPad and iPhone 13 can see the image, and iPhone X only indicates "Connecting...".
I consider - this device is for child with some parental restrictions, but I could not find any reason. Since the site begin loading.

**Comment by steveruizok** [comment]
That shouldn’t really matter… but I don’t think I can help from here. My guess is that there’s a connection issue but I’d expect to see an error state if there was.
