### ISSUE TITLE
Custom cursors question

### ISSUE THREAD

**Issue by WillTaylor22** [tldraw/tldraw#2386]
### What happened?

Apologies if I'm missing anything....

Looking through the code base, it seems like there was at one time support for custom cursors (see thread here: https://github.com/tldraw/tldraw-v1/issues/200), but now there isn't?

I'm using the latest beta.v1 version of TLDraw

I've tried editor.setCursor but the result is not long lived and it only supports a range of CSS cursors.

### How can we reproduce the bug?

I was expecting something like the following, based on the thread above. Might be out of date...

`<Tldraw cursor={null}/>`

or

`<Tldraw cursor={<div>Hey!</div>}/>
`

### Contact Details

will@workflow.design

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
You can use the `components` prop to render custom multiplayer cursors:
```tsx
function MyCursor({className, point, zoom, color, name, chatMessage}) {
    return <div>Hello!</div>
}

function MyApp() {
    return <Tldraw components={{ Cursor: MyCursor }} />
}
```

These only affect the cursors rendered for _other_ users on the canvas, not the current one. We don't currently support changing the cursor for the current user - if that's what you're after, I'd love to hear more about your use-case!

**Comment by judicaelandria** [comment]
Tldraw do have `CollaboratorCursor` too which is used for the collaborator , if this is the case why do we have. `Cursor` and `CollaboratorCursor`? they do the same thing. IMO it makes sense if `Cursor` change the currrent user cursor(this one is a better choice) or shouldn't we remove one of them if they does the same thing? 
thanks!

**Comment by OleksandrB3193** [comment]
@judicaelandria Hello, try it
Good luck


.tl-canvas {
  cursor: url("https://brandeps.com/icon-download/C/Cursor-icon-vector-09.svg"), auto !important;
}
