### ISSUE TITLE
[Bug]: Edge scrolling is buggy with smaller container

### ISSUE THREAD

**Issue by merobal** [tldraw/tldraw#2388]
### What happened?

If the canvas is smaller than the screen and centered, it behaves strangely. Related: #2299

### How can we reproduce the bug?

https://github.com/tldraw/tldraw/assets/5844511/06473274-67ce-4fc5-ba03-f38c754ec666

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsmesuraj20** [comment]
i would like to contribute

**Comment by steveruizok** [comment]
Fixed by #2398 !

**Comment by merobal** [comment]
Thank you, I can confirm it's fixed
