### ISSUE TITLE
[Bug]: ShapeUtil component click events

### ISSUE THREAD

**Issue by orycohen** [tldraw/tldraw#2393]
### What happened?

Hi all 👋🏼

I'm quite new to Tldraw.
I built a custom Util that draws kind of a rectangle that represents a class in a uml diagram.

This rectangle class has an header and a body.
I want different parts of this shape, the different div elements in the Util's component, to be able to respond to different click events, onClick, onDoubleClick, etc.

The thing is, it does not respond to these events. I understand that there is a 'stopPropagation' call somewhere.
I know I can override the onClick in the Util class and use the editor.inputs that has the pointer positions info, but I wonder if there is a way of getting the elements inside the component jsx to respond to click events.

Btw, I use the Tldraw jsx component rather than the TldrawEditor component.

Thanks!! 🙏🏼 

### Contact Details

or.co.blog@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Take a look at our Custom config example. There we render a card that has a clickable button:
https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/custom-config/CardShape/CardShapeUtil.tsx

**Comment by orycohen** [comment]
Oh now I get it..

Any jsx component, rendered inside a Util object, I wish to respond to click events needs to perform the **e.stopPropagation()** on the onPointerDown event in order to respond to various click events.

so this:

```
<HTMLContainer>
  <div 
    onClick={e => console.log("click")}
  >
    Custom Shape Content
  </div>
</HTMLContainer>
```

will _**not**_ print anything in the console, but this:

```
<HTMLContainer>
  <div 
    onPointerDown={e => e.stopPropagation()}
    onClick={e => console.log("click")}
  >
    Custom Shape Content
  </div>
</HTMLContainer>
```

will print **"click"**

It makes sense now.. Thanks!!!
