### ISSUE TITLE
[Feature]: Directly integrate tldraw diagram into markdown file by exporting multiple figures as individual markdown files

### ISSUE THREAD

**Issue by twitu** [tldraw/tldraw#2445]
### What's the feature?

I noticed that this issue from the v1 repo was "closed as completed" recently - https://github.com/tldraw/tldraw-v1/issues/104.

The idea is to make it easy to integrate tldraw diagrams with markdown files. Markdown files can use multiple diagrams exported from a single tldraw files. Some figures in the tldraw file can be marked with a name and when the file is exported, these figures are saved in different image files with the given name. This can make editing a tldraw diagram and having it updated to be included in markdown/html/cms seamless. Something like this.

<img width="1693" alt="shapes at 24-01-11 01 34 35" src="https://github.com/tldraw/tldraw/assets/23196890/32211720-42bf-46bc-af21-f9a42a2acb62">

I checked the latest vscode extension 2.0.21 and it doesn't have this feature. Do you plan to support this? Or is this a direction tldraw is not considering?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by twitu** [comment]
Yes this does closely match how I was imagining it to be. One added convenience will be to export all the figures in a page in one click. It will really simplify editing multiple figures.

**Comment by MitjaBezensek** [comment]
Yeah, that would definitely be nice. We'll keep it in mind.

**Comment by twitu** [comment]
I'll create a different issue to track that feature. Feel free to close it if you don't want a separate issue for it.
