### ISSUE TITLE
[bug] Don't call out the changelog in the vscode ext readme

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#245]
There is a Changelog tab for that which is there in a consistent spot for all extensions:

![image](https://user-images.githubusercontent.com/2193314/141171807-c6c04df2-9ad7-4f4d-b985-278b45ad9c7b.png)

**Comment by HerbCaudill** [comment]
this can be closed

**Comment by Tyriar** [comment]
Yep this is fixed
