### ISSUE TITLE
Default page name always Page 1

### ISSUE THREAD

**Issue by Rokixy** [tldraw/tldraw#2482]
### What happened?

The translation has been changed to `zh-cn`，but the default page name still be "Page 1". I think it should be translated to "页面 1".
What should I do to set the default page name? Or translate the default page name?

![image](https://github.com/tldraw/tldraw/assets/48944401/e4663ea5-48ed-4d3c-953c-8b843db0c6db)

my code:
```
import { getAssetUrls } from '@tldraw/assets/selfHosted'
import { Tldraw } from '@tldraw/tldraw'
import '@tldraw/tldraw/tldraw.css'
import type { ReactElement } from 'react'

const assetUrls = getAssetUrls()
export default function WhiteBoard(): ReactElement {
  return (
    <div className='fixed inset-0'>
      <Tldraw assetUrls={assetUrls} />
    </div>
  )
}
```

version:     
```
"@tldraw/assets": "2.0.0-canary.b7fb31f8f9de",
"tldraw/tldraw": "2.0.0-canary.b7fb31f8f9de",
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Thanks for raising this, it's duplicated over here so I'm closing it: https://github.com/tldraw/tldraw/issues/2482
