### ISSUE TITLE
Multiplayer cursor wobble when pinch zooming

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2487]
1. Join a shared project on two devices. One must be a touch device.
2. On the touch device, pinch-zoom.

Expected: The multiplayer cursor on the other screen should not move.

Actual: The multiplayer cursor wobbles and flickers around. This is more visible when zoomed out more.

![Image](https://github.com/tldraw/tldraw/assets/15892272/8171c0a3-fdc7-46ec-a62e-5c49ba4fb4fe)

**Comment by mimecuvalo** [comment]
fixed in #3695

**Comment by mimecuvalo** [comment]
lemme know @TodePond if this particular issue is not addressed though by that PR
