### ISSUE TITLE
[Feature]: Trackpad Enhancement

### ISSUE THREAD

**Issue by Zenkylo** [tldraw/tldraw#2550]
### What's the feature?

Using trackpads such as the ones built into laptops or external ones (Apple Magic Trackpad) can sometimes be tricky to use with drawing tools such as tldraw. They can be difficult because because to initiate a tool such as _Draw_ or _Rectangle_ pressure needs to be applied and maintained to the trackpad _while_ you move your finger to create your drawing or shape. 
It would be helpful if with your non-trackpad hand you could hold down a key, `ctrl` or example, that would emulate the mousedown event. While the `ctrl` key is in its down state you could use your trackpad hand to create your drawing or shape without having to apply pressure to the trackpad. To end your drawing or shape you'd release the `ctrl` key.

Hope this is explained well enough. Let me know if more clarity is needed.

### Contact Details

k4nderson@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, we do this already with the comma key! But it wasn't working the way I expected it to anymore, so I've made a quick fix.

**Comment by Zenkylo** [comment]
Amazing. Thank you Steve. Works very well. I see the list of keyboard shortcuts in the app via the __?__ menu in the bottom right. However, the `,` behavior isn't listed. Perhaps because it's not technically a keyboard shortcut. Is this behavior described somewhere? I may have had trouble finding it.

**Comment by Taha-Hassan-Git** [comment]
Thanks for the suggestion, I've opened an issue for that here: https://github.com/tldraw/tldraw/issues/3531

Closing this now.
