### ISSUE TITLE
[bug] Saving a file in VS Code tries to save as an .md?

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#256]
Repro:

1. Open a file
2. Draw with pencil
3. ctrl+s

![image](https://user-images.githubusercontent.com/2193314/141176353-a85d26c4-6547-4e1c-8a52-318e4b35ad41.png)

Something is likely wrong in the extension as this doesn't happen in Luna Paint.

**Comment by steveruizok** [comment]
We solved this one, right?
