### ISSUE TITLE
[feature] should recognise .tldr extension by default

### ISSUE THREAD

**Issue by proful** [tldraw/tldraw#259]
![image](https://user-images.githubusercontent.com/354596/141184912-220311de-788e-48b7-b9ae-5ef25f8625fb.png)

Reproduce Steps:-

- Create a new tldr document
- The above warning displayed

Expected Behaviour:-

- No warning or prompt should be displayed

**Comment by seflless** [comment]
@proful The editor opens for you though right, on creating that .tldr, it's just that it also shows that confusing dialog? I definitely see that all the time.

**Comment by seflless** [comment]
In your Reproduce Steps, had you just installed the editor for the first time?

**Comment by proful** [comment]
Not able to reproduce. Closing this ticket for now.

**Comment by seflless** [comment]
I think I see this occasionally, but sounds good. Let's add back if it comes back.
