### ISSUE TITLE
Controlled rendering (on tick)

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#2612]
Prevent the canvas from rendering at more than a given FPS. Use tick to rendering during continuous updates rather than input events. Gather data from events but only render on tick.

This should improve performance on iPad and other devices where GPU uploads are problematic.

mouse move -> update state -> canvas render

continuous interactions (drawing, resizing moving stuff)

* onEnter =() => 
  * listen for editor tick
  * if we're dirty
    * update shapes in store
* onExit = () => 
  * cancel that listener
* onPointerMove () => 
  * updating tool's internal state
  * diff (internal state to the tool)

**Comment by Taha-Hassan-Git** [comment]
We did it!
