### ISSUE TITLE
Arrow keys unexpected behavior with multiple selection

### ISSUE THREAD

**Issue by FrancescoVMK** [tldraw/tldraw#2622]
### What happened?

I encountered an issue where, after selecting multiple objects in the canvas, attempting to move them using the arrow keys caused an unexpected behavior. Instead of moving as intended, the selection became glitched, and all objects were spaced out, extending beyond the visible screen area.

screen shots:
![image](https://github.com/tldraw/tldraw/assets/64145654/26490b68-b98b-4f72-b7ae-36017e10ced0)

![image](https://github.com/tldraw/tldraw/assets/64145654/72950cb7-cd4e-400f-a135-7763a05ba0f2)

![image](https://github.com/tldraw/tldraw/assets/64145654/86555f68-4a71-40d3-a50a-490e66e4f7fb)

### How can we reproduce the bug?

1. Create various shapes on the canvas.
2. Select these shapes by dragging the mouse.
3. Attempt to move the selection using the arrow keys.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

francesco.virgili.inf@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Oh that's a good one!

**Comment by FrancescoVMK** [comment]
i closed the issue since its now fixed, thanks!
