### ISSUE TITLE
Allow you to set a `style` prop on `<Tldraw>`

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2637]
I want to `<Tldraw style={{ width: '720px' }} />`

**Comment by judicaelandria** [comment]
should be an easy change, I can send a PR if you want :)

**Comment by TodePond** [comment]
This may or may not be a good idea - just doing some exploration of design at the moment :)

**Comment by judicaelandria** [comment]
yeah, it doesn't really have a huge impact tho so I think it should be fine, just let me know if I can help

**Comment by TodePond** [comment]
We tried it out and decided to not go ahead with this in the end.
More reasoning here: https://github.com/tldraw/tldraw/pull/2688#issuecomment-1927087851
