### ISSUE TITLE
Tiny breakpoints

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2641]
Can we deal with tiny component sizes?

![image.png](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/cdc9c251-714e-4e3e-8943-185ec375d292/96b2604e-7a85-4fad-99ab-6d1fcd71a48b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS9jZGM5YzI1MS03MTRlLTRlM2UtODk0My0xODVlYzM3NWQyOTIvOTZiMjYwNGUtN2E4NS00ZmFkLTk5YWItNmQxZmNkNzFhNDhiIiwiaWF0IjoxNzA2MjY2ODIzLCJleHAiOjMzMjc2ODI2ODIzfQ.MnjD0DyY98rSCoCjM2Y2LWQZEJkI_X2W2ZDBReAGvNk "=549x")

![image.png](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/18455de3-1881-41a5-881c-60fd0551872e/3718f624-b2bb-42d1-aaa0-a0357bfed774?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS8xODQ1NWRlMy0xODgxLTQxYTUtODgxYy02MGZkMDU1MTg3MmUvMzcxOGY2MjQtYjJiYi00MmQxLWFhYTAtYTAzNTdiZmVkNzc0IiwiaWF0IjoxNzA2MjY2ODIzLCJleHAiOjMzMjc2ODI2ODIzfQ.Aijb5CiiGVvzyUQ0otHWVG0j50S4bR1__QuLNoPYaRo "=717x")

**Comment by Taha-Hassan-Git** [comment]
I think the inline work addressed this issue, please reopen if not, @TodePond
