### ISSUE TITLE
Improved board history culling

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#2667]
Currently we throw out any history for a board older than a certain date. I'd rather compress history on a cron by progressively removing resolution from the history instead.

For example, we could have a cron job that leaves a single survivor from a document's most recent ten minutes, then a single survivor for the next 30 minutes, then a single survivor for the next two hours, then a single survivor for the next 24 hours, and so on, until we have a single survivor for each month of the document's history.

**Comment by kaszmm** [comment]
The idea sounds interesting to me, can you assign this issue to me?
