### ISSUE TITLE
[Bug]: edge scrolling when component is inside of screen

### ISSUE THREAD

**Issue by diandian0420** [tldraw/tldraw#2675]
### What happened?

At the edge of the screen
Use a rectangular brush
The canvas will move

Reproduce video link:
https://meeting.tencent.com/v2/cloud-record/share?id=1I2SpB22ASK4fHU1PiondZRq8x-aw7VDNgHpgh8IEJ0&from=3&record_type=1

### Contact Details

454723784@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! This works as intended, but you can disable it in the preferences (Edge scrolling):
![CleanShot 2024-01-29 at 11 58 03](https://github.com/tldraw/tldraw/assets/2523721/d999dd20-328e-4508-a9eb-be39a37fedc9)
