### ISSUE TITLE
Discussion thread and comments support

### ISSUE THREAD

**Issue by rodrigondec** [tldraw/tldraw#2684]
### What's the feature?

It would be nice to register a comment on the canvas. 

This comment would actually be a discussion thread. So any user on the tldraw project/file could create a new thread or respond to a existing one.

The discussion thread would behave the same way the comment that google docs has. 

This discussion thread could be attached to any figure or element.

This discussion thread could also be resolved or even deleted. Given that's possible to resolve a discussion thread, it would be nice to be able to see all comments on the page/project (resolved or unresolved).

This is a huge feature with a lot of changes. But I think it would be awesome. It would improve further the collaboration aspect of tldraw!

### Contact Details

rodrigondec@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrusso1020** [comment]
Also intersted in this!

**Comment by Taha-Hassan-Git** [comment]
Duplicated here:
https://github.com/tldraw/tldraw/discussions/4013#discussioncomment-9899332
