### ISSUE TITLE
How to set styles of brush in the custom UI?

### ISSUE THREAD

**Issue by faizkhan12** [tldraw/tldraw#2708]
### What's the example?

First of all, I want to congratulate everyone who is involved in this project. I have been using TLDRAW for 1 month now, and this library really helps me a lot. 

So I am creating a custom UI for the whiteboard and I have been using TLDRAW. The custom UI will consist of a brush, eraser, undo/redo, and the option to change brush color and brush size. I have dug at the docs and found how to use some of these APIs. Like to use brush we have to use ```editor.setCurrentTool('draw')``` and we need to pass hideUI props.

Now my question is how I can make use of the styles of the brush like color and brush size. I have been looking at the documentation but could not find anything that can direct me.

Sorry if this question sounds stupid but any help would be appreciated

Note - The UI is simple. At the left side will be several tools like brush, eraser, color picker and at the centre is a whiteboard which is using this wonderful library

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
This is a great idea for an example. In the meantime, you're looking for the setStyleForNextShapes method. Something like this should do the trick for your project.
```javascript
function handleColorChange(color) {
    editor.setStyleForNextShapes(DefaultColorStyle, color);
  }
```

**Comment by mochizuki-pg** [comment]
Has there been any progress on this Issue?

There was also [this Issue](https://github.com/tldraw/tldraw/issues/2708), but this way, after all, only the color defined in DefaultColorStyle can be selected.

I want to use a brush with a color specified by a color code
