### ISSUE TITLE
It's possible to scroll both the page and editor in scrollable example

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2726]
Not entirely sure how to reliably reproduce.

1. While the editor is unfocused…
2. Repeatedly scroll with the trackpad in a fast motion.

Expected: The editor should scroll, not the page.

Actual: Both the editor and the page scroll.

![2024-02-05 at 14.31.39 - Aqua Barracuda.gif](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/8ec5686d-eecf-4988-8ee8-2cdd867800ea/e90d44e6-a740-44e2-aac3-62b3993b01c5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS84ZWM1Njg2ZC1lZWNmLTQ5ODgtOGVlOC0yY2RkODY3ODAwZWEvZTkwZDQ0ZTYtYTc0MC00NGUyLWFhYzMtNjJiMzk5M2IwMWM1IiwiaWF0IjoxNzA5MTE1OTI1LCJleHAiOjMzMjc5Njc1OTI1fQ.VzHHuUTGGazOdnnlZ-LwMDu-dd7RcT6H02FukNVIo7Y "=960x")

**Comment by mimecuvalo** [comment]
I think this maybe was related to dispatch/event coalesing? I can't repro it as much I've tried!
