### ISSUE TITLE
Windows: Grid mode slows down rendering

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#2743]
There's a noticeable performance hit when grid mode is enabled on windows.

1. Place some shapes down on the canvas (so that you can notice any difference more easily).
2. Compare zooming in and out with the grid turned on and off.

Expected: Zooming should look smooth whether the grid is on or off.
Actual: Zooming has some frame loss when the grid is turned on. It's smooth when it's turned off.

**Comment by Leyofficial** [comment]
How did you applied the grid? I can't find how to do this

**Comment by Taha-Hassan-Git** [comment]
main menu > preferences > show grid

or 

cmd/ctrl + '

**Comment by Leyofficial** [comment]
Thank you. But how should I add grid to my app with hidden basic tldraw ui
