### ISSUE TITLE
[Bug]: tldr file is stuck loading in vscode

### ISSUE THREAD

**Issue by myogh** [tldraw/tldraw#2760]
### What happened?

This problem appeared after upgrading to [v2.0.23](https://github.com/tldraw/tldraw/commit/34673156c4a719dc9832c6226669bdbcf674906d).

### How can we reproduce the bug?

Upgrade the tldraw vscode extension to v2.0.23, and open an existing *.tldr file or a new one, and you will see a loading screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! This does seem to work for me. Is there any way you could send us the file since it might be specific to your document?

**Comment by myogh** [comment]
I checked today and it worked fine. Not sure why it didn't work initially. Thanks for your reply.

**Comment by MitjaBezensek** [comment]
Glad to hear it's working now. Let us know if it happens again.
