### ISSUE TITLE
[Bug]: Cursor chat position doesn't take tldraw's client offset into account

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2771]
### What happened?

Using cursor chat with a collapsible sidebar, the cursor chat bubble gets offset by the sidebar's width.

https://github.com/tldraw/tldraw/assets/1242537/20acfdde-24b9-4fe3-b053-98243c2ea8d7

cc @TodePond 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
we had this bug too, I just subtract the mouse position with the container position (x,y) to fix it! it's works smoothly since then! not sure if that'll fix tldraw issue, but worth a try!
