### ISSUE TITLE
[Example Request]: "track" changes outside of the editor

### ISSUE THREAD

**Issue by thien-2** [tldraw/tldraw#2795]
### What's the example?

I think it would be useful to have an example where some editor states, such as current tool or selected shapes, can be "tracked" outside of the editor root.

### 1. Automatic tracking
- What: Use the state directly, and wrap the component with `track`.
- Pros: Straightforward, support multiple editors.
- Cons: Does not work outside of the editor root.

### 2. Event listeners
- What: Get the editor on mount and `editor.store.listen`.
- Pros: Traditional approach, works everywhere, especially outside of the editor.
- Cons: Need to filter out a lot of redundant events. Also it does not work for `getCurrentSelectedTool`.

## What I think we could have

(As an example, not suggesting code changes or new features at all)

### 3. Tracking from outside
- What: Have a hook inside the editor that broadcast specific changes to a context outside.
- Pros: Avoid redundant events and manual filter, closer to real life use cases (single editor).
- Cons: More boilerplate code, opinionated approach.

WYDT?
- Is this a bad practice?
- Is there a better way?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by h2thien** [comment]
Ah sorry my bad, I could always use TLDraw Editor as a provider!
