### ISSUE TITLE
[Bug]: Canvas cannot be smaller than TldrawEditor

### ISSUE THREAD

**Issue by h2thien** [tldraw/tldraw#2797]
### What happened?

When the Canvas is smaller than TldrawEditor, or when the Canvas is moved out of (0, 0) of TldrawEditor, the positioning does not work correctly any more.

> Also tell us, what did you expect to happen?

I think the positioning should work based on the Canvas instead of the TldrawEditor. However, feel free to close if you checked the sandbox and confirm that this is expected.

### How can we reproduce the bug?

This is from our app:

<img width="1280" alt="image" src="https://github.com/tldraw/tldraw/assets/122243953/700d6cb8-68c0-41e4-8bd3-d9040c6501b6">

This is a minimal reproducible code sandbox:

https://codesandbox.io/p/sandbox/tldraw-canvas-crft32

In both case, you can see that the interaction coordination is shifted from the cursor. The distance is equal the distance between the Canvas and the TldrawEditor.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Contact Details

thien@h2corporation.jp, or h2thien on Discord in Steve's DM 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hm, I think that would make sense. There could be knock-on issues by using the canvas rather than the component for sizing, but worth a try!

**Comment by h2thien** [comment]
Thanks @steveruizok 🙏 If the Tldraw team is busy, you folks can just provide some hints and we (my FE team in my company) will try to work on this 🙇

**For others:** our current workaround is to position the Canvas to fill 100% of TldrawEditor, and other panels are absolute positioned. The downside of this workaround is the "zoom to something" is sometimes not correct. However, this is much better than [trying to sync](https://github.com/tldraw/tldraw/issues/2795) the state to outside of the editor.

**Comment by steveruizok** [comment]
PR here: https://github.com/tldraw/tldraw/pull/2798

**Comment by h2thien** [comment]
Wow that was fast, thanks! If it's helpful for us to test this, feel free to tell 😄 We're already on canary but happy to check out the branch and build it locally to test.

**Comment by steveruizok** [comment]
It should work for what you're describing! I'll check with the team on Monday and if it ships it'll go into canary / this week's release.

**Comment by h2thien** [comment]
Thank you! If there's anything we can do to help please do say 🙇

**Comment by h2thien** [comment]
Hey sorry for the late update! I confirmed this is fixed in latest "main", thanks!
