### ISSUE TITLE
[dx]: Check TS project references

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2800]
We should add a precommit check to make sure that any project references that need to present are. i.e. for any pair of workspaces in our monorepo where `@tldraw/A` depends on `@tldraw/B` in either `package.json#dependencies` or `package.json#devDependencies`, `A`'s `tsconfig.json` file should include a project reference pointing to `B`.

We miiight be able to use the yarn constraints thing for this? in yarn.config.cjs. Or there might be some other way to inject code into the yarn checks phase.

**Comment by SomeHats** [comment]
The `check-scripts.ts` script might also be a good place for this - we run it in CI and use it to check just the scripts section of our package.json files, but we could expand the scope to check other package.json-like things too
