### ISSUE TITLE
[Bug]: Expose "value" on getSharedStyles map

### ISSUE THREAD

**Issue by thatsjonsense** [tldraw/tldraw#2809]
### What happened?

The `editor.getSharedStyles` function returns a map with the style values, but the values aren't listed in the Typescript response

![image](https://github.com/tldraw/tldraw/assets/2216153/197749b2-7db4-4007-9590-72e700d58970)

Slapping a ts-ignore on this works, but feels odd. Is this not the intended way to get shared styles?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
The `value` property is only exposed on `shared` types - when all the selected shapes share the same style. When there's a mix of values, there's no one value to return, so we return the `mixed` type: https://tldraw.dev/reference/editor/SharedStyle

You could get around this error by changing your code like this:
```ts
const sharedStyle = editor.getSharedStyles().get(style)
if (sharedStyle.type === mixed') return null
return sharedStyle.value
```

**Comment by thatsjonsense** [comment]
Thanks for clarifying that @SomeHats !
