### ISSUE TITLE
[Bug]: Double-click on text outline behaves poorly when text is right-aligned

### ISSUE THREAD

**Issue by joshuahhh** [tldraw/tldraw#2811]
### What happened?

Suppose text is right-aligned with an oversized outline. If you select the text, then double-click on the text's outline (where you would resize it), the outline shrinks to the text contents – but in a way that assumes the text is left-aligned. This means the text moves over.

See video:

https://github.com/tldraw/tldraw/assets/643799/14c37f99-f07a-4b7b-b11a-fde868fb7b73

(I ran into this not because I was deliberately double-clicking on the outline, but because this happened by accident in the course of working with right-aligned text.)

### How can we reproduce the bug?

See video above.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

just @ me :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imrishabh18** [comment]
Hey @joshuahhh! Is this issue still present? Cause when I am trying this, I can't reproduce it.

https://github.com/tldraw/tldraw/assets/38923768/a552a329-f6a2-4d8f-a28a-873dc7f92835
