### ISSUE TITLE
[documentation] Best workflow for editing tldraw/core and tldraw/tldraw at the same time?

### ISSUE THREAD

**Issue by MaxBittker** [tldraw/tldraw#283]
I am not very familiar with Lerna! 

the development environments for the two repositories work nicely individually. 

is there a recommended way to develop `tldraw/tldraw` against a local copy of `tldraw/core`? Or should I edit the package.json?

**Comment by MaxBittker** [comment]
also running into some issues where the dev server seems to give me stale results, have you seen this?

**Comment by steveruizok** [comment]
I've brought this back into the monorepo and should have all of the typescript issues fixed now. I can reopen if you're still seeing problems!
