### ISSUE TITLE
[feature] Delete object when "del" keyboard button is pressed 

### ISSUE THREAD

**Issue by artyomovs** [tldraw/tldraw#284]
Hi there. 
Absolutely astonishing VScode extension, thank you! 
It would be more useful If I could delete painted object just by pressing "del" button.

**Comment by proful** [comment]
I can able to delete any shape after selecting it.

**Comment by faqie** [comment]
Have you tried the "Backspace" key?

**Comment by proful** [comment]
I'm using Macc. it has only Delete key.

**Comment by hyzyla** [comment]
Intuitively, I also was trying to delete a drawing using DEL button

**Comment by steveruizok** [comment]
Fixed!
