### ISSUE TITLE
[bug] Clicking shape button hiding toolbar

### ISSUE THREAD

**Issue by Proful** [tldraw/tldraw#285]
tldraw: 1.0.3
Using tldraw as a component in Create React App.

Clicking shape button hiding toolbar.

![09-tldraw-shape](https://user-images.githubusercontent.com/354596/142382067-27d41a69-741a-4555-84c5-3e9b11b92044.gif)

**Comment by proful** [comment]
![10-hide-toolbar](https://user-images.githubusercontent.com/354596/142402960-a04a1dc4-5033-42da-a04b-acec07d1a014.gif)

**Comment by steveruizok** [comment]
Is this one still an issue?

**Comment by proful** [comment]
Issue still exist
Ref https://github.com/proful/try-tldraw
