### ISSUE TITLE
[bug] Geometric shape menu does not close when user clicks on a shape.

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#288]
When a user opens a menu and then clicks on something other than the canvas, the menu does not close. This is similar to the bug found (and fixed) with the context menu.

![Kapture 2021-11-18 at 10 19 10](https://user-images.githubusercontent.com/23072548/142396994-5d029893-117b-43d2-8d05-96e76a55887d.gif)

**Comment by proful** [comment]
This seems to be already fixed, not able to replicate. @steveruizok please close it if this issue already fixed.
