### ISSUE TITLE
Arrow label snapping shouldn't scale with arrow length

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#2901]
When an arrow is very long, the snap area gets larger. It should stay the same size, and be dependent on camera zoom.

![Image](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/bee6b4b7-53a7-497c-82c9-01fc4c72653e/6af02a6f-451b-4890-bce7-1ff456656381?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS9iZWU2YjRiNy01M2E3LTQ5N2MtODJjOS0wMWZjNGM3MjY1M2UvNmFmMDJhNmYtNDUxYi00ODkwLWJjZTctMWZmNDU2NjU2MzgxIiwiaWF0IjoxNzA5NDA3OTg3LCJleHAiOjMzMjc5OTY3OTg3fQ.\_aiUex924-TmC_J_8h6WsSjoGmOyIAmFAx1pPdECgEg)

**Comment by Taha-Hassan-Git** [comment]
This still happens, do we want it? @mimecuvalo

**Comment by mimecuvalo** [comment]
Yeah, it's prbly worth tweaking, probably not too big of a change.
