### ISSUE TITLE
Editor focus lost after undo

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2930]
### What happened?

This happens in at least Safari and Chrome on MacOS. The steps to reproduce seem very specific but I worry that the actual underlying problem is much broader.

### How can we reproduce the bug?

1. Create a geo box
2. Change the geo type to cloud
3. Hit undo on the keyboard (the bug will not manifest if you click the undo button in the UI)
4. All keyboard shortcuts stop working

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Anecdotally this seems to be happening as well — I'll try to watch out for it as well. I'll be hitting undo and then it reverts to a browser shortcuts instead of the editor shortcuts.

**Comment by ds300** [comment]
this was fixed by #2936
