### ISSUE TITLE
[Feature]: Expose a function for returning the image generated for useExportAs as a return value

### ISSUE THREAD

**Issue by ambrose-gladwell-sonocent** [tldraw/tldraw#2939]
### What's the feature?

For our use case of tldraw we need to be able to get the image generated from `useExportAs` as a return value to our code so we can save it for our users. 

Currently, tldraw has `useExportAs` which allows downloading the content in various formats. The code for `useExportAs` already does the step needed to support the above use case but the code is not refactored out to make it reusable and exposed as a function through the tldraw API.

The proposal would be to refactor out the code in `useExportAs` which creates the SVG or image blob for a PNG into it's own function and make this available through the tldraw API as something like `useGetImageAs()` or something like along those lines.

### Contact Details

ambrose.gladwell@glean.co

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hi! Thanks for the suggestion. I've made the `exportToBlob` function public in #2893. I think this solves your use-case? Let me know if there's some nuance missing and I'll reopen this.

**Comment by ambrose-gladwell-sonocent** [comment]
Hi @ds300, yeah just had a look and this should solve our use case. Thanks for this, much appreciated.
