### ISSUE TITLE
[bug] Can't rename pages

### ISSUE THREAD

**Issue by omar2205** [tldraw/tldraw#294]
Can't rename a page, I had to save the project and manually edit the save file.

![trying to rename a page](https://i.imgur.com/5GOGAjA.gif)

**Comment by omar2205** [comment]
Windows 11 - Chrome 95

**Comment by Juri-Salminen** [comment]
Same problem for me on Windows 11 and Microsoft Edge 95.0.1020.53.

Can't delete pages either.

**Comment by steveruizok** [comment]
Fixed!

**Comment by omar2205** [comment]
Good job, @steveruizok. What commit, if I may ask?

**Comment by steveruizok** [comment]
Ah sorry, should have included a link. I think this was due to an API change in the Dialog component. #302

**Comment by eklem** [comment]
Nice! When will this surface in the VS code extension?
