### ISSUE TITLE
Expected number got undefined after beta upgrade

### ISSUE THREAD

**Issue by szilarddoro** [tldraw/tldraw#2955]
### What happened?

I bumped the version of tldraw from `beta.2` to `beta.4` today, and I started noticing issues when rendering the canvas.

tldraw started throwing errors like this:
```
{
  "name": "ValidationError",
  "rawMessage": "Expected number, got undefined",
  "path": [
    "shape",
    "(type = arrow)",
    "props",
    "labelPosition"
  ]
}
```

The arrow objects didn't have any specific details before the version bump. They were simply connecting rectangles and had no labels.

### How can we reproduce the bug?

- Create a canvas with the `beta.2` version
- Connect some rectangles with arrows
- Bump the version to `beta.4`
- Open the canvas
- Check the error logs

### What browsers are you seeing the problem on?

Chrome

### Contact Details

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Sorry about that!

It seems like the migration didn't run when you loaded your document. Can you describe to me how you load persisted data into your tldraw store? A link to your code would be very helpful if it's public

**Comment by szilarddoro** [comment]
Unfortunately, the code is in a private repository, but I can give you some information.

I used the [tldraw-yjs-example](https://github.com/tldraw/tldraw-yjs-example) as a starting point, and I pass the store (with status) that is returned by the `useYjsStore` hook directly to the `<Tldraw />` component.

```jsx
function Page() {
  const { store } = useYjsStore(...);
  
  return <Tldraw store={store} ... />;
}
```

I reverted to `beta.2` and printed out the records. Hope that helps:
https://gist.github.com/szilarddoro/181553d0e1f2770989114c553430c8b5

**Comment by szilarddoro** [comment]
Thanks @ds300! It would be amazing if you could extend the example with the migration as it would be super helpful for everyone.

**Comment by ds300** [comment]
Added migrations to the example in this PR https://github.com/tldraw/tldraw-yjs-example/pull/14

**Comment by szilarddoro** [comment]
I checked the updated example and applied the changes to my customized `useYjsStore` implementation but I still see the same error popping up.

**Comment by szilarddoro** [comment]
I looked at our implementation, and apart from a few minor changes, it's almost identical to the example in the repository.

It seems like this line still throws an error:
https://github.com/tldraw/tldraw-yjs-example/blob/main/src/useYjsStore.ts#L125

Is it even supposed to reach that line before migrating old records?

**Comment by ds300** [comment]
@shillo-a 

> Is it possible to migrate older format of data?

Yeah! If you serialize the schema from the previous version you had installed you can paste it in there as a fallback.

i.e.

1. check out the commit from before you upgraded tldraw
2. console.log(JSON.stringify(editor.store.schema.serialize()))
3. const oldSchema = <paste json here>
4. const documentSchema = meta.get('schema') ?? oldSchema

something like that should do the trick

**Comment by shillo-a** [comment]
@ds300, thank you very much for response!
I followed your steps, but, unfortunately, encountered the following error after all:
`Uncaught ValidationError: At instance_page_state.selectedShapeIds: Expected an array, got undefined`

I should somehow enrich my data with this property?

**Comment by ds300** [comment]
@shillo-a you shouldn't be manually managing `instance_page_state` records. Try deleting those before updating the store. And make sure you're using the 'document' scope filter in [store.listen](https://github.com/tldraw/tldraw/blob/cd02d03d063b50d93d840aa8194aeced43a6a9c5/packages/tlsync/src/lib/TLSyncClient.ts#L156-L162). The only record types you should be storing in the yjs document store are the `page`, `document`, `shape`, and `asset` types.
