### ISSUE TITLE
[bug] Dark mode not applied to menu pop-out 

### ISSUE THREAD

**Issue by shettypuneeth** [tldraw/tldraw#296]
Not sure if this was intentional, in dark mode, the menu pop-out still retains light mode colours.

<img width="540" alt="Screenshot 2021-11-19 at 12 20 43 PM" src="https://user-images.githubusercontent.com/3356679/142578400-01181854-cbdb-4e5a-b77a-e9165435ed54.png">

Can raise a PR if this wasn't intentional.

**Comment by steveruizok** [comment]
This is due to a current limitation in our menu library, Radix. We're working on a fix!
