### ISSUE TITLE
[bug] Sign out button always shows

### ISSUE THREAD

**Issue by emmanuelmahove** [tldraw/tldraw#297]
The sign out button in the dropdown menu always shows even when a user is not signed in.

![Screenshot 2021-11-19 105724](https://user-images.githubusercontent.com/59018510/142594683-7b78bb12-3c9f-48f9-889b-5a52c9791f28.png)

I suspect that this is an error in the way the code that handles whether this button is displayed works:

https://github.com/tldraw/tldraw/blob/699b1167bdce9f78f81589eae155080174153270/packages/tldraw/src/components/TopPanel/Menu.tsx#L64

**Comment by steveruizok** [comment]
Fixed!
