### ISSUE TITLE
[Bug]: Dragging after pressing the middle mouse button in Safari browser, the gesture does not automatically recover after releasing the middle button.

### ISSUE THREAD

**Issue by wisinfun** [tldraw/tldraw#3013]
### What happened?

Dragging after pressing the middle mouse button in Safari browser, the gesture does not automatically recover after releasing the middle button.

### How can we reproduce the bug?

Safari 17.3.1
https://www.tldraw.com

Dragging after pressing the middle mouse button in Safari browser, the gesture does not automatically recover after releasing the middle button.

### What browsers are you seeing the problem on?

Safari

### Contact Details

wisinfun@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Thanks for the report! ❤️
