### ISSUE TITLE
Canary marked as latest on NPM

### ISSUE THREAD

**Issue by thien-2** [tldraw/tldraw#3019]
### What happened?

I'm not entirely sure if this is expected. Usually the "latest" tag on NPM is for the latest **stable** version (which in tldraw's case should be `2.0.0`). However, at the moment the "latest" tag is pointed to the canary version. This means `npm install tldraw` would install the canary version.

<img width="1264" alt="image" src="https://github.com/tldraw/tldraw/assets/122243953/3f192242-fa43-4106-be74-e13287c5efc7">

### How can we reproduce the bug?

There are 2 ways to reproduce this. First, we can go to [tldraw's NPM page](https://www.npmjs.com/package/tldraw), where we can see the latest version as canary:

<img width="1264" alt="image" src="https://github.com/tldraw/tldraw/assets/122243953/9bbe0a56-0f98-4b32-8cad-a10925e5bacf">

Otherwise, we can also try it locally by installing the package without any version:

```bash
npm install tldraw
```

Then check the installed version, either in "package.json", in the lock file, or at the output itself.

### Contact Details

thien@h2corporation.jp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
I think @ds300 fixed this! Thanks for the report

**Comment by ds300** [comment]
Yep I fixed our script in #3048, and updated the `latest` tags on npm to point to 2.0.0
