### ISSUE TITLE
Auto size font

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3025]
As the text increases to overflow its container, the size of the font decreases in order to prevent overflow.

* how would we migrate shapes? Check whether they have growY?
* would we preserve existing overflowing sticky notes?
* would the user be able to control notes?

**Comment by mimecuvalo** [comment]
Just to remember here if we go this route: we need to make sure that we should measure true length of the string, not JS length (i.e. emoji characters can be of 'length' 8 but are rendered only as one character).
