### ISSUE TITLE
Sticky note reacji

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3034]
Can we add reactji to sticky notes?

Could we do this without attribution / logged in users?

**Comment by mimecuvalo** [comment]
I'll copy comment from https://github.com/tldraw/tldraw/issues/3035

Fwiw, this can be also accomplished with logging in — with our existing user-provided names.
The trade-off is 'fidelity' of the user, knowing truly that the user is who they say they are vs. somebody impersonating someone else. In a public, internet facing canvas this would be problematic. However, in more downstream case, this tradeoff can be more ok where you assume trust vs. malicious impersonation intent.

**Comment by mimecuvalo** [comment]
although i think we can still add this in the future :)
