### ISSUE TITLE
Author attribution

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3035]
Created by…

Could we do this without logged in users / true attribution?

**Comment by mimecuvalo** [comment]
Fwiw, this can be also accomplished with logging in — with our existing user-provided names.
The trade-off is 'fidelity' of the user, knowing truly that the user is who they say they are vs. somebody impersonating someone else. In a public, internet facing canvas this would be problematic. However, in more downstream case, this tradeoff can be more ok where you assume trust vs. malicious impersonation intent.

**Comment by mimecuvalo** [comment]
we might revisit this in the future, this was during sticky spike
