### ISSUE TITLE
[feature] Add new text fonts

### ISSUE THREAD

**Issue by beatrizoliveiira** [tldraw/tldraw#304]
- It would be interesting to add font options for text where the user could choose 
- for example:

![image](https://user-images.githubusercontent.com/65451957/142631524-65f23ad8-e5f5-459a-bcaa-e7d7c4f86161.png)

**Comment by steveruizok** [comment]
On it! See https://github.com/tldraw/tldraw/pull/308

**Comment by steveruizok** [comment]
Shipped!

**Comment by bmitchinson** [comment]
@steveruizok is this available in the beta? Can't seem to find it 🤔 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/33632286/208140289-4858199f-7e02-478b-8cbd-128593a3d3ae.png">

(Amazing tool! Looking forward to supporting + advocating we use it at work!)

**Comment by steveruizok** [comment]
Glad you're enjoying it!

The answer is yes and no—sort of. It's actually implemented in the app but we pulled the UI for it for launch as we hadn't decided on final fonts. I'd expect the different fonts to return soon now that we have a new font to design around. (see staging.tldraw.com for the latest but potentially buggiest daily builds).
