### ISSUE TITLE
Expose setStyleForNextShape

### ISSUE THREAD

**Issue by thien-2** [tldraw/tldraw#3045]
### What's the feature?

Recently tldraw exposes "get styles for next shape" (https://github.com/tldraw/tldraw/pull/3039), which reminds me of a small issue in our integration, that we are not sure how to "set styles for next shape".

To avoid an XY problem: what we are trying to do here is to make a tool that draws a "geo shape" whose "geo" is always an "arrow". We also have another, similar tool whose "geo" is always a "triangle".

What we are doing is extending the "geo shape tool" and update the shape "on pointer up":

<img width="1264" alt="image" src="https://github.com/tldraw/tldraw/assets/122243953/1b223d90-8f90-4c9a-8554-88d4639ea792">

This is the "convert":

<img width="1264" alt="image" src="https://github.com/tldraw/tldraw/assets/122243953/f79ecb7b-d483-4388-a96c-061cfd244bd6">

This has 2 problems:
1. A visual problem as the default geo shape is created first, so a big rectangle is visible for a split second before we converted it to our geo shape.
2. A state problem as an "orphan" shape exists for a split second. "Orphan" shape is our internal term for tldraw's shapes that are not converted to our shapes yet (i.e., have its "meta" populated with our data).

What do you think we should do? _Maybe_ if we can "set styles for next shape" then we don't need to update the shape after it is created ("on pointer up"). But even so, I'm not sure if we can even set "meta" in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hello! The [`Editor.setStyleForNextShapes`](https://tldraw.dev/reference/editor/Editor#setStyleForNextShapes) method should be what you're looking for, right?
