### ISSUE TITLE
[Bug]: Pasting excalidraw content can fail

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#3060]
### What happened?

Seems related to the work on handles. See sentry bug cc @SomeHats 
 https://tldraw.sentry.io/issues/4999952937/events/24e339ae22624d6aa8af828b2e1a0df1/?environment=production&project=4504203639193600&query=is%3Aunresolved+ValidationError&referrer=previous-event&statsPeriod=90d&stream_index=2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Not seeing any new sentry issues for this, closing for now.
