### ISSUE TITLE
[Examples]: Tiptap plugin example

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3070]

**Comment by oytuntez** [comment]
Do you have any examples for a tiptap integration?

**Comment by mimecuvalo** [comment]
I'm working an PR to enable this but it's still under discussion: https://github.com/tldraw/tldraw/pull/3051
Feel free to fork and try it out :)

**Comment by oytuntez** [comment]
@mimecuvalo of yes, I am watching that PR actually. Let me try to fork and run locally. Hope you can make this out soon! Let me know if you need any help.

**Comment by mimecuvalo** [comment]
merging this issue into an earlier issue: https://github.com/tldraw/tldraw/issues/1879
