### ISSUE TITLE
[Feature]: Hope the connecting line supports elbows

### ISSUE THREAD

**Issue by wisinfun** [tldraw/tldraw#3077]
### What's the feature?

Hope the connecting line supports elbows, Very useful in creating flowcharts
<img width="1029" alt="image" src="https://github.com/tldraw/tldraw/assets/41355260/cef1ec50-8dd3-444b-8190-7e3ae5212413">

### Contact Details

wisinfun@qq.com

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
dupe of https://github.com/tldraw/tldraw/issues/1738
