### ISSUE TITLE
[Feature]: `toSvg()` method for `Geometry2d`

### ISSUE THREAD

**Issue by lorenzolewis** [tldraw/tldraw#3080]
### What's the feature?

If storing custom shape data as `Geometry2d` you will most likely need to render this out at some point. You can see a lot of this custom rendering happening internally already (examples below for brevity). I would suggest adding an abstract method to `Geometry2d` such as `toSvg(shape: Geometry2d, props?: SVGProps<SVGSVGElement>): JSX.Element`. By using `props` that would allow passing common attributes to customise such as `color`, `stroke-width`, etc. 

## External Usage

By exposing such a function as `toSvg()` to developers it will give them the option to define their geometry using the `Geometry2d` classes and easily render them. Of course, some developers may have much more custom use cases, but this provides a standard baseline for someone to start with.

I'm not exactly sure what the plans are for `Geometry2d` other than for basic debugging, indicators, and path collision checking, but adding this as a potential use case seems like a win to me.

## Internal Cleanup

Some of this rendering functionality already exists in some of the internal Geo shapes. These are all using different approaches to create the path strings but are ultimately resulting in the same output. By centralising this in a single place it could help clean this up a bit (and also make it much easier to add additional shapes in the future, either internally or by 3rd-party devs).

There could be some difficulty for the drawn styles as some jitter is applied to those paths. 

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/cloudOutline.ts#L265

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/SolidStyleEllipse.tsx#L23

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/SolidStyleOval.tsx#L60

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/SolidStylePolygon.tsx#L22

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/DashStyleCloud.tsx#L63-L64

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/DashStyleEllipse.tsx#L46

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/components/DashStylePolygon.tsx#L24

https://github.com/tldraw/tldraw/blob/40aeebab46ff8b0f2755fe815a0f410f98b521da/packages/tldraw/src/lib/shapes/geo/cloudOutline.ts#L301

https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/geo/components/DrawStylePolygon.tsx#L30

There are a few other places as well but I figure this gives enough examples

## Implementation

There are a few different ways I could see implementing this (although if this is something that wants to be investigated I would love to hear feedback!):

1. Using a single `<path d="complex path data here" />` and returning that from the function
2. Using any relevant SVG elements such as `rect`, `ellipse`, `polyline`, etc. Some of the more complex `Geometry2d` classes (such as `Stadium2d`) may need to fall back to a custom `<path />` element. This would return the relevant path for each.

### Barriers to implementation

Looking at `Arc2d` as an example, using an [elliptical arc curve](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#elliptical_arc_curve) we would need attributes such as `large-arc-flag` `sweep-flag` which as indeed used in the constructor of `Arc2d`, but aren't saved internally. This might need to be saved to help with rendering the relevant SVG element.

## Additional notes

I would be happy to help out with a PR if desired with the guidance of the team.

May impact/be impacted by https://github.com/tldraw/tldraw/pull/3020

---

Hope this makes sense and thank you all for an awesome project!

### Contact Details

tldraw Discord: lorenzolewis

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
We did a lot of work in the past months to make this more unified.
Example https://github.com/tldraw/tldraw/blob/066dd08336999e85d65fd24e8dc53a71a7898d1b/packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx#L530-L569
and https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx

Probably that addresses your issue afaict!
