### ISSUE TITLE
[Feature]: Add a physical scale and measurement widget

### ISSUE THREAD

**Issue by alexkreidler** [tldraw/tldraw#3081]
### What's the feature?

Suppose I want to draw a mockup of my architecture/interior design idea or do scene blocking for plays, movies, or videos. It would be great to have an overlay that shows a physical scale that resizes with zoom, like on Google Maps. A measurement tool that computes and displays the distance as a straight line or with multiple points would also be really useful. This would allow me to build my scene to scale and with the right distances!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
merging into an earlier issue https://github.com/tldraw/tldraw/issues/1243
