### ISSUE TITLE
[feature] Add Discord link to Menu

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#309]

**Comment by dinaco** [comment]
Howdy Steve, I am trying to give my first contribution on github and I chose this project as its pretty cool (just installed the plugin in my vscode).

The thing is, the `@radix-ui/react-icons` library doesnt has a Discord icon, so I generated a HTML SVG code to be able to include it, another solution would be to find another icon library, but i dont think its something that you'd like.

**Comment by steveruizok** [comment]
Closed by @dinaco! I would have done the same with that icon, cheers.
