### ISSUE TITLE
[bug] Area selecting a group, adds the individual items to the selection instead of the whole group

### ISSUE THREAD

**Issue by levhita** [tldraw/tldraw#314]
This creates an unexpected behavior when for example, aligning elements.

https://user-images.githubusercontent.com/225066/142699838-659cb692-803b-4292-a95a-e60b89bd7ebb.mov

**Comment by levhita** [comment]
Another example

https://user-images.githubusercontent.com/225066/142700068-780b94cc-6ebe-4cc5-ad61-45cd0c8b7e74.mov

**Comment by steveruizok** [comment]
Nice one, that's definitely the wrong behavior.
