### ISSUE TITLE
DefaultToolbarContent and useIsToolSelected not exported

### ISSUE THREAD

**Issue by prajwalad101** [tldraw/tldraw#3246]
### What happened?

When trying to follow an example of [custom toolbar](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/custom-toolbar/README.md), I got an error while importing the DefaultToolbarContent and useIsToolSelected.

### How can we reproduce the bug?

Import the DefaultToolbarContent and useIsToolSelected hook from the tldraw package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
We did export them on [one of the recent PRs](https://github.com/tldraw/tldraw/pull/3067/files#diff-2a6cffa6fbe7e26126e7f0044e272564cc6e24adabeeb13954feae2cd21e1e33), but we haven't released the package with that change yet. Maybe you can switch to canary / wait for use to do a new release?

**Comment by prajwalad101** [comment]
Yeah sure. Thanks
