### ISSUE TITLE
[Bug]: Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by timonson** [tldraw/tldraw#3247]
### What happened?

I cloned the repo and ran `npm i tldraw` on one Ubuntu and one Arch system. I also changed the tag. In all cases I get the following error:

> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:*

### How can we reproduce the bug?

npm i tldraw
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /home/ubuntu/.npm/_logs/2024-03-24T12_29_36_802Z-debug-0.log

### Contact Details

timo.rossa@tutanota.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! For local development on the library [we are using yarn](https://github.com/tldraw/tldraw?tab=readme-ov-file#local-development). Maybe you can try that out and see if that works?

**Comment by timonson** [comment]
Thanks, it worked!
