### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by stormbinary** [tldraw/tldraw#3248]
### What happened?

uild-types::<rootDir> Node.js v20.11.0
build-types::<rootDir>  ERROR OUTPUT
Typechecking files: []
node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync C:\tldraw-main\node_modules\.bin\tsc ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at execFileSync (node:child_process:919:15)
    at main (c:\tldraw-main\scripts\typecheck.ts:22:2) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\tldraw-main\\node_modules\\.bin\\tsc',
  path: 'C:\\tldraw-main\\node_modules\\.bin\\tsc',
  spawnargs: [ '--build' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Thanks for the report. I don't have a lot of experience debugging Windows builds. You could try searching in the issues and our Discord. There are a few users who have solved Windows problems there before.

**Comment by mimecuvalo** [comment]
It's hard to tell what's going on here. This particular build issue is out-of-scope for our developers to help with unfortunately. (looks like you have to figure out your typescript setup in general)
