### ISSUE TITLE
Snap points on either side

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3250]
![image.png](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/22bc8b80-97bd-48ed-85de-3db213e8500c/f01cd8f1-fcaa-404c-a5ae-c3fefc543fce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS8yMmJjOGI4MC05N2JkLTQ4ZWQtODVkZS0zZGIyMTNlODUwMGMvZjAxY2Q4ZjEtZmNhYS00MDRjLWE1YWUtYzNmZWZjNTQzZmNlIiwiaWF0IjoxNzExMzU1MjM0LCJleHAiOjMzMjgxOTE1MjM0fQ.HgQve2O8OZDDVm5XV6O50_3vzvH80skU6IjVFFGUm0A "=1403x")

**Comment by mimecuvalo** [comment]
(oh i see: this is from the PR https://github.com/tldraw/tldraw/pull/3133#issuecomment-2017431087 )
