### ISSUE TITLE
Allow deleting tools/actions from UI

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#3262]
Currently, if you want to remove a tool or action from our UI, you have to both remove it from the schema, then copy-paste all the UI default content into your app with the relevant action/tool removed. If you just try to delete it from the schema, the UI components will crash. 

Instead, we could make it so that if a tool/action is missing from the schema, we don't render the UI components referencing it. That would make it much easier for people to prune down our UI to just the set that's useful for their application.

**Comment by engin-can** [comment]
Hi @SomeHats - I was looking into a way to remove tools from the toolbar. Would you mind sharing a snippet to achieve this?
