### ISSUE TITLE
[Bug]: Error when using the text shape after reaching 2000 shapes.

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3273]
### What happened?

After creating 2000 shapes, creating a text shape causes a crash (in editing state without an editing shape).

### How can we reproduce the bug?

1. Create 2000 shapes.
2. Create a text shape.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
this looks fixed
