### ISSUE TITLE
[Feature]: Zoom with just mouse

### ISSUE THREAD

**Issue by e1turin** [tldraw/tldraw#3287]
### What's the feature?

It's really convenient to zoom canvas with just mouse. Usually applications zoom with Ctrl+scroll but more convenient way is hold left mouse button and scroll.

Such control has Pixso white board.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
dupe of https://github.com/tldraw/tldraw/issues/1344
