### ISSUE TITLE
[Bug]: export on remote image and video doesn't work. Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by khootuckhoe** [tldraw/tldraw#3288]
### What happened?

As what the title suggested, we use `registerExternalAssetHandler` to upload image to a s3 bucket. Images displayed fine. But it just won't export possibly due to cross-origin behaviors.

Message:
`Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`
```
Uncaught (in promise) TypeError: Failed to fetch
    at getDataURIFromURL (ImageShapeUtil.tsx:45:25)
    at ImageShapeUtil.toSvg (ImageShapeUtil.tsx:184:17)
    at Editor.ts:8170:28
    at Array.map (<anonymous>)
    at Editor.getSvg (Editor.ts:8160:10)
    at getSvg (export.ts:132:27)
    at exportToBlob (export.ts:192:11)
    at exportAs (exportAs.ts:39:21)
    at ScreenshotDragging.onPointerUp (Dragging.ts:87:9)
    at ScreenshotDragging.handleEvent (StateNode.ts:151:3)
```

![image](https://github.com/tldraw/tldraw/assets/42006253/ebb22514-3201-45da-9585-4aca91a4a76c)
![image](https://github.com/tldraw/tldraw/assets/42006253/bdaa9274-c0bc-4e4f-bc53-a72f11016e92)

### How can we reproduce the bug?

1. Register a custom file upload process using  `registerExternalAssetHandler` and uploads to s3.
2. Click on export or custom screenshot tool
3. Error thrown without exporting

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Contact Details

tuck.hoe.khoo@butter.us

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
You're right that this is a cross-origin issue! There are some details on this in here: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

It's not something that we can do anything about from tldraw (although we could document this a bit better). The server that you're uploading your assets to needs set CORS headers allowing access from the site you're using tldraw on (or be on the same origin)
