### ISSUE TITLE
[Example Request]: Get canvas data

### ISSUE THREAD

**Issue by timonson** [tldraw/tldraw#3290]
### What's the example?

Hello,

I serve tldraw using your example: https://tldraw.dev/quick-start

Would you mind telling me, how I get access to the binary data of the canvas? I would like to store the canvas on my server. 

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kesavaraja** [comment]
Hope this helps. 
async function downloadAsImage() {
    let shapes = data.getCurrentPageShapeIds();
    const blob = await exportToBlob({ editor: data, shapes, format: "png" });
    const file = new File([blob], name, { type: blob.type });
    let b64Data = await blobToBase64(file)
    console.log(b64Data)
  }
  const blobToBase64 = (blob) => {
    const reader = new FileReader();
    reader.readAsDataURL(blob)
    return new Promise((resolve) => {
      reader.onloadend = () => {
        resolve(reader.result);
      };
    });
  };

**Comment by timonson** [comment]
Thank you, I have access to the Editor class and therefore to `const ids = [...editor.getCurrentPageShapeIds()]` but where do I get the function `exportToBlob` from? The reason why I ask is that I can't find access to the `Tldraw` class inside React, which contains the èxportAs`method.

**Comment by Kesavaraja** [comment]
import {
  exportAs,
  exportToBlob
} from "tldraw";

**Comment by mhemon** [comment]
Hello, i have a question how you get data in this line?

 let shapes = data.getCurrentPageShapeIds();

**Comment by SomeHats** [comment]
@timonson it depends what you mean by "store the canvas on my server".

If you just want to store a non-editable image, then @Kesavaraja has the right approach - you can get at the editor (`data` in that example) either with the `useEditor` hook inside the `<Tldraw />` component, or `<Tldraw onMount={editor => { ... }} />` outside of it. You can find `exportToBlob` here: https://tldraw.dev/reference/tldraw/exportToBlob

If you actually want to store an editable version of the canvas though, you probably want to store the data for the canvas, not just a picture of it. For that, you might want to look at the snapshots example: https://tldraw.dev/examples/editor-api/snapshots

Hope this is helpful!

**Comment by Kesavaraja** [comment]
> Hello, i have a question how you get data in this line?
> 
> let shapes = data.getCurrentPageShapeIds();

Apologies. I used let data = useEditor(). I have modified the code now.

**Comment by timonson** [comment]
Thank you all. @SomeHats, `exportToBlob` works perfectly. I thought those were methods part of a class and not separate functions.
