### ISSUE TITLE
Rotate whole page

### ISSUE THREAD

**Issue by iacore** [tldraw/tldraw#3303]
### What's the feature?

In many drawing applications including Krita, there is a way to rotate the canvas to draw better since the human hand cannot be rotated 360° and still be attached to the wrist. I find this feature useful to be in tldraw, since I use it for playing paper-based games.

I am willing to implement this feature. Please tell me how. I have installed tldraw on my own server with the relevant tweak on listening PORT and domain name. Should I send that as a separate PR as well?

### Contact Details

Here on Github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
This would be a pretty big change. We'd need to add another dimension to the camera (technically a z rotation, though we use z for scale), then update the screenToPage and pageToScreen to use this value, and add the gestures needed to change this value.
