### ISSUE TITLE
[Example Request]: Toast usage.

### ISSUE THREAD

**Issue by assada** [tldraw/tldraw#3347]
### What's the example?

```js
import { Tldraw, useToasts } from 'tldraw';
const { addToast, removeToast, clearToasts, toasts  } = useToasts();
console.log(addToast, removeToast, clearToasts, toasts); //undefined undefined undefined undefined
```

is it possible to use built-in toasts?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Will close this one in favor of https://github.com/tldraw/tldraw/issues/4000. I copied the code over.
