### ISSUE TITLE
Large number of shapes causes perf regression with hitTestPoint

### ISSUE THREAD

**Issue by mimecuvalo** [tldraw/tldraw#3359]
We noticed on a board with a number of shapes that dragging something gets 'stuck' for a couple ticks because we're doing a large # of calculations.

cc @lu

**Comment by TodePond** [comment]
this is the cause of the slowdowns we were seeing

<img width="819" alt="2222" src="https://github.com/tldraw/tldraw/assets/15892272/5127b66c-1bec-41aa-8c96-ee1060b8d83d">
<img width="381" alt="3333" src="https://github.com/tldraw/tldraw/assets/15892272/87d7b2d9-821c-410e-a308-9725ce6a5f23">

![4444](https://github.com/tldraw/tldraw/assets/15892272/8cf51256-01ed-4fd9-b63d-b0628fa7aee5)


and looks like we're pitting everything too, not just notes
https://github.com/tldraw/tldraw/assets/15892272/4f562b75-8993-46e7-94b2-69c5f4847360

**Comment by mimecuvalo** [comment]
thx for investigating @TodePond !
