### ISSUE TITLE
Low level-of-detail shadows don't match rotated notes

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#3388]
<img src="https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/83401ef7-b487-4a1a-a562-d97c25d6c244/0cc32ba2-54c3-4654-89ad-86bd3ef2a2a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS84MzQwMWVmNy1iNDg3LTRhMWEtYTU2Mi1kOTdjMjVkNmMyNDQvMGNjMzJiYTItNTRjMy00NjU0LTg5YWQtODZiZDNlZjJhMmE5IiwiaWF0IjoxNzEyNTcxMTYxLCJleHAiOjMzMjgzMTMxMTYxfQ.GY8TGD5az49ZLKUOi2LTNDxqClpSKBEDBWfoILqYU8Q " alt="image.png" width="674" height="352" />

Maybe the low level-of-detail shadow should be on the same edges as the full level-of-detail note.

**Comment by mimecuvalo** [comment]
This is ok / intentional!
