### ISSUE TITLE
Context menu missing ungroup for grouped items

### ISSUE THREAD

**Issue by khootuckhoe** [tldraw/tldraw#3421]
### What happened?

When trying to ungroup an item within a group, the option of ungroup is not available when right clicking on the group item itself. It is only available when right-clicking on the resizable border or a blank space between the items.

Demonstrated in the screenshot. 
Screenshot 1 when right-clicking on the grouped item
Screenshot 2 when right-clicking on the empty space between the grouped items

![image](https://github.com/tldraw/tldraw/assets/42006253/431b07f2-944b-404c-9c1f-5c241fe23b2b)
![image](https://github.com/tldraw/tldraw/assets/42006253/c79ae0d3-6071-4088-80c4-f3e23f7e55a9)

### How can we reproduce the bug?

1. Create two grouped notes
2. Highlight them and click on group items
3. Try ungrouping by right clicking on one of the items within the group. Options not available

### Contact Details

tuck.hoe.khoo@butter.us

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
In both instances, it's now available under Edit → Group. Thanks for the bug report!
