### ISSUE TITLE
ValidationError for instance.insets

### ISSUE THREAD

**Issue by gempir** [tldraw/tldraw#3463]
### What happened?

I have canvas on `2.0.0-beta.2` 

I tried upgrading to `2.0.2` but when I try to start the editor I get this error in the console.

```
Uncaught ValidationError: At instance.insets: Expected an array, got undefined
```

The Error seems to happen somewhere here.
```
super(t?`At ${n}: ${r}`:r),this.rawMessage=e,this.path=t}name="ValidationError"}function s(e,t){try{return t()}catch(t){if(t instanceof o)throw new o(t
```

![azw8I](https://github.com/tldraw/tldraw/assets/9765622/d2e9f31a-7bf7-4962-8aec-99c9bc7848a2)

More specific version:
```
"@tldraw/tldraw@^2.0.0-beta.2":
  version "2.0.0-beta.2"
  resolved "https://registry.yarnpkg.com/@tldraw/tldraw/-/tldraw-2.0.0-beta.2.tgz#b3760b33f37a5e019dedbdcf574aec481c18531b"
  integrity sha512-gQU7JyTHobWSJ+azcrNRdjpqDknAT+3NGas/9BG9YZc+h2y+uwcy2DaY9FiAEJjQTyS+dSOrm18F6QyOUntY9g==
  dependencies:
    "@radix-ui/react-alert-dialog" "^1.0.0"
    "@radix-ui/react-context-menu" "^2.1.5"
    "@radix-ui/react-dialog" "^1.0.5"
    "@radix-ui/react-dropdown-menu" "^2.0.6"
    "@radix-ui/react-popover" "^1.0.7"
    "@radix-ui/react-select" "^1.2.0"
    "@radix-ui/react-slider" "^1.1.0"
    "@radix-ui/react-toast" "^1.1.1"
    "@tldraw/editor" "2.0.0-beta.2"
    canvas-size "^1.2.6"
    classnames "^2.3.2"
    downscale "^1.0.6"
    hotkeys-js "^3.11.2"
    lz-string "^1.4.4"
```

### How can we reproduce the bug?

I don't have a way to reproduce this bug on my dev environment yet. 

If it helps in any way my Project is open source and this is how the editor is setup https://github.com/gempir/gempbot/blob/8c99890a16fcb103dc834e79356dbbbff878c012/web/src/components/Overlay/Editor.tsx

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! [We added ](https://github.com/tldraw/tldraw/pull/2401/files#diff-ab94e4013882132d800091e3720337f12320fc17eb5ea0751e148f907dce64f0)`insets` prop to `TLInstances`. It seems to me that your saved data from the previous version would need to be migrated, so that the migrations would run and add the missing property.

You can also manually fix you `default_store.ts` by adding `insets: [false, false, false, false]` to `'instance:instance'`

**Comment by gempir** [comment]
Hmm, I understand.

Is there any guide how to migrate data? 

I setup the default_store, but I assume it will only apply to new elements, because I still get the error with this the extended default_store.

**Comment by MitjaBezensek** [comment]
`loadSnapshot` should migrate the data, but looks like you might not be [passing in the schema](https://github.com/tldraw/tldraw/blob/mitja%2Fadd-back-rbush/apps/dotcom/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx#L20-L24). Maybe this example helps.

**Comment by mimecuvalo** [comment]
We hope you were able to sort this out @gempir with the migration. If you're still stuck, please reopen and we'd be happy to help!
