### ISSUE TITLE
 HTTP 404 error appears on screen.

### ISSUE THREAD

**Issue by Anuj-Kundar** [tldraw/tldraw#348]
In Contributing.md file under the "Welcome to the tldraw contributing guide" section in 4th line table of contents icon image is not reachable. 
![image](https://user-images.githubusercontent.com/89484481/142854543-7ac857b8-bf3f-4b66-810f-4e68416ab26c.png)

![image](https://user-images.githubusercontent.com/89484481/142854650-af7390ba-a59c-46ad-ad6a-e522d73b08b9.png)

**Comment by steveruizok** [comment]
Fixed! Thanks
