### ISSUE TITLE
[feature] Middle mouse wheel pan

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#349]
The middle mouse wheel should trigger a pan event, similar to holding the space bar and dragging.

**Comment by proful** [comment]
I don't use mouse wheel that much (I'm Mac Trackpad user). Still I am trying with a external mouse, seems ok to me. Scrolling wheel shape going top down & Shift + mouse wheel movement is happening left and right direction. Not sure what behaviour expected.

![12-wheel](https://user-images.githubusercontent.com/354596/142988856-739cbe58-7899-4b4e-8450-401c6210bd1f.gif)
