### ISSUE TITLE
useIsEditing cannot be called in class component

### ISSUE THREAD

**Issue by IreneTanggh** [tldraw/tldraw#3496]
### What happened?

Hi, I am experimenting the examples for customizing my own shape utils. However, the problem happens as the title said when I tried to duplicate this example: https://tldraw.dev/examples/shapes/tools/editable-shape. 
The problem will happen when I use no matter useState and useIsEditing in a class component.

If I only use useIsEditing, the error will be:
React Hook "useIsEditing" cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
Search for the keywords to learn more about each error.

Do you know how can I solve the problem and use "useIsEditing" so that I can customize the interactions with editable shapes?

Version: `tldraw@2.0.2`

### How can we reproduce the bug?

Run this example: https://tldraw.dev/examples/shapes/tools/editable-shape

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Hi! This is because ESLint confuses the ShapeUtil class with a React class component. You can safely ask ESLint to ignore this by adding a comment above the line like this: ```// eslint-disable-next-line react-hooks/rules-of-hooks```
