### ISSUE TITLE
Selection frames misaligned on Android

### ISSUE THREAD

**Issue by Igorgro** [tldraw/tldraw#3529]
### What happened?

I tried to use tldraw on my Samsung Galaxy Tab S9, Google Chrome and see the following problem: selection frames of all shapes are misaligned and it is almost impossible to drag the edges or resize them. See screenshot

![photo_2024-04-19_00-38-14](https://github.com/tldraw/tldraw/assets/22894169/c4508b71-d574-424f-854c-772c701039ae)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackson-dahl42** [comment]
I was not able to reproduce this bug on my Galaxy S20 FE on Chrome Version 125.0.6422.52. It might have been fixed.
