### ISSUE TITLE
Add comma key to kbd shortcuts menu

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#3531]
### What's the feature?

From this issue: https://github.com/tldraw/tldraw/issues/2550

The user wasn't aware that the comma key can simulate a pointer down because we don't seem to document it anywhere. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suraj-pradhan** [comment]
I would like to work on this enhancement.
Please assign it to me

**Comment by Taha-Hassan-Git** [comment]
Go for it, suraj!
