### ISSUE TITLE
Cannot drag line shape under locked shape

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#3553]
### What happened?

1. Create a line shape.
2. Create another shape on top.
3. Lock the shape on top.
4. Select the line shape.
5. Try to move it by dragging it.

Expected: You can move the line.
Actual: You can't :(

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Fixed
