### ISSUE TITLE
[feature] tldraw spellcheck

### ISSUE THREAD

**Issue by jenningsb2** [tldraw/tldraw#357]
I would love it if tldraw had built-in spell check. I am a terrible speller, so it would be much appreciated if this was included.

**Comment by steveruizok** [comment]
This should just be a matter of turning that prop back on in the textarea components in the TextUtil and StickyUtil components.

**Comment by BRO3886** [comment]
Can I take it up?

**Comment by proful** [comment]
Sure go ahead @BRO3886
