### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by AccessViolation95** [tldraw/tldraw#3629]
### What's the feature?

https://tldraw.com/ does not support the most recent Internet Protocol version. It would be nice for people on IPv6-only networks (such as myself as of recent) to able to use tldraw as well

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Agreed we should add this:
- we need to add AAAA records to our DNS
- it looks like Vercel isn't ready to support this though... https://github.com/orgs/vercel/discussions/47
