### ISSUE TITLE
[Feature]: automatically choose dark mode or light mode according to system theme

### ISSUE THREAD

**Issue by xuanswe** [tldraw/tldraw#3668]
### What's the feature?

Same as https://excalidraw.com

![image](https://github.com/tldraw/tldraw/assets/24372782/27ea7678-41dd-4be8-a24e-9aca16aee79c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Thanks for the suggestion! We already default to the system theme when you open tldrw for the first time, but if you override that then there's no way of going back to the system theme. Should maybe have it as an option.

**Comment by xuanswe** [comment]
> Should maybe have it as an option.

Yes, that's exactly the problem. User should be able to control 3 cases: force dark, force light and according to the system theme.
Excalidraw can do it, so I expect that tldraw can too.

**Comment by MitjaBezensek** [comment]
Solved in #3703
