### ISSUE TITLE
Add table shape support

### ISSUE THREAD

**Issue by xuanswe** [tldraw/tldraw#3671]
### What's the feature?

~~Currently grid is super useful in many cases. It could be enabled at "Preferences > Show grid."
It would be more useful if we could select an area and convert the grid under this area into an actual shape, which is basically a table.~~ (Remove the initial complicated idea and replace with a new feature description as below)

While interviewing I need to draw a chessboard to explain how to solve an [8-queens puzzle](https://en.wikipedia.org/wiki/Eight_queens_puzzle).
This feature could help me save 1-2 minutes in this specific case.

According to my real-life experiences, I got many similar cases, especially with a dynamic programing problem. A table with cells in arbitrary size is extremely useful.

My proposal is to create a new **Table** shape, which is similar to the Rectangle shape but with cells inside.
The larger the drag area, the more cells the table has.
The app should have a simple algorithm to increase/decrease the number of cells when the drag area is expanded/shrunk.
After having the table with the number of cells user want, user can easily resize the whole shape to fine tune the size of cells.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xuanswe** [comment]
I would try to give my proposal on how it could be implemented.

I think this should work similar to how we draw a **Rectangle** shape.

1. Select shape **Rectangle**
2. Drag the mouse
3. The start point and the end point form the rectangle

For a **Table** shape, we can do the same

1. Select shape **Table**
2. Drag the mouse
3. The start point and the end point form the rectangle area where we can create a table inside this area

![image](https://github.com/tldraw/tldraw/assets/24372782/6d375047-ff47-4168-974a-76f4976c0e5f)

5. The rectangle area at step 3 covers a specific grid behind it and can create the table on top of that grid

![image](https://github.com/tldraw/tldraw/assets/24372782/7625dff7-9eaa-410c-bca1-55629308850e)

Note that it works even if the user doesn't enable "Preferences > Show grid."

**Comment by xuanswe** [comment]
Maybe I over complicated this shape when relating it with the grid system.
An easier way is just having a normal table shape.
By knowing the drag area, we can compute the number of cells per row/col of the table.
User can resize the whole shape, which will resize the cells accordingly.

**Comment by oytuntez** [comment]
table would be very useful, or otherwise a WYSIWYG integration like TipTap can also provide that.

**Comment by mimecuvalo** [comment]
merging this into a previous issue https://github.com/tldraw/tldraw/issues/1780
