### ISSUE TITLE
[Bug]: loadSnapshot disables keyboard

### ISSUE THREAD

**Issue by WilfredoHQ** [tldraw/tldraw#3696]
### What happened?

The keyboard stopped responding when deleting, copying, cutting, etc.
Using the buttons on the user interface, actions are carried out normally.

### How can we reproduce the bug?

- Create a shape
- Save with getSnapshot somewhere
- Delete the shapes or make any changes (optional)
- Load the saved snapshot with loadSnapshot

```ts
const snapshot = editor.store.getSnapshot()
editor.store.loadSnapshot(snapshot)
```

[See an example](https://codesandbox.io/p/sandbox/tldraw-example-forked-pgp74w)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Contact Details

wilfredo_sj@hotmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Thanks for reporting this, we'll investigate it a bit further. 

The issue seems to be that the editor looses focus. As a temporary workaround you can use:
```typescript
editor.updateInstanceState({ isFocused: true })
```

**Comment by WilfredoHQ** [comment]
Thank you very much, as you mentioned what I was trying to achieve is to load a document when the page loads for the first time.
The suggested temporary solution works great, the option to use "all" when obtaining the snapshot works just as well, but it saves data that I don't really need to save. Anyway, it's great for other cases.

**Comment by mimecuvalo** [comment]
Looks like you were able to sort this out. Let us know if you still had any issues with this though and we can work through it!
