### ISSUE TITLE
Keyboard shortcut issue

### ISSUE THREAD

**Issue by OSsqirat** [tldraw/tldraw#3699]
tldraw.com is good because it's accessible everywhere on our favorite browsers..,,, and that's exactly the issue....

# Issue:
 on Opera ... when I try to click "Ctrl G" Shortcut for grouping things.... it takes my Opera browser Shortcut first... as a priority and that doesn't allow me to Group things....

# Temp_Solution:
I changed my shortcut in my opera browser...

 I'm not into coding yet.... I don't know how to run tldraw on my laptop... I hate running it on the browsers because the browsers aren't designed for tldraw shortcuts...

**Comment by MitjaBezensek** [comment]
Thanks for letting us know. Customizable keyboard shortcuts would indeed be nice to have.

**Comment by mimecuvalo** [comment]
going to fold this into https://github.com/tldraw/tldraw/issues/3894 as it's in the same spirity
