### ISSUE TITLE
[Example Request]: How to specify a non-default font for text

### ISSUE THREAD

**Issue by mochizuki-pg** [tldraw/tldraw#3700]
### What's the example?

Are there other ways to use fonts?

```js
DefaultFontStyle: import('./StyleProp').EnumStyleProp<
  'draw' | 'mono' | 'sans' | 'serif'
>
```

I want to use an external font

I tried using defineEnum to define a new one, but it gave me an error

```js
ValidationError: At instance(id = instance:instance).stylesForNextShape.app:.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Sorry, but we don't have a good way of adding custom fonts at the moment. One way you can do it is to host the fonts yourself and then just rename the custom fonts to the names that our default fonts use. This would override one of the existing fonts though.

We definitely want to improve this in the future.
