### ISSUE TITLE
[Bug]: 800% zoom bugged for patterned shapes

### ISSUE THREAD

**Issue by MitjaBezensek** [tldraw/tldraw#3704]
### What happened?

When you have a shape with a pattern and zoom in to 800% you stop seeing the pattern and instead see a solid background for the shape.

Seems to be a result of the camera controls work, namely we changed the number of patterns we generate [in `defaultStyleDefs`](https://github.com/tldraw/tldraw/pull/3282/files#diff-9592d7e465f528dc0aa6de67043dcf938f20b2cc9c31ff738885f22368eb16dfR19), which means that some patterns then don't exist when we want to [use them in `PatternFill`](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx#L48).

### How can we reproduce the bug?

https://github.com/tldraw/tldraw/assets/2523721/707d5b83-6a7a-4cb7-b9fe-ef5ebf68d68e

### What browsers are you seeing the problem on?

Chrome

### Contact Details

mitja.bezensek@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackson-dahl42** [comment]
I was not able to reproduce this bug. When I zoom in the pattern does not disappear. Maybe this issue was fixed?
