### ISSUE TITLE
[Bug]: vite throwe error does not provide an export named 'DefaultTextAlignStyle'

### ISSUE THREAD

**Issue by cuiyajie** [tldraw/tldraw#3709]
### What happened?

I want to import tldraw normally.

### How can we reproduce the bug?

Update the tldraw to latest version

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
This seems to be exported now, are you still seeing it?

**Comment by mimecuvalo** [comment]
Let us know if you're still experiencing the issue - we'd be happy to help!
