### ISSUE TITLE
Option to exclude shape selection from history

### ISSUE THREAD

**Issue by KedarDevs** [tldraw/tldraw#3710]
### What's the feature?

I'm building an application using tldraw in which I'm using custom undo redo which effects  some data wrt whats drawn in the canvas. The issue i have is tldraw register selecting a shape and unselecting it in its History stack. I want a way to make sure that this events are not registered 
Let me know if its possible with the current features available

### Contact Details

kedard249.kd@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Bit of a hack, but you could override `setSelectedShapes` to wrap it in `editor.history.ignore`:
```tsx
<Tldraw
  onMount={(editor) => {
    const originalSetSelectedShapes = editor.setSelectedShapes
    editor.setSelectedShapes = (...args) => {
      editor.history.ignore(() => {
        orginalSetSelectedShapes.apply(editor, args)
      })
      return editor
    }
  }
/>
```

**Comment by KedarDevs** [comment]
Hey,
Thanks for the quick response but it appears that ignore is not a function in history in the version 2.0.0-alpha.19
Attaching screen shot for reference 
please let me know if there are any other methods or hacks available
thanks
![Screenshot from 2024-05-08 10-02-19](https://github.com/tldraw/tldraw/assets/154220624/02243e08-6852-4e1d-8857-edf060831f38)

**Comment by SomeHats** [comment]
Ahh yes sorry, this is only on the canaries at the moment - you'd need to update to a recent one of those, or wait for tldraw 2.2 in a couple of weeks. We recently reworked the whole undo/redo system. I think in 2.1 and below you can use the same approach of overriding the method, but need to pass in history options as a second arg instead:

```ts
    const originalSetSelectedShapes = editor.setSelectedShapes
    editor.setSelectedShapes = (ids, opts) => {
      return originalSetSelectedShapes.call(editor, ids, {...opts, ephemeral: true})
      return editor
    }
```

https://tldraw.dev/reference/editor/Editor#setSelectedShapes

**Comment by KedarDevs** [comment]
It worked
Thanks a lot
