### ISSUE TITLE
[feature] Improve text alignment

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#372]
A few changes:

- remove justify alignment
- make the default alignment center

**Comment by proful** [comment]
Can you please elaborate? Maybe one screen shot which section you are referring.

**Comment by steveruizok** [comment]
Hey, sorry this was a quick one. 

What I mean is:

- The default alignment for Text shapes should be Middle, rather than Start.
- The "justify" alignment style, shown below, should be removed from the app.

![image](https://user-images.githubusercontent.com/23072548/144766962-9e0f52c2-acc9-4109-a5a4-5510edabf1ea.png)

**Comment by steveruizok** [comment]
Closed by https://github.com/tldraw/tldraw/pull/936
