### ISSUE TITLE
[Example Request]: Custom shape with min width/height or with dynamic width/height

### ISSUE THREAD

**Issue by VadimTVJ** [tldraw/tldraw#3724]
### What's the example?

Some custom shapes should have min width/height or dynamic width/height depends on content

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Sure thing: take a look at our Speech Bubble example for something that can grow depending on the content!
https://examples.tldraw.com/speech-bubble
