### ISSUE TITLE
Mouse does not switch back to select after pan

### ISSUE THREAD

**Issue by mostaphaRoudsari** [tldraw/tldraw#3733]
### What happened?

I was playing around with the camera options and the change in the wheel behavior which is excellent! I notice that the cursor stays as a hand if I use the left click for panning instead of changing back to select mode. I can get around the issue by using the right click but it should not happen in the first place.

https://github.com/tldraw/tldraw/assets/2915573/5c7a84c2-f457-4a61-939c-5dc05c766be6

### How can we reproduce the bug?

Go to https://examples.tldraw.com/camera-options/full. Click on the middle button to pan. Now select by clicking on the left click and dragging. A hand shows up instead of the selection cursor. Here is a recording with a voice-over.

https://github.com/tldraw/tldraw/assets/2915573/9e96efeb-2ec0-4560-970c-a8434b16805a

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Thanks for the report! ❤️
