### ISSUE TITLE
[Bug]: When you run build app nextjs version 12.3.4

### ISSUE THREAD

**Issue by PequenoJoohn** [tldraw/tldraw#3734]
### What happened?

Hello everyone, today I encountered a bug while building my project using nextjs version 12.3.4. I changed the two position on the code removing the reservations names const the archives schema and validate. Altering this positions and next running again the yarn build is works.

### Step 1
node_modules/@tldraw/tlschema/dist-cjs/index.d.ts
```js
                   \/  Remove this
static defineEnum<const Values extends readonly unknown[]>(uniqueId: string, options: {
        defaultValue: Values[number];
        values: Values;
    }): EnumStyleProp<Values[number]>;
```
<img width="728" alt="Captura de Tela 2024-05-10 às 12 09 54" src="https://github.com/tldraw/tldraw/assets/25863252/7472110a-d103-4f74-8517-203e6a42011a">

### Step 2

node_modules/@tldraw/validate/dist-cjs/index.d.ts
```js
                              \/ Remove this
declare function literalEnum<const Values extends readonly unknown[]>(...values: Values): Validator<Values[number]>;
```
<img width="887" alt="Captura de Tela 2024-05-10 às 12 21 36" src="https://github.com/tldraw/tldraw/assets/25863252/b5efde68-f24d-4443-8dd8-1690d58c68a0">

### How can we reproduce the bug?

When you run build app nextjs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Thanks for the report! I will close this with no action because it seems like a typescript backwards compat issue.
