### ISSUE TITLE
[Feature]:  Add center markers for circles and shapes

### ISSUE THREAD

**Issue by Elmash** [tldraw/tldraw#3736]
### What's the feature?

Suggestion: Enhance visualization with center markers for circles and other shapes

Description: It would be helpful to have a visual indicator (e.g., a small dot or crosshair) to mark the center of circles and other shapes in the visualization. This would make it easier to understand the geometry and relationships between the shapes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
This is possible to add for custom versions of tldraw (the power of it being an open source toolkit!) But it's not something we'll be adding for our tldraw.com flagship product. Thanks for the suggestion nonetheless!
