### ISSUE TITLE
[Example Request]: Drag-and-Drop Image Upload in CustomUI Editor

### ISSUE THREAD

**Issue by mochizuki-pg** [tldraw/tldraw#3738]
### What's the example?

In customUI, is it possible to drag and drop an image in the server as an image tag and upload it to the editor?

I want to do the same thing with images displayed as `<img>` (image tag) that I can drag and drop from the Finder on my Mac to create image shapes in the editor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Our custom UI example already supports drag-and-drop from finder.

![Kapture 2024-05-17 at 16 09 10](https://github.com/tldraw/tldraw/assets/1242537/2a4be9c9-f5e4-43c8-8c32-ea09f07fb409)

I'm not sure what you mean by 'in the server' or 'image tags' though. Can you give a more detailed description of what you're trying to achieve?

**Comment by mochizuki-pg** [comment]
@ds300 

Thanks for the reply

I understand that it is possible to upload from Finder, and then I would like to know if it is possible to display an image with the image tag  (`<img />`) next to the canvas, for example, and then convert the displayed image to a shape on the campus if I slide it sideways


![スクリーンショット 2024-05-18 10 15 14](https://github.com/tldraw/tldraw/assets/38402160/2bec4b67-6803-4c40-aea3-20993b73217d)

#### image
![スクリーンショット 2024-05-18 10 19 40](https://github.com/tldraw/tldraw/assets/38402160/37d461e4-f887-4a99-b6f5-44886b61efea)
![スクリーンショット 2024-05-18 10 19 58](https://github.com/tldraw/tldraw/assets/38402160/c1964547-fb76-4601-9be3-976e55ec807a)
