### ISSUE TITLE
PDF editor example missing exported function

### ISSUE THREAD

**Issue by spencerchang** [tldraw/tldraw#3744]
### What happened?

Step1: Install page folder latest next.js 14.2.3 with default typescript.
Step2: Install latest tldraw 2.1.4,  npm install tldraw 
Step3: Follow [https://tldraw.dev/examples/use-cases/pdf-editor](url) create same folders and files.
Step4: Some missing exported function showed up.
Step5: Example couldn't work.

ExportPdfButton.tsx:
`import { Editor, assert, exportToBlob, useEditor } from 'tldraw'`
Module '"tldraw"' has no exported member 'assert'.ts(2305)

PdfPicker.tsx:
`import { AssetRecordType, Box, TLAssetId, TLShapeId, assertExists, createShapeId } from 'tldraw'`
Module '"tldraw"' has no exported member 'assertExists'.ts(2305)

PdfEditor.tsx:
`import { Box, DEFAULT_CAMERA_OPTIONS, SVGContainer, TLComponents, TLImageShape, TLShapePartial, Tldraw, compact, getIndicesBetween, react, sortByIndex, track, useEditor, } from "tldraw";`

Module '"tldraw"' has no exported member 'DEFAULT_CAMERA_OPTIONS'.ts(2305)
Module '"tldraw"' has no exported member 'compact'.ts(2305)

### How can we reproduce the bug?

Step1: Install page folder latest next.js 14.2.3 with default typescript.
Step2: Install latest tldraw 2.1.4,  npm install tldraw 
Step3: Follow [https://tldraw.dev/examples/use-cases/pdf-editor](url) create same folders and files.
Step4: Some missing exported function showed up.
Step5: Example couldn't work.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Contact Details

cww20811ss@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Thanks for the report! This was fixed in #3746 and the docs site will update to reflect those changes in our next sdk release which is planned for next week. I'll leave this open until that happens.
