### ISSUE TITLE
[Example Request]: How to hide the frame label of a Frame in custom UI

### ISSUE THREAD

**Issue by mochizuki-pg** [tldraw/tldraw#3759]
### What's the example?

Is there any way to hide the frame label of a custom UI frame?

![スクリーンショット 2024-05-15 12 15 17](https://github.com/tldraw/tldraw/assets/38402160/f7a4f50f-579a-439c-9e63-27c471e9c759)

```js
const overrides: CustomTLUiOverrides = {
  frame: (app, frame) => {
    return {
      ...frame,
      
    }
  },
}
```

```js
editor.createShapes([
    {
	    type: 'frame',
    },
])
```		

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Our SDK API doesn't support that explicitly at the moment but if you never want to show a frame label you should be able to use css

```css
.tl-frame-heading {
  display: none !important;
}
```
