### ISSUE TITLE
[Bug]: Context toolbar demo is broken

### ISSUE THREAD

**Issue by IsaacHatton** [tldraw/tldraw#3773]
### What happened?

When adding a square to canvas got this error:
![image](https://github.com/tldraw/tldraw/assets/74068072/de6a4b5e-3f76-49fc-b64b-bfb14840fbf2)

https://examples.tldraw.com/context-toolbar

Expected: no error, the context toolbar appears

### How can we reproduce the bug?

Open https://examples.tldraw.com/context-toolbar
Add a square to the page

### What browsers are you seeing the problem on?

Microsoft Edge

### Contact Details

IsaacHatton@outlook.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Thanks for the report! 🙇🏼 

I added a fix for it in #3782
