### ISSUE TITLE
Set element dimensions and position manually

### ISSUE THREAD

**Issue by rotten77** [tldraw/tldraw#3774]
### What's the feature?

As a user, I want to set the element's dimensions and position manually by entering a value so I am able to draw precise technical drawings.

Example:

Adding a line is done by the mouse down the first point, moving the mouse, and releasing the mouse button to define the second point. I want to be able to set both points manually by entering an X/Y value.

The inspiration for these features came from LibreCAD (and other CAD software):

![2024_05_18_09-26-20_PowerToys_stVjimcmFv](https://github.com/tldraw/tldraw/assets/2885380/c962e351-aeea-4ae0-94cb-242572a3560f)

The possibility to edit the element's properties will be great as well. So I can draw a line and then manually change the values. These values are apparently shown in the debug mode.

![image](https://github.com/tldraw/tldraw/assets/2885380/fb04de5a-016f-428d-a130-7804ef4ddff0)

Maybe this can be solved by "Manual add" or "Manual edit" dialogs, e.g.

![image](https://github.com/tldraw/tldraw/assets/2885380/4db0a8cb-edb9-4541-827e-95e8998ba315)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hi! Thanks for the suggestion! 

This kind of fine-grained control is somewhat at odds with tldraw's basic design philosophy. We definitely want other people to be able to add features like this inside their own apps powered by tldraw, and I think they can already. However for the core whiteboard experience it's a little too heavy.

It might make sense for a debug tool, but I wouldn't necessarily say that we'd gladly welcome PRs to that effect.
