### ISSUE TITLE
[Bug]: VSCode extension v2.0.33 prevents vscode from opening any panels

### ISSUE THREAD

**Issue by Gozala** [tldraw/tldraw#3785]
### What happened?

Since last week TLDraw vscode extension made use of vscode nearly impossible as it prevents command pallet or any other floating panels from functioning. For a brief moment panels appear and then disappear right away. If no document with tldraw is open everything works as expected.

My vscode version is  Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z (1 wk ago)
My tldraw extension version is: v2.0.33

I'm not sure what exactly is going on but I suspect that tldraw just attempt to gain a focus causing any floating panels to close.

### How can we reproduce the bug?

1. Open any file with `.tldraw` extension
2. Trigger command pallet (e.g. via CMD-Shift-P combo)

I would expect to be able to type inside command pallet. Instead command pallet appears and dissapears.

### Contact Details

contact@gozala.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Are you still seeing this? Tried to reproduce but was not able to.

**Comment by Gozala** [comment]
Seems to be fixed in latest vscode and extension, thanks.

**Comment by MitjaBezensek** [comment]
Great, thanks for letting us know.
