### ISSUE TITLE
[Bug]: With next.js having EventEmitter error

### ISSUE THREAD

**Issue by spencerchang** [tldraw/tldraw#3816]
### What happened?

1. Pure install next.js page folder installation (next.js version 14.2.3) 
2. npm install tldraw (tldraw version 2.1.4)
3. Paste the github sample code:
import { Tldraw } from 'tldraw'
import 'tldraw/tldraw.css'

```
export default function App() {
    return (
        <div style={{ position: 'fixed', inset: 0 }}>
            <Tldraw />
        </div>
    )
}
```

Having error message like screenshot.

<img width="1002" alt="2024-05-12_10 44 57" src="https://github.com/tldraw/tldraw/assets/10862903/b03e0f60-16d3-4915-9435-0b393357a287">

Similar with #1817 and follow comment by phgn0
Change files from node_modules and patch it can fix this issue but seems wired because when new user using it at first with 2 issues and have to modify node_modules to patch it.

### How can we reproduce the bug?

1. Pure install next.js page folder installation (next.js version 14.2.3) 
2. npm install tldraw (tldraw version 2.1.4)
3. Paste the github sample code:
import { Tldraw } from 'tldraw'
import 'tldraw/tldraw.css'

```
export default function App() {
    return (
        <div style={{ position: 'fixed', inset: 0 }}>
            <Tldraw />
        </div>
    )
}
```

Having error messages

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Contact Details

cww20811ss@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acidtib** [comment]
running into the same issue with fresh.deno.dev, commenting here so i can get notify

**Comment by SomeHats** [comment]
We changed this recently, but it's not been published yet. Could you try installing a canary (`npm install tldraw@canary`) and seeing if that fixes the issue?

**Comment by imdhineshtp** [comment]
After installing the canary version, the issue got resolved, and now it's working fine in my Next.js project.

**Comment by spencerchang** [comment]
Since v2.2.0 this issue fixed.
Thank you.
