### ISSUE TITLE
[bug] Tldraw Component Doesn’t Stay in Parent Container

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#382]
I'm trying a test where I embed the  @tldraw/tldraw component into a page in a small window. But it doesn't respect the container I put it in. It's width/height of the page window no matter what.

grey part is the container, that'd I'd expect it to stay within
<img width="1440" alt="22A0A620-ED96-49CC-883D-F7B6B3844F11" src="https://user-images.githubusercontent.com/1845/143367136-1eec1dea-a2e2-483b-820f-a992d673d64e.png">

**Comment by seflless** [comment]
Steve commented on this on Discord;

```
Oh really? That shouldn’t be the case.

You're right, eek

Ah you might need to wrap it
```

```ts
<div
        style={{
          position: 'relative',
          width: '100%',
          height: '500px',
          overflow: 'hidden',
          marginBottom: '32px',
        }}
      >
        <Tldraw />
      </div>
```
![29AD8F1D-EDD4-4366-9C76-5C473C8E56DA](https://user-images.githubusercontent.com/1845/143367439-2980d6e1-05a5-4f6e-8cf9-09f85b3a4c20.png)

```
The position will fill the first relative position above it

body if nothing else

```

**Comment by steveruizok** [comment]
Closing this one, though glad to have this discoverable as an issue.
