### ISSUE TITLE
[Example Request]: Export Custom shape as Image

### ISSUE THREAD

**Issue by Kesavaraja** [tldraw/tldraw#3820]
### What's the example?

As explained in the title, we have examples for custom shapes but what we are missing in the sample I visited( #Sample 1, #Sample 2) are we are not able to export the custom component as image. It download blank component.
<img width="264" alt="shape_ejVcb-sngy65GCiEbjfYB at 24-05-23 16 35 20" src="https://github.com/tldraw/tldraw/assets/12864243/76add5a8-8432-483c-b963-891aaa194f43">

https://tldraw.dev/examples/shapes/tools/interactive-shape
https://tldraw.dev/examples/shapes/tools/custom-shape

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! We now have an example of how to do an export. You have to override the `toSvg` method. You can see it [here](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/toSvg-method-example/CustomShapeToSvgExample.tsx).

(for now just on the [staging version of docs](https://staging.tldraw.dev/examples/shapes/tools/toSvg-method-example))

**Comment by Kesavaraja** [comment]
Thanks for the example. But still we are unable to make it possible. Can you make the changes in #[this example](https://tldraw.dev/examples/shapes/tools/custom-config) ?
