### ISSUE TITLE
[Bug]: arrow binding points are sometimes missing on tldraw.com

### ISSUE THREAD

**Issue by si14** [tldraw/tldraw#3831]
### What happened?

Picture is worth a thousand words, a gif is worth a million:

https://github.com/tldraw/tldraw/assets/316910/cee45a74-9735-4b45-aa1a-977fb4bcc792

Note how the grey binding point blinks a couple of times but is generally not there.

### How can we reproduce the bug?

This file reproduces the behaviour for me on tldraw.com as of now

[green_box.tldr.zip](https://github.com/tldraw/tldraw/files/15433548/green_box.tldr.zip)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kobe651jp** [comment]
I have same issue

**Comment by mimecuvalo** [comment]
Hi Dan! 👋 thanks for the report :)

**Comment by si14** [comment]
It is now resolved, thank you ❤️
