### ISSUE TITLE
[bug] Text 'completing' before typing has finished

### ISSUE THREAD

**Issue by Glazy** [tldraw/tldraw#384]
When using multiplayer, text often 'completes' and loses focus before I have finished typing. This means I have to double click on the text box again to make it editable and continue typing.

This happens fairly frequently for me in multiplayer rooms but I haven't yet been able to reproduce it in a solo drawing room.

**Comment by steveruizok** [comment]
This is related to #373 ! We should be "syncing" after you're finished typing, rather than on every character. It's a bug!

**Comment by steveruizok** [comment]
Good god this is an annoying one.

**Comment by steveruizok** [comment]
Closed by #427 !
