### ISSUE TITLE
[Bug] example(interactive-shape) not working properly in mobile(tablet)

### ISSUE THREAD

**Issue by kobe651jp** [tldraw/tldraw#3845]
### What happened?

The [example](https://tldraw.dev/examples/shapes/tools/interactive-shape) not working mobile(android,ios).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Fixed here https://github.com/tldraw/tldraw/pull/4209
