### ISSUE TITLE
[Feature]: the latest release v2.1.4 do not include some functions than main branch has. such as MediaHelpers.isImageType

### ISSUE THREAD

**Issue by danlanxiaohei** [tldraw/tldraw#3853]
### What's the feature?

MediaHelpers.isImageType is in main branch , but not include in the latest release v2.1.4, so when i use [npm install tldraw] in my project, i can not use functions like: MediaHelpers.isImageType...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Yeah, we haven't cut a release to NPM yet, we're waiting for some more API stability. Thanks for your patience!

**Comment by mimecuvalo** [comment]
This has been released since the last comment 👍
