### ISSUE TITLE
[Bug]: editor.getFocusedGroupId() returns the page Id when there is no group focused

### ISSUE THREAD

**Issue by ricardo-crespo** [tldraw/tldraw#3858]
### What happened?

`editor.getFocusedGroupId()` returns the page Id when there is no group focused. What I was expecting is getting `undefined`, the result we get with `editor.getFocusedGroup()` in the same situation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Thanks for bringing this up. 

Yeah, this is a leftover of some code from before. At least for now we decided not to change it though. If you really need to just get the group id then you can use the mentioned `getFocusedGroup` and then get id from the returned shape. Or you can also use `isShapeId` helper to see if we are dealing with a shape or a page id.
