### ISSUE TITLE
[bug] Main menu clicking

### ISSUE THREAD

**Issue by csholmq** [tldraw/tldraw#386]
When clicking e.g `Copy` in the main menu I would expect it to go away as to confirm my action. But the menu persists causing me to question if I was successful in clicking.

Maybe introduce an animation for the clicking or simply have the menu go away when clicked on a child node?

**Comment by steveruizok** [comment]
Good point, there's really no feedback at the moment. Perhaps #45 could help?

Our menu is currently a hack of Radix-UI's dropdown menu. IIRC the default behavior is for those buttons to close the menu, and we're preventing that behavior in some places (for example, toggling dark mode) where a user may be "trying out" different modes.

**Comment by csholmq** [comment]
If you want to keep inhibiting the default menu behaviour for other reasons then I think #45 would be a good improvement 👌

**Comment by steveruizok** [comment]
Closing this issue, as it will be addressed in #45. Thanks @csholmq
