### ISSUE TITLE
[Feature]: Add "New shared project" to the File menu

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3861]
### What's the feature?

On tldraw.com, add an option in the File menu to create a new shared project.

This should:
- emit a ui tracking event
- navigate to /r/new

<img width="668" alt="image" src="https://github.com/tldraw/tldraw/assets/23072548/c2a9cef8-f472-44a3-b607-c5dc7b293a48">

<img width="596" alt="image" src="https://github.com/tldraw/tldraw/assets/23072548/dd40232a-8a4f-4dd1-8de8-60c4b7cdb36d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
✅
