### ISSUE TITLE
Docs are outdated

### ISSUE THREAD

**Issue by Favourz1** [tldraw/tldraw#3864]
### What happened?

Docs say import useEditor but example [here](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/editor-focus/EditorFocusExample.tsx) uses a diffrent method

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Inside of the `<Tldraw />` component (ie custom in-editor UI, anything on the canvas, custom shapes, etc.) `useEditor` is still the easiest way to get hold of the editor instance. It only works in children of that component though. In that example, we're working with components outside of the tldraw component - so we use that alternative approach instead.
