### ISSUE TITLE
Image cropping sets crop mode for all images instead of just selected one

### ISSUE THREAD

**Issue by mimecuvalo** [tldraw/tldraw#3872]
Going into crop mode makes all images go into crop mode. It feels maybe a bit unexpected (at least to me and David when we ran into this). Maybe only the selected image should go into crop mode.

**Comment by dimateos** [comment]
Might be intended, but I agree that it seems unintuitive given the fact that to _enter_ crop mode you double click a _specific_ image.

I would keep single click for selecting always **consistent** and leave double click to start cropping other images.

Right now, if your need to quickly select and move other you need to _exit_ crop mode before being able to do so:

![2024-06-07_(101547)_chrome](https://github.com/tldraw/tldraw/assets/26868611/6b2b7daf-a003-476b-8dad-b3f1ad19b6aa)

**Comment by MitjaBezensek** [comment]
> Going into crop mode makes all images go into crop mode. It feels maybe a bit unexpected (at least to me and David when we ran into this). Maybe only the selected image should go into crop mode.

The reasoning was to keep it consistent with text editing. There you also continue editing even when you select a different text shape 🤷‍♂️

**Comment by mimecuvalo** [comment]
Yeah, I could understand this reasoning! Ok, closing this issue. Thanks for the responses!
