### ISSUE TITLE
Persistence link not rendered on Editor docs page

### ISSUE THREAD

**Issue by Oktosha** [tldraw/tldraw#3901]
### What happened?

The chapter [Listening for changes, and merging changes from other sources](https://tldraw.dev/docs/user-interface#Listening-for-changes-and-merging-changes-from-other-sources) contains the following sentence

"""
For information about how to synchronize the store with other processes, i.e. how to get data out and put data in, see the (Persistence)[/docs/persistence] page
"""

The last part of it looks like an unrendered link.

Also there is a typo in the word "synchronize", the autocorrect tells it should be "synchronise".

### How can we reproduce the bug?

Open the link https://tldraw.dev/docs/user-interface#Listening-for-changes-and-merging-changes-from-other-sources

### Contact Details

kolodaria@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Oktosha** [comment]
Hmm, the links in my bug report are messed up, should be https://tldraw.dev/docs/editor#Listening-for-changes-and-merging-changes-from-other-sources with the "editor" not "user-interface" in them ._.

**Comment by Oktosha** [comment]
The issue didn't show up when I built the docs locally.

**Comment by MitjaBezensek** [comment]
Thanks for reporting this! 🙌 
Looks to be [solved](https://tldraw.dev/docs/editor#Listening-for-changes-and-merging-changes-from-other-sources) now. Syncronize is the British spelling of the word, so I think I'll leave it at that.
