### ISSUE TITLE
[documentation] Switch to "Tldraw" from "tldraw-org" on the VS Code Extension Marketplace

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#394]
It'd be more consistent to use "tldraw" instead of "tldraw-org" on the marketplace.
<img width="624" alt="this-org" src="https://user-images.githubusercontent.com/1845/143680493-6b67a175-59f5-4390-b180-705a996959b5.png">

**Comment by steveruizok** [comment]
I do have tldraw as an org now, but I'm not sure if we can republish the same extension from different orgs. It could end up having users needing to uninstall the one extension in order to install the other, which would be a lot of friction. We could just keep it?

**Comment by seflless** [comment]
I'd assume you can transfer ownership to another org like you can an npm package or git repo, but might be wrong.

I just wanted to track the question if it was easy. Feel free to close this if you'd like.

**Comment by steveruizok** [comment]
Right on. I'm going to close until I know more about transferring between projects.
