### ISSUE TITLE
[Bug]: Copy-pasting from tldraw.com to the file using VSCode Plugin produces empty `"records"` field

### ISSUE THREAD

**Issue by TheKnarf** [tldraw/tldraw#3940]
### What happened?

- Create a diagram on tldraw.com
- Install the VSCode plugin for Tldraw
- Create an empty file called `something.tldr`, opening it shows an empty drawing
- Copy-paste a diagram from tldraw.com into the VSCode plugin
- The diagram shows up in editor but the file have an empty `"records"` field

To fix:
- Simply edit anything in the diagram and then save. 

### How can we reproduce the bug?

See steps above ^

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Could you please try this again and let us know if you still see it? I'm suspecting the website and the VS Code were not on the same version when that happened.

**Comment by TheKnarf** [comment]
![Screenshot 2024-09-13 at 10 39 48](https://github.com/user-attachments/assets/f2c255d4-86a6-46d4-b1ce-127eb80d3c69)

Works even worse now... Can't even open a new empty file.

## What happened?

- Install the VSCode plugin for Tldraw
- Create an empty file called something.tldr, opening it and it crashes...

**Comment by MitjaBezensek** [comment]
Can you tell us a bit more:
* What version of the extension are you using?
* What's your VS Code version? 

I tried it on VS Code Version: 1.91.1  and tldraw v2.12.0 and it does seem to work for me, so it must be some difference in our environments.

https://github.com/user-attachments/assets/fedd370e-0351-407f-b1de-742b685dd330

**Comment by TheKnarf** [comment]
Restarted VSCode and it now shows an empty file again. So might have been a version problem. But my original reported problem seems to persist:

![Screenshot 2024-09-13 at 11 17 22](https://github.com/user-attachments/assets/9b02c157-2a83-437b-9fe5-5098fb833f59)

![Screenshot 2024-09-13 at 11 18 39](https://github.com/user-attachments/assets/27dd1a61-048f-4c2c-976c-4cc9c74df9e0)

tldraw extension v2.12.0

**Comment by MitjaBezensek** [comment]
You definitely need to save the document for the change to persist to the file, it's the same as with regular text files - just pasting won't persist it on disk. That said, just pasting should mark the file as dirty. When I paste I get this dot notifying me that I have unsaved changes in the file. Does this not happen to you? Does it only appear after making another change?
![image](https://github.com/user-attachments/assets/820af481-7ed4-4018-a035-1a70da6f1123)

**Comment by TheKnarf** [comment]
Not getting any dot.

**Comment by TheKnarf** [comment]
https://github.com/user-attachments/assets/a64e465c-cb0b-43fe-b861-4dabc9854859

**Comment by MitjaBezensek** [comment]
Thanks for the info, will investigate. Seems like the dirty tracking is not working as it should in this case.

**Comment by MitjaBezensek** [comment]
We just released a new pre release version that should fix this issue. Could you give it a try and let me know if it now works?
To install a prerelease version you can go to the extension manager, select tldraw, then click the switch to prerelease:
![CleanShot 2024-09-20 at 15 16 29@2x](https://github.com/user-attachments/assets/3d0b2f1f-4ae4-467a-95da-6a7816045df7)
