### ISSUE TITLE
Shape shifting when scaling

### ISSUE THREAD

**Issue by andreterron** [tldraw/tldraw#3945]
### What happened?

I created a pencil shape with a rectangle and triangle. When scaling it, the triangle shifts away from the rectangle.

https://github.com/tldraw/tldraw/assets/1753594/ed2217e5-a17a-4b62-bb1f-88b331369e0a

### How can we reproduce the bug?

https://github.com/tldraw/tldraw/assets/1753594/34a2619e-7525-44e0-90f2-d1c12c99d4bf

### What browsers are you seeing the problem on?

Chrome

### Contact Details

andre.v.terron@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Quick note for later, the shapes must have different rotations to reproduce the bug.
