### ISSUE TITLE
Copy and paste not working on Firefox

### ISSUE THREAD

**Issue by screaminglineage** [tldraw/tldraw#3949]
### What happened?

Copying and pasting drawings and uploaded images does nothing on Firefox but work perfectly on chromium based browsers. This is the case for both the keyboard shortcuts as well as the right click menu.

### How can we reproduce the bug?

Draw or upload an image and try to copy and paste it.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
This was fixed, please try it out and let us know if it now works for you.

**Comment by screaminglineage** [comment]
@MitjaBezensek Seems like its fixed for me. Copy-pasting works as usual
