### ISSUE TITLE
Build error in Next.js with tldraw v2.2.1

### ISSUE THREAD

**Issue by imdhineshtp** [tldraw/tldraw#3961]
### What happened?

When attempting to run the yarn build command in my Next.js project, which includes the tldraw v2.2.1 whiteboard implementation, I encounter a TypeScript error originating from the @tldraw/store package in node_modules.

**Environment:**
- tldraw version: 2.2.1
- Next.js version: 12.1.5
- Node.js version: 20.9.0
- Yarn version: 1.22.19
- Operating System: Win 11

**Expected Behavior:**
The project should build successfully without any errors.

**Actual Behavior:**
The build process fails with the following error:

```
./node_modules/@tldraw/store/dist-cjs/index.d.ts:79:44
Type error: Type parameter declaration expected.

  77 |  * @public
  78 |  */
> 79 | export declare function createMigrationIds<const ID extends string, const Versions extends Record<string, number>>(sequenceId: ID, versions: Versions): {
     |                                            ^
  80 |     [K in keyof Versions]: `${ID}/${Versions[K]}`;
  81 | };
  82 |
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How can we reproduce the bug?

- Install tldraw v2.2.1 in a Next.js project.
- Attempt to build the project using the yarn build command.

### Contact Details

imdhineshtp@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
What version of typescript are you using? Maybe you can try bumping that and see if it helps (we are using 5.3.3 just as an example).

**Comment by imdhineshtp** [comment]
It's resolved after upgrading the typescript. 

Thanks @MitjaBezensek

**Comment by MitjaBezensek** [comment]
Awesome, thanks for getting back to me 🙌
