### ISSUE TITLE
Validation error for pin binding type

### ISSUE THREAD

**Issue by kobe651jp** [tldraw/tldraw#3985]
### What happened?

I created a custom shape pin by referring to [example](https://tldraw.dev/examples/shapes/tools/pin-bindings)  (it's almost the same).

When I created a shape and placed a pin on it, the following error occurred.

However, this kind of error does not occur in the official example.

I think I'm using it wrong somewhere, but if anyone has any idea, please give me some advice.

![image](https://github.com/tldraw/tldraw/assets/44263972/fc8e5528-9c35-434a-b6ce-45e8aeb7d7c0)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Please check that the name you used when you created the `PinBinding` is the same as the one you use when you create the binding via `editor.createBinding`. Seems like you might have a mismatch there.
