### ISSUE TITLE
Set origin to center in shape object

### ISSUE THREAD

**Issue by dennishansen** [tldraw/tldraw#3989]
### What's the feature?

Would be helpful to set the origin of a shape to be the center so that the x and y properties would correspond to the center of the object, and simply passing in rotation values would rotating around the center origin. My use case is simplify controlling rotations and positions in holograph.so

### Contact Details

dhansen909@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Did you try using the `editor.rotateBy` method? That one should rotate things around the centre.

**Comment by mimecuvalo** [comment]
Let us know if that didn't solve the issue for you by reopening this ticket and we'd be happy to help out more 👍
