### ISSUE TITLE
Custom embed definitions

### ISSUE THREAD

**Issue by jorgen-braseth-adsk** [tldraw/tldraw#3994]
### What's the feature?

Today, the getEmbedInfo function is exposed, which lets us plug into the already supported embeddable urls and how they map to shapes (using EMBED_DEFINITIONS).

However, we are building a solution on top of TLDraw, and we have our own URLs that are only embeddable within our application - we would very much like to use the embed definitions in order to handle our own URLs, but right now, we just have to add our own, parellell logic to handle our own urls.

### Contact Details

jorgen.aars.braseth@autodesk.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Yeah, we definitely want to add this. Will close this one in favor of #2579
