### ISSUE TITLE
Mismatching types

### ISSUE THREAD

**Issue by merobal** [tldraw/tldraw#3999]
### What happened?

For `loadSnapshot` the fields of `TLEditorSnapshot` are optional, see `_snapshot: Partial<TLEditorSnapshot>`

but for `TldrawImage` and `useTLStore` (and at few other places) all fields of `TLEditorSnapshot` are required, see `snapshot: TLEditorSnapshot`

but the snapshot is loaded to `loadSnapshot`, so it seems it can be safely optional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EryouHao** [comment]
I encountered the same problem, have you solved it?
