### ISSUE TITLE
[bug] Remove warning when pasting plain text.

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#400]
When you have copied text from either outside Tldraw or say a Sticky's textarea, and then paste, an exception is logged to the console.

This doesn't seem to effect behavior, but perhaps the console.warning of the error should be removed?

https://user-images.githubusercontent.com/1845/143690170-e4af3fd2-993a-4363-b43c-b0b10f7b6826.mov

**Comment by BRO3886** [comment]
Yeah from what I could see, the code is trying to parse JSON just in case it was copied from tldraw, to make it a shape again. It's wrapped in a try-catch so for regular text it just throws a warning via `console.warn()`

The warning can be removed I guess
