### ISSUE TITLE
Request to Increase 6,000 Shape Limit in Tldraw

### ISSUE THREAD

**Issue by Higashi-Kota** [tldraw/tldraw#4028]
### What's the feature?

# Abstract

I believe the shape limit in Tldraw has been increased to `4,000`. Could you please consider raising this limit to `6,000`?
I am currently developing an application that requires a large number of shapes, and the `4,000` limit poses a restriction.
As illustrated in the screenshot below, each item consists of a rectangular shape paired with a text label representing that rectangle. There are more than `2,000` such items, and thus, the total number of shapes exceeds `4,000`.

![demo](https://github.com/tldraw/tldraw/assets/70569799/718cf7c3-d713-48eb-9571-d210472962eb)

# Related

- [ ] https://github.com/tldraw/tldraw/issues/3842
- [ ] https://github.com/tldraw/tldraw/pull/3716

### Contact Details

higashi.kota@gri.jp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
![Over_9000](https://github.com/tldraw/tldraw/assets/469604/ec2ce2b5-6d8a-4552-aed4-f459fed0f70c)

sorry, it had to be said :P

**Comment by Higashi-Kota** [comment]
> ![Over_9000](https://github.com/tldraw/tldraw/assets/469604/ec2ce2b5-6d8a-4552-aed4-f459fed0f70c)
> 
> 
> 
> sorry, it had to be said :P

Thank you for letting me know! Since it will not exceed 9,000 items, the limit of 6,000 items is fine.

**Comment by SomeHats** [comment]
Hey! If you're developing a custom app with the tldraw SDK, you can set the shape limit to anything you like using the `options` prop on the `<Tldraw />` component: https://tldraw.dev/reference/editor/TldrawOptions

e.g.
```tsx
const options = {maxShapesPerPage: 9000}

function MyApp() {
    return <Tldraw options={options} />
}
```

**Comment by Higashi-Kota** [comment]
Thank you for letting me know!
