### ISSUE TITLE
[bug] Pink Menu button shown for sponsors in multiplayer 

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#404]
When a user is a sponsor and is logged in, the menu button is shown as white and the Sponsor button is hidden. However, in the multiplayer route (apps/www/pages/r/[id].tsx) the menu button is still shown the same as if the user was not logged in or not a sponsor.

**Comment by japneetsingh035** [comment]
Hello, @steveruizok I would like to work on this bug. Please let me know if I can start.

**Comment by steveruizok** [comment]
> Hello, @steveruizok I would like to work on this bug. Please let me know if I can start.

Go for it!
