### ISSUE TITLE
[Feature]: Allow an "API only lock" for. TLDraw shapes

### ISSUE THREAD

**Issue by anmolsood21** [tldraw/tldraw#4041]
### What's the feature?

Locking shapes currently also prevents from any programatic updates/deletions to them. As a result, we always need to unlock them before performing such API updates. It would be helpful to lock updates from the user but still allow any programatic updates.

See discussion here: https://discord.com/channels/859816885297741824/1255938459978432623

### Contact Details

anmol@getalai.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! We just introduced a new method called `run` on the `Editor` class. It allows you to run some code with some additional options, one of them being `ignoreShapeLock` which is exactly what you need. This is now available in the canary version of the package and it should be coming to next stable release.

**Comment by MitjaBezensek** [comment]
Resolved by https://github.com/tldraw/tldraw/pull/4042
