### ISSUE TITLE
Make ShapeIndicators customizable

### ISSUE THREAD

**Issue by anmolsood21** [tldraw/tldraw#4072]
### What's the feature?

`ShapeIndicator`  (which renders the specific indicator for a shape) is customizable but [`ShapeIndicators`]((https://github.com/tldraw/tldraw/blob/c1fe8ec99aa96a7f355c587d7ce97afdc66bab45/packages/editor/src/lib/components/default-components/DefaultCanvas.tsx#L451))  (which calculates all the shapes for which the indicator should be rendered and then wraps around ShapeIndicator) isn't.

 The latter seems very tightly coupled with the select tool and certain states there and given that the tools themselves are customizable (for example one can have a custom select tool), I would expect ShapeIndicators to be customizable too like all other components in the DefaultCanvas.

See https://discord.com/channels/859816885297741824/1258169204138442782/1258169204138442782 for discussion

### Contact Details

anmol@getalai.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
This was added here https://github.com/tldraw/tldraw/pull/4083
