### ISSUE TITLE
[Example Request]: Load JSON/tldr in component

### ISSUE THREAD

**Issue by Vanshbordia** [tldraw/tldraw#4076]
### What's the example?

Using store & persistent is useful to span the data across browser tabs, but I want to have a <Tldraw> Component on the page with custom data passed to it, the store prop would make it persistent with other pages and cause issues. Is there a simpler way to just save / export from tldraw and host the file and pass the json / tldr file to render on my page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kesavaraja** [comment]
[editor.store.loadSnapshot](https://tldraw.dev/reference/editor/loadSnapshot) may help you

**Comment by Kesavaraja** [comment]
If you see that there is a variation with your JSON, kindly check the version of TLdraw you are using.
Because I am able to use getSnapshot and loadSnapshot from editor.store without any issues.

**Comment by Vanshbordia** [comment]
I am on version 2.3.0. Exporting from the website tldraw.com as well as the local version the json does not contain the same data that store or snapshot contains, the structure itself is different

**Comment by Kesavaraja** [comment]
Export is different from Snapshot. Snapshot contains Schema and store in json but export as json contains schema and shapes. Just use getSnapshot and loadSnapshot from editor.store for easier work.

**Comment by mimecuvalo** [comment]
Looks like you were able to figure this out. Thank you @Kesavaraja for your assistance!!

**Comment by acmoles** [comment]
If you also end up in a pickle where you started using .tldr or .json export and wanted to switch to snapshots, here are some scripts: https://gist.github.com/acmoles/ff525d1e8a0c7bf14ea3d47fd6cab6b1
