### ISSUE TITLE
[Bug]: example error

### ISSUE THREAD

**Issue by chengfengfengwang** [tldraw/tldraw#4081]
### What happened?

When I add config option to Tldraw the code from [store-events](https://tldraw.dev/examples/editor-api/store-events) can't work.

### How can we reproduce the bug?

just add a cameraOptions config will cause infinite loops bug.

```
<Tldraw cameraOptions={{zoomSpeed:0.7}} onMount={setAppToState} />
```

### What browsers are you seeing the problem on?

Chrome

### Contact Details

602120734@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
I wasn't able to reproduce this. What version of the library are you using? Can you maybe try canary to see if it was maybe fixed?

**Comment by mimecuvalo** [comment]
@chengfengfengwang if you are able to provide more information that would be helpful. Please reopen this issue if so and we'd be happy to help!
