### ISSUE TITLE
[Feature]: Make useStateTracking hook public

### ISSUE THREAD

**Issue by anmolsood21** [tldraw/tldraw#4085]
### What's the feature?

TLDraw allows custom `ShapeIndicator` component. TLDraw's `DefaultShapeIndicator` uses useStateTracking hook to optimize perf. 

I want a custom shape indicator as I don't necessarily want my indicator to just be an SVG.  I still want to be able to use `useStateTracking` to have the same optimizations while I change how the indicators look.

### Contact Details

anmol@getalai.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
I think I'd be happy to do this now that it seems very stable, is it blocking you? If so you could always copy+paste the implementation. None of the underlying APIs are going to change and I believe they're all public.

**Comment by anmolsood21** [comment]
@ds300, the reason I cannot copy paste the implementation is that it uses `EffectScheduler` which isn't public from the tldraw library

**Comment by ds300** [comment]
ah sorry! that's a definite error. it should be public. I guess I'll just make them both public now.
