### ISSUE TITLE
[Bug]: Not able to add Google Slides url

### ISSUE THREAD

**Issue by deannaboiani** [tldraw/tldraw#4093]
### What happened?

I have attempted to add a Google Slides url and I am getting the "We cannot create an embed from that URL" pop-up which blocks the create button. Is there a specific url format or place I need to retireve the url from? I have tried going into the slides themselves and copying the url from my window, I also tried using the share link. I have made my slides public to anyone as well.

### How can we reproduce the bug?

Go into a presentation from google slides, copy the url and attempt to add it using the Google Slides insert embed option.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

deanna@pendulumintel.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! You need to publish it to the web. You can find that under File -> Share -> Publish to the web and then copy the link from there. Let me know if that works.

**Comment by deannaboiani** [comment]
That worked, thank you!

**Comment by MitjaBezensek** [comment]
Great!
