### ISSUE TITLE
[bug] Non-pinch zoom incorrect when embedded

### ISSUE THREAD

**Issue by AdventureBeard** [tldraw/tldraw#413]
Mac OS, Chrome 96.0.4664.55, but confirmed on Windows Chrome/FF as well.

In the embedded demo, when using Option + Scroll zoom, the zoom anchor point moves around and causes the viewport to fly off in a direction related to mouse position. The Ctrl+Scroll zoom, or pinch zoom, does not have the same issue. This problem goes away when the Tldraw container CSS is set to `position: fixed; top: 0; left: 0;`.

**Comment by steveruizok** [comment]
Thanks!
