### ISSUE TITLE
[Example Request]: Project sharing and data storage for self-hosting

### ISSUE THREAD

**Issue by Charbo23** [tldraw/tldraw#4130]
### What's the example?

I'm working on self-hosting, but found it difficult to meet my needs.
I want each of my files can have a unique link, like the official demo site do, so that anyone who gets the link can access the collaboration. 
In order to implement this, the first thing to do is how to store the data in my own database.
Any example would be appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Sure! Take a look at our fully-featured Cloudflare example: https://github.com/tldraw/tldraw-sync-cloudflare
That should help you on your journey. That example uses Cloudflare's Durable Objects but you could also figure out a postgres database instead behavior too.

Hope that helps! Please let us know if you still feel like you're stuck after taking a look at that example though.
