### ISSUE TITLE
[Example Request]: How do i disable certain shortcuts like ctrl+z for undo 

### ISSUE THREAD

**Issue by KedarDevs** [tldraw/tldraw#4131]
### What's the example?

I want to disable certain shortcut as they effect the way things are rendered on my app, let me know how i can disable undo redo on shortcut

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rangelkoli** [comment]
You can use the KeyboardShortcut.tsx example and edit the code as below

```
const overrides: TLUiOverrides = {
	//[a]
	actions(_editor, actions): TLUiActionsContextType {
		const newActions = {
			...actions,
			'toggle-grid': { ...actions['toggle-grid'], kbd: 'x' },
			'copy-as-png': { ...actions['copy-as-png'], kbd: '$1' },
			undo: { ...actions['undo'], kbd: '' },
			redo: { ...actions['redo'], kbd: '' },
		}

		return newActions
	},
	//[b]
	tools(_editor, tools): TLUiToolsContextType {
		const newTools = { ...tools, draw: { ...tools.draw, kbd: 'p' } }
		return newTools
	},
}
```


By adding 			
undo: { ...actions['undo'], kbd: '' },
redo: { ...actions['redo'], kbd: '' },
to the actions, you can disable them, it wont show up in the Keyboard shortcut menu either.
