### ISSUE TITLE
[Bug]: If the parent element is scaled, all tool positions will be abnormal. 

### ISSUE THREAD

**Issue by StringKe** [tldraw/tldraw#4139]
### What happened?

When the scale of the parent element is not 1, all tools will be offset and their positions will be incorrect.

### How can we reproduce the bug?

Toggle zoom and use the brush at different zooms

https://codesandbox.io/p/sandbox/tldraw-example-forked-785nmd

### What browsers are you seeing the problem on?

Chrome

### Contact Details

stringke@126.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Closing this, looks like a duplicate of https://github.com/tldraw/tldraw/issues/1865
