### ISSUE TITLE
[bug] Erasing within an unfilled shape erases the shape

### ISSUE THREAD

**Issue by rjt-rockx** [tldraw/tldraw#414]
When a rectangle (or any other shape for that matter) is drawn with no fill, erasing within it currently erases the shape itself. 
This can be pretty annoying, like when using a rectangle as a frame for hand-drawn artwork inside.
The expected behavior here would be for outer shapes to get erased only if they either have a fill or the eraser goes over the shape stroke.

**Comment by AnaghaS24** [comment]
Hi! I'm interested in working on this bug. If nobody else is working on it, can I be assigned to the issue @steveruizok?

**Comment by steveruizok** [comment]
> Hi! I'm interested in working on this bug. If nobody else is working on it, can I be assigned to the issue @steveruizok? 

Go for it!

**Comment by steveruizok** [comment]
This is maybe related: for geometric shapes, should we force users to click on / brush against the edges of the shape? In other words, should the `hitTestBounds`, `hitTestLineSegment`, and `hitTestPoint` for these shapes return different results if the shape is filled?
