### ISSUE TITLE
Create new .tldr file sometimes appends .json extension

### ISSUE THREAD

**Issue by Seanmclem** [tldraw/tldraw#417]
VS Code extension. Opening file doesn't open tldraw editor. just JSON. There is no way to open an existing drawing.  Only create-new.. I need to open them in the extension too..

Mac OS 11.5.2, M1
VS Code 1.62.3
Extension 1.2.2

**Comment by steveruizok** [comment]
Is the file a valid .tldr file? Would you be able to post the contents or send them to me (on Discord maybe?). Can you open the file in the webapp?

**Comment by Seanmclem** [comment]
> Is the file a valid .tldr file? Would you be able to post the contents or send them to me (on Discord maybe?). Can you open the file in the webapp?

For some reason, the file was created with a .json extension. So it was `name.tldr.json`. Once I removed the .json, it worked fine. Might be a but that the extension added the extra extension>

**Comment by zachy-ho** [comment]
Haven't been able to reproduce. Tried with an empty (no elements created) .tldr file, tried with just a bunch of random elements on. Tried opening via the command line (i.e. `code test.tldr`), tried opening via `Open file` on vscode.
Not sure if this bug is still present 🤔
