### ISSUE TITLE
Arrows lose bindings after page refresh

### ISSUE THREAD

**Issue by mmonzonqa** [tldraw/tldraw#4177]
### What happened?

After drawing several shapes, I used arrows to interconnect the shapes and binded to the center of each.  After refreshing the page, the arrow bindings were gone, and the arrows were no longer aligned / out of place.

### How can we reproduce the bug?

Repro Steps
1. Draw several shapes (such as squares). 
2. Draw a one-sided arrow. 
3. Drag the tail end of the arrow to the center of a shape (so it binds).
4. Drag the head of the same arrow to the center of another shape (so it binds). 
5. Drag one of the shapes to confirm arrow binding.
6. Refresh the page.
7. Drag one of the shapes to verify arrow bindings and observe.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

michael@framevr.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! Is this using tldraw.com or the the package? Just tried it on tldraw.com and could not reproduce, but might be missing something?

https://github.com/user-attachments/assets/14a7b027-da9b-4508-aae9-f51d5a4f3721

**Comment by mmonzonqa** [comment]
@MitjaBezensek - Looks like this was an issue introduced by our changes and has been fixed. Thank you for the investigation!

**Comment by MitjaBezensek** [comment]
Great, thanks for getting back to me.
