### ISSUE TITLE
[Example Request]: Custom Arrow

### ISSUE THREAD

**Issue by mdroidian** [tldraw/tldraw#4178]
### What's the example?

With the new Bindings API, it would be awesome to see an example of a custom arrow.

An idea for the example could be an arrow that only can bind to specific shapes.
Another idea could be custom arrow heads.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey, thanks for the suggestion 🙌 

Not sure if you are aware, but we did port our existing arrows to the bindings api. So as a start you might look into that to get some ideas?
https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
