### ISSUE TITLE
[Improvement] tldr file size can be reduced upto 4x times.

### ISSUE THREAD

**Issue by ammarahm-ed** [tldraw/tldraw#418]
A simple but great improvement would be to minify the JSON data before storing as file in `.tldr` format. If you ask me how much difference would make. I tired to minify a 230 KB document and it's size reduced to only 40KB. I used this [website](https://codebeautify.org/jsonminifier) to test the difference in file size.

**Comment by steveruizok** [comment]
Want to give it a shot? Looks like there are several npm packages that could help with this without effecting the bundle size too much. My recommendation would be to minify only in production, as we're still doing some work with the VS Code extension that involves reviewing/editing the JSON by hand.

**Comment by BRO3886** [comment]
Can I try this?

**Comment by steveruizok** [comment]
Go for it!

**Comment by BRO3886** [comment]
Hi! I was caught up with university exams and interviews, did not get time to do so, I'll pick it up next week if someone is not working on this

**Comment by alex-kim-dev** [comment]
> Looks like there are several npm packages that could help with this

Why use a package at all? Shouldn't `JSON.stringify(file)` be enough for prod?
