### ISSUE TITLE
Add customizable laser tool delay

### ISSUE THREAD

**Issue by raviteja83** [tldraw/tldraw#4211]
### What's the feature?

I would like the possibility of customising the delay after which the laser tool drawings disappear.

### Contact Details

rt12148@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
If you'd like to create a pull request for this, we'd probably accept it! You could
1. Add a `laserDelayMs` property to [`TldrawOptions`](https://github.com/tldraw/tldraw/blob/main/packages/editor/src/lib/options.ts) (and maybe options for the other laser things)
2. Update the laser tool to use those options. Get at them in the tool via `this.editor.options`

**Comment by raviteja83** [comment]
@SomeHats raise a PR take a look.
