### ISSUE TITLE
[bug] Conflicting shortcut for Ungrouping

### ISSUE THREAD

**Issue by BRO3886** [tldraw/tldraw#422]
Grouping is done by `ctrl + G` and ungrouping (as per context menu) is `ctrl + shift + G`

Both features work fine. But the problem with having `ctrl + shift + G` for ungroup is that it has a side effectt of enabling grid. Grid enabling and disabling should not work when some component is selected.

If it's okay can I take it up?

Also, focus mode on linux is being enabled by `ctrl + .` instead of `shift + .`. I don't know if that's the intended behaviour or not...

**Comment by steveruizok** [comment]
Good catch. We could get rid of the shortcut for grid, or make it more obscure; or we could drop the ungroup shortcut. Grouping grouped shapes will ungroup them, so perhaps as that's already "in the app" we can drop the shortcut for ungroup?

**Comment by BRO3886** [comment]
Instead of changing shortcuts we can disable functionality which enables and disables grid when a component is selected?

**Comment by BRO3886** [comment]
I tried doing this, doesn't work properly because it's ungrouped as soon as it tries to enable grid, so the hook which tells whether a group is selected returns `false`

I guess I'll just drop the ungroup shortcut for now...

> Instead of changing shortcuts can we disable functionality which enables and disables grid when a component is selected?
