### ISSUE TITLE
[bug] Multiplayer does not support simultaneous actions.

### ISSUE THREAD

**Issue by AdventureBeard** [tldraw/tldraw#425]
Was playing around on Tldraw.com with a friend when I noticed these issues:

When another user makes a simultaneous change:

1. If you are in a draw session, the editor crashes.
2. If you are in a shape creation session (just added a rectangle and resizing it, etc), the shape is immediately deleted.
3. If you are typing, the typing is interrupted and the text field is blurred.

Unfortunately, this means users must take turns for the multiplayer to work. I'll be snooping around the codebase in the meantime looking for root cause.

**Comment by steveruizok** [comment]
Woah, that's a pretty bad regression. I'll look into it too.

**Comment by steveruizok** [comment]
Soft closed, let's keep an eye on this.

**Comment by AdventureBeard** [comment]
(duplicating message here) I can confirm #426 fixes drawing sessions and text editing sessions. I'm still seeing the vanishing behavior for shape creation sessions.

**Comment by steveruizok** [comment]
Closed by #427 ! Thanks again @AdventureBeard
