### ISSUE TITLE
Add native mobile support for iOS and Android

### ISSUE THREAD

**Issue by username14415** [tldraw/tldraw#4251]
### What's the feature?

Are there any plans for native mobile support (ios - swift, android - kotlin)?

### Where would you like this feature?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! At least for now we don't have any plans for that. We are focusing on making the best React / browser based library. So at least for now the only way is to use React native / webview route.
