### ISSUE TITLE
Cloud outlines tear

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#4291]
### What happened?

Found an issue with cloud outlines while investigating: https://github.com/tldraw/tldraw/issues/3945

![2024-07-25 at 16 52 35 - Olive Bat](https://github.com/user-attachments/assets/ad86e37d-48eb-4820-8635-53ed890fac6d)

### Where did this happen?

The tldraw.com website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Saw this a while ago as well, but think we closed that issue #2084

**Comment by mimecuvalo** [comment]
ah, my bad! I couldn't repro at the time.

**Comment by ds300** [comment]
this happens quite reliably in dynamic sizing mode when you're zoomed in

**Comment by ds300** [comment]
partially fixed by #4380
