### ISSUE TITLE
Export bookmarks (URLs) as SVG/PNG correctly.

### ISSUE THREAD

**Issue by kobe651jp** [tldraw/tldraw#4298]
### What's the feature?

As far as I know, currently when I export bookmarks to svg/png it comes out blank.

Has anyone tried to implement this method?

I am trying to achieve this functionality on my own.

I would be grateful if someone could share their ideas on how to achieve this.

Btw, I have already created the backend logic to get the URL meta information.

![image](https://github.com/user-attachments/assets/ba59c2d2-e5f5-4b5a-b187-3ce7b6355aeb)

### Where would you like this feature?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
When exporting we call the `toSvg` function the shape util. So to make this work you would need to write the `toSvg` method for the `BookmarkShapeUtil`.

We have an example for how to add support for exporting [here](https://tldraw.dev/examples/shapes/tools/toSvg-method-example).

**Comment by kobe651jp** [comment]
Is there a way to override the original shape behavior without creating a my-custom-shape?

`extends BookmarkShapeUtil?`

I just want to add `toSvg` to `BookmarkShapeUtil`

**Comment by SomeHats** [comment]
`BookmarkShapeUtil.prototype.toSvg = yourImplementation`
