### ISSUE TITLE
Are discussions disabled for the repo?

### ISSUE THREAD

**Issue by raviteja83** [tldraw/tldraw#4299]
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/bfeb1941-5b66-481f-a061-9c035d1373b1">

**Comment by Taha-Hassan-Git** [comment]
Yeah, we decided there was too much surface area for helping people with developer problems. If you have any questions feel free to [join the discord](https://discord.com/invite/SBBEVCA4PG) and ask!
