### ISSUE TITLE
[bug] Saving Pages in VSCode

### ISSUE THREAD

**Issue by dennemark** [tldraw/tldraw#431]
Hi,

I have tested tldraw recently in vscode and it´s been great so far.

I am not sure, if it is correct to open issues in this repository if it is concerning the vscode extension. Please let me know, if it should be opened somewhere else.

I realised I cannot  save or rename pages properly within vscode. If I press save and reopen the document old pages are not visible, except for the first one.

Kind regards!

**Comment by dennemark** [comment]
Might be a different issue... I just tried to create another .tldr document, but cannot save that one, too.
Will try to figure out the reason.

**Comment by dennemark** [comment]
This is what happens now even after restarting computer and reinstalling tldraw and opening a new project. It´s pretty confusing. Issues you don´t want to deal with, sorry 😅

![tldraw](https://user-images.githubusercontent.com/29654902/144597862-875ffce6-5905-4ca4-aa04-59a74a507a7f.gif)

**Comment by steveruizok** [comment]
uh oh

**Comment by steveruizok** [comment]
Looking into this. I don't think anything on our side changed recently, so it may be an API change?

**Comment by steveruizok** [comment]
Thanks for raising this @dennemark. There's an error thrown when saving, shown below. @seflless any insight?

```
  ERR Unknown webview handle:b2640434-23e3-4091-afe4-9e3f5a9d896f: Error: Unknown webview handle:b2640434-23e3-4091-afe4-9e3f5a9d896f
```

**Comment by seflless** [comment]
I won’t recognize the issues from reading this. Will look at it tonight when I’m back at my desk. Thanks for reporting it!

**Comment by steveruizok** [comment]
It's also happening in dev, so at worst we could manually roll back changes until it works again to see what broke it. 

I'm not seeing anything on the Discord channels, so either we're using an obscure part of the web view API has changed, or else it was something on our side. But AFAIK none of the changes for the last few weeks were substantial, just keyboard shortcuts?

**Comment by seflless** [comment]
Definitely just try rolling back and see if it’s fixed locally as a quick sanity check. I’m taking that approach if you don’t beat me to it

**Comment by steveruizok** [comment]
Got it, looks like it was introduced last week with 1.2.3. Thanks again for raising this @dennemark.

**Comment by dennemark** [comment]
Thanks a lot! @seflless and @steveruizok 
Works properly again :)
