### ISSUE TITLE
Customize background grid with measurement scale

### ISSUE THREAD

**Issue by nrsmarterlaunch** [tldraw/tldraw#4313]
### What's the feature?

**Provide more grid configuration options:**

- Level of opacity (lines / dots)
- Scale of grid boxes (ability to set a certain measurement amount/type (foot, inch, centimeter, etc). For example, 1 grid box equals X [inches, feet, mm, cm, m, yard, etc.]
- Ability to modify snap-to grid (Snap at [.25, .5, 1] per grid box)
- Add option to 'Include measurements' as a shape option. When enabled, any shape tool would include measurements as a label on each side. For example, if I were to draw a square and measurements were enabled when I was creating the element, it would show the size of each side of the box as the label for that shape. If I drew a line, the label would display my measurement in the middle of that line, circle perhaps has the total circumference, etc.

### Where would you like this feature?

The developer package

### Contact Details

nick@smarterlaunch.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Thanks for the recommendations!
I'll refer you to some existing issues on this though, to split up these ideas:
- opacity on grid: https://github.com/tldraw/tldraw/issues/4065 and https://github.com/tldraw/tldraw/issues/3620
- scale of grid boxes (measurement): https://github.com/tldraw/tldraw/issues/2577 and https://github.com/tldraw/tldraw/issues/1243
- snap-to grid: https://github.com/tldraw/tldraw/issues/3265
- measurements: same as the 2nd

I'll close this issues as I think they're fairly captured in these other issues. Thanks though!
