### ISSUE TITLE
[Example Request]: How to change background and text Color with "DefaultColorThemePalette"?

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4343]
### What's the example?

[Related docs link](https://tldraw.dev/examples/ui/changing-default-colors)
[Repo for this](https://github.com/tldraw/tldraw/blob/main/packages/tlschema/src/styles/TLColorStyle.ts)
In this example, I can change lightMode.black.solid to "aqua".
But, I can't change color with DefaultColorThemePalette.[Mode in ["lightMode","darkMode"]].text and .background.
How to change it?
I tried these codes.
```
DefaultColorThemePalette.lightMode.text = "aqua";
DefaultColorThemePalette.lightMode.text = "#000";
DefaultColorThemePalette.lightMode.text = "rgba(255, 255, 255, 0.5)";
// same code except .text->.background ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
We're defining colors using both CSS and that color theme palette. This is confusing, sorry.

The colors for text are being inherited from CSS variables, like these: https://github.com/tldraw/tldraw/blob/9d20b43a2ba4762754cc7176cd7ee87fd3402233/packages/editor/editor.css#L128-L129

We _should_ unify the theme and colors in the app. But for now you may need to use CSS to change the colors. The theme object will be used for image exports.

**Comment by nayounsang** [comment]
> We're defining colors using both CSS and that color theme palette. This is confusing, sorry.
> 
> The colors for text are being inherited from CSS variables, like these:
> 
> https://github.com/tldraw/tldraw/blob/9d20b43a2ba4762754cc7176cd7ee87fd3402233/packages/editor/editor.css#L128-L129
> 
> We _should_ unify the theme and colors in the app. But for now you may need to use CSS to change the colors. The theme object will be used for image exports.

Thank you for showing me a good method!
I use like this to make bg color transparent.
```
.tl-theme__light {
	--color-background: rgba(0, 0, 0, 0); /* Light Theme Background */
}

.tl-theme__dark {
	--color-background: rgba(255, 255, 255, 0); /* Dark Theme Background */
}
```
