### ISSUE TITLE
[Bug]: There is a link in Docs whose meaning is difficult to understand.

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4346]
### What happened?

In this [link](https://tldraw.dev/examples/basic/basic) about Tldraw component, It looks like the link to [**persistenceKey**](https://tldraw.dev/peristence-key) hasn't been created yet, or it takes you to an unintended link.
In more detail, this part.
- By default, the component does not persist between refreshes or sync locally between tabs. To keep your work after a refresh, check the [persistenceKey](https://tldraw.dev/peristence-key) example.

### How can we reproduce the bug?

I think [this example](https://tldraw.dev/examples/basic/peristence-key) is valid link.
If it is not indented link, I can make PR to fix docs.

### What browsers are you seeing the problem on?

Chrome

### Where did this happen?

The tldraw.com website

### Contact Details

nayounsang722@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey!  I took a look and it seems we already fixed this in #4340, we just need to redeploy the new version. Let us know if you spot any other issues 🙌
