### ISSUE TITLE
[Example Request]: Setting flexible zoom from base width and height

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4355]
### What's the example?

1. The size ratio is fixed. (such as 16:9)
2. <Tldraw/> in parent div size with the appropriate ratio specified by me, base size is 1600:900
```js
const [size, setSize] = useState({width:1600,height:900})
const handleSize = (width) => {
  setSize({width:width,height:width*9/16})
}
// ...
<div style={{width:size.width, height:size.height}}>
  <TlDraw/>
</div>
```
3. If the size state changes, I want tldraw to set the appropriate zoom.
4. I think I can use setCameraOptions, but I'm confused because I don't know how to use it in detail.
5. I want a flexible zoom like this [example](https://tldraw.dev/examples/use-cases/pdf-editor)
6. However, even if you refer to the example, the zoom is not adjusted as expected.

If you need more information, please leave a comment 
At the time of writing this issue, I have urgent work to do and I feel like there is not enough content, so I will add more content later.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayounsang** [comment]
I solve this!
1. Don't lock camera to change zoom
```
		editor.setCameraOptions({
			//isLocked: true,
			wheelBehavior: 'none',
		})
```
2.  setCamera with vector when you want to change zoom
```
const zoom = calculateZoom(size);
editor.setCamera({...editor.getCamera(),z:zoom}, { immediate: true });
```

**Comment by ds300** [comment]
Hi, sorry the docs for that type are lacking info. I'll fix that but for now here's a version with comments: https://github.com/tldraw/tldraw/blob/b58b024b777a37c5719467324dd3f0a55f0a23ff/packages/editor/src/lib/editor/types/misc-types.ts#L21

Thanks for updating this issue with your solution! I'll close this issue now. Let us know if there are any outstanding questions 🙏🏼
