### ISSUE TITLE
Export more tldraw UI components

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4367]
### What's the feature?

Hello, I am using tldraw well in my project.
I like the existing UI and want to customize it using the most of it.
However, some UI components are not exported, so I want to improve.
For example, I want to custom defaultToolbar.
```
export const CustomToolbar = memo(function DefaultToolbar() {
	const editor = useEditor()
	const breakpoint = useBreakpoint()
	const isReadonlyMode = useReadonly()
	const activeToolId = useValue(
		'current tool id',
		() => editor.getCurrentToolId(),
		[editor],
	)

	const { ActionsMenu, QuickActions } = useTldrawUiComponents()

	return (
		<div className="tlui-toolbar">
			<div className="tlui-toolbar__inner">
				<div className="tlui-toolbar__left">
					<div className="tlui-toolbar__extras">
						<div className="tlui-toolbar__extras__controls tlui-buttons__horizontal">
							{QuickActions && ActionsMenu && <CustomActionsMenu />}
						</div>

						<ToggleToolLockedButton activeToolId={activeToolId} /> // not export
					</div>

					<OverflowingToolbar> // not export
						<CustomToolbarContent />
					</OverflowingToolbar>
				</div>
				{breakpoint < PORTRAIT_BREAKPOINT.TABLET_SM && !isReadonlyMode && (
					<div className="tlui-toolbar__tools">
						<MobileStylePanel /> // not export
					</div>
				)}
			</div>
		</div>
	)
})
```
But, ToggleToolLockedButton, OverflowingToolbar and MobileStylePanel are not exported.
I suggest that some UIs that are not exported be exported!

### Where would you like this feature?

The developer package

### Contact Details

nayounsang722@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
We already [exported those](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/index.ts) and are available in Canary. Will also come out with the next version of the package.
