### ISSUE TITLE
[improvement] Global space and middle mouse button panning state.

### ISSUE THREAD

**Issue by AdventureBeard** [tldraw/tldraw#439]
Many whiteboard applications, such as Excalidraw and Figjam, use a global panning state when the spacebar or the middle mouse button is pressed. This allows you to make canvas adjustments regardless of what tool you're currently using. I think it would be quite handy in Tldraw!

**Comment by jescowuester** [comment]
@steveruizok would love to take this. In the select tool we handle it like this:
```
if (
      (this.status === Status.SpacePanning && e.buttons === 1) ||
      this.status === Status.MiddleWheelPanning &&
      e.buttons === 4
    ) {
      this.app.onPan?.({ ...info, delta: Vec.neg(info.delta) }, e as unknown as WheelEvent)
      return
    }
```
Should I copy that (or a helper containing that code) for every single tool, or do we have a dedicated way to create global actions?

**Comment by steveruizok** [comment]
Awesome, I'll check the PR!

**Comment by steveruizok** [comment]
You might be able to handle this on the TLApp (it handles each events before forwarding it to the active tool), but otherwise yeah we'd need to repeat some code for each tool.
