### ISSUE TITLE
[Example Request]: How the tldraw data store? so that we can open it for editing next time.

### ISSUE THREAD

**Issue by liaodalin19903** [tldraw/tldraw#4394]
### What's the example?

We can run tldraw easily in React:
```
import './App.css';

import { Tldraw } from 'tldraw'
import 'tldraw/tldraw.css'

function App() {
  return (
    <div className="App" >
      <Tldraw />
    </div>
  );
}

export default App;
```

![QQ_1723951824743](https://github.com/user-attachments/assets/69ec5414-a175-47c1-b112-1f07f5b38d2a)

but how the tldraw data store? so that we can open it for editing next time.

<img src="https://github.com/user-attachments/assets/c57aed78-3618-4e5d-8f93-1fc1e44a206a" width="200px">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! We have a guide on how to persist the data:
https://tldraw.dev/docs/persistence
