### ISSUE TITLE
[Example Request]: When i click in tldraw asset shape, how can i access the onselect function to perform my specific task

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4395]
### What's the example?

When i click in tldraw asset shape, how can i access the onselect function to perform my specific task? Please if anyone can help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtalhastar** [comment]
@ds300 If you can helpout. Thanks

**Comment by ds300** [comment]
If you're working with a custom shape type, you can add an `onClick` or `onDoubleClick` handler to the shape util class.

If you're working with a built-in shape type, I don't know if we support adding click handlers for those. Can you share more information about your use-case?

**Comment by mtalhastar** [comment]
const handleMount = useCallback((editorInstance: Editor) => {
 
    setEditor(editorInstance);
   
    console.log('Tldraw mounted');
   
    if (!base64Image || imageAdded) {
      console.log('No image to add or image already added');
      return;
    }
 
    const assetId = AssetRecordType.createId();
    const imageWidth = 600; // Adjust width to fit your needs
    const imageHeight = 600; 

    editorInstance.createAssets([
      {
        id: assetId,
        type: 'image',
        typeName: 'asset',
        props: {
          name: 'generated-image.png',
          src: base64Image,
          w: imageWidth,
          h: imageHeight,
          mimeType: 'image/png',
          isAnimated: false,
        },
        meta: {},
      },
    ]);

    editorInstance.createShape({
      type: 'image',
      x: (window.innerWidth - imageWidth) / 2,
      y: (window.innerHeight - imageHeight) / 2,
      props: {
        assetId,
        w: imageWidth,
        h: imageHeight,
      },
    });

    setImageAdded(true);
  }, [base64Image, imageAdded]);
  
  Yes for example i add an image shape dynamically through code here, when i click on certain selected image on canvas, i want to display a my custom modal on top of that image when image is selected. I am not having any onselect method available on this. I just need on select method and x and y coordinates of that image so i can display my custom modal on top of it
  
![image](https://github.com/user-attachments/assets/a1b94d42-6d31-41f8-a673-b6140c83b969)

**Comment by ds300** [comment]
ah yes, we call this kind of toolbar a 'context toolbar'. We have an example of how to do it here: https://tldraw.dev/examples/ui/context-toolbar

There is no 'onselect' event but you can check what is currently selected in your react component. Something like this:

```ts
const editor = useEditor()
const onlySelectedShape = useValue('onlySelectedShape', () => editor.getOnlySelectedShape(), [editor])
if (onlySelectedShape?.type !== 'image') return null

return <div>{...toolbar stuff}</div>
```

And then it will show/hide the toolbar based on the current selection state.

**Comment by mtalhastar** [comment]
Thanks @ds300 , I have one more question currently i have static background for canvas changing the tldraw.css but when i zoom in the image is static, the dots never get zoomed in as image gets zoomed in. The background canva image remain of static size.Is there a way to add background with dynamic zoom in tldraw?

![image](https://github.com/user-attachments/assets/2696bd8e-e1ec-4d5d-931a-d5a38a1bcf8c)

**Comment by ds300** [comment]
you can use the `editor.getZoomLevel()` option to update your background texture as the user zooms in and out. 

maybe something like
```tsx
const editor = useEditor()
const backgroundRef = useRef()
useQuickReactor('update background zoom', () => {
  if (!backgroundRef.current) return
  backgroundRef.current.style.transform = `scale(${editor.getZoomLevel() * 100}%)`
})

return <div ref={backgroundRef} className="my-background" />
```

but also note that tldraw ships with a smart adaptive grid mode that you can enable by setting `editor.updateInstanceState({isGridMode: true})` on mount.

**Comment by mtalhastar** [comment]
hi @ds300 , this is my current logic it is displaying the toolbar on shapes but not images, how can i do it for images too? I mean image shapes

  const ContextToolbarComponent = track(() => {
    const editor = useEditor()
    const showToolbar = editor.isIn('select.idle')
    if (!showToolbar) return null
    const selectionRotatedPageBounds = editor.getSelectionRotatedPageBounds()
    if (!selectionRotatedPageBounds) return null
  
    // [2]
    const size = editor.getSharedStyles().get(DefaultSizeStyle)
    if (!size) return null
    const currentSize = size.type === 'shared' ? size.value : undefined
  
    const pageCoordinates = editor.pageToViewport(selectionRotatedPageBounds.point)
  
    return (
      <div
        style={{
          position: 'absolute',
          top: Math.max(16, pageCoordinates.y - 48),
          left: Math.max(16, pageCoordinates.x),
          pointerEvents: 'all',
          // [3]
          width: selectionRotatedPageBounds.width,
        }}
        // [4]
        onPointerDown={(e) => e.stopPropagation()}
      >
         <div className='flex text-white bg-[#9a9a9a] p-1 space-x-1 w-40 h-20 text-sm rounded-lg'>
             <img src='/xfigura.png' alt='Image 1' width={40} height={40} className='rounded-lg' />
             <img src='/galleryicon.png' alt='Image 2' width={40} height={40} className='rounded-lg' />
             <button className='rounded-lg bg-[#6f6f6f] h-[40px] text-center p-2'  >Edit Image</button>
             <img src='/expandable.png' alt='Image 4' width={40} height={40} className='rounded-lg'/>
             <img src='/download.png' alt='Image 5' width={40} height={40} className='rounded-lg'/>
          </div>
           
         
        </div>
      
    )
  })
  
  Thankyou

**Comment by mtalhastar** [comment]
![image](https://github.com/user-attachments/assets/fb097c29-c1be-41c4-9b00-0551c3f25b62)
![image](https://github.com/user-attachments/assets/59c46840-f873-4c13-910c-49517a01d67c)
it never shows up on image shapes

**Comment by ds300** [comment]
> exporting it

```ts
import { exportAs } from 'tldraw'
exportAs(editor, editor.getSelectedShapeIds(), 'png', 'myfile.png', { padding: 0 })
```

> get it in the code for use furthur as a file

```ts
import { exportToBlob } from 'tldraw'


const blob = await exportToBlob({
  editor,
  ids: editor.getSelectedShapeIds(),
  format: 'png',
  opts: { padding: 0 },
})
const file = new File([blob], 'myfile.png', { type: blob.type })

```

**Comment by ds300** [comment]
I think this issue is resolved now so I'll close this. Feel free to open more issues or ask questions in the developer forum on discord 🙏🏼
