### ISSUE TITLE
Add multicolor text support

### ISSUE THREAD

**Issue by 0PandaDEV** [tldraw/tldraw#4399]
### What's the feature?

When you select a piece of text it would be useful to be able to change only the color of that piece instead of the entire text field.

### Where would you like this feature?

The developer package

### Contact Details

contact@pandadev.net

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hello! Thanks for the suggestion. This is indeed something we intend to support one day, under the broader feature of 'rich' text support.

I'm gonna close this because it's implied by #1879, but thanks again for sharing this idea!
