### ISSUE TITLE
[Bug]: Unable to use both onMount and options props

### ISSUE THREAD

**Issue by AntonelloDN** [tldraw/tldraw#4400]
### What happened?

If you use both props **onMount** and **options** Editor becomes unusable. Select tool is set continuously.

### How can we reproduce the bug?

Starting from [Canvas events](https://tldraw.dev/examples/editor-api/canvas-events) example. Add **options** - for example to set up max shapes per page.

You get something like this:
```typescript
import { useCallback, useState } from 'react'
import { Tldraw, TLEventInfo } from 'tldraw'
import 'tldraw/tldraw.css'
import './custom-ui.css'

export default function CanvasEventsExample() {
  const [events, setEvents] = useState<any[]>([])

  const handleEvent = useCallback((data: TLEventInfo) => {
    setEvents((events) => {
      const newEvents = events.slice(0, 100)
      if (
        newEvents[newEvents.length - 1] &&
        newEvents[newEvents.length - 1].type === 'pointer' &&
        data.type === 'pointer' &&
        data.target === 'canvas'
      ) {
        newEvents[newEvents.length - 1] = data
      } else {
        newEvents.unshift(data)
      }
      return newEvents
    })
  }, [])

  return (
    <div style={{ display: 'flex' }}>
      <div style={{ width: '50%', height: '100vh' }}>
        <Tldraw
          options={{
            maxShapesPerPage: 10000
          }}
          onMount={(editor) => {
            editor.on('event', (event) => handleEvent(event))
          }}
        />
      </div>
      <div
        style={{
          width: '50%',
          height: '100vh',
          padding: 8,
          background: '#eee',
          border: 'none',
          fontFamily: 'monospace',
          fontSize: 12,
          borderLeft: 'solid 2px #333',
          display: 'flex',
          flexDirection: 'column-reverse',
          overflow: 'auto',
          whiteSpace: 'pre-wrap',
        }}
        onCopy={(event) => event.stopPropagation()}
      >
        <div>{JSON.stringify(events, undefined, 2)}</div>
      </div>
    </div>
  )
}

```

Select tool is called continuously:

https://github.com/user-attachments/assets/b31ac244-b056-4c80-a392-6c0062ef4150

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Try defining the options outside of the component, see our [custom options example](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/custom-options/CustomOptionsExample.tsx#L4-L7).
The way you have it set right now means that the options prop object get recreated on each rerender.

**Comment by AntonelloDN** [comment]
Hi @MitjaBezensek, Thanks for the clarification! Feel free to close the issue, it is already documented in the [example](https://github.com/tldraw/tldraw/blob/main/apps/examples/src/examples/custom-options/CustomOptionsExample.tsx#L4-L7).

**Comment by MitjaBezensek** [comment]
👍
