### ISSUE TITLE
Add API for record difference detection

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4422]
### What's the feature?

Excuse me, but maybe I can't find the API.
I talk about [store.listen](https://tldraw.dev/reference/store/Store#listen).
**onHistory func**, I can get added or removed or UPDATED event.
In updated event, I can get prev & current record.
In more detail, updated object's key is RecordID<any>, value is array of length 2. (Idx 0 is prev, Idx 1 is current.)
Is there an API to get difference between prev & current Record?
This is because the amount of messages during socket communication is too large(**tens of thousands of bytes
  In certain situations**) to send index 1(current Record).
My team use self-implemented deep-compare function to get difference.
If use this, I can send & get web-socket messages of **hundreds of bytes in size**(almost < 200).
However, it would be more stable if this was provided by a library.

### Where would you like this feature?

The developer package

### Contact Details

nayounsang722@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hello! This has been requested a couple of times but we haven't added it yet for a number of reasons:

- we only use fine-grained (deep) diffs in our sync engine, which was only recently made public
- although our deep diff code has been quite stable so far, it has some peculiarities that I don't want to impose on other people, especially in how it handles arrays and the fact that it doesn't produce reversible diffs.
- there are good small and fast tools for diffing json payloads on npm already.

As far as stability goes, I can guarantee that we'll only put json-compatible data in our store records so any old json differ should work for you going forward.

**Comment by ds300** [comment]
> Can you explain some peculiarities especially in how it handles arrays and the fact that it doesn't produce reversible diffs?
it only supports 'append' and 'update' operations on arrays, it doesn't support deletions or insertions in the middle. and yeah I think most people expect diff formats to be reversible but we didn't need that so I was able cut some corners for perf. If you want to use our code you can copy+paste from here https://github.com/tldraw/tldraw/blob/main/packages/sync-core/src/lib/diff.ts but yeah I don't think we are gonna make those part of the public api.

as for npm libraries, the two classics are probably https://www.npmjs.com/package/deep-diff and https://www.npmjs.com/package/jsondiffpatch but I'm sure there'll be others.

**Comment by nayounsang** [comment]
Thanks, I'll check out the code and library.
This issue appears to have been resolved. But I don't know if I can close it arbitrarily.
If it doesn't need to be open, @ds300  can close it.
