### ISSUE TITLE
Toolbar with only pen, undo and colors

### ISSUE THREAD

**Issue by MattyDfromSanDiego** [tldraw/tldraw#4430]
Is it possible to remove all of the tools and just leave the pen & undo buttons with color palette? Thank you for the help. Love TLDraw. @MattyDfromSanDieogo

**Comment by mimecuvalo** [comment]
Heya @MattyDfromSanDiego, take a look at https://examples.tldraw.com/custom-menus and the corresponding code: https://github.com/tldraw/tldraw/tree/main/apps/examples/src/examples/custom-menus

You can definitely make your own toolbar!

**Comment by ds300** [comment]
Here's also an example that probably gets towards what you want by just customizing and disabling our existing menus [on codesandbox](https://codesandbox.io/p/sandbox/tldraw-sync-demo-forked-2p3sjt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz0yklxy00073b6j7v2mwo8z%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz0yklxy00033b6j0cndo66q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz0yklxy00043b6j0fbvctvf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz0yklxy00063b6jvkxyjse5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz0yklxy00033b6j0cndo66q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz0yklxy00023b6j87launyj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A44%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A44%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz0yklxy00033b6j0cndo66q%2522%252C%2522activeTabId%2522%253A%2522clz0yklxy00023b6j87launyj%2522%257D%252C%2522clz0yklxy00063b6jvkxyjse5%2522%253A%257B%2522id%2522%253A%2522clz0yklxy00063b6jvkxyjse5%2522%252C%2522activeTabId%2522%253A%2522cm0f1sf5e003b3b6is3rrf7nh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz0yklxy00053b6jy7eu1yor%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0f1sf5e003b3b6is3rrf7nh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clz0yklxy00043b6j0fbvctvf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz0yklxy00043b6j0fbvctvf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
