### ISSUE TITLE
Custom context toolbar to be on Top Center of the shape or image

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4431]
### What's the example?

I want context toolbar to be on top center instead of top left of the image exactly , @ds300 please can you help me what should be options to do that. Thanks 
 
 
 `   return (
      <div
        style={{
          position: 'absolute',
          top: Math.max(16, pageCoordinates.y - 40),
          left: Math.max(16, pageCoordinates.x+50),
          pointerEvents: 'all',
          // [3]
          width: selectionRotatedPageBounds.width,
        }}
        // [4]
        onPointerDown={(e) => e.stopPropagation()}
      >
 
    <div className='flex text-white bg-[#000000] p-2 space-x-1 text-sm rounded-lg items-center w-[280px] justify-center'>
    <button className='rounded-lg bg-[#113b68] h-[40px] w-[40px] flex items-center justify-center' onClick={handleToggleModelSettings}>
        <img src='/xfigura-icons.svg' alt='Image 1' width={40} height={40} className='rounded-lg' />
        </button>
      <button className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center' onClick={handlesetShowGallery}>
        <img src='/menu_white.svg' alt='Image 2' width={30} height={30} className='rounded-lg' />
      </button>
      <button className='rounded-lg bg-[#6f6f6f] h-[40px] text-center p-2' onClick={()=>handleEditImage(editor)}>
        Edit Image
      </button>
      <button className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center' onClick={()=>handleFullScreen(editor)}>
        <img src='/fullscreen.png' alt='Image 4' width={40} height={40} className='rounded-lg'/>
      </button>
      <button className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center' onClick={()=>handleDownload(editor)}>
        <img src='/download.svg' alt='Image 5' width={20} height={20} className='rounded-lg'/>
      </button>
    </div>
    </div>
)
})`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
The outer div there is supposed to span the width of the image and be positioned directly above it, then you can position stuff within it however you like.

The one error i see is that you added 50 px to the x position of the div, so first i'd remove that. Then you are constraining the width of the flex container, so you probably need to just add another flex container around that to do the positioning, or add `flex justify-center` to the outer div. Something along those lines.

**Comment by mtalhastar** [comment]
@ds300  is there a way to find out selected image width so i can add that  to outer div?

 const pageCoordinates = editor.pageToViewport(selectionRotatedPageBounds.point)
    
    return (
      <div
      style={{
        position: 'absolute',
        top: Math.max(16, pageCoordinates.y - 40),
        left: Math.max(16, pageCoordinates.x),
        pointerEvents: 'all',
        display: 'flex',    
        justifyContent: 'center',
      }}
      onPointerDown={(e) => e.stopPropagation()}
    >
      <div className='flex items-center justify-center w-full text-white bg-[#000000] p-2 space-x-1 text-sm rounded-lg'>
        <button
          className='rounded-lg bg-[#113b68] h-[40px] w-[40px] flex items-center justify-center'
          onClick={handleToggleModelSettings}
        >
          <img src='/xfigura-icons.svg' alt='Image 1' width={40} height={40} className='rounded-lg' />
        </button>
        <button
          className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center'
          onClick={handlesetShowGallery}
        >
          <img src='/menu_white.svg' alt='Image 2' width={30} height={30} className='rounded-lg' />
        </button>
        <button
          className='rounded-lg bg-[#6f6f6f] h-[40px] text-center p-2'
          onClick={() => handleEditImage(editor)}
        >
          Edit Image
        </button>
        <button
          className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center'
          onClick={() => handleFullScreen(editor)}
        >
          <img src='/fullscreen.png' alt='Image 4' width={40} height={40} className='rounded-lg' />
        </button>
        <button
          className='rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center'
          onClick={() => handleDownload(editor)}
        >
          <img src='/download.svg' alt='Image 5' width={20} height={20} className='rounded-lg' />
        </button>
      </div>
    </div>
)
})

**Comment by ds300** [comment]
you had it in the first post: `width: selectionRotatedPageBounds.width`

**Comment by mtalhastar** [comment]
![image](https://github.com/user-attachments/assets/cdc4443b-9cd1-4d2d-862b-5308ffea2c55)
I did this but it never moves it to center of the image
`return (
      <div
        style={{
          position: 'absolute',
          top: Math.max(16, pageCoordinates.y - 40),
          left: Math.max(16, pageCoordinates.x),
          width: selectionRotatedPageBounds.width,
          display: 'flex', // Use flexbox to center the inner div
          justifyContent: 'center', // Center the inner div horizontally
        }}
        onPointerDown={(e) => e.stopPropagation()}
      >
        <div className="w-full flex items-center justify-center">
          <div className="flex items-center justify-center text-white bg-[#000000] p-2 space-x-1 text-sm rounded-lg">
            <button
              className="rounded-lg bg-[#113b68] h-[40px] w-[40px] flex items-center justify-center"
              onClick={handleToggleModelSettings}
            >
              <img src="/xfigura-icons.svg" alt="Image 1" width={40} height={40} className="rounded-lg" />
            </button>
            <button
              className="rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center"
              onClick={handlesetShowGallery}
            >
              <img src="/menu_white.svg" alt="Image 2" width={30} height={30} className="rounded-lg" />
            </button>
            <button
              className="rounded-lg bg-[#6f6f6f] h-[40px] text-center p-2"
              onClick={() => handleEditImage(editor)}
            >
              Edit Image
            </button>
            <button
              className="rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center"
              onClick={() => handleFullScreen(editor)}
            >
              <img src="/fullscreen.png" alt="Image 4" width={40} height={40} className="rounded-lg" />
            </button>
            <button
              className="rounded-lg bg-[#6f6f6f] h-[40px] w-[40px] flex items-center justify-center"
              onClick={() => handleDownload(editor)}
            >
              <img src="/download.svg" alt="Image 5" width={20} height={20} className="rounded-lg" />
            </button>
          </div>
        </div>
      </div>
    );
})`

**Comment by mtalhastar** [comment]
![image](https://github.com/user-attachments/assets/c90e4727-72a1-4f57-be5e-e191afd67cd8)

selectedRotatedPageBounds is not returning me the current image width but this overall width

**Comment by ds300** [comment]
hm not sure what's going on there, if you can share a codesandbox or something I'm happy to take a look

**Comment by mtalhastar** [comment]
is it possible to come on google meet for 5mins or discord @ds300 to have a look?

**Comment by mtalhastar** [comment]
https://tldraw.dev/examples/ui/context-toolbar

okay @ds300 if you see example of even context toolbar, the toolbar here even never remains exactly on top center of the image but moves when you zoom in and zoom sometimes goes to left and sometime to right,can we make it static to top center of the image independent of zooming in and zooming out, if get this example correct my problem will be solved

**Comment by mtalhastar** [comment]
hi @ds300 , also one more question, is it possible that image don't overlap each other every time this function is called, each image is generated in position next to other?

  const handleMount = useCallback((editorInstance: Editor) => {
    editorInstance.updateInstanceState({isGridMode:true})
    setEditor(editorInstance);
    console.log('Tldraw mounted');
   
    if (!cloudinaryImageLink || imageAdded) {
      console.log('No image to add or image already added');
      return;
    }
    
    const assetId = AssetRecordType.createId();
    const imageWidth = 600; // Adjust width to fit your needs
    const imageHeight = 600; 

    editorInstance.createAssets([
      {
        id: assetId,
        type: 'image',
        typeName: 'asset',
        props: {
          name: 'generated-image.png',
          src: cloudinaryImageLink,
          w: imageWidth,
          h: imageHeight,
          mimeType: 'image/png',
          isAnimated: false,
        },
        meta: {},
      },
    ]);

    editorInstance.createShape({
      type: 'image',
      x: (window.innerWidth - imageWidth) / 2,
      y: (window.innerHeight - imageHeight) / 2,
      props: {
        assetId,
        w: imageWidth,
        h: imageHeight,
      },
    });

    setImageAdded(true);
  }, [cloudinaryImageLink, imageAdded]);

[example(1).webm](https://github.com/user-attachments/assets/1e1e923b-eb0d-4286-a406-be7e212aa558)

**Comment by ds300** [comment]
so the width should have been

`width: selectionRotatedPageBounds.width * editor.getZoomLevel()`

I added a fix to our example in #4440 

> is it possible that image don't overlap each other every time this function is called, each image is generated in position next to other

We don't have that behavior built-in. You need to get the bounds of the previous shape and use it to adjust the position of the next shape.

**Comment by ds300** [comment]
I think this has been addressed so will close this now, feel free to open more issues or ask questions on discord if you still need help!
