### ISSUE TITLE
[Feature]: opt arg in exportToBlob() may be ambiguous.

### ISSUE THREAD

**Issue by nayounsang** [tldraw/tldraw#4439]
### What's the feature?

I implemented a feature that allows users to export draws as blob & PNG format in absolute position & bound sizes.
Unfortunately ,I felt [opt in exportToBlob()](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/utils/export/export.ts#L140)'s type is ambiguous.
Because its type is  [TLSvgOptions](https://tldraw.dev/reference/editor/TLSvgOptions), I understood this to be simply about export as SVG format.
Fortunately, [exportAs()](https://tldraw.dev/reference/tldraw/exportAs) has description about opt.
However, I wish there was some mention that this isn't just about SVG.
Maybe it would be a good idea to change the type name. What do you think about this?
I think it would be good to add a related example.
``` typescript 
// ...
  const bounds = new Box(x, y, w, h); // Developers can set the values
  return await exportToBlob({
    editor,
    ids,
    format: "png",
    opts: {
      padding: 0,
      bounds: bounds,
    },
  });
};
```

### Where would you like this feature?

The developer package

### Contact Details

nayounsang722@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Cool call on the type name! I made a PR to change it #4442

**Comment by nayounsang** [comment]
> Cool call on the type name! I made a PR to change it #4442

Thx for PR!
