### ISSUE TITLE
[Bug]: Shapes generated with create shape appear weird for some unknown reason

### ISSUE THREAD

**Issue by KedarDevs** [tldraw/tldraw#4450]
### What happened?

![Screenshot from 2024-09-03 17-58-09](https://github.com/user-attachments/assets/9e7e37ed-5c11-433a-8cc2-63c9f9e0c394)
As you can see from the above screenshot tlraw shapes appear weird and out of place 
not sure why it is happening. I am creating this shapes using createShape functions.
the version im using is ^2.0.0-alpha.19

### How can we reproduce the bug?

Not sure

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where did this happen?

The developer package

### Contact Details

kedar@acciorobotics.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Hi 👋🏼  Sorry we don't support the alpha version. If you are able to upgrade and you still see the same issue, feel free to open another issue 🙏🏼
