### ISSUE TITLE
[Bug]: Shapes generated with create shape appear weird for some unknown reason

### ISSUE THREAD

**Issue by KedarDevs** [tldraw/tldraw#4452]
### What happened?

shapes are getting cut when they are created using createShape function, not sure why it is happening even in latest versions. 
please let me know if there is any possible solution
attaching screenshots for better understanding
 
![Screenshot from 2024-09-04 10-55-42](https://github.com/user-attachments/assets/0a03aac0-0e00-47db-9d0d-6799c52c3609)
![Screenshot from 2024-09-04 10-55-21](https://github.com/user-attachments/assets/a3fd7062-5e4f-4baa-ab72-15422a2dba37)

### Where did this happen?

The developer package

### Contact Details

kedar@acciorobotics.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
It's really hard to tell what's going on there just by looking. I've never seen arrow shapes get cut off like that, and I have no idea why it might happen.

Are you able to share a codesandbox link or something so I can help debug? If not it might be helpful if you could at least paste your code that is creating these shapes, along with noting any custom stuff you're adding to tldraw.

**Comment by KedarDevs** [comment]
Hi David
I figured what the issue is and it has nothing to do with tldraw so ill be closing this issue
the issue was wrt another library called as rsuite whose css was effecting the rendering of shapes in tldraw
i still dont know exactly which class it was but will mostly try to get a work around from their side
Thank you for your quick response and sorry for the inconvenience caused
