### ISSUE TITLE
[Bug]: Image stored in Base64 exceeds file limit

### ISSUE THREAD

**Issue by 0PandaDEV** [tldraw/tldraw#4456]
### What happened?

I was using the Obsidian plugin of tldraw. While trying to add a image the entire canvas crashed because the image was added in base64 it exceeded the character limit on Obsidian which meant i lost my entire progress.

### How can we reproduce the bug?

1. install obsidian with tldraw plugin
2. open a new canvas
3. insert a image or two of normal size (e.g. 2MB)
4. close the canvas and open it again

### Where did this happen?

The developer package

### Contact Details

contact@pandadev.net

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! tldraw supports images up to 10MB, so this limitation must be on the obsidian or the plugin side. I'd say it would probably be best to open an issue in the obsidian plugin repo - we are not the ones developing it. I guess the correct repo is [this one](https://github.com/holxsam/tldraw-in-obsidian)?

**Comment by mimecuvalo** [comment]
Btw, in newer versions of tldraw (since v2.3.0 https://github.com/tldraw/tldraw/releases/tag/v2.3.0) we don't store images anymore in base64. So it could be that the Obsidian plugin is using an older version of tldraw that was still converting images  into base64 (and making them accidentally quite large)

**Comment by MitjaBezensek** [comment]
This is now tracked here https://github.com/holxsam/tldraw-in-obsidian/issues/46

**Comment by 0PandaDEV** [comment]
> Btw, in newer versions of tldraw (since v2.3.0 [`v2.3.0` (release)](https://github.com/tldraw/tldraw/releases/tag/v2.3.0)) we don't store images anymore in base64. So it could be that the Obsidian plugin is using an older version of tldraw that was still converting images into base64 (and making them accidentally quite large)

Ok that's weird because the plugin uses 2.4.4 or that is what is in the package.json
