### ISSUE TITLE
[Feature]: Add `assetUrls`  property to  `TldrawImageProps`

### ISSUE THREAD

**Issue by jon-dez** [tldraw/tldraw#4464]
### What's the feature?

Description:

This feature will allow the component `TldrawImage` to make use of static assets, such like the example for the component `Tldraw`: https://tldraw.dev/examples/basic/static-assets

Who it would help:

It would help those who use tldraw in offline mode, and inside an Obsidian vault where tldraw documents can be embed as previews using the component `TldrawImage`.
https://github.com/holxsam/tldraw-in-obsidian/issues/47

Examples:
n/a

### Where would you like this feature?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jon-dez** [comment]
I can create a PR if needed.
https://github.com/jon-dez/tldraw/commit/a8434c5297ad5987174ac4894092427f40ab62e0

**Comment by ds300** [comment]
Thanks for the issue report! I added a PR here: https://github.com/tldraw/tldraw/pull/4465

The change will go out with the next release.
