### ISSUE TITLE
[Example Request]:  How to edit STROKE_SIZES ? 

### ISSUE THREAD

**Issue by yoosion030** [tldraw/tldraw#4490]
### Current Behavior

Currently, the DrawShapeUtil in tldraw uses a predefined STROKE_SIZES object with fixed values:

```js
export const STROKE_SIZES: Record<TLDefaultSizeStyle, number> = {
	s: 2,
	m: 3.5,
	l: 5,
	xl: 10,
}
```

https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts

https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx

### Desired Behavior

I would like to be able to customize these STROKE_SIZES values to better fit my application's needs. Specifically, I want to:

Change the existing size values (e.g., make 'xl' much larger).

```js
export const STROKE_SIZES: Record<TLDefaultSizeStyle, number> = {
	s: 4,
	m: 8,
	l: 10,
	xl: 18,
}
```

### Questions

Is there an officially supported way to customize STROKE_SIZES?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
Nope, we haven't made that possible yet I'm afraid. For now patch-package (or yarn/pnpm patch) is your best bet.

**Comment by oidw** [comment]
> Nope, we haven't made that possible yet I'm afraid. For now patch-package (or yarn/pnpm patch) is your best bet.

Hi @ds300 , do you have any plan on this issue? If only the api is used, is there any way we can modify the stroke size?
Thank you!
