### ISSUE TITLE
[Example Request]: Navigate automatically in canvas where recent shape is generated

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4499]
### What's the example?

Hi @ds300 , when a new shape gets generated programmatically, i have to find it by going through the canvas, is there a way canva moves automatically there where recent shape is generated. Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
```javascript
const id = createShapeId()
editor.createShape({
// your shape and pass in the id
})

const bounds = editor.getShapePageBounds(shapeId)
editor.zoomToBounds(bounds)
```
