### ISSUE TITLE
How do I create default shapes in external UI?

### ISSUE THREAD

**Issue by jdgalani** [tldraw/tldraw#4540]
### What's the example?

I have a custom toolbar UI placed on right side of the canvas.

I am replicating same shapes there, but I dont know what method to call for the select particular shape.

Example say for ellipse,
I have tried,

` editor.setCurrentTool("geo.ellipse");
`   
` editor.setCurrentTool("ellipse");
`

I have tried using internal MenuComponents it works out of the box, but it does not go well with the UI I am planning to build.
I am replacing the icons also.
So my best bet is to have a method.

I have done hand, select, note those things are working great.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey!

If your UI is inside the `ToolsContext` then you can do something like this:
```ts
const tools = useTools()
const oval = tools['oval']
oval?.onSelect('menu')
```

And if you are using it outside of the context then you can do it directly, just like we do it in [useTools hook](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/ui/hooks/useTools.tsx#L104-L108)):
```ts
editor.setStyleForNextShapes(GeoShapeGeoStyle, 'oval')
editor.setCurrentTool('geo')
```

You can see all the `geo` tool ids [here](https://github.com/tldraw/tldraw/blob/main/packages/tlschema/src/shapes/TLGeoShape.ts#L28-L47).

**Comment by jdgalani** [comment]
Thanks, for quick response. First one works like charm.
