### ISSUE TITLE
[Example Request]: 

### ISSUE THREAD

**Issue by Athena-Solutions** [tldraw/tldraw#4572]
### What's the example?

![Screenshot 2024-09-23 102008](https://github.com/user-attachments/assets/c6b8e3f1-ae68-452c-9a3b-cdc58fd2009c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Could you give some more information on the example that you want? it may already exist.
