### ISSUE TITLE
[Example Request]: How do I use DefaultPageMenu and DefaultQuickActions into external-ui-context?

### ISSUE THREAD

**Issue by bhNibir** [tldraw/tldraw#4592]
### What's the example?

I have a custom MenuBar UI placed on the Top outside of the canvas. Now I want to add DefaultPageMenu and DefaultQuickActions into my MenuBar.

I am following this example :
[External UI (Context)](https://tldraw.dev/examples/ui/external-ui-context)

There are examples of tools from external UI. But How Can I use  DefaultPageMenu and DefaultQuickActions in an external Menu?

How Can I do it? Please give me an example.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Our default menus rely on the editor's and Radix's context to function. There's no way to use those components in your external UI, we should maybe update the example to make that more clear.

**Comment by bhNibir** [comment]
Thank you so much for your reply.

I tried to build a delete button for my external menu, but it didn't work.


```
<button
 className="external-button"
 data-isactive={currentToolId === 'quick-actions.delete'}
 onClick={() => editor.setCurrentTool('quick-actions.delete')}
>
  Delete
</button>
```

Is there any option to build a menu using the DefaultQuickActions menu's tools, that can be used from an external UI?  

and how can I build a Page tool for external UI, that can work like DefaultPageMenu?

**Comment by Taha-Hassan-Git** [comment]
The external ui example shows how to set the current tool of the editor. Tools are a state the editor can be in and are used to make shapes on the canvas, like a rectangle or draw shape. You don't want to use a tool to delete a shape, you want the editor's delete shapes method. But you'll first need to get the id of the shape or shapes you want to delete and pass it in as an array.

```javascript
// get shape to delete, maybe editor.getSelectedShapes()
editor.deleteShapes([shapeId])
```
To set the current page you can use:

```javascript
editor.setCurrentPage(pageId)
```

The editor has many many methods that you can use to control the canvas. If you look at the tldraw source code in those default menus you'll find the editor methods you need to create new pages, rename pages, export files, zoom in and out etc. etc. etc.

Hope that helps! I'm going to close this issue now.
