### ISSUE TITLE
How to send auth headers to all requests when using custom server.

### ISSUE THREAD

**Issue by jdgalani** [tldraw/tldraw#4606]
### What's the example?

I have created a custom server running on EC2 using node-js template.
I am using `useSync` on client side to connect with my own server.
I have requirement that some rooms are private and can only be joined if user is validated in my server.
I have added `hook` in `fastify` and created a snippet which works if i send auth headers.

But dont know how to send headers from client side.
Tried sending it via query param's but JWT token is quite long and request is not even reaching to server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Hi, thanks for raising this!

It's actually not possible to send custom headers with a websocket connection unfortunately. There's some info on this here: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

You should be able to pass your JWT as part of the URL - this is the approach we've used before to implement this ourselves. How long is your JWT? Do your requests reach the server when the JWT isn't included? What sort of error do you get?

you could also look at having the `getUrl` callback make a preliminary request to the server to create a shorter single-use connection token and use that for auth?

**Comment by jdgalani** [comment]
@SomeHats Thanks for your response,
I managed to shorten the token, and it works with request params.
