### ISSUE TITLE
[Enhancement]: Rotate selected element

### ISSUE THREAD

**Issue by yishayhaz** [tldraw/tldraw#4613]
> TLDR; have the ability to rotate elements

![image](https://github.com/user-attachments/assets/55bc5d72-6798-49ae-a9da-0f703defefee)

### Motivation

Most apps that support shape creation and resizing also allow rotating elements (e.g., Figma). While there seems to be some support for this feature, it feels limited and not easily accessible in the current UI.

Additionally, the current functionality only allows rotation in 45-degree increments. It would be much more flexible and intuitive if users could rotate elements freely using a mouse drag.

If improvements are needed in this area, I'd be happy to contribute!

### Current Behavior

Click the very well-hidden rotate buttons, which feels like a waste of resources since there are two separate buttons. One would be sufficient for this functionality.

![image](https://github.com/user-attachments/assets/4a77b727-5c2c-4496-aea7-735eeda84ab3)

### Suggested Behavior

Upon selecting an element, a small circular arrow will appear, allowing users to drag and rotate the element freely.

### Nice to have

- The current angle would also be displayed on the screen for better precision.
- A keybind could be added: while holding the rotate button with the mouse, pressing an arrow key would rotate the element in that direction, allowing for precise angle adjustments—preserving the current functionality

![image](https://github.com/user-attachments/assets/ccc80786-9273-4819-991a-c192a419051a)

### Where would you like this feature?

All of them

### Contact Details

yishayhaz@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yishayhaz** [comment]
I came across this file `packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts`, which suggests that there is support for rotating elements. However, I don't see the option in the GUI. What am I missing?

**Comment by MitjaBezensek** [comment]
Hey! We do have something like that on mobile. On desktop we went with rotating when close to the edge, but I guess it might be a bit too subtle. Here's how it looks like:

https://github.com/user-attachments/assets/3159926f-a4ba-4dd7-afe6-7e421373de98

**Comment by yishayhaz** [comment]
@MitjaBezensek 

I appreciate the quick response.
And if this is the behavior you went with I assume you've already discussed other design solutions, so I'll go ahead and close this issue

Thanks again
