### ISSUE TITLE
[Example Request]:How to change its postion to bottom right

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4620]
### What's the example?

![image](https://github.com/user-attachments/assets/9744b927-04eb-4fc7-ad29-1a72e4e14113)
@ds300 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Hey there, to change the position of the style panel you can set it to null in the component prop of the Tldraw component, and then render it yourself as a child of the component. I think this is covered by our menu examples and custom ui example. However I can provide you with a bit of code here to get you started with implementing your own solution. Make sure that you don't cover up the watermark, as that would put you in breach of our license.

```typescript
function CustomStylePanel() {
	return (
		<div style={{ position: 'absolute', bottom: 50, right: 0 }}>
			<DefaultStylePanel />
		</div>
	)
}

const components: TLComponents = {
	StylePanel: null,
}

export default function CustomActionsMenuExample() {
	return (
		<div className="tldraw__editor">
			<Tldraw components={components}>
				<CustomStylePanel />
			</Tldraw>
		</div>
	)
}
```

<img width="1258" alt="Screenshot 2024-10-28 at 11 58 35" src="https://github.com/user-attachments/assets/0c5f8519-5be4-46e4-8024-1495c433d3b3">
