### ISSUE TITLE
[documentation] Renderer "assets" props

### ISSUE THREAD

**Issue by gsouf** [tldraw/tldraw#464]
Hi,

I'm following the readme of tldraw/core, it works well, but my IDE is complaining that the prop `assets` is required to use the component `Renderer`. It seems to work well without specifying this prop, and it is not documented. I'm not sure if it is really required or not. 

Ultimately it would be nice to have a bit of documentation about it.
 
Thanks!

**Comment by steveruizok** [comment]
Added to the core ! The `assets` property is also now optional for the `Renderer`.

**Comment by gsouf** [comment]
@steveruizok thank you!
