### ISSUE TITLE
 How can I add loading state on tldraw shapes?

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4713]
### What's the example?

@ds300 
Please can you help in this , incase an image isnt fully loaded can we show a loading state in tldraw?
![image](https://github.com/user-attachments/assets/3770dd20-692f-42ae-a910-7a18c25a5db5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
I'm guessing you upload the image to a server and then get the url of the uploaded image
you can do that by creating a loading shape, show that when image is not loaded at first then delete it and replace with the actual image shape when image is ready
or else you can add a blured version of the image and replace it when  the uploaded image is ready

**Comment by Taha-Hassan-Git** [comment]
Are you using a custom shape or a tldraw image shape? If custom then the loading state logic will have to go in the component method of your custom shape util. Something like:

```typescript
component() {
		// eslint-disable-next-line react-hooks/rules-of-hooks
		const [loading, setLoading] = useState(false)
		return (
			<>
				{loading ? (
					<HTMLContainer style={{ backgroundColor: '#efefef' }}>your component here</HTMLContainer>
				) : (
					<div>loading...</div>
				)}
			</>
		)
	}
```

If you're using a tldraw image shape then I think the approach above would work well, using a custom loading shape and deleting it when the image loads. It's up to you how you want to handle it, and different developers will have different needs. For that reason I don't think it makes sense as an example. However you're welcome to ask for help and guidance on the tldraw discord: https://discord.gg/HmRxbaDg
