### ISSUE TITLE
Dropping images creates two shapes

### ISSUE THREAD

**Issue by peilingjiang** [tldraw/tldraw#4716]
### What happened?

https://github.com/user-attachments/assets/84b81d5d-7b45-45e8-a284-4074c29522fc

Two shapes are created for the asset when a new image is dropped onto the canvas. I have noticed the behavior since v3.3, which didn't exist in v3.2, and can be reproduced on tldraw.com.

### How can we reproduce the bug?

Please refer to the video above.

### What browsers are you seeing the problem on?

Chrome

### Where did this happen?

The tldraw.com website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
resolved in https://github.com/tldraw/tldraw/pull/4704

**Comment by peilingjiang** [comment]
@mimecuvalo Thanks. Is the tldraw.com tracking the main branch? Or will it be released in the package soon?

**Comment by mimecuvalo** [comment]
We typically release the tldraw.com website once a week, and the SDK once every two weeks or so. I'll hotfix this though later today.

**Comment by steveruizok** [comment]
Thanks for the hotfix here @mimecuvalo !
