### ISSUE TITLE
[Bug]: dragover events are being dispatched as drop events

### ISSUE THREAD

**Issue by trygve-aaberge-adsk** [tldraw/tldraw#4717]
### What happened?

When dragging something over the canvas the `dragover` events are being dispatched as `drop` events. We use `drop` events to handle custom things being dropped on the canvas, and getting `drop` events every time the mouse moves is unexpected and makes them hard to use.

This is a regression introduced in #4651. As you can see it sets the `onDrop` function as a listener for `dragover` events, and redispatches a `drop` event.

Issue #4716 and PR #4704 are related, but while that PR fixes the issue with dragged images creating multiple shapes, the issue with the `drop` event remains.

### How can we reproduce the bug?

This patch on current `main` (commit 29d7ecaa7) logs the dragover and drop events:

```
diff --git a/apps/examples/src/examples/basic/BasicExample.tsx b/apps/examples/src/examples/basic/BasicExample.tsx
index 159fa1289..6907f6621 100644
--- a/apps/examples/src/examples/basic/BasicExample.tsx
+++ b/apps/examples/src/examples/basic/BasicExample.tsx
@@ -1,10 +1,35 @@
-import { Tldraw } from 'tldraw'
+import { useEffect } from 'react'
+import { Tldraw, useEditor } from 'tldraw'
 import 'tldraw/tldraw.css'
 
+const DropEvents = () => {
+	const editor = useEditor()
+
+	useEffect(() => {
+		const enableDrag = (e: Event) => {
+			console.log('dragover')
+			e.preventDefault()
+		}
+		const onDrop = () => {
+			console.log('drop')
+		}
+		editor.getContainer().addEventListener('dragover', enableDrag)
+		editor.getContainer().addEventListener('drop', onDrop)
+		return () => {
+			editor.getContainer().removeEventListener('drop', onDrop)
+			editor.getContainer().removeEventListener('dragover', enableDrag)
+		}
+	}, [editor])
+
+	return null
+}
+
 export default function BasicExample() {
 	return (
 		<div className="tldraw__editor">
-			<Tldraw persistenceKey="example" />
+			<Tldraw persistenceKey="example">
+				<DropEvents />
+			</Tldraw>
 		</div>
 	)
 }

```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JStuve** [comment]
Upgraded to 3.3.0 and I'm experiencing the same issue.

**Comment by mimecuvalo** [comment]
Will be in the next release! Thanks for your patience.
