### ISSUE TITLE
[Bug] Toast description and button are not aligned

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#4718]
If a toast has a description, the bottom padding should be reduced to make the button and description align.

**Comment by Syed-Bilal-Haider-Engineer** [comment]
@steveruizok I wanna resolve it, but you should add a screen of the issue. thanks

**Comment by steveruizok** [comment]
Sure thing: it's about a pixel or two off. Easier to see when the description is one line.

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/313d77a8-5b68-4989-9191-6b4859d47fba">
