### ISSUE TITLE
[bug] Prevent shape cloning while editing text

### ISSUE THREAD

**Issue by NikxDa** [tldraw/tldraw#474]
While editing the text of a node, pressing tab to type a tab will simultaneously clone the selected node.

The corresponding code is here:
https://github.com/tldraw/tldraw/blob/d7a697647b79939c9b88377183da7d48eb978fc7/packages/tldraw/src/state/tools/SelectTool/SelectTool.ts#L197

Probably needs a check to see whether the node is currently being edited.

**Comment by NikxDa** [comment]
Given that this also occurs for other keyboard events such as `spacePanning`, maybe a status `editing` may be worth exploring.

**Comment by steveruizok** [comment]
Good catch! Relates to #116 but I believe we can fix that sooner.

**Comment by steveruizok** [comment]
Fixed! Thanks @NikxDa
