### ISSUE TITLE
Arrows should not always snap

### ISSUE THREAD

**Issue by bradymadden97** [tldraw/tldraw#4755]
### What happened?

Is there no way to just _not_ have arrows always snap to the center of an obeject (and be hidden behind it). I'm constantly having to do weird hacks to get around this feature by drawing the arrow somewhere else on my canvas the way **I** want it to look, and then dragging it over the shape that I want it to be over. It's pretty surprising that this is the default behavior, and I still havent found a way of opting out.

### How can we reproduce the bug?

Literally draw two squares, try to draw an arrow between them that actually overlaps the squares and doesn't point directly at the middle. You'll see that tldraw just takes over and snaps it and doesn't overlap it.

### What browsers are you seeing the problem on?

Chrome

### Where did this happen?

The tldraw.com website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Hey, sorry about that, it sounds frustrating. You can hold down option/ctrl while dragging an arrow handle to stop it snapping to the middle. Ctrl will make sure the arrow always points to the outline of the shape, and option/alt will point to the specific point within the shape. 

We have some user manuals in the works that will surface more of these helpful features!

Hope that helps!

**Comment by bradymadden97** [comment]
Oh sweet, that works perfectly for me, TIL. Thanks!
