### ISSUE TITLE
[bug] Undo/redo bug in multiplayer with bound shapes

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#479]
When undoing in multiplayer, a shape's binding can be restored even if the shape it is bound to has been deleted.

https://user-images.githubusercontent.com/23072548/147915396-74e17bbd-b1d3-4567-92b9-a0dd0cd9acb3.mov

**Comment by judicaelandria** [comment]
Fixed!!
https://user-images.githubusercontent.com/46365844/187204184-b562de33-2a24-4744-b439-85b2a7b3299e.mov
