### ISSUE TITLE
[Example Request]: images to be displayed side by side instead of overlapping on each other

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4792]
### What's the example?

I would like the images to be displayed side by side rather than overlapping on each other
Like this
![image](https://github.com/user-attachments/assets/3baab2af-b494-438a-bffb-3705d59bb845)

how can i change the code below that way
`// useHandleMount.ts
import { useCallback } from "react";
import { Editor, createShapeId, AssetRecordType} from "tldraw";

const useHandleMount = (
  cloudinaryImageLink: string,
  setEditor: React.Dispatch<React.SetStateAction<Editor | null>>,
  setImageAdded: React.Dispatch<React.SetStateAction<boolean>>,
  imageAdded: boolean
) => {
  return useCallback(
    (editorInstance: Editor) => {
      editorInstance.updateInstanceState({ isGridMode: true });
      setEditor(editorInstance);
      console.log("Tldraw mounted");

      if (!cloudinaryImageLink || imageAdded) {
        console.log("No image to add or image already added");
        return;
      }

      const assetId = AssetRecordType.createId();
      const imageWidth = 600; // Adjust width to fit your needs
      const imageHeight = 600;

      editorInstance.createAssets([
        {
          id: assetId,
          type: "image",
          typeName: "asset",
          props: {
            name: "generated-image.png",
            src: cloudinaryImageLink,
            w: imageWidth,
            h: imageHeight,
            mimeType: "image/png",
            isAnimated: false,
          },
          meta: {},
        },
      ]);

      const id = createShapeId();
      editorInstance.createShape({
        id: id,
        type: "image",
        x: (window.innerWidth - imageWidth) / 2,
        y: (window.innerHeight - imageHeight) / 2,
        props: {
          assetId,
          w: imageWidth,
          h: imageHeight,
        },
      });

      const bounds = editorInstance.getShapePageBounds(id);
      editorInstance.zoomToBounds(bounds!);
      setImageAdded(true);
    },
    [cloudinaryImageLink, imageAdded, setEditor, setImageAdded]
  );
};

export default useHandleMount;
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
I don't think this is appropriate for an example and it's specific to your app and the behaviour you're looking for. Feel free to join the discord and post on developer help for some guidance on this. I think a minimal reproduction on codepen would be very helpful.

https://discord.gg/HmRxbaDg
