### ISSUE TITLE
Implement quill text editor

### ISSUE THREAD

**Issue by youssef7amdi** [tldraw/tldraw#4799]
Can I make a custom shape that render quill texteditor?
Or override the default text editor shape to be a quill editor?

**Comment by youssef7amdi** [comment]
> <p><a href="https://linear.app/tldraw/issue/TLD-2795/implement-quill-text-editor">TLD-2795 Implement quill text editor</a></p>

How can i get access to show that?

**Comment by MitjaBezensek** [comment]
> > [TLD-2795 Implement quill text editor](https://linear.app/tldraw/issue/TLD-2795/implement-quill-text-editor)
> 
> How can i get access to show that?

Hey! That's just a copy of the issue in linear, which we use for internal issue tracking.

**Comment by MitjaBezensek** [comment]
> Can I make a custom shape that render quill texteditor? Or override the default text editor shape to be a quill editor?

You can definitely add a custom shape to use quill editor, see our docs on **custom shapes**.

**Comment by mimecuvalo** [comment]
We have rich text editing on our radar — going to merge this ticket with that one: https://github.com/tldraw/tldraw/issues/1879
