### ISSUE TITLE
[Bug]: local scratchpad sidebar causes scrollbar and can't be removed

### ISSUE THREAD

**Issue by souporserious** [tldraw/tldraw#4801]
### What happened?

For some reason, this local scratchpad sidebar continues to persist and cannot be removed:

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/e34c5890-4bb5-498c-a7b4-6d1820faaf38">

This adds scrollbars, requiring scrolling to the right to see the tool panel:

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/3b4b061d-10f5-42f5-8952-390e7e287a0d">

Not sure if there is a conflict with an old version I previously loaded, but clearing local storage / indexed db did not seem to do anything.

### How can we reproduce the bug?

I'm not sure how to reproduce this. I've tried clearing all of the site data, but it seems to persist.

### What browsers are you seeing the problem on?

Chrome

### Where did this happen?

The tldraw.com website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
I guess you are using the `tldraw navbar` browser extension? You could try removing the extension, which should make the sidebar go away.

**Comment by souporserious** [comment]
🤦 ah I totally overlooked that being an extension. I must have installed it a while back and forgot about it. Thank you for the help!

**Comment by MitjaBezensek** [comment]
No worries, glad we found the culprit 😄

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
