### ISSUE TITLE
[bug] Ctrl + zooms in the entire browser window instead of only the canvas

### ISSUE THREAD

**Issue by techware01** [tldraw/tldraw#481]
**Problem:**
- when pressing `ctrl +` on tldraw.com the entire browser window is zoomed in

**Excepted behavior:**
- the zoom level of the entire window stays the same and only the drawing board is zoomed in.
- zooming out with `ctrl -` on the other hand works as expected

**System:** 
- Firefox 95.0.2 (64 bit)
- Arch Linux with Gnome Desktop

**Comment by steveruizok** [comment]
Nice find. Would you mind trying another browser? This will be hard to debug for me, since you're on Linux. Hopefully it's just a bug for Firefox.

**Comment by techware01** [comment]
Quickly checked it on Chromium and there it works!

**Comment by steveruizok** [comment]
Fixed!
