### ISSUE TITLE
[bug] Long-press on Mobile Shows 2 Context Menus

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#483]
See video of issue.

https://user-images.githubusercontent.com/1845/147973132-069bb50f-ae55-4867-a897-630b2145c51d.mov

Repro steps:
 1. Open Tldraw.com in mobile Safari
 2. Select the draw tool
 3. Long press
 4. You will then see the bigger context menu, and when you let go, the smaller context menu

**Comment by steveruizok** [comment]
I've fixed a bug related to the menu. It may have fixed this bug too. Could you check whether you can still reproduce this one?

**Comment by Francois-Laberge-Bose** [comment]
I hard refreshed tldraw.com and tried again. Still occurs with the above repro steps. In case it hints at the issue, this issue doesn't happen when you have the Select, Eraser, Rect/Oval/etc, Text, or StickyNote tools activated. The Draw and Arrow tool have a similar issues

**Comment by steveruizok** [comment]
Fixed!

**Comment by steveruizok** [comment]
(almost certain, will reopen if it comes up)
