### ISSUE TITLE
[feature] refactor copySvg into @tldraw/core

### ISSUE THREAD

**Issue by fabianmu** [tldraw/tldraw#485]
I came across the requirement to export a whole canvas as SVG. `@tldraw/tldraw` contains code to do that, however having this available in `@tldraw/core` seems reasonable as well. Maybe even as a counterpart to `import { Renderer } from '@tldraw/core'`

This might also be related to #450 & #468

**Comment by steveruizok** [comment]
Let me think about this one. The SVG exports tend to be very much based on the specific shape implementations, and so for this to work developers would have to follow the patterns set in our `copySvg` method. If we did move it down, we'd need to have each `TLShapeUtil` implement an `exportSvg` method.

**Comment by fabianmu** [comment]
Ah, I see. As developers already have to follow the method to create a shape, I think it would be straightforward to also have them write an export method, if needed. And have a core method trigger the export and iterate the shapes export methods to build the whole image export.
However, just thinking about this and I clearly do not have an deep understanding on which functionality is best in core vs tldraw.

**Comment by steveruizok** [comment]
No worries! In general, the core library is concerned with rendering only, so I try to only add things to that library that will directly effect what gets rendered or how.
