### ISSUE TITLE
New shapes should align to grid when enabled

### ISSUE THREAD

**Issue by mimecuvalo** [tldraw/tldraw#4868]
### What happened?

See discussion here: https://discord.com/channels/859816885297741824/1301871095929901147/1301871095929901147

- turn on Grid mode
- create a new sticky note
- sticky note should start out aligned

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
This interracts in a funny way with dynamic size turned on as well.

**Comment by mimecuvalo** [comment]
resolved in https://github.com/tldraw/tldraw/pull/4875
