### ISSUE TITLE
[feature] Change Icon When Holding Spacebar to Pan

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [tldraw/tldraw#487]
It's just a small improvement, but having the cursor icon change when you hold down spacebar, to indicate you can now pan if you click drag would be cool.

Figma's design as a reminder
https://user-images.githubusercontent.com/34040155/148244127-b2ef3c3e-e643-46aa-9bc6-199192ae7d2b.mov

**Comment by steveruizok** [comment]
Could be part of #280!
