### ISSUE TITLE
[bug] Multiplayer - Two people erasing at the same time causes crash

### ISSUE THREAD

**Issue by milo-** [tldraw/tldraw#489]
Two people erasing at the same time triggers a crash:
`Cannot read properties of undefined (reading 'isStateful')`

Demo: https://www.loom.com/share/f2b84aa0edfc4ba3b3837232bdfbc607

<img width="605" alt="Screenshot 2022-01-06 at 15 16 23" src="https://user-images.githubusercontent.com/999442/148405288-a6d272e5-e1ba-4b01-9a46-44d934f83214.png">

**Comment by milo-** [comment]
Started digging into this, I believe it's caused by the EraseSession patching the state of a shape that has been deleted by the other user. In useShapeTree the shape only has one property when it crashes: { isGhost: true }

**Comment by steveruizok** [comment]
Great catch, I saw this one on Sentry but didn't know where it was coming from!

**Comment by steveruizok** [comment]
I wonder if this "deleted during session" issue is present on any other session. We might have to add a "patched state" callback to sessions to resolve any changes to the document that have happened during this session.

**Comment by milo-** [comment]
Thanks @steveruizok, just tested 1.4.3 and it's fixed 🙌🙌
