### ISSUE TITLE
[bug] Flipping shapes is consistent and repositions them sometimes

### ISSUE THREAD

**Issue by fabianmu** [tldraw/tldraw#492]
I noticed that flipping shapes is not consistent and sometimes shapes are changing the position while flipping.
Images are not flipping at all.
[See Video](https://discord.com/channels/859816885297741824/859816885801713729/928528464968052747)

**Comment by steveruizok** [comment]
Nice one. I'm considering adding a `flip` or `scale` property to all shapes to solve some issues we've had with flipped shapes. (We'd use CSS to do the actual flipping).

**Comment by steveruizok** [comment]
Solved!
