### ISSUE TITLE
Is redrawing while panning necessary?

### ISSUE THREAD

**Issue by darrinm** [tldraw/tldraw#4923]
I would have sworn I saw a tldraw demo at one point showing lightning fast panning despite a huge number of objects. Using it today, I pan a large number of objects (1024 built-in note shapes) the frame rate is quite low. This is when zoomed out so they're all visible. It's super fast when I'm zoomed in and only a few are visible.

Did you run into a reason why something other than transforming the canvas position is necessary during panning?

![screenshot 2024-11-14 at 19 12 44@2x](https://github.com/user-attachments/assets/e5a5405a-78d7-4256-a9b7-ac5a4ae4ae1a)

**Comment by MitjaBezensek** [comment]
Hey! 

I do seedropped frames when panning around many note shapes and when zoomed out. That said I don't see any dom changes, apart from the container position changing. So it looks like it's just browser that's that slow rendering so many dom elements / calculating their styles.

https://github.com/user-attachments/assets/9e1a596d-4341-4086-b84a-259c40b6d7f4

Notes are a bit more heavy than other shapes (they have some shadows, label,...), so it's definitely more noticeable. I also noticed that there's a significant performance drop when zoomed out and it seems to be related to how we render the shadows / borders of notes. Will see what we can do.

**Comment by darrinm** [comment]
I think there is more to it than that because what is causing all the style recalculation? For example if have a ton of objects and you zoom in and right-click to bring up the context menu and move your mouse over the menu it is snappy and responsive. But if you zoom out and do the same it is sluggish.

Chrome Performance recording indicates the time is spent in the GPU. I tried adding `will-change: transform` to the parent element and that helps some and virtually eliminates the reported GPU time but is still sluggish. Performance graph says most the time is going to "Layerize" then.

**Comment by darrinm** [comment]
I did try another test with labelled rectangles instead of notes and can confirm that it is much faster. Still seems to be some unaccounted for per-shape overhead since in theory it could have same performance as scrolling (only spending time on objects becoming visible).
