### ISSUE TITLE
Error message links should be colored blue.

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#4927]
<img src="https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/777cc55b-be03-4de6-8b69-5ac65910609d/94c642bc-163a-4a53-b372-569d6a32bbc9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS83NzdjYzU1Yi1iZTAzLTRkZTYtOGI2OS01YWM2NTkxMDYwOWQvOTRjNjQyYmMtMTYzYS00YTUzLWIzNzItNTY5ZDZhMzJiYmM5IiwiaWF0IjoxNzMxNzUwMTE0LCJleHAiOjMzMzAyMzEwMTE0fQ.Ealm3y8dw3AHUmoMXFGUEByCByzG0aIYcc9Zwf8C66g " alt="image.png" width="649" height="270" />

The "create a GitHub issue" and "Discord" text in the above image are links, let's show that.

**Comment by nayounsang** [comment]
hello. I'd like to contribute to this issue, is it possible?
