### ISSUE TITLE
[bug] SVGs not loading in multiplayer

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#493]
SVG images are not embedding correctly in multiplayer projects.

When you add an SVG shape to a multiplayer project, the file uploads correctly to the S3 bucket, however the `getSizeFromSrc` function throws an error.

```ts
export function getSizeFromSrc(src: string): Promise<number[]> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve([img.width, img.height])
    img.onerror = () => reject(new Error(`Could not get image size.`))
    img.src = src
  })
}
```

Any ideas?

**Comment by milo-** [comment]
@steveruizok looks like the Content-Type header when SVG's are uploaded gets set to binary/octet-stream rather than image/svg+xml

**Comment by steveruizok** [comment]
Very weird. That's coming from S3 right?
