### ISSUE TITLE
[bug] File Save/Save As/Open shows error

### ISSUE THREAD

**Issue by nimeshnayaju** [tldraw/tldraw#495]
https://user-images.githubusercontent.com/35807215/148847512-919c78e7-3bf3-4b54-b6ea-636927d41553.mov

**Comment by nimeshnayaju** [comment]
I don't mind working on this if someone's already not working on it.

**Comment by nimeshnayaju** [comment]
@steveruizok I don't mind working on this if someone's already not working on it.

**Comment by techware01** [comment]
Is there currently any work around to open a saved project? I'm currently using tldraw for sketching an interface and now I'm not able to access it and can't show it to anyone.

**Comment by techware01** [comment]
> Is there currently any work around to open a saved project? I'm currently using tldraw for sketching an interface and now I'm not able to access it and can't show it to anyone.

Ok installed the VSCode extension and with that I'm able to open my project.
