### ISSUE TITLE
Add toast access in overrides

### ISSUE THREAD

**Issue by cqh963852** [tldraw/tldraw#4982]
### What's the feature?

I want create a custome action `ctrl + s` to save file.

If success, I need a toast.

But I found that useToasts outside of a toast provider

And I can't figure out an elegant way to solve this problem.

![image](https://github.com/user-attachments/assets/c105fb19-fdb6-4d6b-a016-9a39f0d6e0fa)

add toast's context to overrides' actions. like 
```
          actions(editor, actions, toast) {
            
            return {
              "save-file": {
                id: "",
                label: "save",
                kbd: "$s",
                onSelect: () => {
                  state.saved = true;
                  toast.addToast({ title: "Hello world!", severity: "success" });
                },
              },
              ...actions,
            };
          },
```

### Where would you like this feature?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Good shout @cqh963852 . I'm going to make a PR that adds a lot of these actions into the `helpers` prop of the action overrides.
