### ISSUE TITLE
[bug] On Windows, alt-scroll zooms in opposite of expected direction

### ISSUE THREAD

**Issue by HerbCaudill** [tldraw/tldraw#499]
On Windows, the mouse scrolling direction is the opposite of the default direction on MacOS. On Mac, IIRC this is configurable in settings; on Windows it can only be modified by getting dirty in the registry. 

Normal up/down scrolling in tldraw works as expected, but alt-scrolling to zoom in/out works in the opposite direction that users would expect:

- alt-scroll up zooms out, but should zoom in
- alt-scroll down zooms in, but should zoom out

**Comment by HerbCaudill** [comment]
I'd be happy to take a stab at this if you want to assign it to me.

**Comment by steveruizok** [comment]
Thanks @HerbCaudill !
