### ISSUE TITLE
[Example Request]: Valid / Invalid licencing examples

### ISSUE THREAD

**Issue by gladkikhartem** [tldraw/tldraw#5001]
### What's the example?

Hi, 
First of all I want to thank everyone that has contributed to tldraw product - i love it and use it everyday to document and explain the software that I write.

I love it so much that I wanted to crate a free/open-source site for software documentation where people can combine Markup & tldraw diagrams on same page.
Think about it like Confluence or Google Docs, but instead of having images on the page - you have tldraw canvas where you can draw right away. I see it very often that people struggle to keep diagrams, text and code being consistent together and wanted to create a site where I will love to create documentation.

However - i'm not sure if I can use tldraw as a part of this website without breaking the licence - can you clarify following line in the Licence agreement and provide valid/invalid licencing scenarious?

> Not to distribute the Software or modifications of the Software as a standalone product, but only as part of another application.

Because I don't quite understand what you meant here.
Will the use-case I have described above can be considered a valid case where tldraw is a part of my application and not a standalone product?
Will this still be equally valid for commercial and non-commercial use?

Thanks once again for a creating tldraw!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, you should be fine with this @gladkikhartem. That line is intended to protect us against tldraw being wrapped as another SDK. As long as you're not re-distributing tldraw as something like "gladkikhartem's cool infinite canvas sdk" you're all good. :)

**Comment by gladkikhartem** [comment]
@steveruizok Thanks for explanation!
This is what I came up with:
[![Link](https://clouddragon.net/diagrams/tGjcNp5lgecSNuY09ISTj.svg 'Link')](https://clouddragon.net/diagrams/tGjcNp5lgecSNuY09ISTj.svg)

Basically I save diagram as SVG and now I can paste it in documentation (Github/Confluence/etc.)
And when I need to edit it - I click on picture and  editing opens up so that I can update the docs.
