### ISSUE TITLE
[bug] Alt + click copying an image/video shape and undoing causes crash

### ISSUE THREAD

**Issue by milo-** [tldraw/tldraw#502]
To Reproduce:
1. Add an image shape
1. Alt + Click to Copy a few times
1. Undo a couple of times

Similar to https://github.com/tldraw/tldraw/issues/489 this also throws and exception in the useShapeTree as the shape type property is missing. This only seems to be an issue with local undo/redo, it doesn't impact Liveblocks multiplayer undo/redo.

I'm wondering if there needs to be a filter here as a fallback in case any unknown shapes / shapes missing a type are found to prevent these crashes. 

Demo: https://www.loom.com/share/59b3f36c324e45ec9c5012b6ef775c98

**Comment by steveruizok** [comment]
Is this just an issue with the ImageShape? No other shapes are producing the same bug?

**Comment by milo-** [comment]
ImageShape and VideoShape, I've not been able to reproduce with any of the other shapes.
