### ISSUE TITLE
[feature] Add IDs to UI elements to make them easy to override

### ISSUE THREAD

**Issue by FarazzShaikh** [tldraw/tldraw#503]
Adding IDs to the UI elements like the menu tabs will make it easier to style/remove them. This is useful as my application uses TLDraw but wants to disable some of the features from the menu.

**Comment by FarazzShaikh** [comment]
@steveruizok What do you think? Can you assign this to me if you're wiling to have this in?

**Comment by steveruizok** [comment]
Sure, go for it!

By the way, this is a direction I'm planning to further with in the next version of tldraw (ie override-able components as props, similar API to MDX).

**Comment by FarazzShaikh** [comment]
Huh neat! Component props should be quite straightforward, maybe I’ll take that up next, sounds fun!
