### ISSUE TITLE
[Bug]: Frame rendering crashes after Editor is recreated

### ISSUE THREAD

**Issue by trygve-aaberge-adsk** [tldraw/tldraw#5047]
### What happened?

If you change any of the props passed to `Tldraw`/`TldrawEditor` so `new Editor` is called again (so any dependencies of the `useLayoutEffect` that is calling `new Editor`), and then e.g. zoom or create a new shape, all frames will render as "Error" and this exception is thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at TextManager.measureElementTextNodeSpans (TextManager.ts:151:22)
    at TextManager.measureTextSpans (TextManager.ts:256:39)
    at getFrameHeadingInfo (frameHelpers.ts:41:35)
    at FrameShapeUtil.getGeometry (FrameShapeUtil.tsx:61:23)
    at Editor.ts:4178:40
    at __UNSAFE__Computed.derive (Store.ts:787:15)
    at __UNSAFE__Computed.__unsafe__getWithoutCapture (Computed.ts:223:24)
    at haveParentsChanged (helpers.ts:22:20)
    at __EffectScheduler__.maybeScheduleEffect (EffectScheduler.ts:91:31)
    at flushChanges (transactions.ts:128:6)
```

It seems like the old `Editor` instance is still doing some stuff, which leads to `FrameShapeUtil.getGeometry` being called which does some text measurement. However, the element the text measurement is using to measure has been removed from the document when the new `Editor` instance was created which makes the measurement fail.

This started happening in v3.5.0 when `FrameShapeUtil.getGeometry` started using `TextManager.measureTextSpans`.

### How can we reproduce the bug?

Run tldraw like this:

```
import { useState } from 'react'
import { Tldraw, TldrawOptions } from 'tldraw'
import 'tldraw/tldraw.css'

export default function CustomOptionsExample() {
	const [options, setOptions] = useState<Partial<TldrawOptions>>({
		maxPages: 3,
	})

	return (
		<div>
			<button
				style={{ position: 'fixed', zIndex: 1000 }}
				onClick={() => void setOptions({ maxPages: (options.maxPages ?? 0) + 1 })}
			>
				Change options
			</button>
			<div className="tldraw__editor">
				<Tldraw persistenceKey="example" options={options} />
			</div>
		</div>
	)
}
```

After page load click the "Change options" button and then zoom the canvas.

### What browsers are you seeing the problem on?

Chrome

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trygve-aaberge-adsk** [comment]
@ds300: Thanks for the fix! This fixes it when props are changed normally. I still encounter an issue when running locally and hot reloading the file that renders the Tldraw/TldrawEditor component though.

To reproduce apply this patch to `apps/examples/src/examples/local-storage/LocalStorageExample.tsx`:

```
diff --git a/apps/examples/src/examples/local-storage/LocalStorageExample.tsx b/apps/examples/src/examples/local-storage/LocalStorageExample.tsx
index 51bba84aa..75dfcb948 100644
--- a/apps/examples/src/examples/local-storage/LocalStorageExample.tsx
+++ b/apps/examples/src/examples/local-storage/LocalStorageExample.tsx
@@ -6,6 +6,7 @@ import 'tldraw/tldraw.css'
 // There's a guide at the bottom of this file!
 
 const PERSISTENCE_KEY = 'example-3'
+const isShapeHidden = () => false
 
 export default function PersistenceExample() {
 	//[1]
@@ -29,6 +30,7 @@ export default function PersistenceExample() {
 				loadSnapshot(store, snapshot)
 				setLoadingState({ status: 'ready' })
 			} catch (error: any) {
+				console.log(error)
 				setLoadingState({ status: 'error', error: error.message }) // Something went wrong
 			}
 		} else {
@@ -70,7 +72,7 @@ export default function PersistenceExample() {
 
 	return (
 		<div className="tldraw__editor">
-			<Tldraw store={store} />
+			<Tldraw store={store} isShapeHidden={isShapeHidden} />
 		</div>
 	)
 }

```

Then run `yarn dev`, open the local storage example, create a frame and save the `LocalStorageExample.tsx` file so it hot reloads.

I then get this error, which occurs in the same place as the one in the original post, but seem to be invoked from somewhere else further down in the stack:

```
TypeError: Cannot read properties of undefined (reading 'top')
    at TextManager.measureElementTextNodeSpans (TextManager.ts:151:22)
    at TextManager.measureTextSpans (TextManager.ts:256:39)
    at getFrameHeadingInfo (frameHelpers.ts:41:35)
    at FrameShapeUtil.getGeometry (FrameShapeUtil.tsx:61:23)
    at Editor.ts:4178:40
    at __UNSAFE__Computed.derive (Store.ts:787:15)
    at __UNSAFE__Computed.__unsafe__getWithoutCapture (Computed.ts:223:24)
    at __UNSAFE__Computed.get (Computed.ts:266:16)
    at Object.get (Store.ts:790:7)
    at Editor.getShapeGeometry (Editor.ts:4197:40)
```

I'm not sure if this issue can occur in production too, or if it's entirely specific to hot reloading.

**Comment by ds300** [comment]
@trygve-aaberge-adsk fix incoming shortly. this was indeed only something that happens during hot reload.

**Comment by trygve-aaberge-adsk** [comment]
Thanks! Though, if the container is recreated (e.g. if you change the JSX in `LocalStorageExample.tsx`) it will still fail because the container is not connected anymore.

Also, the baseElm that's created after the editor is disposed is never removed, so you get a new tl-text-measure element every time it reloads. But if this is only happening during local development that's probably not a problem.

**Comment by trygve-aaberge-adsk** [comment]
> I'm not able to reproduce this, can you push a commit with a repro somewhere perhaps?

I pushed two branches now. Try to checkout https://github.com/trygve-aaberge-adsk/tldraw/tree/replace-container-crash-before, have the local storage example open and then switch to https://github.com/trygve-aaberge-adsk/tldraw/tree/replace-container-crash-after. As before, make sure you have at least one frame in the canvas.

**Comment by ds300** [comment]
thanks! i was able to reproduce the problem there.

I figured out that the real problem is that react was re-running the useLayoutEffect even though the store instance had not changed. I think this was our fault for creating the store with the useState initializer pattern. I changed it to use useMemo and it fixed the problem 🤷🏼

**Comment by trygve-aaberge-adsk** [comment]
Hm, that's weird. As far as I can see, the useLayoutEffect is re-run both when you use useState and when you use useMemo. However with useState the store hasn't changed, while with useMemo a new store is created. For some reason, the text measurement for the frame is run when the editor is disposed when the store hasn't changed (when useState is used), but it's not when the store has changed (when useMemo is used).
