### ISSUE TITLE
[Example Request]: Create an awesome-tldraw repository

### ISSUE THREAD

**Issue by torwag** [tldraw/tldraw#5060]
### What's the example?

I'm amazed by many of the GUI enhancements demonstrated in the ``show-and-tell`` on discord.
However, as it is show-and-tell, it is hard to find, hard to track and even harder to find links to possible source code etc.
I would like to suggest creating a curated awesome-draw repository in the same way as other awesome-lists [[1](https://github.com/awesome-selfhosted/awesome-selfhosted), [2](https://github.com/ml-tooling/best-of-python), [3](https://github.com/veggiemonk/awesome-docker)]. That would allow people to send a PR to own repositories and by time we have a nice list of project using tldraw.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
early days but PRs welcome! https://github.com/tldraw/awesome-tldraw

**Comment by torwag** [comment]
I'm not an expert of discord, but I know there are discord robots. Maybe one can be created that scans for GitHub and Co links in the show-and-tell, ask the sender to add some more infos like category and short description and then create automatically a PR for the curated list. Sure, the moderator should approve the PR before it lands on the page.
