### ISSUE TITLE
[bug?] Typing / (forward slash) in a text node doesn't work as expected

### ISSUE THREAD

**Issue by hamlim** [tldraw/tldraw#507]
### Description:

Unsure if this is intentional or expected, however if I am in a text field and I type the `/` (forward slash) character the cursor is removed from the field and instead the text node is outlined (however it isn't selected).

### Steps to Replicate:

- Open tldraw.com
- Select Text from the toolbar (or hit `t` on the keyboard)
- Click somewhere on the canvas and begin to type something
- Attempt to type `/` and notice the bug

**Comment by steveruizok** [comment]
Ah right, we bound that to create "fake" pointer events, but didn't filter out the active element. I'll make a fix!

**Comment by steveruizok** [comment]
Fixed by #509 !

**Comment by hamlim** [comment]
Awesome thanks!
