### ISSUE TITLE
[Example Request]: How to register only perticular changes in history stack Version2.4

### ISSUE THREAD

**Issue by KedarDevs** [tldraw/tldraw#5081]
### What's the example?

Hi team,

I’m building a 2D CAD tool using Tldraw (version 2.4) and implementing the undo/redo feature. My tool represents nodes as ellipses and edges as arrows, and their colors often change based on specific properties of the nodes.

However, I’ve encountered an issue where changes to the color or the removal of shapes are added to the history stack. As a result, when I use undo/redo, the nodes, edges, and shapes on the canvas become mismatched, leading to significant confusion.

How can I ensure that only specific actions are added to Tldraw’s history stack?

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KedarDevs** [comment]
Also just some additional info
I'm using editor.run(()=>{},{history:'ignore'}) as of now as a possible solution
just want to know if there is any better alternative or anything specific u guys have worked on wrt history stack
Thank you

**Comment by SomeHats** [comment]
`editor.run(() => { ... }, {history: 'ignore'})` is the way to go!
