### ISSUE TITLE
[bug] Should the vscode extensionKind include ui?

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#514]
Not sure if this was intentional, I would expect it to be a workspace extension as it's mainly a custom editor:

https://github.com/tldraw/tldraw/blob/89797787e8a5cf40712aabfe5b64131b39986559/apps/vscode/extension/package.json#L39

Docs:

https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds

**Comment by steveruizok** [comment]
@seflless you may know?

> "extensionKind": ["ui", "workspace"] — Indicates the extension prefers to run as a UI extension, but does not have any hard requirements on local assets, devices, or capabilities. When using VS Code, the extension will run in VS Code's local extension host if it exists locally and means the user does not have to install the extension on the remote. Otherwise, the extension will run in VS Code's workspace extension host if it exists there. When using VS Code for the Web with Codespaces, it will run in the remote extension host always (as no local extension host is available).

https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location

**Comment by Francois-Laberge-Bose** [comment]
Yep, looks like just using "workspace" should be fine. Thanks @Tyriar . Not sure why I had that, it's been months since I did this part. I'll fix this and create a PR today.

**Comment by seflless** [comment]
https://github.com/tldraw/tldraw/pull/523
