### ISSUE TITLE
Add option to remove snow effect

### ISSUE THREAD

**Issue by Zorbiks** [tldraw/tldraw#5144]
### What's the feature?

The current snow animation on the interface is visually appealing but can be distracting for some users. Additionally, it consumes CPU resources, which may affect performance, especially on lower-end devices.

Please implement an option in the preferences menu that allows users to enable or disable the snow animation.

Thank you for considering this request!

### Where would you like this feature?

The tldraw.com website

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Sorry folks, this one might not be as charming as I’d hoped. You can turn it off for now with Menu > Preferences > Reduce motion.

**Comment by RareParsec** [comment]
Here's a permanent fix. You can simply block the HTML block that produces the snow.

Get uBlock Origin. Hit the settings tab to open up the uBlock dashboard. Go to filters, and insert this line as a filter:

`www.tldraw.com##.tl-snowstorm`

Apply the filter, and the snow should now be gone.

**Comment by yochaigal** [comment]
> Sorry folks, this one might not be as charming as I’d hoped. You can turn it off for now with Menu > Preferences > Reduce motion.

Thanks for this! For what its worth, I don't think I'd have ever figured out that "reduce motion" disabled the snow effect.

Great app, thank you!
