### ISSUE TITLE
[improvement / bug] Create input / dialog for renaming pages

### ISSUE THREAD

**Issue by wanfuuyu** [tldraw/tldraw#518]
rename a page in vscode not work, nothing happend after click rename

![image](https://user-images.githubusercontent.com/8027958/149858489-188310e1-cff1-4ac1-aea6-ccb096a54c68.png)

**Comment by steveruizok** [comment]
Confirmed bug. We use `window.prompt` for the rename page UI and this does not work in VS Code.

Sounds like we need some actual UI!

**Comment by nutstick** [comment]
Probably can use `vscode.window.showInputBox` (https://code.visualstudio.com/api/references/vscode-api#InputBoxOptions) when we open in vscode instead.

**Comment by steveruizok** [comment]
Solved!
