### ISSUE TITLE
[bug] Saving Acts as Undo Sometimes in VS Code Extension

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#519]
I don’t have more context than this tweet, tracking it though:
https://twitter.com/shoppingtheatre/status/1483141855563120642?s=21

**Comment by steveruizok** [comment]
> it may be a bug, sometimes save becomes undo. happened a couple of times. files also save as .json first which has to be renamed into .tldr when a new file is launched. also, zoom instead of pan. maybe 🥂

**Comment by DavidDNA** [comment]
The issue arises when pressing the hotkey ctrl+s directly after ctrl+z.

https://user-images.githubusercontent.com/14218920/151999620-3b84c71c-b556-414a-8c2d-4508190c1199.mp4

**Comment by seflless** [comment]
Can't repro on macOS, so that's good. I'll dig up my Windows computer and give it a try there. Thanks for the repro video, that's VERY helpful and motivating.

**Comment by DavidDNA** [comment]
I confirm it doesn't happen on macOS (both Safari & Chrome) but does on Windows (Chrome & Edge).

**Comment by Francois-Laberge-Bose** [comment]
Ok, cool. I just tested on Windows and can repro this consistently on tldraw.com and in the extension. 

@steveruizok this happening on the website too means it's not extension specific. You want to look at this?

**Comment by DavidDNA** [comment]
I've opened a PR (#551) today which should fix it.

**Comment by MaxAtoms** [comment]
@Francois-Laberge-Bose 
As #551 has been merged, I guess this issue can be closed?

**Comment by seflless** [comment]
Yeah this is way old and resolved. I’ll close
