### ISSUE TITLE
[feature] White background (or transparent background?) on export

### ISSUE THREAD

**Issue by Brifien** [tldraw/tldraw#522]
Hello,
Thanks for tldraw, it is really great!
I noticed that the background is not really white (RGB: 248, 249, 250). When the drawing is exported to PNG and imported in Word (for example), the background is therefore not white (or transparent) and it is not "nice".
Could you change the background to white or an option to do it?
Thanks :-)

**Comment by steveruizok** [comment]
That's a good idea, especially for export! I'll think over our options there. I'm personally a fan of the off-white canvas, so that the white UI shows up more clearly, but I'm open to ideas.

**Comment by sul4bh** [comment]
Can I work on this feature?

My thoughts so far are to provide a new `Export -> PNG (transparent)` option and then change the puppeteer based export api to set background color of various divs(.tl-container?) to transparent.

Another option is to allow a user to select a page background color including transparent.

Any preference? Thoughts?

**Comment by aral** [comment]
@sul4bh The ability to easily set a custom background colour would be very interesting for streamers (as they could green screen their drawings) ;)

**Comment by sul4bh** [comment]
I got sidetracked with other things. I won't be able to complete this issue.
