### ISSUE TITLE
[bug] Exporting 2nd (or later) page to image fails

### ISSUE THREAD

**Issue by devkev** [tldraw/tldraw#524]
Exporting (to PNG) the 1st page works fine, but when I try to export the 2nd, 3rd, 4th, etc page, I get a blank image containing centered text that says "Application error: a client-side exception has occurred (see the browser console for more information).".  Unfortunately, there are no log messages in the browser console.

This is on tldraw.com in Chrome 97 on Linux.  The `https://www.tldraw.com/api/export` endpoint returns 200, with `content-type` of `application/octet-stream` and `content-length` that exactly matches the downloaded file.  So I suspect that this is actually a server-side error.

Happens when exporting to png or jpeg.  Webp saves a file that is just `{}` (and `/api/export` returns 500).  SVG and JSON seem to work fine.

If I delete the 1st page, then the page which was 2nd (and is now 1st) still fails in this way.

**Comment by steveruizok** [comment]
Oh that makes sense actually, let me make a PR.

**Comment by steveruizok** [comment]
Fixed!

**Comment by devkev** [comment]
Thanks!!
