### ISSUE TITLE
[bug] Large images breaking PNG export

### ISSUE THREAD

**Issue by FarazzShaikh** [tldraw/tldraw#529]
A page with a large image (here: 2MB) like this: 

![image](https://user-images.githubusercontent.com/55190601/150329424-67d30ac7-1f0b-4bb2-9145-59f16de27150.png)

Exports incorrectly as a PNG to this: 

![image](https://user-images.githubusercontent.com/55190601/150329664-eb599c89-edc3-4f72-a0e7-94cf3718fc08.png)

(Screenshot because original export is 81MB)

Interestingly, JPG, SVG and WEBP work normally.

![Page 1 (3)](https://user-images.githubusercontent.com/55190601/150330058-a942b3ea-ab2d-4efc-ba46-357d8724a25b.jpeg)

**Comment by steveruizok** [comment]
Zuh?? No idea why that would be happening. Maybe something to do with puppeteer?

**Comment by judicaelandria** [comment]
fixed!
