### ISSUE TITLE
[bug] Media upload fails in Multiplayer Room

### ISSUE THREAD

**Issue by jibe-b** [tldraw/tldraw#536]
Clicking on "Upload Media" in the menu works when using a default room but not when the room is a "Multiplayer Room".
The expected file selection window does not show up, and no log appear in the console.

I tryied on desktep, using Firefox 96 and Chromium 97 on Ubuntu 20.04

PS: this app is definitively great, even at this early stage, congrats to the devs!

**Comment by steveruizok** [comment]
Good catch! Working on a fix.

**Comment by steveruizok** [comment]
Fixed!
