### ISSUE TITLE
[bug] Text is offset incorrectly when copying as svg

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#538]
In tldraw in vscode:

![image](https://user-images.githubusercontent.com/2193314/151632851-284bfe56-e8a1-4297-a814-abbe6b637d77.png)

The svg:

![image](https://user-images.githubusercontent.com/2193314/151632870-b370da8c-ff69-44e3-979c-4e6366401e64.png)

The arrow text is very off but the rectangle text is also not aligned correctly.

**Comment by nx-jan-fischer** [comment]
Does also happen if you export as png.

**Comment by steveruizok** [comment]
Closed by #936
