### ISSUE TITLE
[bug] Don't use the Windows key (on Windows/Linux) for keybindings

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#540]
This is bad practice, I'm assume it's because this is more mac focused currently?

![image](https://user-images.githubusercontent.com/2193314/151633141-29398fb3-32b0-43d0-b831-2dcdfe14bce9.png)

Windows+= is actually bound at the OS level to the screen magnifier a11y feature

**Comment by steveruizok** [comment]
Huh, that should never be Windows, even on Windows—it should be Ctrl. We do recognize either `event.ctrlKey` or `event.metaKey` for these commands. What key is `metaKey` on Linux?

**Comment by steveruizok** [comment]
The code in question is here:

```json
{
  "key": "cmd+numpad_add",
  "title": "Zoom In",
  "command": "tldraw.tldr.zoomIn",
  "category": "tldraw",
  "when": "resourceExtname == .tldr"
},
```

I'm guessing we change that `cmd` to something else, but what would cover ctrl or cmd on Mac but only ctrl on Windows/Linux?

**Comment by Tyriar** [comment]
`cmd` ends up mapping to the windows key on Windows and Linux. You'll need to have platform overrides for this:

```
{
  "key": "ctrl+numpad_add",
  "mac": "cmd+numpad_add",
  "title": "Zoom In",
  "command": "tldraw.tldr.zoomIn",
  "category": "tldraw",
  "when": "resourceExtname == .tldr"
}
```

**Comment by harin49** [comment]
can the cmd/windows key be replaced altogether by the alt/option key? works on all targeted platform OS I believe.
