### ISSUE TITLE
[bug] Unable to rename, delete page in vscode

### ISSUE THREAD

**Issue by nutstick** [tldraw/tldraw#543]
There's no response after clicking rename/delete page.

https://user-images.githubusercontent.com/11162782/151702038-182a9cb4-1b26-424d-bc5a-762d25ac2070.mov

I have tried it on the web version, it's worked fine. I suspect due to [prompt](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/components/TopPanel/PageOptionsDialog/PageOptionsDialog.tsx) used in implementation but it doesn't support in vscode

**Comment by BRO3886** [comment]
Duplicate of #518 I think

**Comment by BRO3886** [comment]
Yes the issue is with prompt

**Comment by nutstick** [comment]
Oops, sorry I didn't see it already reported. Let me close this issue.
