### ISSUE TITLE
[bug] Not exporting png / jpg/ webp

### ISSUE THREAD

**Issue by nichitaa** [tldraw/tldraw#549]
[New Document.zip](https://github.com/tldraw/tldraw/files/7973590/New.Document.zip)

In the zip is a small .tldr sketch with the issue.
This small drawing is not exporting to any of the png / jpg / webp formats.
I could only export it to json and svg but the text is too big where it is supposed to be smaller.

Could you please help me ?

Thanks

**Comment by BRO3886** [comment]
I'll check

**Comment by gaikaz** [comment]
Having the same issue here. But took a little time now to make a "tldr" version of my buggy file.
[buggy.tldr.zip](https://github.com/tldraw/tldraw/files/7976798/buggy.tldr.zip)
Visually it only contains a rotated square with a text field inside. It wasn't me who made this little crasher, so I can't exactly say, how to reproduce it, but maybe it'll help anyway 🙂

**Comment by gaikaz** [comment]
Forgot to mention! The bug has something to do with Grouping. If you ungroup the elements, it starts exporting.

**Comment by davidXire** [comment]
> Forgot to mention! The bug has something to do with Grouping. If you ungroup the elements, it starts exporting.
> 
> Another edit: That's just it!! I created a new project, added two squares and just grouped them and it stopped exporting.

I confirm, same here

**Comment by BRO3886** [comment]
Sorry could not get time to check earlier. It is an issue with the api in  `pages/api/export.ts`. I'm on it, will push a fix soon
