### ISSUE TITLE
[feature] Paste image from clipboard

### ISSUE THREAD

**Issue by thomasaull** [tldraw/tldraw#550]
The feature to import images/videos is really helpful, e.g. to annotate screenshots. To make it even better, in my case it would be really helpful to be able to paste an image from clipboard. I constantly take screenshots of an existing web app, load it into tldraw and put some annotations here and there. To be able to paste directly from clipboard would eliminate the steps of saving the screenshot and having to find the file in the file picker thus removing some friction.

**Comment by guettli** [comment]
I would even pay for this feature! For me pasting images is enough (I don't paste videos).

**Comment by thomasaull** [comment]
@guettli https://github.com/sponsors/steveruizok?frequency=recurring&sponsor=steveruizok ;-)

**Comment by guettli** [comment]
Thanks for the hint, I am sponsoring this project now. I hope pasting screenshots from the clipboard will be supported soon.

**Comment by judicaelandria** [comment]
You can use this feature  now

**Comment by thomasaull** [comment]
Awesome :)
