### ISSUE TITLE
[bug] Meaning of 'Cancel' Confusing in New-Project/Open/etc Flows

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#559]
In cases where you are about to blow away the current working file, the dialog box buttons aren't what I'd expect.

Repro steps
 1. Go to https://tldraw.com/
 1. Create at least one shape (not sure this part is necessary, but bare with me)
 1. Open the top/left hamburger menu, select `File -> Open file`
 1. Dialog will pop up saying: `Do you want to save changes to your current project?` and `Cancel` and `Ok' buttons
 1. What I'd expect
    1. 'Cancel' to mean, cancel Opening a new file'
      1. I think a 'Cancel' and 'No'/'Don't Save'/'Skip Saving' open should be added for a total of 3 choices. Escape key should mean 'Cancel' as in stop Opening action
    1. 'Ok' means what I'd expect, but maybe 'Yes' or 'Save Project first'/'Save Project...` 

Here's a video of the current behavior. I'm choosing 'Cancel' here and so it's skipping saving and goes to open the file. This is also confusing, because it's hard to tell if you chose either choice because a file picker shows up next regardless of which choice you made.

https://user-images.githubusercontent.com/1845/152546776-4c01b351-83a0-4d70-bb9d-3c54ecb1ceb6.mov

**Comment by steveruizok** [comment]
Tracking on #817
