### ISSUE TITLE
[bug] Copy as SVG Keyboard Shortcut Broken

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#560]
When I do `Command+Shift+C` on macOS on the website (https://tldraw.com) at least, it doesn't copy SVG text to my clipboard.

**Comment by eswarclynn** [comment]
The issue seems to be due to no hotkey attached for `⌘+shift+c,ctrl+shift+c` in `useKeyboardShortcuts.tsx`. Could create a PR to add it, if that's the case.

**Comment by seflless** [comment]
@eswarclynn Yes please!

**Comment by steveruizok** [comment]
Fixed! Thanks to @eswarclynn.
