### ISSUE TITLE
[feature] Help panel

### ISSUE THREAD

**Issue by AgapovOne** [tldraw/tldraw#572]
To learn all the available shortucts it would be cool to have some kind of a floating window somewhere on a canvas.
For example, it can be shown with:
- Toggles shown/hidden via hotkey
- Toggles shown/hidden via tap on some icon/menu item
- Toggles always shown inside a window with some `stick` button.

A good example for me is Bear app. Sometimes I forget all the hotkeys and all I need is just open their menu at the bottom right corner.
<img width="1224" alt="Screenshot 2022-02-12 at 11 41 13" src="https://user-images.githubusercontent.com/4246455/153700396-e2f21ac1-5908-414b-9c1f-7fd37da1818c.png">

Also other editors like Blender has a bottom menu where toggling cmd/shift/option would show commands that could be used only with those toggled.
<img width="2131" alt="Screenshot 2022-02-12 at 11 44 54" src="https://user-images.githubusercontent.com/4246455/153700436-fd288509-4330-406c-b789-702475a883d8.png">

I think it would improve the learning curve of moving into tldraw from other editors, or even for those who can't remember that just one hotkey.

**Comment by Proful** [comment]
This is very good suggestion.

**Comment by ayushagg31** [comment]
I would love to work on this feature request, if team is interested to add this.
