### ISSUE TITLE
[bug] Rotated text does not align correctly when exported

### ISSUE THREAD

**Issue by andyvanosdale** [tldraw/tldraw#579]
When I rotate a text shape, it does not stay in the spot that it shows in the UI.

Repro: https://www.tldraw.com/r/1644950310920

UI:
![image](https://user-images.githubusercontent.com/2337208/154127711-24473593-f6c6-4022-bcf7-d0eae23f34bc.png)

Exported JPEG (PNG shows the same thing):
![Page 1](https://user-images.githubusercontent.com/2337208/154127750-0ad1c0cd-4a6a-44bf-a3ed-ce283448a55f.jpeg)

**Comment by steveruizok** [comment]
Thanks for the issue, I believe this should be addressed by @seflless's work with SVG text.

**Comment by judicaelandria** [comment]
fixed!
