### ISSUE TITLE
[bug] Close popover when clicking trigger button again

### ISSUE THREAD

**Issue by dpschen** [tldraw/tldraw#583]
# Steps to reproduce

1) Open a popover e.g. click once on the menu icon in the top left
2) Don' move you cursor but instead click once again

# Expected outcome

Popover closes

# Actual outcome

Popover closes shortly and then opens again.

-----------

This can also be reproduced by opening one of the tool selection popovers.

**Comment by judicaelandria** [comment]
Hi @dpschen, I think this is the default behavior of this, but you can click outside to  close it

**Comment by dpschen** [comment]
Hi @judicaelandria,
what do you mean by default behavior? That this is intended – because that feels counterintuitive for me.

When you click e.g. the arrow in the watch or star dropdown button in this repo twice the dropdown will open and close.

**Comment by judicaelandria** [comment]
Someone has already made a pr about this, you can retry and close the issue if it's working for you!

**Comment by dpschen** [comment]
> Someone has already made a pr about this, you can retry and close the issue if it's working for you!

You are right! Perfectly fine now :) Closing
