### ISSUE TITLE
[bug] Emoji appear as black rectangle when exporting

### ISSUE THREAD

**Issue by Limezy** [tldraw/tldraw#588]
**Screenshot view :** 
![image](https://user-images.githubusercontent.com/24638389/154784677-5f9d02f1-8b41-4266-9bd6-e3bdb603241e.png)

**Export view :**
![2-ensemble (1)](https://user-images.githubusercontent.com/24638389/154784659-9d9045e3-1e6f-4c0c-ac5d-4e99ea16880e.png)

Thanks for this awsome project !

**Comment by steveruizok** [comment]
Thanks for the issue! @Soyn's made some good progress here.

**Comment by judicaelandria** [comment]
working!
