### ISSUE TITLE
[bug] Undo reopens last closed tab on Safari

### ISSUE THREAD

**Issue by hadihallak** [tldraw/tldraw#593]
Undo hotkey also reopens the last closed tab on Safari 
------------------
OS: MacOS Monterey
Browser: Safari 15.3

**Comment by mrkldshv** [comment]
I've tried to prevent default event handling and it seems to solve it. Is it safe to use `event.preventDefault()` here? I'd be happy to open PR if it's acceptable solution!

**Comment by judicaelandria** [comment]
I think so, yes! you send that pr @mrkldshv
