### ISSUE TITLE
[bug] copying images from a single player doc to a multiplayer doc doesn't work in certain image combinations

### ISSUE THREAD

**Issue by cgrobb** [tldraw/tldraw#604]
When a .tldr created and exported using tldraw.com has 2+ images where at least 1 image is incorporated via drag and drop and at least 1 image created via File...>Media Upload, the image incorporated via File...>Media Upload does not display correctly when pasted  (from tldraw.com) into and shared in a tldraw.com/r/* (aka multiplayer) doc.

Yeah, that's pretty specific, but I hit this issue just trying to collab with coworkers when communicating UI wireframes.

1. Go to tldraw.com
2. Create a new project via File...>New Project
3. Drag an image (Image 1) from the Finder into browser tab for 2. above
4. Add an image (Image 2) to the browser tab in 2. above via File...>Media Upload
5. Save .tldr locally using File...>Save
6. Open the .tldr from 5. in tldraw.com (no issue yet)
7. In a separate tab create a Multiplayer Canvas via tldraw.com UI
8. Paste all content from 6. into 7. using select all, copy, switch tabs, paste (no issue yet)
9. Copy the URL from 8. and paste into another browser. Image 2 is not displayed, instead "tl_image_asset" text is. Image 1 is shown correctly.

<img width="1189" alt="Screen Shot 2022-03-04 at 9 32 13 AM" src="https://user-images.githubusercontent.com/805297/156792376-c59540e0-0629-456b-ac40-d5d54ef884ee.png">

[image-issue-test-3-mix.tldr.zip](https://github.com/tldraw/tldraw/files/8187001/image-issue-test-3-mix.tldr.zip)
https://www.tldraw.com/r/1646406308736

These URLs and tldrs (attached) exhibited no issues.
https://www.tldraw.com/r/1646405825511
[image-issue-test-1.tldr.zip](https://github.com/tldraw/tldraw/files/8186951/image-issue-test-1.tldr.zip)

https://www.tldraw.com/r/1646406028557
[image-issue-test-2-dand.tldr.zip](https://github.com/tldraw/tldraw/files/8186953/image-issue-test-2-dand.tldr.zip)

**Comment by steveruizok** [comment]
Thanks for the issue. This is going to take some work to fix! 

I believe we already include serialized assets in clipboard content, however we'll need to recognize these when multiplayer is enabled, check to see whether we already have uploaded the asset, and if not upload a new one to the server.

**Comment by cgrobb** [comment]
Thanks!

Perhaps now's the time to spec the UI and deeper work where shared and remote tldr projects appear user-seamless where say a single UI toggle automagically makes a tldr.com project sharable or private to you (and conversely)?

**Comment by steveruizok** [comment]
I think this is fixed now?
