### ISSUE TITLE
[bug] VS Code Extension Does Not Include Export Options

### ISSUE THREAD

**Issue by GrumpyLabRat** [tldraw/tldraw#605]
The current VS Code extension (1.8.1) appears to be missing the Right Click > Export > PNG, etc. capability found in the browser version.

**Comment by steveruizok** [comment]
Good catch, adding here: https://github.com/tldraw/tldraw/pull/608

**Comment by steveruizok** [comment]
Fixed! Will push a new version today.

**Comment by GrumpyLabRat** [comment]
Awesome!  Thanks for the speedy fix!  Love this little tool! From: Steve Ruiz ***@***.***>Date: Wednesday, March 9, 2022 at 7:32 AMTo: tldraw/tldraw ***@***.***>Cc: GrumpyLabRat ***@***.***>, Author ***@***.***>Subject: Re: [tldraw/tldraw] [bug] VS Code Extension Does Not Include Export Options (Issue #605)Closed #605.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
