### ISSUE TITLE
[bug] Bounding rectangle Shrinking Bug with Monospace Text objects when reopening browser

### ISSUE THREAD

**Issue by cgdougm** [tldraw/tldraw#606]
### Reproduce
* create a one-line text object in Monospace font (the fourth choice)
* close the tldraw browser tab 
* re-open tldraw

### Unexpected results
* The text's rectangle becomes slightly smaller in X, so the last character(s) are moved to the next line.

![image](https://user-images.githubusercontent.com/1143761/157109160-28c7f3c1-2ddc-49cd-b898-2a052348c666.png)

### Comment 
I guess the problem is the size calculation of a given string when it's that particular font.

**Comment by cgdougm** [comment]
I have tested this more and I see what may be the problem:
The bounding rectangle that is saved is for the third font, not the current font.
You can see this if you:

- use the first font (very condensed compared to others)
- close browser (forcing the save)
- re-open browser 
...you will see that the rectangle is much longer than the first-font text.
- switch to the third font
...you will see NO change in the rectangle (suggesting that the box was read from the persistent storage as the third font, not the actual first font.)

Hope this helps!

**Comment by steveruizok** [comment]
I'll chase this now, thanks!

**Comment by steveruizok** [comment]
Fixed!
