### ISSUE TITLE
[bug] Page list should be scrollable

### ISSUE THREAD

**Issue by Limezy** [tldraw/tldraw#607]
Depending on your screen size, once you reach a certain number of pages, the list becomes unusable !

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/24638389/157142613-99d4b88c-34af-4996-849f-c17fe86b9e50.png">

**Comment by steveruizok** [comment]
Fixed!

**Comment by Limezy** [comment]
Great, thanks !
