### ISSUE TITLE
[bug] Export does not display Japanese characters

### ISSUE THREAD

**Issue by tacomanator** [tldraw/tldraw#618]
Great work on this app! I'm testing it out, and found issues when exporting drawings with Japanese text.

PNG and JPG don't display the Japanese characters. Presumably the fonts in tldraw do not include Japanese (and probably Chinese). Typically fallback fonts are used to render unsupported characters, but I don't know how the mechanics of how this happens. I tried all four of the fonts available, all had the same result.

SVG works better, probably because font rendering is up to the consuming app. However, sticky note text wrapping does not work the same way as in the app itself. Maybe because Japanese does not use spaces?

Happy to provide any details requested. Minimal example below.

### Screenshot of drawing
<img width="1092" alt="Screen Shot 0004-03-11 at 9 01 04" src="https://user-images.githubusercontent.com/63794/157775985-256aa157-38e7-40eb-ac6b-b3add29cf846.png">

### JPG Export
![Page 1](https://user-images.githubusercontent.com/63794/157775996-3240f625-ea24-4fbb-a41a-21bb863a0994.jpeg)

### PNG Export
![Page 1](https://user-images.githubusercontent.com/63794/157776015-90bc707f-6a6d-47f1-a2f6-490becfbca99.png)

### SVG Export
![Page 1](https://user-images.githubusercontent.com/63794/157776025-64095b2f-df3a-4c90-8a6e-672d23b3c075.svg)

### Drawing file
```{json}
{
  "name": "New Document",
  "fileHandle": {},
  "document": {
    "id": "doc",
    "name": "New Document",
    "version": 15.3,
    "pages": {
      "page": {
        "id": "page",
        "name": "Page 1",
        "childIndex": 1,
        "shapes": {
          "bb53cf46-0bf8-4bf6-2161-1b85c3d92df3": {
            "id": "bb53cf46-0bf8-4bf6-2161-1b85c3d92df3",
            "type": "text",
            "name": "Text",
            "parentId": "page",
            "childIndex": 1,
            "point": [
              560.89,
              263.95
            ],
            "rotation": 0,
            "text": "あいうえお",
            "style": {
              "color": "white",
              "size": "small",
              "isFilled": false,
              "dash": "draw",
              "scale": 1,
              "font": "script",
              "textAlign": "middle"
            }
          },
          "ed4e7a43-8769-40b9-1bba-35eaffc66a30": {
            "id": "ed4e7a43-8769-40b9-1bba-35eaffc66a30",
            "type": "text",
            "name": "Text",
            "parentId": "page",
            "childIndex": 2,
            "point": [
              601.39,
              342.42
            ],
            "rotation": 0,
            "text": "漢字",
            "style": {
              "color": "white",
              "size": "small",
              "isFilled": false,
              "dash": "draw",
              "scale": 1,
              "font": "script",
              "textAlign": "middle"
            }
          },
          "a62f02fe-1f86-46f4-121c-9cd7666ea69f": {
            "id": "a62f02fe-1f86-46f4-121c-9cd7666ea69f",
            "type": "sticky",
            "name": "Sticky",
            "parentId": "page",
            "childIndex": 3,
            "point": [
              533.89,
              429.11
            ],
            "size": [
              200,
              200
            ],
            "text": "聞くは一時の恥、聞かぬは一生の恥。",
            "rotation": 0,
            "style": {
              "color": "white",
              "size": "small",
              "isFilled": false,
              "dash": "draw",
              "scale": 1,
              "font": "script",
              "textAlign": "middle"
            }
          }
        },
        "bindings": {}
      }
    },
    "pageStates": {
      "page": {
        "id": "page",
        "selectedIds": [
          "bb53cf46-0bf8-4bf6-2161-1b85c3d92df3",
          "ed4e7a43-8769-40b9-1bba-35eaffc66a30",
          "a62f02fe-1f86-46f4-121c-9cd7666ea69f"
        ],
        "camera": {
          "point": [
            -130.81,
            -137.7
          ],
          "zoom": 1
        },
        "editingId": null
      }
    },
    "assets": {}
  },
  "assets": {}
}
````

**Comment by senntore** [comment]
The export of Japanese input is working fine for me in Firefox.

### Screenshot of the tldraw:
![image](https://user-images.githubusercontent.com/58325574/182302107-15adcb1d-fae9-4f2b-a92c-707cf3e7e16a.png)

### Screenshot of the JPEG export:
![Page 2](https://user-images.githubusercontent.com/58325574/182302158-f1ea4e93-330c-40c2-abb5-99213393d039.jpeg)

And here is the document:
> {
  "name": "New Document",
  "fileHandle": null,
  "document": {
    "id": "doc",
    "name": "New Document",
    "version": 15.5,
    "pages": {
      "page": {
        "id": "page",
        "name": "Page 2",
        "childIndex": 1,
        "shapes": {
          "bdbf8ace-b18d-4c01-0ddb-a964f8ea7f48": {
            "id": "bdbf8ace-b18d-4c01-0ddb-a964f8ea7f48",
            "type": "rectangle",
            "name": "Rectangle",
            "parentId": "page",
            "childIndex": 1,
            "point": [
              -81.76,
              -253.9
            ],
            "size": [
              749.35,
              435.29
            ],
            "rotation": 0,
            "style": {
              "color": "white",
              "size": "small",
              "isFilled": true,
              "dash": "draw",
              "scale": 1
            },
            "label": "",
            "labelPoint": [
              0.5,
              0.5
            ]
          },
          "7afd668e-6934-4bdb-2907-f3a9aa814074": {
            "id": "7afd668e-6934-4bdb-2907-f3a9aa814074",
            "type": "text",
            "name": "Text",
            "parentId": "page",
            "childIndex": 2,
            "point": [
              -44.681893120101044,
              -180.65387320179218
            ],
            "rotation": 0,
            "text": "あいうえお",
            "style": {
              "color": "lightGray",
              "size": "medium",
              "isFilled": false,
              "dash": "draw",
              "scale": 1.3480405907955182,
              "font": "erif",
              "textAlign": "start"
            }
          },
          "8068c0ed-ae9a-4004-3dbd-edd15e227db1": {
            "id": "8068c0ed-ae9a-4004-3dbd-edd15e227db1",
            "type": "text",
            "name": "Text",
            "parentId": "page",
            "childIndex": 3,
            "point": [
              -44.681893120101044,
              -56.06455552108713
            ],
            "rotation": 0,
            "text": "私のほしぞら",
            "style": {
              "color": "lightGray",
              "size": "medium",
              "isFilled": false,
              "dash": "draw",
              "scale": 1.3480405907955182,
              "font": "erif",
              "textAlign": "start"
            }
          },
          "5b2fffcd-c804-427c-1ad8-bced2f54a454": {
            "id": "5b2fffcd-c804-427c-1ad8-bced2f54a454",
            "type": "sticky",
            "name": "Sticky",
            "parentId": "page",
            "childIndex": 4,
            "point": [
              360.92,
              -191.26
            ],
            "size": [
              200,
              200
            ],
            "text": " 黒の奇跡",
            "rotation": 0,
            "style": {
              "color": "black",
              "size": "small",
              "isFilled": false,
              "dash": "draw",
              "scale": 1,
              "font": "script",
              "textAlign": "middle"
            }
          }
        },
        "bindings": {}
      }
    },
    "pageStates": {
      "page": {
        "id": "page",
        "selectedIds": [
          "bdbf8ace-b18d-4c01-0ddb-a964f8ea7f48",
          "7afd668e-6934-4bdb-2907-f3a9aa814074",
          "8068c0ed-ae9a-4004-3dbd-edd15e227db1",
          "5b2fffcd-c804-427c-1ad8-bced2f54a454"
        ],
        "camera": {
          "point": [
            667.09,
            513.26
          ],
          "zoom": 1
        }
      }
    },
    "assets": {}
  },
  "assets": {}
}

**Comment by tacomanator** [comment]
It does seem to have improved. Even in Chrome the characters displayed in the export. There is still an issue with the sticky notes and text wrapping (try making the text of sticky note longer such that it wraps to next line and then exporting). Would you like me to create a separate issue?

### screen

<img width="1057" alt="Screen Shot 0004-08-20 at 8 15 22" src="https://user-images.githubusercontent.com/63794/185718492-14f3565e-2180-431d-99e9-92edaffb5be1.png">


### export

![Page 2(1)](https://user-images.githubusercontent.com/63794/185718503-9bc5fd80-de99-4884-8bf0-0108364def03.png)

**Comment by judicaelandria** [comment]
yes please! 
with the document! thanks
