### ISSUE TITLE
[feature] Add custom mouse cursor icons for tools

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#62]
It would help to reduce confusion if your mouse changed to the current tool's icon. It currently is always the default pointer icon. Otherwise you have to look to the bottom of the screen to figure it out.

Personally I like that you keep the drawing tool selected after you draw, unlike some tools that switch back to the selection tool, but it being different makes me sometimes forget the behavior, as I have to use other tools too. So this would help reduce falsely drawing for instance, when I meant to grab.

**Comment by anudaweerasinghe** [comment]
Hey, we were considering using the tool icons in the toolbar? What do you think, should we go ahead and start working on it?

**Comment by 789betting** [comment]
It’s appropriate time to make some plans for the future and it’s time to
be happy. [789bet หวยออนไลน์](https://www.789bet-vip.net/lotto/)

**Comment by steveruizok** [comment]
Started at #280 . Let's continue the discussion there!
