### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by igoyetche** [tldraw/tldraw#624]
I was using the app in Chrome and after doing a change the app crashed and now I can't access any of the Diagrams I had.

![image](https://user-images.githubusercontent.com/6946311/158846973-f2d11be5-e3ba-478d-adec-1027d4a6d20a.png)

The messages I have in the console:
![image](https://user-images.githubusercontent.com/6946311/158847094-0a61f7f1-9253-4594-808b-20ee0e22de34.png)

**Comment by steveruizok** [comment]
Hi @igoyetche, could you try reloading the page? It should recover.

**Comment by steveruizok** [comment]
...if not, could you DM me on the Discord channel?

**Comment by igoyetche** [comment]
I already reloaded the page many times and still the same issue.

**Comment by gcoch** [comment]
Same issue here.
![Screen Shot 2022-03-21 at 6 32 15 PM](https://user-images.githubusercontent.com/4117604/159375107-cc7f3455-656d-43b5-ae7b-0637e5982f13.png)

**Comment by steveruizok** [comment]
Working on it!
