### ISSUE TITLE
[feature] Constraints to restrict dragging of shapes inside renderer

### ISSUE THREAD

**Issue by jeroenv** [tldraw/tldraw#625]
Would be nice if there was a way to restrict the dragging area of a certain shape inside the Renderer component. 

For example, you could this library to create a label designer where you have a limited drawing space where you can add shapes and drag shapes around in. In the screenshot below you it should in the ideal case only be possible to drag the shape in the constraints of the illustrated red box:
![image](https://user-images.githubusercontent.com/717935/159159851-b2c8c510-b0ef-4363-8890-d2a3585a61a7.png)

[Forked a sandbox example](https://codesandbox.io/s/tldraw-core-example-forked-lq7l03?file=/src/useAppState.tsx) and played around a bit with the onPointerMove event to make this possible but don't seem to be able get the shape size to be taken into account.

**Comment by steveruizok** [comment]
Thanks for the ticket @jeroenv. I think this will need to be implemented outside of the library for now. If we do implement #908 then that might solve this one too.

**Comment by steveruizok** [comment]
Here's an example implementation of this, btw:

https://codesandbox.io/s/tldraw-example-keep-shapes-in-viewport-myhvfb?file=/src/App.tsx
