### ISSUE TITLE
[feature] Option to switch between white and transparent background on export

### ISSUE THREAD

**Issue by johschmitz** [tldraw/tldraw#630]
Could you add an option to the export to switch between a white or a transparent background during export? Both are useful depending on where the drawing should be used. I had to load the file into GIMP and add a white background which was quite a lot of unnecessary extra work.
Other than that I have to say nice project :+1:

**Comment by clbarrell** [comment]
The alternative I used when I have to is to just take a screenshot instead of exporting the selection.

**Comment by steveruizok** [comment]
I believe exporting to PNG will make an image with a transparent background. Agreed that this would be a great feature to build some UI around!

**Comment by steveruizok** [comment]
Merged!
