### ISSUE TITLE
[feature] Export to URL, shareable link

### ISSUE THREAD

**Issue by johschmitz** [tldraw/tldraw#631]
Your "competitor" excalidraw has a feature called `Shareable link` which encodes the whole drawing into a shareable link. Could the same be done with a tldraw drawing?

**Comment by steveruizok** [comment]
This would be a serialized URL, or a multiplayer room? If the latter, then it could dovetail with the "copy to multiplayer document" feature that has been floating around.

**Comment by johschmitz** [comment]
From what I understand a serialized URL. I don't know the other feature.
