### ISSUE TITLE
[bug] The ID passed to onAssetCreate is not the same as onAssetDelete

### ISSUE THREAD

**Issue by a-type** [tldraw/tldraw#633]
When a file is added to the canvas, an ID string is passed to the second parameter. I get the idea is to let you upload the file to external storage and perhaps create a row in the database to track its existence based on the ID so you have a record of uploaded files and their state.

When an image or video is deleted, the `onAssetDelete` handler is called - but the ID passed is not the same as the one given to `onAssetCreate`. That undermines any way of knowing that the deleted file is the same as the one you tracked during creation, so cleanup isn't possible.

# Expected behavior

When I drop a file on the canvas, `onAssetCreate` should be called with a `File` and a unique ID, so I can upload the file to storage.

When I delete the shape containing the file, `onAssetDelete` should be called with the exact same ID so I can lookup the file in storage and remove it.

**Comment by steveruizok** [comment]
Want to take a crack at this Grant @a-type? As long as it's behavior for new assets, I can't imagine it would cause any regressions.

**Comment by a-type** [comment]
Would be happy to help, should have a PR up soon.

**Comment by a-type** [comment]
Ok, here's the snag (based on my understanding of the code) -

Currently the code relies on `onAssetCreate` to process and store a file if it is provided. It expects to receive back a URL for that file. At this point we need `assetId` to be defined and stable - basically first thing.

But after that block, when the file is processed to a source string (URL or base64), the code checks for an existing asset match, utilizing the `src`.

```ts
const match = Object.values(this.document.assets).find(
  (asset) => asset.type === assetType && asset.src === src
)
```

If there's a match, **the matched asset's ID is used**, not a generated one.

It's basically a chicken-and-egg problem. We can't know the final asset ID until after we've called `onAssetCreate`, because we might look it up and find an existing asset after the user provided us their uploaded URL.

### Proposed solution / design change

Don't try to optimize by looking up matching assets; generate a new one each time. Then we can generate the ID from line 1 and provide it to the callback.

Trying to deduplicate assets makes sense if you're parsing them into large base64 strings and want to reduce the size of the state blob, but _library users who have external file storage don't want the same ID to be provided for identical files._ I'd imagine most users are going to implement a callback which uploads the file to S3 or other storage and returns the unique URL. You don't want to detect if the file already exists in storage, because if you have multiple unrelated users uploading a byte-identical file, you don't want it to disappear for everyone if one of them deletes it!

This optimization seems a little too catered toward making base64 remotely viable, but (and excuse my ignorance on the history of this feature) it doesn't seem like it really will be for any serious use case. It's a nice demo feature but I'm not sure it warrants optimization or added complexity.

If keeping the deduplicated ID for base64 is still a hard requirement, you could generate the ID as a hash of the base64 string only for that use case, while generating a stable unique ID from the beginning for `onAssetCreate` users. Since base64 only happens if the `onAssetCreate` callback is not provided, there's no need to know the ID before processing it. Basically you could generate an assetID, and if the callback is defined you use it, otherwise you regenerate it from the hash of the base64.

**Comment by a-type** [comment]
I've got a regression test written awaiting whatever fix we decide on. Unfortunately I can't seem to get the repo to build on Windows, seems like the `lask` CLI might be spawning processes incorrectly, but I can't find the source code for it to debug further. I'll try cloning in WSL when I have some time to resume work on this.

**Comment by a-type** [comment]
I've got a regression test written awaiting whatever fix we decide on. Unfortunately I can't seem to get the repo to build on Windows, seems like the lask CLI might be spawning processes incorrectly, but I can't find the source code for it to debug further. I'll try cloning in WSL when I have some time to resume work on this.

```
@tldraw/curve:build: $ D:\work\tldraw\node_modules\.bin\lask
@tldraw/curve:build: node:events:368
@tldraw/curve:build:       throw er; // Unhandled 'error' event
@tldraw/curve:build:       ^
@tldraw/curve:build:
@tldraw/curve:build: Error: spawn tsc ENOENT
@tldraw/curve:build:     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
@tldraw/curve:build:     at onErrorNT (node:internal/child_process:477:16)
@tldraw/curve:build:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
@tldraw/curve:build: Emitted 'error' event on ChildProcess instance at:
@tldraw/curve:build:     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
@tldraw/curve:build:     at onErrorNT (node:internal/child_process:477:16)
@tldraw/curve:build:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
@tldraw/curve:build:   errno: -4058,
@tldraw/curve:build:   code: 'ENOENT',
@tldraw/curve:build:   syscall: 'spawn tsc',
@tldraw/curve:build:   path: 'tsc',
@tldraw/curve:build:   spawnargs: [
@tldraw/curve:build:     '--project',
@tldraw/curve:build:     'D:\\work\\tldraw\\packages\\curve\\tsconfig.build.json',
@tldraw/curve:build:     '--outDir',
@tldraw/curve:build:     'D:\\work\\tldraw\\packages\\curve\\dist'
@tldraw/curve:build:   ]
@tldraw/curve:build: }
```

**Comment by steveruizok** [comment]
Hm, that looks like it would be an issue here?

```ts
      // Build types
      const ts = spawn(`tsc`, [`--project`, tsconfig, `--outDir`, outdir])
```
