### ISSUE TITLE
[feature] Share Button [easy]

### ISSUE THREAD

**Issue by fire17** [tldraw/tldraw#636]
Hi there !
first of all let me just say 
i immediately fell in love with tldraw

One feature that i'll think will be great , is to have a simple share button
that generates a tldraw link that i can send to someone
(it should open a duplicate of the current sketch in multiplayer mode)
currently the only option i see is export, which doesn't lead back to any interactive interface

my current workaround is opening a new multiplayer project , and copy pasting everything from my sketch
essentially i want to **switch to multiplayer mode** and send a link **without leaving my current sketch**

i now see that this was sort of mentioned in #631 
but how i see it is:
clicking multiplayer mode -> asks if to open a new project / load from current sketchs
clicking Share -> asks if to share a view-only or go into multiplayer mode

Hope you like this idea , and that it'll be simple to make
Thanks a lot and have a good one ! :heart:

**Comment by steveruizok** [comment]
This should be possible now with the liveblocks API (it wasn't when I wrote our multiplayer integration).
