### ISSUE TITLE
Add color swatch on the side directly

### ISSUE THREAD

**Issue by ericsia** [tldraw/tldraw#644]
I love this extension a lot, it is so good. Now I don't need to open another app to draw, but......
When I am performing a demo to explain what is happening to my students, I need to use a different color for them to easier identify what is happening. But it is very difficult for me to switch colour. So here is my suggestion, are you able to add a color switch right here below, I provided 16 color code to ease you implement it:
```
16 default color - so that on clicking change pen color ❤
FFC114
F6630D
FF0066
E71224
5B2D90
AB008B
CC0066
004F8B
00A0D7
33CCFF
008C3A
66CC00
000000
333333
849398
FFFFFF
```

![image](https://user-images.githubusercontent.com/24624808/163690249-48742b33-e74d-4f16-af5f-46ea095a4cd4.png)
and here is a screenshot representing what i'm thinking.

**Comment by judicaelandria** [comment]
hi @ericsia, you're in the wrong project, this is tldraw not excalidraw

**Comment by ericsia** [comment]
> hi @ericsia, you're in the wrong project, this is tldraw not excalidraw

I am aware of that, simce the screenshot able to express my thought, so I use that screenshot.

Can you help to add a color swatch panel in next update please please please please please

**Comment by judicaelandria** [comment]
a color swatch for the what exactly, the drawing tool or for the box (stroke, fill) ?

**Comment by ericsia** [comment]
> a color swatch for the what exactly, the drawing tool or for the box (stroke, fill) ?

Forgive me, I'm unfamiliar with the given name.
What I meant is when the pen is active, ideally the color swatch can appear like arrow pointed above. So it ease us to pic color directly.

**Comment by ericsia** [comment]
> > a color swatch for the what exactly, the drawing tool or for the box (stroke, fill) ?
> 
> Forgive me, I'm unfamiliar with the given name. What I meant is when the pen is active, ideally the color swatch can appear like arrow pointed above. So it ease us to pick color directly.

@judicaelandria when the pen is active, can you keep the swatches opened with say default 16colors like screenshot above? So that we can direct pick the color without repeating click the box/panel to expand it for changing color. Because when people drawing most likely they will change color frequently back and forth.

**Comment by judicaelandria** [comment]
@steveruizok any thought ?

**Comment by ericsia** [comment]
> @steveruizok any thought ?

this is really a need, I mean how can a drawing don't have this, it is so convenient:
![image](https://user-images.githubusercontent.com/24624808/169507265-540220aa-9daf-43f4-966d-8d1eb8bd2b35.png)

**Comment by ericsia** [comment]
> > @steveruizok any thought ?
> 
> this is really a need, I mean how can a drawing tool don't have this, it is so convenient to use any color at any time with single click: ![image](https://user-images.githubusercontent.com/24624808/169507265-540220aa-9daf-43f4-966d-8d1eb8bd2b35.png)

**Comment by steveruizok** [comment]
Give this a shot! https://github.com/tldraw/tldraw/pull/697

**Comment by judicaelandria** [comment]
Yeah I got it but I want to know what Steve thinks about this 😄

**Comment by steveruizok** [comment]
@ericsia This is a good request! I think I'd made a note somewhere about something similar, as the menu interaction was annoying when drawing quickly and switching between colors. Our UI tries to strike a balance between usability and minimalism, though this could be a place where an extra option is really useful.

**Comment by judicaelandria** [comment]
alright then! I'll implement it

**Comment by judicaelandria** [comment]
oh looks live Steve finished it already 😄!

**Comment by ericsia** [comment]
Steve can you group the color to something like this please? So it's easier for us to pick color in a single click, what I mean is don't collapse the color menu:
![image](https://user-images.githubusercontent.com/24624808/169510341-0f7deee1-32e0-4cd2-bcfa-26faa83096ed.png)

**Comment by steveruizok** [comment]
Merged! I wouldn't mind revisiting the style menu to see if we can come up with a better design.

**Comment by ericsia** [comment]
Btw, I just noticed smt.
Just tiny potential improvement, if Styles is position in middle (beside undo redo) when pressing "keep open", it can appear to be at most right.
So from
<Styles> <undo, redo> <100%>
Become
<undo, redo> <Styles> <100%>

Or another thing I can imagine is make it float so user can drag it anywhere. (But maybe challenging?)

**Comment by steveruizok** [comment]
Good call on the position of the style menu. I tried out a few different positions and I'm going to put it at the right corner. 👍

**Comment by steveruizok** [comment]
Also fixing the keyboard shortcuts while the menu is open.
