### ISSUE TITLE
reduce bundle size

### ISSUE THREAD

**Issue by no-1ne** [tldraw/tldraw#648]
Bundle Phobia shows radix-ui/icons taking almost as much size and tldraw library. after tree shaking i hope it doesnt take up as much space or is there a scope of improvement here may be make the  icons self contained 
https://bundlephobia.com/package/@tldraw/tldraw@1.10.0

![image](https://user-images.githubusercontent.com/11027129/163984079-19dd65cf-cecf-4994-bfa2-879ff4cd75a6.png)

**Comment by steveruizok** [comment]
I believe esbuild (which we use to build the app) does not do complete tree-shaking, which probably explains the size. We do use quite a lot of icons, however—I remember once manually extracting just the ones that we use, and it produced very little change.
