### ISSUE TITLE
[feature] VSCode Plugin: Export without an external service

### ISSUE THREAD

**Issue by trusz** [tldraw/tldraw#649]
Hi there!

Is there any way to use the VS Code plugin without depending on an external service for the export function?
Lot of times we cannot use external services and the plugin already does a great work of working offline. I have looked into the "Copy as SVG" option, but it seems buggy.

Could one help in any way?

**Comment by judicaelandria** [comment]
Hi @trusz, thanks for your feedback! what's the issue you're facing with a copy as SVG? and could you please give some details about using external services? thanks

**Comment by trusz** [comment]
Hi @judicaelandria, thank you for answering so quick.

I'll describe first the problems with the SVG Export. Let me know if you want me to open a separate bug.


## Bugs

### Bug 1

The SVG works fine if you export it in the light mode.

Screen shot of the TLDRaw in VSCode in light mode:
<img width="1264" alt="page1-light" src="https://user-images.githubusercontent.com/1510715/164989629-fdabd3cc-c3f9-40b7-8b89-2ba0944240ec.png">

Here is the exported SVG:
![page1-light](https://user-images.githubusercontent.com/1510715/164989646-44735777-6f73-4b93-b338-8983ce75a3ca.svg)

### Bug 2

Screen shot of the TLDRaw in VSCode in dark mode:
<img width="1256" alt="page1-dark" src="https://user-images.githubusercontent.com/1510715/164989688-cddfdbf3-0445-408c-a149-b48603a88487.png">

Here is the exported SVG:
![page1-dark](https://user-images.githubusercontent.com/1510715/164989704-9c803c51-8019-4448-a55c-148cf59d334e.svg)

The colors do not quite match, but I would expect that the text is white on the dark background

### Bug 3

Also you maybe noticed but that in GitHub the fonts are not rendered correctly. I'm not sure one could do anything about it. Opening an SVG export directly in the browser locally works fine. But if I upload it to GitHub the font gets lost.

Also example gist:
https://gist.github.com/trusz/fd8ff238f7fdcb6d7dd4e3d6426b85d7


## Feature

So onto the feature request. 😄
The VSCode extension uses the `https://www.tldraw.com/api/export` API. This is, however, not allowed in our projects because we could send classified information to the server.
As far as I could see the server uses puppeteer to generate the PDF. Would it be possible to do that offline? 
I saw a similar approach in a VS Code plugin that converts markdown to pdf via puppeteer offline: https://github.com/yzane/vscode-markdown-pdf/blob/master/extension.js#L405

Thanks for bearing with me 😄

**Comment by judicaelandria** [comment]
interesting will investigate! thanks for this great explanatation

**Comment by trusz** [comment]
Hi!
The following tweet's proposition seems to be a possible solution to this problem. Or did I miss something?

https://twitter.com/steveruizok/status/1523989134938882048?s=21&t=bYPcLnN8b8fnnMLva7mukg

**Comment by trusz** [comment]
Congrats on the new feature: https://twitter.com/tldraw/status/1524423222720180226?s=20&t=2pAfZSmW1qCURCVtgErUSA 
👍 
I think we could close this issue, but I believe the bugs are still there.
@judicaelandria , would you like me to open two bug issues for them?

**Comment by judicaelandria** [comment]
hmm, export in light mode is working,
dark mode doesn't,
for the fonts, I'm not sure (maybe it's about the path that should be relative) cc @steveruizok

**Comment by steveruizok** [comment]
This should now all be possible!

**Comment by judicaelandria** [comment]
when exporting svg on dark mode and filled box, there's a bug
![New Page (1)](https://user-images.githubusercontent.com/46365844/168019083-c33f5964-4803-4f1c-b0ec-9e7008890764.svg)

**Comment by steveruizok** [comment]
All fixed now! Thanks for the push @trusz.
