### ISSUE TITLE
[bug] Copy/Cut/Paste for Text shape not working

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#656]
**Repro steps**
 1. Run/install the Tldraw VS Code extension
 2. Create a Text element
 3. Start editing the text
 4. Try copying, cutting, or pasting shortcuts, none will work
 5. Stickynote text editing works fine though.

There was an issue with this that was fixed in the past: https://github.com/tldraw/tldraw/pull/399. The sticky notes still work, looks like there was some refactoring to the Text shape, so it might be related.

**Comment by steveruizok** [comment]
Closed by #683 ! Thanks @seflless
