### ISSUE TITLE
[bug] Empty window when opening existing or creating new tldraw in VSCode with v1.10

### ISSUE THREAD

**Issue by KristoferHansson** [tldraw/tldraw#657]
Running VSCode 1.66.2 with tldraw extension 1.10

After upgrading to 1.10 none of the existing .tldraw files render and the command "tldraw: New file" just renders a empty black window.
Taking a look at the developer tools output gives me the following every time i create or open a tldraw file:
index.js:5063 ReferenceError: React is not defined
...
index.js:39038 Uncaught ReferenceError: React is not defined
...

Extension host log does not show anything.

**Comment by steveruizok** [comment]
Thanks for raising the issue @KristoferHansson !
