### ISSUE TITLE
[bug] Performance impact when creating complex line using Draw or Pencil

### ISSUE THREAD

**Issue by colinfwren** [tldraw/tldraw#664]
# Steps to reproduce:
- Load app.tldraw.dev on iPad (15.3.1)
- Use finger or Apple Pencil to draw a complex line with loads of points in it (e.g. rapid close back and forth similar to shading with a pencil)
- Once you've got a high level of complexity stop drawing the line (if it hasn't already given up) and draw a new line

# Expected results
- The line continues to be drawn without any impact for subsequent lines

# Actual results
- Sometimes the line will just stop drawing and the draw tool will fallback to being `idle` instead of `creating`
- Other times if the line doesn't stop drawing the new line will have a lot of delay that means that the line doesn't reflect what was drawn

# Evidence
In order to capture the pencil not being lifted I couldn't get a screen capture so apologies for the low quality

https://user-images.githubusercontent.com/182613/166584755-173e6fa5-2ea2-4f42-b926-ffc872031ca0.mp4

https://user-images.githubusercontent.com/182613/166584912-93b13ba0-234a-4d78-b292-79836021368c.mp4

**Comment by judicaelandria** [comment]
Hi @colinfwren, thanks for your feedback but app.tldraw.dev is under heavy dev yet so not released, you can use [tldraw.com](https://tldraw.com) for now

**Comment by steveruizok** [comment]
I'll add it to the private repo's issues, thanks!
