### ISSUE TITLE
[feature] `hideCursors` prop

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#677]
Add a prop to hide cursors in multiplayer documents.

**Comment by okdistribute** [comment]
We'd also like to modify how cursors look and behave. 

Would it make sense to have the ability to pass in the React component that renders a cursor, to override the default one that TLDraw provides? That would really help us -- and if you wanted to hide the cursor, you can pass that property `null` and it won't render the cursor.

**Comment by steveruizok** [comment]
> We'd also like to modify how cursors look and behave. 
> 
> 
> 
> Would it make sense to have the ability to pass in the React component that renders a cursor, to override the default one that TLDraw provides? That would really help us -- and if you wanted to hide the cursor, you can pass that property `null` or `false` and it won't render the cursor.
> 
> 
> 
> I am imagining something like:
> 
> 
> 
> ```
> 
> <TLDraw cursor={(user: TLUser) => <MyUserComponent user={user} />} />
> 
> ```
> 
> 
> 
> ```
> 
> <TLDraw cursor={false} />
> 
> ```

That's exactly how I'm handling this in the next version (which is where I'm spending the majority of my dev time). There are a few issues that make this more complicated, however, such as when a dev wants to add arbitrary data to the definition of a user that gets passed to the custom component (mostly a TypeScript concern).

That said, you're right that it's the most convenient solution, and I'd like to "back port" it to v1.

**Comment by okdistribute** [comment]
Awesome! Thanks!
