### ISSUE TITLE
[bug] Source error when try with the latest branch Main

### ISSUE THREAD

**Issue by smpleader** [tldraw/tldraw#678]
I pulled repo today. And:
- yarn install
- yarn build:www, show error:

`@tldraw/www:build:www: Failed to compile.`
`@tldraw/www:build:www: `
`@tldraw/www:build:www: ./pages/_app.tsx:56:8`
`@tldraw/www:build:www: Type error: 'Component' cannot be used as a JSX component.`
`@tldraw/www:build:www:   Its element type 'ReactElement<any, any> | Component<{}, any, any>' is not a valid JSX element.`
`@tldraw/www:build:www:     Type 'Component<{}, any, any>' is not assignable to type 'Element | ElementClass'.`
`@tldraw/www:build:www:       Type 'Component<{}, any, any>' is not assignable to type 'ElementClass'.`
`@tldraw/www:build:www:         The types returned by 'render()' are incompatible between these types.`
`@tldraw/www:build:www:           Type 'React.ReactNode' is not assignable to type 'import("/Users/SourceCode/Node/tldraw/node_modules/@types/react-router/node_modules/@types/react/index").ReactNode'.`
`@tldraw/www:build:www:             Type '{}' is not assignable to type 'ReactNode'.`
`@tldraw/www:build:www: `
`@tldraw/www:build:www:   54 |         <title>tldraw</title>`
`@tldraw/www:build:www:   55 |       </Head>`
`@tldraw/www:build:www: > 56 |       <Component {...pageProps} />`
`@tldraw/www:build:www:      |        ^`
`@tldraw/www:build:www:   57 |     </>`
`@tldraw/www:build:www:   58 |   )`
`@tldraw/www:build:www:   59 | }`

- yarn start:www show error:

`@tldraw/core:start: ‣ @tldraw/core: src/hooks/useZoomEvents.ts:129:9 - error TS2322: Type 'number' is not assignable to type 'Vector2 | ((state: PinchState & { event: WheelEvent | TouchEvent | PointerEvent | WebKitGestureEvent; }) => Vector2) | undefined'.`
`@tldraw/core:start: `
`@tldraw/core:start: 129         from: zoom, `

- yarn start show same error with @tldraw/core: src/hooks/useZoomEvents.ts:129:9

Could you please have a suggestion.
Thank you.

**Comment by steveruizok** [comment]
I believe this is a bug in React's TypeScript types. Could you nuke node_modules and re-install?

**Comment by smpleader** [comment]
Thank you Steve for your reply.
I tried git pull today , remove node_modules and try re-install
I run yarn build:www
I run yarn start:www
And site is available in  http://localhost:55944
When I test the site, it's  a bug 
`Uncaught TypeError: Cannot read properties of null (reading 'useState')`
Is there any step I missed ?

**Comment by steveruizok** [comment]
Closing, I believe I solved this in the most recent update (or maybe the types were updated correctly by React?).

**Comment by smpleader** [comment]
I have tested again with new clone and it works.
Thank you [steveruizok](https://github.com/steveruizok), [judicaelandria](https://github.com/judicaelandria)
