### ISSUE TITLE
[bug] Double scroll acction

### ISSUE THREAD

**Issue by yevhenii-kas-oppizi** [tldraw/tldraw#681]
For both Mac and Win, it makes “double-action” when a single little scroll of the wheel is made. Basically double scroll. Same thing for pad zoom

https://user-images.githubusercontent.com/93513279/168310481-07614496-e5b2-4df7-9be1-970555a91110.mov

.

**Comment by steveruizok** [comment]
This happens when zooming with a mouse wheel, right?

**Comment by yevhenii-kas-oppizi** [comment]
> commented
Both, with mouse and with trackpad

**Comment by steveruizok** [comment]
I'm going to include this in future work on mouse scrolling / zooming.
