### ISSUE TITLE
[feature] Image Exporting Properties

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#70]
It'd be cool if like say Sketch or Figma you could specify regions (or the whole file) you want exported as named images and pressing Cmd/Ctrl + E would export everything one go. In browser it would trigger downloading a folder with all the images, and on desktop or the VS Code extension you could save the files straight to disk. 

A nice use case would be having one larger file with many diagrams to see how they all fit together, but then be able to quickly export to images and include parts or the whole as images in markdown files or static websites. If you check your generated images in, this would work great for git/github hosted documentation.

**Comment by seflless** [comment]
For me at least, I'm more of a single page type of organizer with organization spread into clumps across a board. So for me, the frame around approach (or really just any object) is more powerful. Being able to see all your pieces side by side is nicer for tuning/thinking, so being able to export them with one command or piecemeal is sooo nice.

**Comment by judicaelandria** [comment]
> so being able to export them with one command or piecemeal is sooo nice.

you mean, add a keyboard shortcut for exporting the page into image?

**Comment by seflless** [comment]
Being able to trigger it by top-level menu, context menu, and a keyboard shortcut would be great.

What other tools do is let you select objects and set up export properties, though most allow some smart default. For Tldraw for instance it might be you want it exported as SVG or PNG at x1, x2, and x4 resolutions. Supporting multiple exports for some document sub-tree is great.

I like how Figma allows you to hit one Command+E and you get all of your exports triggered and the generated files get zipped into a single file and automatically downloaded. But then you can also manually trigger any specific element/element-tree's export
