### ISSUE TITLE
[feature] Support .tldr.json extension type

### ISSUE THREAD

**Issue by hydrosquall** [tldraw/tldraw#700]
## Motivation

- Enable typescript projects or files that aren't compatible with the .tldr extension to interpret the file as JSON correctly, enable typescript projects to import .tldr.json fixture files without needing to reconfigure your bundler to support a new extension type

## Related work

See how excalidraw-vscode handles it:

https://github.com/excalidraw/excalidraw-vscode/blob/c1eeff214b6fab13988fe43eaa7e834036f9f519/extension/package.json#L186-L197

**Comment by steveruizok** [comment]
Looks good!
