### ISSUE TITLE
[bug] Updating readOnly prop causes app to crash in some scenarios

### ISSUE THREAD

**Issue by teenoh** [tldraw/tldraw#705]
Thanks for this awesome package! I noticed a bug with `readOnly` prop when trying to make use of it.

## Steps to reproduce
- Draw on the canvas (`readOnly` prop should be false for this to be possible)
- Set `readOnly` prop to `true`
- Try clicking on the canvas

## Expected result
- Clicking on the canvas shouldn't do anything, since it's in readOnly mode

## Actual result
- App crashes with this error 
```
selectedIds is set to the id of a shape that doesn't exist: 1841870b-27d5-4e26-2d14-6ecf637e076f
```

https://user-images.githubusercontent.com/16928688/171011917-c012023c-166f-40e6-8dcb-de5f30196412.mov

Reproducible example => https://codesandbox.io/s/pedantic-https-l4ebnf?file=/src/App.tsx

**Comment by steveruizok** [comment]
Should be fixed now in 1.16.0.
