### ISSUE TITLE
No pen pressure for Wacom Intuos Pro Pen in Firefox

### ISSUE THREAD

**Issue by senntore** [tldraw/tldraw#711]
Screen Recording of the pen pressure sensitivity testing:

https://user-images.githubusercontent.com/58325574/172053671-99a211da-a63d-4271-978c-587aa80ede9e.mp4

Each stroke is using different pressure but the results are same.

OS: Pop_OS! 22.04(Linux)
Browser: Firefox 101.0(64-bit)
Pen: Wacom Intuos Pro Pen

Other Notes: Also a question somewhat related to this issue, is it possible to turn off stabilization?

**Comment by senntore** [comment]
@steveruizok I'm not sure if it's working correctly in there(it's showing weird dots unless that's intended) but here is the screenshot with different pressure
![Screenshot 2022-06-10 at 07-58-21 tablet pressure test - Tazal - OpenProcessing](https://user-images.githubusercontent.com/58325574/172978451-1a1f13ec-f382-4ae5-953f-e9b89efe1181.png)

The pressure works correctly in Krita, Pixiv Sktech. 
I can show the tablet sensitivity tester available in Krita.
Here, It shows data with change in pressure:
![Screenshot from 2022-06-10 10-32-03](https://user-images.githubusercontent.com/58325574/172994116-fd5f2c4e-ffac-47e8-9cc6-68b437ebc941.png)

**Comment by steveruizok** [comment]
> @steveruizok I'm not sure if it's working correctly in there(it's showing weird dots unless that's intended) but here is the screenshot with different pressure ![Screenshot 2022-06-10 at 07-58-21 tablet pressure test - Tazal - OpenProcessing](https://user-images.githubusercontent.com/58325574/172978451-1a1f13ec-f382-4ae5-953f-e9b89efe1181.png)

Yeah, this makes me think it's some sort of configuration error (if it were working in Firefox, it would be showing dots of varying sizes). You might google around for other issues people have had with pen pressure not registering on Firefox. Very strange but thankfully not a tldraw bug. 😮‍💨

I'll close this ticket but please do reply if you figure it out.
