### ISSUE TITLE
[example] Create an example of a custom UI.

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#724]
Where the original UI is hidden and a customized UI is shown instead. 

Possibly start with this example route: https://github.com/tldraw/tldraw/blob/main/examples/tldraw-example/src/ui-options.tsx

**Comment by creampnx-x** [comment]
I want to do this.

**Comment by steveruizok** [comment]
Go for it!

**Comment by hdoro** [comment]
I started to work on this to get familiar w/ customizing tldraw - glad to join efforts, @creampnx-x !

**Comment by judicaelandria** [comment]
Maybe @hdoro  and @creampnx-x work on different examples?
