### ISSUE TITLE
[bug] Panning with middle button of the mouse triggers unwanted paste on Linux

### ISSUE THREAD

**Issue by dragonman225** [tldraw/tldraw#737]
https://user-images.githubusercontent.com/25148955/175045261-23a4c45c-745c-4b5d-88cc-945e1ef186e7.mp4

It's a long-standing problem that something in the [X Window System](https://en.wikipedia.org/wiki/X_Window_System) hard-coded the middle-click paste behavior and provides no way to disable it. This has led to [all kinds of strange workarounds](https://www.reddit.com/r/archlinux/comments/8d1us1/disable_middle_click_paste/), but many people just leave it as it is since those workarounds can be fragile or have unwanted side effects, and instead, prefer solving the issue at the application side when middle button is actually used.

[Excalidraw encountered the same issue](https://github.com/excalidraw/excalidraw/issues/1383), and [they also have got a fix for it](https://github.com/excalidraw/excalidraw/blob/cdf352d4c3bcd6a0f4c906d85ca729b54248ea89/src/components/App.tsx#L3212), maybe tldraw can follow the same pattern.

**Comment by steveruizok** [comment]
Good catch!
