### ISSUE TITLE
[feature] Laser pointer

### ISSUE THREAD

**Issue by devrimcavusoglu** [tldraw/tldraw#739]
Laser pointer would be super good.

[Related q&a](https://www.quora.com/What-is-the-use-of-the-laser-feature-in-Google-Jamboard)
and [related feature request](https://support.google.com/jamboard/thread/2346226/laserpointer?hl=en) for Google's Jamboard. 

Laser pointer is a very nice feature for presenting or explaining the flow in the board to someone.

**Comment by steveruizok** [comment]
Duplicate of https://github.com/tldraw/tldraw/issues/569 but I think a good idea nonetheless. We now have this "eraser line" or "scribble" shape, using perfect-freehand, so I'm happy to implement it.

**Comment by devrimcavusoglu** [comment]
Sorry that I create a duplicate, nice to hear development will be going on 🙂 
I'll close this issue as duplicate.
