### ISSUE TITLE
[feature] "New tab" browser extension

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#742]
Create a browser extension that displays a tldraw project for the "new tab" page in a browser.

**Comment by infinite-nil** [comment]
Hey @steveruizok are you working on this one? If not, I'm glad to help.

**Comment by steveruizok** [comment]
Closed by https://github.com/tldraw/tldraw/pull/773! And should be on the Chrome marketplace soon.

@infinite-nil If you have any ideas for improvement, let me know.
