### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by ali-alhaidary** [tldraw/tldraw#767]
tldraw as stand alone app, works fine has the language been RTL or LTR, but as tldraw is being integrated in many apps and mainly in BBB, missing RTL functionality makes it not usable in BBB session as BBB supports RTL for so many languages.

**Comment by antobinary** [comment]
Hi, just an important clarification: https://github.com/bigbluebutton/bigbluebutton/issues/15284#issuecomment-1171400833

**Comment by ali-alhaidary** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/15301#issuecomment-1171469728
