### ISSUE TITLE
[bug] Uploading directly from camera not possible

### ISSUE THREAD

**Issue by JaPossert** [tldraw/tldraw#769]
When not signed in, taking an image with Samsung Galaxy Note 10 lite does all the steps without putting it in. 
No buffer or anything, it just stays on the insert-file screen.
Inserting an existing image works though

![Screenshot_20220629-141733_Chrome.jpg](https://user-images.githubusercontent.com/46620569/176434215-cc817518-d4d1-4ec1-848f-8768af3b9ab5.jpg)

**Comment by steveruizok** [comment]
Could you test this again? It should have been fixed with the latest update.

**Comment by JaPossert** [comment]
Thank you Steve.

Yes indeed it does work now :)

Great work, thank you
