### ISSUE TITLE
Translation for the context menu "Align / Distribute".

### ISSUE THREAD

**Issue by sugitlab** [tldraw/tldraw#787]
Hi, I'd like to translate this context menu to Japanese, so please add to `translations/main.json` defines.

https://github.com/tldraw/tldraw/blob/4d900fb7fd154d70c1c0ddcfc20dfd2b76689b58/packages/tldraw/src/components/ContextMenu/ContextMenu.tsx#L348

<img src="https://user-images.githubusercontent.com/26006414/177247876-b41661fe-3ec6-4df8-ae3e-ccb7d12df51e.png" width="400" />

**Comment by steveruizok** [comment]
Fixed in #789 !
