### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by zniper17** [tldraw/tldraw#801]
I was trying integrate tldraw in my next js app, i was using the reference codesandbox given in the discord channel

**Comment by judicaelandria** [comment]
You need to use dynamic

**Comment by steveruizok** [comment]
Yep, see how we're doing it [here](https://github.com/tldraw/tldraw/blob/main/apps/www/pages/index.tsx):

```tsx
const Editor = dynamic(() => import('components/Editor'), { ssr: false }) as any
```
