### ISSUE TITLE
[bug] Copy as PNG doesn't preserve font family

### ISSUE THREAD

**Issue by hamlim** [tldraw/tldraw#808]
### How to reproduce:

- Add text to a new drawing
- Set the font family to one of the options besides Serif (default font for example, or the sans-serif option)
- Select the text
- Go to menu, choose `Copy as PNG`
- Paste the png somewhere and notice the text is using the Serif font family

### Examples:

Screenshot of tldraw.com:

![](https://user-images.githubusercontent.com/5579638/178166888-1f81fdda-bdc7-46b1-b42f-3d48ca763efb.png)

Copied text as png:

_Might be hard to see if your GitHub theme is using a dark background 😅_

![](https://user-images.githubusercontent.com/5579638/178166898-a44e9a08-4a6c-4285-8d08-ba31bc4fac6f.png)

**Comment by hamlim** [comment]
From some additional testing, it seems like this issue happens for the other media exports as well:

- svg
- jpg
- webp

(both copy as and save as flows)

Although the SVG that you copy seems to correctly include the font-family `@import` 🤔

**Comment by judicaelandria** [comment]
Hey @hamlim, I can't reproduce this, it works for me? what browser did you use?
> I tested it with chrome firefox and safari

**Comment by hamlim** [comment]
Weird, I can't seem to replicate the issue now in Chrome or Arc, going to close this!
