### ISSUE TITLE
[bug] Zooming out with mouse wheel even one step zooms to 10%

### ISSUE THREAD

**Issue by hybridherbst** [tldraw/tldraw#822]
Seems zoom with mouse wheel is currently:
- zooming in very fast (2x on every wheel click)
- always zooming out to 10% (on just one wheel click)

Every zoom action in this video is caused by holding Ctrl + scrolling single clicks with a regular mouse wheel:

https://user-images.githubusercontent.com/2693840/178966705-5e6784b7-072b-46e8-b807-b517b3d64a21.mp4

This is on Windows + Chrome, and windows mouse wheel settings are at default ("3 lines").

Maybe related:
- #681

**Comment by steveruizok** [comment]
Similar to #255. Here's the relevant code, which seems to be failing: https://github.com/tldraw/tldraw/blob/2352985e949d14270fc89dc60144239c37c8ff91/packages/core/src/hooks/useZoomEvents.ts#L153

**Comment by hybridherbst** [comment]
Thanks, didn't find that - closing as duplicate then :)
