### ISSUE TITLE
[bug] Mobx required, but package.json no mobx dependency

### ISSUE THREAD

**Issue by XAKEPEHOK** [tldraw/tldraw#828]
Hello! 
I cant run tldraw without mobx, and in your discourd channel i see, that mobx is a peer dependency. 
May be you can add mob as dependency?

**Comment by XAKEPEHOK** [comment]
And tools like webpack/rollup/etc should use only needed functions

**Comment by steveruizok** [comment]
> Hello @XAKEPEHOK, yes you need to install mobx manually! we choose to not add it as a dependency, to avoid adding more size to the package

That's actually not the reason (folks would still have to install it regardless). Mobx is listed as a peer dependency, which some package managers respect and some do not. For example, npm won't install them and so you'll need to install mobx manually.

Side note:

I'm still not sure if mobx really needs to be in this library.

Most projects aren't using the features where it would be useful. Given that it's not absolutely necessary, I may remove mobx as a dependency in a later version. At the same time, I've been putting most of my attention into a rewrite of tldraw  (v2) that makes much more and better use of mobx than the current version. It would be quite a lot of work to rewrite v1 to use mobx in those ways, but it could still be work it!
