### ISSUE TITLE
some keyboard shortcuts are not localized

### ISSUE THREAD

**Issue by ali-alhaidary** [tldraw/tldraw#837]
in the keyboard shortcuts screen, some items are not localized although they are present in main.json file.
Such as:
tools
view
file
rectangle
ellipse
triangle
line
transform
edit

**Comment by judicaelandria** [comment]
rectangle
ellipse
triangle
line
are already there

**Comment by ali-alhaidary** [comment]
rectangle
ellipse
triangle
line
Are still not localized...

**Comment by judicaelandria** [comment]
yeah this is because all the other translation uses different keys
