### ISSUE TITLE
Can't `yarn install` packages locally

### ISSUE THREAD

**Issue by with-heart** [tldraw/tldraw#875]
I've been unable to install packages locally using `yarn workspace @tldraw/tldraw add <package>` since I started contributing the other week. It fails with `An unexpected error occurred: "expected workspace package to exist for \"<PACKAGE>\"`, where `PACKAGE` changes depending on the current commit.

Using `git bisect`, I was able to determine that the problem started in 88fbdacaea0ae8a48b12fec60941fc405aabe463. That doesn't really make sense to me because it only added two `@testing-library` packages and shouldn't have caused problems, but installing works fine for commits before that one so it must be true.

After poking around a bit, I was able to determine that running `npx yarn-deduplicate && yarn` resolves the issue and allows me to install. 

However, that only works on commits _before_ #870. Something about `@trivago/prettier-plugin-sort-imports` and/or the `resolutions` config added as part of that PR seems to cause a similar but separate issue. The error reported now is `"expected workspace package to exist for \"@babel/traverse\"`. If I remove that package and `resolutions` and deduplicate, installing works fine.

The other weird thing is that if I install the dependencies to the root, they install just fine. It only fails when installing into a specific workspace.

`yarn` version: fails with both `1.22.17` & `1.22.19`

cc: @ggallon @steveruizok

**Comment by steveruizok** [comment]
I was just running into the same issue. I believe this was introduced by the recent cleanup changes.

**Comment by steveruizok** [comment]
Pushing a fix for this now. Turned out to be a few packages added to the workspace that shouldn't have been there. Working for me locally, could you confirm?

**Comment by with-heart** [comment]
@steveruizok Yeap, it's working!

**Comment by ggallon** [comment]
Sorry about that 😓 I'll check it out!

This is the workaround for `@trivago/prettier-plugin-sort-imports` with the resolution for `@babel/parser` which must have corrupted the `yarn.lock`...

@steveruizok thank you for the quick fix

**Comment by with-heart** [comment]
@ggallon It's all good! The issue already existed before your PR (I had that issue last week), there's just something about that package or `resolutions` that made it worse

**Comment by steveruizok** [comment]
No worries @ggallon. I've pulled the sort-imports for now. If you can get them back in without causing the package manager to fall over, I'd be happy to restore them. :)
