### ISSUE TITLE
[feature] Rename Dialog should close after pressing enter

### ISSUE THREAD

**Issue by deadcoder0904** [tldraw/tldraw#902]
I think the rename dialog could use an improvement. I like figma's rename when you double-click & it starts a text-editing block then & there.

But would love the dialog to exit once I type what I want & press enter. It waits until I click `Cancel` which is weird UX afaict.

Sidenote: started using tldraw for quick annotations & it's so much better than using Figma for little annotations as it takes too long to open up

**Comment by judicaelandria** [comment]
Hey! thanks you, will fix it right away!
