### ISSUE TITLE
[feature] Numbered annotation

### ISSUE THREAD

**Issue by deadcoder0904** [tldraw/tldraw#905]
for example, [zappy](https://zapier.com/zappy) has it:

![zappy](https://user-images.githubusercontent.com/16436270/184329841-eb2c6e3d-8a94-48c3-831b-81721aa2b7ad.png)

ui is pretty simple if u install zappy. just a number that increments starting from 1 surrounded by a circle.

useful for quickly annotating steps to follow in 1 screenshot :)

**Comment by judicaelandria** [comment]
Hey again! as for the annotation, I think you can use the circle

**Comment by deadcoder0904** [comment]
too much work with just the circle. trust me, i tried. if you try zappy, you'll see how quick & useful it is :)

**Comment by steveruizok** [comment]
Closing this one. I've been kicking around a "sticker" tool that could work like this, but you'll need to hack it for now.
