### ISSUE TITLE
[feature] Prop for pages that want to have a non-infinite canvas and background.

### ISSUE THREAD

**Issue by andoni-enriquez** [tldraw/tldraw#908]
If you want to develop an app that it's more like a ppt, you will be looking for a non infinite canvas and some features like background, auto scale...

So it would be interesting to develop some new props for the canvas, like the ones below, 
1. Non infinite canva solution
2. Background (colors, images, videos)
3. Auto scale of the elements on window resize

**Comment by judicaelandria** [comment]
duplicat? same feat https://github.com/tldraw/tldraw/issues/625

**Comment by andoni-enri** [comment]
Not really, the first prop yes but the other ones no...

**Comment by andonienri** [comment]
Not really, the first prop yes but the other ones no...

**Comment by steveruizok** [comment]
Hey, this could be done with tldraw! But these are not necessarily features for tldraw's core library.

in #625 I've linked an example of what this might look like using the tldraw API: https://codesandbox.io/s/tldraw-example-keep-shapes-in-viewport-myhvfb?file=/src/App.tsx
