### ISSUE TITLE
[feature] add "reset to default" in menu

### ISSUE THREAD

**Issue by deadcoder0904** [tldraw/tldraw#909]
i changed a few settings in console & it made my arrows smaller.

would've loved to make it bigger in the menu by using "reset to default" option.

it should call `app.reset()` function. i used it in console to reset but still think it's worth adding to menu :)

**Comment by judicaelandria** [comment]
maybe undo your change? (command + z)

**Comment by deadcoder0904** [comment]
i don't think it works that way.

even if it did, i had spent a day on it so refreshed the tab, etc... so even if it remembered the state, it might've forgotten.

still a reset button would be a cool addition 👍

**Comment by steveruizok** [comment]
What would be being reset here? Styles?

**Comment by deadcoder0904** [comment]
for me, i changed the largest arrows from large to small when i entered in the console `size: 1` or something like that.

see my previous discord chat but i think `app.reset()` did the job.

i mean reset settings mean go back to the default so whatever the default is, it should go back to that. which means if it's small font-size, single-lined arrow (instead of dashed), etc.. then it should go back to that.
