### ISSUE TITLE
[feature] add `export` within 1-click rather than 3-clicks

### ISSUE THREAD

**Issue by deadcoder0904** [tldraw/tldraw#912]
currently, the `export` function is hidden within 3-clicks.

i have to check a few times to find `export` bcz i keep forgetting it's in the `edit` menu.

honestly, a download icon at the bottom would be preferable for export function like we have for rectangle, circle, triangle, line.

instead of rectangle, circle, triangle, line, it'd have png, svg, webp & jpeg.

of course, i don't mean to remove rectangle, just add an additional icon for download.

**Comment by senntore** [comment]
Yeah, I would love it if the Export could be in the top floating panel like undo/redo, etc & also outside of Edit menu.

**Comment by gordielachance** [comment]
...At least, it would be more logical to move it to the file menu.
