### ISSUE TITLE
[bug] Centered text of shape is right-aligned after export

### ISSUE THREAD

**Issue by mcndt** [tldraw/tldraw#913]
Browsers tried: Firefox, Chrome

Editor view:

![image](https://user-images.githubusercontent.com/23149353/184596072-cfa36466-8c41-482c-81c7-7e0e7f7820f8.png)

Export output (any format):

![Page 1(2)](https://user-images.githubusercontent.com/23149353/184596113-8dadba91-d3af-4d2d-8b5b-3924a79b319c.png)

**Comment by mcndt** [comment]
[example.tldr.txt](https://github.com/tldraw/tldraw/files/9335797/example.tldr.txt)

Here is the file for the example above.

**Comment by judicaelandria** [comment]
hey @mcndt, priority fix for today!

**Comment by steveruizok** [comment]
I think the bug here is when labels have alignments. 

You can replicate this by:

- Create a Box
- Assign a label to the box
- Create a text shape
- Select both the box and the text shape
- Select align right in the styles menu
- Export the shapes as an image

**Comment by steveruizok** [comment]
Fixed!
