### ISSUE TITLE
[feature] Maintain all changes history

### ISSUE THREAD

**Issue by mandric** [tldraw/tldraw#916]
It would be nice if no history of changes was lost, similar to git.  So you could create a share/collaborate with many people without fear of someone overwriting changes that are lost forever.  I was wondering if other people think this would be a useful feature and would love to help in implementation or design as well.  

Even neater but maybe too crazy is a "git backend" so changes are literally written to a git repo and then entire git toolset is available to your designs/schemas.

**Comment by steveruizok** [comment]
Hey, we're working on a new multiplayer implementation that might help in this direction. I've never seen a git-style deep undo work super well, however things like branching may be possible, or scrubbing back in time. Keep an eye out. :)

**Comment by mandric** [comment]
Cool, I've looked a little at other apps like [logseq](https://logseq.com) which uses a git backend.  It might be cool if there was a nice solution for web frontends for a git sync. I also looked a bit at [getditto](https://github.com/getditto) which looks like next level replication algorithm.  But git has ubiquity going for it... etc, thanks for feedback!

**Comment by steveruizok** [comment]
Closing this for now (it won't be worked on for a bit).
