### ISSUE TITLE
[bug] Images aren't working in VS Code Extension

### ISSUE THREAD

**Issue by seflless** [tldraw/tldraw#924]
I can add an image to a file, but on closing and reopening it, there's a broken image. Have tried on various files and fresh files.

Using latest extension. Haven't been using it in a while, so this might not be new new.

https://user-images.githubusercontent.com/1845/185805890-8d708f20-5094-4b62-917e-5403835f9525.mov

**Comment by Proful** [comment]
I too noticed this one. Felt I'm only having issues.
