### ISSUE TITLE
[bug] Can't start repository

### ISSUE THREAD

**Issue by hraschan** [tldraw/tldraw#930]
Cloned repo
`yarn`
`yarn start` throws the following errors:

`tldraw/tldraw:dev: ‣ @tldraw/tldraw: src/Tldraw.tsx:495:17 - error TS2322: Type '{ id: string | undefined; containerRef: RefObject<HTMLDivElement>; shapeUtils: { rectangle: RectangleUtil; triangle: TriangleUtil; ... 7 more ...; video: VideoUtil; }; ... 70 more ...; onDrop: TLDropEventHandler; }' is not assignable to type 'IntrinsicAttributes & RendererProps<TLShape, { isDarkMode: boolean; }>'.
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:   Property 'onPinchStart' does not exist on type 'IntrinsicAttributes & RendererProps<TLShape, { isDarkMode: boolean; }>'.
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 495                 onPinchStart={app.onPinchStart}
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:                     ~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: Rebuilt types. Encountered errors:
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: src/state/shapes/DrawUtil/DrawUtil.tsx:131:31 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ draw: string; solid: string; dotted: string; dashed: string; }'.
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 131       const strokeDasharray = {
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:                                   ~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 132         [DashStyle.Draw]: 'none',
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: ... 
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 135         [DashStyle.Dashed]: `${strokeWidth * 4} ${strokeWidth * 4}`,
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 136       }[style.dash]
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: src/state/shapes/DrawUtil/DrawUtil.tsx:138:32 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ draw: string; solid: string; dotted: string; dashed: string; }'.
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 138       const strokeDashoffset = {
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:                                    ~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 139         [DashStyle.Draw]: 'none',
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: ... 
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 142         [DashStyle.Dashed]: `0`,
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: 143       }[style.dash]
@tldraw/tldraw:dev: ‣ @tldraw/tldraw:     ~~~~~~~~~~~~~~~~~~~
@tldraw/tldraw:dev: ‣ @tldraw/tldraw: [11:22:47] Found 3 errors. Watching for file changes.`

**Comment by judicaelandria** [comment]
Steps to run the repo:

- yarn
- yarn build
- yarn start
go to localhost:5420

you should be able to run the repo even tho these error are there
