### ISSUE TITLE
[bug] Text on bent arrow misaligned as PNG

### ISSUE THREAD

**Issue by tekumara** [tldraw/tldraw#935]
1. Draw a bent arrow and add text:

<img width="659" alt="Screen Shot 2022-08-25 at 11 31 43 am" src="https://user-images.githubusercontent.com/125105/186553759-fbbf1db4-aa18-4c67-aa25-4af3f56ffbdc.png">

2. Export/copy as PNG:

![Page 1(1)](https://user-images.githubusercontent.com/125105/186553909-16dc343b-64a6-4908-982c-d110c795104d.png)

**Comment by steveruizok** [comment]
Fixed by #936!

![image](https://user-images.githubusercontent.com/23072548/187060274-47183978-13f7-429f-8262-22799ffbf9a2.png)
