### ISSUE TITLE
[feature] Export-as would be even better if there was a to-clipboard too.

### ISSUE THREAD

**Issue by paul-hammant** [tldraw/tldraw#937]
My OmniGraffle (Mac) workflow often rests on export-as-svg to clipboard and a paste into some other tool that recognizes that.  Minimalisticaly, that's straight into a markdown editor for the sake where <svg></svg> is jusy inlined into the resulting HTML page.

Tldraw would be even better if it had this feature :)

**Comment by judicaelandria** [comment]
Hey! I think that the same as Copy as doing
<img width="288" alt="Screen Shot 2022-08-29 at 2 11 15 PM" src="https://user-images.githubusercontent.com/46365844/187188557-93e18cec-0841-4817-ad11-560dae0d8a98.png">

**Comment by paul-hammant** [comment]
Fantastic!
