### ISSUE TITLE
[documentation] Could the README call out the backing-store technology for drawings-at-rest please?

### ISSUE THREAD

**Issue by paul-hammant** [tldraw/tldraw#938]
No sure what the server-side backing store is. I know it is not `sqlite` as i've searched for that in repo.  Similarly it's not `mariadb`, `postgres`, nor `mysql`.

Thx.

**Comment by paul-hammant** [comment]
My bad - there's an effective File->Open & File->Save/As facility

**Comment by judicaelandria** [comment]
yes, and we're using IndexedDB :)
