### ISSUE TITLE
[bug] Version 1.20 in MacOS, VSCode not working

### ISSUE THREAD

**Issue by siliconsorcery** [tldraw/tldraw#941]
MacOS v12.4
VSCode v1.70.2
tldraw v1.20.0
Results in a blank screen when opening a 'good' *.tldr file.

Installing
tldraw v1.19.0
Seems to work as expected.

**Comment by QuantelUSA-spinkham** [comment]
Same issue on Windows 10, VSCode v1.70.0, tldraw v1.20.0. 
tldraw v1.19.0 works

**Comment by NigelThorne** [comment]
Same issues on linux. v1.19.0 works

**Comment by judicaelandria** [comment]
thanks for reporting this bug! i'll take a look at it soon

**Comment by j0no** [comment]
Same issue on Mac and Ubuntu:
MacOS v12.4
VSCode v1.70.2
tldraw v1.20.0


Ubuntu v22.04
VSCode v1.70.2
tldraw v1.20.0

**Comment by judicaelandria** [comment]
it's fixed! you can update to the latest version
