### ISSUE TITLE
[feature] Improve the font tool

### ISSUE THREAD

**Issue by gordielachance** [tldraw/tldraw#943]
Hi! Awesome app, thanks !  
Keep it simple, that's what makes it beautiful !

Some improvements could be made, among others regarding the text tool :

- font size
- alignment (default should be left, not centered, it feels weird)

It would be nice to be able to scale a text block, like we can for images.

There is a nice feature in Adobe After Effect, which is that the _same_ text tool can either be used to start a simple text line, but, if you hold the mouse, you can draw a text box that will contain the text :

![GIF 01-09-22 10-46-44](https://user-images.githubusercontent.com/4077261/187873566-1d380ce6-53c6-481f-8a7b-e0e0b2813883.gif)

**Comment by steveruizok** [comment]
Thanks for the idea @gordielachance! I've been experimenting with this kind of thing for text shapes for the next big version—the UX is a bit more complex than it may seem. At best we'd want to have a fixed width but not a fixed height. Anyway, we most likely won't be changing the way the text tool works on this version.
