### ISSUE TITLE
[bug] Reversed zoom in and zoom out

### ISSUE THREAD

**Issue by turkerdev** [tldraw/tldraw#954]
<kbd>CTRL</kbd>+<kbd>+</kbd> should zoom in,
<kbd>CTRL</kbd>+<kbd>-</kbd> should zoom out,
but it's reversed.

**Comment by judicaelandria** [comment]
what operating system are you using? navigator? @turkerdev

**Comment by turkerdev** [comment]
> what operating system are you using? navigator? @turkerdev

windows 10, chrome latest
the issue persists on firefox, edge, incognito mode and even in windows sandbox with edge.

**Comment by turkerdev** [comment]
using numpad plus and minus keys have this issue, the other combination works as expected.
