### ISSUE TITLE
[bug] Incorrect bounds for a curved / labeled line when selecting multiple shapes

### ISSUE THREAD

**Issue by alex-kim-dev** [tldraw/tldraw#966]
1. The line text isn't inside the bounds:
   ![screenshot_01](https://user-images.githubusercontent.com/45559664/189108956-ac1f8a75-9017-4d63-9ada-69c94ed1ea8b.png)
2. ~~Same for the curved line endings:~~ fixed in #979 
   ![screenshot_02](https://user-images.githubusercontent.com/45559664/189109560-e0434e4b-2e71-471e-aa16-5d3be1a7fe47.png)
   ![screenshot_03](https://user-images.githubusercontent.com/45559664/189110117-963b7efb-5081-4bcb-8415-328b9a77f509.png)

**Comment by steveruizok** [comment]
Just to check: you would expect the bounding box of the arrow to include the label?
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/23072548/189123868-2c6af5d4-eb6d-41cf-9514-ad63bdc7cb5b.png">

**Comment by alex-kim-dev** [comment]
Yes. Is it by design? I mean, it's not such a big deal, but I think the endings still have to be inside.

**Comment by steveruizok** [comment]
Hm, yeah, I'm going to say this is sort of by design. If we did measure the text as part of the bounds checking, it could have an impact in other arrow behaviors, so it would take some time to implement.

**Comment by alex-kim-dev** [comment]
ok, I think I'll close this for now
