### ISSUE TITLE
[bug] Broken resizing and flipping of curved lines

### ISSUE THREAD

**Issue by alex-kim-dev** [tldraw/tldraw#967]
Some weird stuff happens to the curved line when:
1. resizing it when multiple shapes selected
   ![Peek 2022-09-08 16-28](https://user-images.githubusercontent.com/45559664/189111556-4ade61dd-d1f1-467d-83f8-b18085b22326.gif)
2. flipping
   ![Peek 2022-09-08 16-30](https://user-images.githubusercontent.com/45559664/189111600-8f38515d-b020-4f97-88d5-53ad786e32ea.gif)

**Comment by steveruizok** [comment]
Oooh that's a good one.

**Comment by alex-kim-dev** [comment]
@steveruizok @judicaelandria Flipping is fixed, but resizing multiple shapes is still buggy:

![Peek 2022-09-13 17-10](https://user-images.githubusercontent.com/45559664/189897666-d7efa9c1-6227-4767-b7a1-18785b4fda05.gif)

**Comment by judicaelandria** [comment]
resizing work but that's undo, different issue

**Comment by alex-kim-dev** [comment]
I've just tested it in Chrome and Firefox private tabs and resizing isn't working for me. Or is not shipped yet? I thought every commit to main triggers a deploy for `tldraw.com`

**Comment by judicaelandria** [comment]
> I've just tested it in Chrome and Firefox private tabs and resizing isn't working for me. Or is not shipped yet? I thought every commit to main triggers a deploy for `tldraw.com`

hmm, yeah there're some weird issue with resizing, I'll take a look at it after I finish my actual task
