### ISSUE TITLE
[bug] Scrolling menus can't be put in container

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#969]
Currently any menu that scrolls (e.g. the languages menu) has to be parented to the body rather than to the container. This means that the menu does not follow the current theme. Whenever I put it back into the container, however, it breaks scrolling. I'm almost certain that it's our own CSS preventing this but I haven't been able to figure out which values or any other reason why it's happening!

**Comment by alex-kim-dev** [comment]
`useZoomEvents` listens to scroll and zoom events on the `<StyledLayout>` which is the parent for both canvas and all the UI toolbars and menus. So even if we hover over any toolbar or a menu and start scrolling, this hook handles it and does `event.preventDefault()`.

I tried tracking these events on the canvas instead in #977
