### ISSUE TITLE
[bug] Could not find a binding to match the start handle's bindingId

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#988]
To reproduce:

- Create two shapes
- Draw an arrow between the two shapes
- Move the arrow away from both shapes
- Drag the arrow's handle back to one of the shapes

![Kapture 2022-09-19 at 09 29 04](https://user-images.githubusercontent.com/23072548/190978422-87f69f10-c767-44a2-833a-98b58927978b.gif)

See error in console.

**Comment by judicaelandria** [comment]
https://github.com/tldraw/tldraw/issues/850
